### ISSUE TITLE
[Item] Thundering\Cresting\Burning Charms.

### ISSUE THREAD

**Issue by highness** [dalaranwow/dalaran-wow#1003]
http://www.wowhead.com/item=4480

http://www.wowhead.com/item=4481

http://www.wowhead.com/item=4479

These thingies should insta-kill any Arathi elemental they're linked with.

http://www.wowhead.com/item=4480 kills http://www.wowhead.com/npc=2761, http://www.wowhead.com/item=4481 kills http://www.wowhead.com/npc=2760, http://www.wowhead.com/item=4479 kills http://www.wowhead.com/npc=2762.

Otherwise, thingies shouldn't have any effect on any other mobs or players.

Currently, they affect correct targets, but do nothing to them (save for aggro).

Cheers.

**Comment by Rushor** [comment]
DB/Creature: Burning Exile + Cresting Exile + Thundering Exile - Add despawn on spellhit of banishspells

* closes https://github.com/dalaranwow/dalaran-wow/issues/1003
* commit: 2a719e82035729e41bbcfbcad86a8ead26417d89
* also updated the combatscript for  Thundering Exile (CMC)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
