### ISSUE TITLE
[Quest][Classic] Misplaced quest: Spirits of the Stonemaul Hold.

### ISSUE THREAD

**Issue by highness** [dalaranwow/dalaran-wow#1004]
http://www.wowwiki.com/Brogg

As you can see, the chain he offers is: 

[39] Bloodfen Feathers -> [39] Banner of the Stonemaul -> [39] The Essence of Enmity -> [41] Spirits of Stonemaul Hold -> [41] Challenge to the Black Flight 

Here you can take Spirits of the Stonemaul Hold quest (http://www.wowhead.com/quest=27410) any time you wish (i.e. it ignores all quest requirements for it). 

![wowscrnshot_120713_070401](https://f.cloud.github.com/assets/5235996/1697740/53790db2-5efd-11e3-8852-e373bf100410.jpg)

**Comment by Rushor** [comment]
DB/Quest: Spirits of the Stonemaul Hold - Add prevquestchain

* closes https://github.com/dalaranwow/dalaran-wow/issues/1004
* you now need to reward http://wotlk.openwow.com/quest=11161 and http://wotlk.openwow.com/quest=11160 in order to get quest http://wotlk.openwow.com/quest=11159
* commit: b341a7038a0637f7df3b787dd75ad23c55045232

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
