### ISSUE TITLE
[Quest][Classic] Challenge to the Black Flight script issues.

### ISSUE THREAD

**Issue by highness** [dalaranwow/dalaran-wow#1005]
http://www.wowhead.com/quest=27411

When you place a banner and Smolderwing appears, he should /yell the following lines:

```
"Pitiful mortal, Onyxia answers to no one! 
"Your pathetic challenge has not gone unnoticed. I shall enjoy toying with you before you die." 
```

Then he should attack banner, then player character and become attackable as well.

Here he spawns and does nothing instead.

Video from retail here: http://www.youtube.com/watch?v=HqPA3ngwI4E

**Comment by Rushor** [comment]
DB/Quest: Challenge to the Black Flight - Add spawnevent

* closes https://github.com/dalaranwow/dalaran-wow/issues/1005
* commit: 854efabdf9da2e7dc3df6029ae0766353f68e2de


![GitHub Logo](http://i.imgur.com/ONmL0rf.jpg)
![GitHub Logo](http://i.imgur.com/8cDRsdL.jpg)
![GitHub Logo](http://i.imgur.com/kEtVkTn.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
Ref: https://github.com/TrinityCore/TrinityCore/issues/18444
