### ISSUE TITLE
[Quest][Classic] Captain Vimes missing script.

### ISSUE THREAD

**Issue by highness** [dalaranwow/dalaran-wow#1008]
Upon completing the quest (http://www.wowhead.com/quest=1220), Captain Garran Vimes (http://www.wowhead.com/npc=4944) should say:

```
Captain Garran Vimes places the scroll on the table and reads... 
Captain Garran Vimes says: By the Light! This cursed spy was a good one! I'm glad he's dead. 
Captain Garran Vimes says: Thank you for this report, <name>. It is now clear that we must tighten our patrols near Theramore. 
```

Currently he says nothing.

**Comment by Rushor** [comment]
DB/Quest: Captain Vimes - Add textendevent

* closes https://github.com/dalaranwow/dalaran-wow/issues/1008
* commit: a46f33abff6443f96258872955282a07e1b9293f

![GitHub Logo](http://i.imgur.com/rx5mqcn.jpg)
![GitHub Logo](http://i.imgur.com/Ye7lCpj.jpg)
![GitHub Logo](http://i.imgur.com/ekrluuP.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
Ref.: https://github.com/TrinityCore/TrinityCore/issues/18426

**Comment by Rushor** [comment]
updates with https://github.com/dalaranwow/dalaran-wow/issues/994
