### ISSUE TITLE
[GO] Bubbly Fissure

### ISSUE THREAD

**Issue by Blackeight** [dalaranwow/dalaran-wow#1010]
Hello,

I went to Desolace to farm some Footlockers underwater at coords: 36, 20.. There is a Bubbly Fissure there which should help me out and give me air when I need it so I don't have to go to the surface all the time. Unfortunately it doesn't give me any :-)

Here is a screenshot for it just in case: http://i40.tinypic.com/acpq88.jpg

The Fissure is exactly at coords: 36.6, 20.0
I'm not sure if all the Bubbly Fissures "don't work" or it's just that one.

Thank you for reading

**Comment by Rushor** [comment]
DB/Gameobject: Bubbly Fissure - Enable underwater breathing spell 

* closes https://github.com/dalaranwow/dalaran-wow/issues/1010
* commit: e798fec9e16b8b2a831c93e6c60eb93ef64de9fa

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
