### ISSUE TITLE
[Quest][Classic] Prospect of Faith (2) missing post-script.

### ISSUE THREAD

**Issue by highness** [dalaranwow/dalaran-wow#1012]
When you turn the quest (http://www.wowhead.com/quest=724) to Historian Karnik (http://www.wowhead.com/npc=2916), Hammertoe's Spirit (http://www.wowhead.com/npc=2915) should appear and the following dialogue between them occurs:

Hammertoe's Spirit says: Karnik, me friend, I wish I could see you with me own eyes again, but we need'ta talk of Ragnaros. His influence is spreading.
Historian Karnik says: Ragnaros? Terrible news indeed...
Hammertoe's Spirit says: I'll tell you more, Karnik, in time. But first, send this traveler'ta Belgrum--there's more business'ta attend to.
Historian Karnik says: You heard him, traveler. Speak to me again when you're ready to speak to Belgrum.

Hammertoe's Spirit disappears after a while. 

Currently, none of the above happens yet.

Cheers.

**Comment by Rushor** [comment]
Ref: https://github.com/TrinityCore/TrinityCore/issues/18427

**Comment by Rushor** [comment]
DB/Quest: Prospect of Faith - Add endevent with Creature 'Hammertoe's Spirit'

* closes https://github.com/dalaranwow/dalaran-wow/issues/1012
* commit: 5a9d026633321f25d15d40e5489807e386ca3bed

![GitHub Logo](http://i.imgur.com/XW0sY0D.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
