### ISSUE TITLE
[Quest][Classic] The Bloodcurse Legacy

### ISSUE THREAD

**Issue by Jazex** [dalaranwow/dalaran-wow#1029]
http://www.wowhead.com/quest=9672

You are supposed to start this quest by receiving a mail with the item 'A Letter from the Admiral' which will start this quest. You will receive this mail after completing the quest 'Urgent Delivery'.

If you happen to abandon this quest after starting it, you can retake it from the NPC Admiral Odesyus (http://www.wowhead.com/npc=17240) in order to continue the quest chain.

However Admiral Odesyus gives this quest already, even if you haven't abandoned the quest you get the item (A Letter from the Admiral). This quest should only become available at the NPC once you have abandoned the regular quest (which you obtain in a different way).

Figured this out when I saw my mail, got the item and it said 'You do not meet the requirements for this quest'. Turns out I had already completed the whole questchain before I noticed this item in my mailbox.

**Comment by Rushor** [comment]
DB/Quest: The Bloodcurse Legacy - Only show quest if quest 'Urgent Delivery' is rewarded

* closes https://github.com/dalaranwow/dalaran-wow/issues/1029
* commit: 4eb8be7f9d3c5cc1fee310c3941bb0f31632401b
* There is no condition that only shows quest XY if quest XY is abandoned, so i added the workaround, that you can only see and accept the quest http://wotlk.openwow.com/quest=9751 from Admiral Odesyus  once quest http://wotlk.openwow.com/quest=9671 was rewarded

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
