### ISSUE TITLE
[Quest][Classic] The Platinum Discs (2) (Alliance)

### ISSUE THREAD

**Issue by highness** [dalaranwow/dalaran-wow#1035]
http://www.wowwiki.com/Quest:The_Platinum_Discs_%28Alliance%29

http://www.wowhead.com/quest=2279

This quest should be obtainable from http://www.wowhead.com/object=131474 after it's prerequisite, http://www.wowwiki.com/Quest:The_Platinum_Discs_%28Neutral%29 (http://www.wowhead.com/quest=2278) is complete.

Currently, you can take both quests at the same time, breaking continuity a bit.

Need to be tested at Horde side too.

![wowscrnshot_121413_131453](https://f.cloud.github.com/assets/5235996/1748315/cc18c230-64b1-11e3-8f2b-913baf836e0b.jpg)

**Comment by Demlock** [comment]
It works fine on the Horde side

**Comment by Rushor** [comment]
DB/Quest: The Platinum Discs - Add prevquest "The Platinum Discs"

* closes https://github.com/dalaranwow/dalaran-wow/issues/1035
* commit: 03870e896b25ba091b7f32ce90541883d297e8d2

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
