### ISSUE TITLE
[Quest][Classic] Misplaced quest: Jonespyre's Request

### ISSUE THREAD

**Issue by highness** [dalaranwow/dalaran-wow#1040]
http://www.wowhead.com/quest=3787

This quest should become available to players only after they complete Morrowgrain Research (http://www.wowhead.com/quest=3785).

Currently all players of level 47++ can take it, regardless of the requirement above.

**Comment by Rushor** [comment]
DB/Quest: Jonespyre's Request - Add prevquest: Morrowgrain Research 

* closes https://github.com/dalaranwow/dalaran-wow/issues/1040
* commit: e8612c9fa0d310e167f4e11c7411cfc037548046

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
