### ISSUE TITLE
[Hellfire Ramparts] [Boss] Vazruden

### ISSUE THREAD

**Issue by Blackeight** [dalaranwow/dalaran-wow#1042]
Hello,
I've been doing several rdfs and joined Hellfire Ramparts. All good but when we reached Vazruden and his fellow mount Nazan, we've got to kill several Vazrudens.. So here is what happened:

We killed last two guards in front of Nazan, we got in combat and attacked by Vazruden on foot, then we got out of combat.

That is when we approached Nazan aaaand we got attacked by another Vazruden. In the meantime Nazan goes off.. When we killed that second Vazruden and after that Nazan.. third Vazruden spawned and attacked us. 

Here is a screenshot where we killed Nazan and Vazruden and there is a chest already and another Vazruden spawned
http://i44.tinypic.com/30d8adt.jpg

This happened 3 times in 3 rdfs, during 2 of them there were only 2 Vazrudens.. 3rd rdf was with 3 Vazrudens.

I believe there's supposed to be only 1 Vazruden :-)
link to Vazruden in wowhead: http://www.wowhead.com/npc=17537/

Thank you for reading

**Comment by Rushor** [comment]
Scripts/HellfireRamparts: Vazruden - Change Aggro and chestspawnmechanic

* it should no longer be possible that Vazruden will be summned twice
* closes https://github.com/dalaranwow/dalaran-wow/issues/1042
* commit: 55fc7eb0c8c9f58c814abe5b3618eb6e5a14c8e1

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
