### ISSUE TITLE
[Quest][Classic] The Annals of Darrowshire 5154

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#1043]
All the Musty tome contain the quest item
"The trick with this quest is to carefully examine the books on the floor. "Trapped" tomes that spawn guards have a clear white/gray split on their pages, whereas the real thing has a smooth transition from white to gray. This may only become apparent if you zoom in and highlight a book, but it's worth it to avoid unneccessary fights."
http://www.wowhead.com/quest=5154/the-annals-of-darrowshire#.

**Comment by Demlock** [comment]
Confirmed.

**Comment by Rushor** [comment]
DB/Quest: The Annals of Darrowshire - Add spawn of Decrepit Guardian for fakeobjects

* closes https://github.com/dalaranwow/dalaran-wow/issues/1043
* commit: d1c09ff107688096729a6d3f92bdf63a48277419

![Awesome cat gif](http://media.giphy.com/media/l0HlSWcKYP7cQ8A6Y/giphy.gif) 


![GitHub Logo]()
![GitHub Logo]()

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
