### ISSUE TITLE
[NPC] Training Dummies - Damage taken / Rage regeneration

### ISSUE THREAD

**Issue by HeadOwns** [dalaranwow/dalaran-wow#1050]
Hey there, since that ddos attack that we've got maybe 2 months ago I think, I don't generate rages when attacking a dummy, I mean, it's like on molten now, I generated more rages when I was lvl 72 than I do now, so the rage thing was fixed before and now it's not anymore, and btw, I don't have any idea about the dummies from other places except Orgrimmar, Orgrimmar is the only place where I attack the dummies and they are bugged there, maybe other dummies aren't bugged and maybe they are, so since noone reported this yet cuz maybe they didn't have the same problem as me or they don't train in dummies or they didn't think about reporting, so, please, if you could fix this asap it would be awesome.
Thanks in advance.

**Comment by Rushor** [comment]
you don't get rage, cuz the creatures will not get damage in the script.

Scripts/World: Allow Damage for training dummies and add healthreset every 5 seconds

* closes https://github.com/dalaranwow/dalaran-wow/issues/2098
* commit: 39f2997da11c6c8ab3dfcc21a871d980dbc708f0

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
