### ISSUE TITLE
Auto Attack while Dual Wielding

### ISSUE THREAD

**Issue by Rathyan** [dalaranwow/dalaran-wow#1060]
Wowhead's link: http://www.wowhead.com/spell=6603

What's wrong: When dual wielding and starting to attack an enemy, the off hand skips the first swing and doesn't do damage

How it should work: when starting to attack an enemy, both the weapons should do damage at the start

How to reproduce: Hug a dummy, right click on it > the main hand will do damage only, while the off hand will wait for the next swing to do it

**Comment by robinsch** [comment]
On PTR.

**Comment by Rushor** [comment]
The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Edzero** [comment]
Off-hand weapons will no longer skip their first swing when attacking an enemy whilst dual wielding.

**Comment by TeridanDW** [comment]
Work as intended on ptr.
