### ISSUE TITLE
[Item] Disenchant: Infinite Dust, loot table

### ISSUE THREAD

**Issue by vexohm** [dalaranwow/dalaran-wow#1090]
Issue present:
The loot table for disenchanting northrend items is not updated to the proper patch, yielding significantly less Infinite Dust than supposed to.

Could the loot tables be updated via a querry, according to the proper item levels listed below?

From wowhead comments.
http://www.wowhead.com/item=34054/infinite-dust#comments

"By theoryaction (204 – 2) on 2009/11/26 (Patch 3.2.2)
Pre-hotfix average Infinite Dust drop rates per DE:
iLevel 130-150 1.5   <--- Currently on Kirin Tor, 1-2 dust per disenchant
iLevel 154-182 3.5   <--- 2-5 dusts per disenchant
3.2.2 Updated average Infinite Dust drop rates per DE:
iLevel 130-150 2.5 (+66.6%)   <--- should be this, 2-3 dusts per disenchant
iLevel 154-182 5.5 (+57.1%)   <--- should be this, 4-7 dusts per disenchant"

"By KatzztaK (916 – 1·9) on 2009/10/24 (Patch 3.2.2)
With the hot fix from this morning, I disenchanted several bags of Northrend greens. Disenchanting greens that would normally yield 2-5 Infinite Dust are now yielding 4-7 Infinite Dust."

"By Jagno (4,780 – 1·8·33) on 2009/04/28 (Patch 3.1.1)
Updated for 3.2.2 hotfix!
Here are the most efficient items to disenchant specifically for finding Infinite Dust from each crafting profession:

Blacksmithing
8 Cobalt Bars, 4-7 Infinite Dust (0.515625 dust/bar)
Horned Cobalt Helm

8 Cobalt Bars, 2 Crystallized Water, 4-7 Infinite Dust (0.515625 dust/bar)
Reinforced Cobalt Shoulders
Reinforced Cobalt Helm
Reinforced Cobalt Legplates
Reinforced Cobalt Chestpiece

Jewelcrafting
2 Eternals, 4-7 Infinite Dust (2.0625 dust/eternal)
Shadowmight Ring
Stoneguard Band

1 Gem, 2 Crystallized Earth, 2-3 Infinite Dust (1.875 dust/gem)
Bloodstone Band
Crystal Chalcedony Amulet
Crystal Citrine Necklace
Sun Rock Ring

Leatherworking
8 Borean Leather, 2-3 Infinite Dust (0.234375 dust/leather)
Arctic Boots
Frostscale Belt
Iceborne Gloves
Nerubian Legguards

Tailoring
15 Frostweave Cloth, 1 Eternium Thread, 2-3 Infinite Dust (0.125 dust/cloth)
Frostwoven Shoulders
Frostwoven Wristwraps
Frostwoven Gloves
Frostwoven Belt

35 Frostweave Cloth, 1 Eternium Thread, 4-7 Infinite Dust (0.117857 dust/cloth)
Duskweave Belt - Despite giving very slightly less dust/cloth, you save some gold on this pattern because you will have to buy less than half as many Eternium Threads.

Edit: Updated for hotfix during 3.2.2 patch which increased dust drop rates from disenchanting greens."

**Comment by belegija** [comment]
also the chance on armor items for infinite dust seems awful low, meaning that cosmic essences drop more than they should. we should be reserved for disenchanting green weapons

**Comment by npmusicftw** [comment]
I second this entire thread. The DE chance of Cosmic Essence (#34055 & 34056) is significantly higher than the 20% it should be. The exact percentage I am unsure of, but it seems to be more around 50%, give or take.

Secondly, and I'm using Duskweave Boots as an example, when DE'd, I get anywhere from 1-5. 

However, according to WoWhead, you should get anywhere from 4-11. 

http://www.wowhead.com/item=41544/duskweave-boots#disenchanting

17% to get 4
18% to get 5
17% to get 6
20% to get 7
0.6% to get 8
0.3% to get 9
0.07% to get 10
0.09% to get 11

The **average** though, throughout all of them, is roughly 19% chance to get 4,5,6 and 7 Infinite Dust. and then a <1% chance to get 8,9,10 or 11. 

And then a roughly 10% chance to get a 1 or 2**Greater** Cosmic Essence, and a <1% to get 3 or 4. 

Then there is a roughly 3% chance to get a Dream Shard.

Of course, each item varies.

This is data gathered from items of *around* ilvl 162, including but not limited to the entire Duskweave Tailoring set, The Horned and Reinforced Cobalt Blacksmithing armor, and other pieces. 

http://www.wowhead.com/item=40955/horned-cobalt-helm#disenchanting
http://www.wowhead.com/item=40959/reinforced-cobalt-chestpiece

**Comment by Rushor** [comment]
DB/Disenchant: DB: Update amount of enchanting materials from Wrath greens 

* closes https://github.com/dalaranwow/dalaran-wow/issues/1090
* more infos in https://github.com/TrinityCore/TrinityCore/issues/16206
* commit: 9b5b8827feacd7496bf13357e3a28d4034a6d429

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by stubnyag** [comment]
Disenchanting [Duskweave Belt](https://wotlk.evowow.com/?item=41543#disenchanting) yielded 2 [Infinite Dust](https://wotlk.evowow.com/?item=34054)s today. According to the disenchant table it wouldn't even have been possible, because it should have yielded at least 4. The disenchant amounts are still seriously off!
