### ISSUE TITLE
[Item] Runescroll of Fortitude

### ISSUE THREAD

**Issue by Jazex** [dalaranwow/dalaran-wow#1099]
If used with a lower level character, it will still give the full 165 stamina even though the low level character should be ineligible to a scroll of this high level. This will give a lower level a much too high hp pool.

**Comment by Rushor** [comment]
it should not give the buff on targets < level 70. that's the only way it could be fixed currently.

Scripts/Item: Runescroll of Fortitude - Not usable on target < level 70

* closes https://github.com/dalaranwow/dalaran-wow/issues/1099
* commit: 34a26818e9814c8af6e9699e0b4926a9d06b45ad

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
