### ISSUE TITLE
[Stratholme] Just Compensation

### ISSUE THREAD

**Issue by medan** [dalaranwow/dalaran-wow#1108]
http://www.wowwiki.com/Quest:Just_Compensation_%28Alliance%29

In this quest you have to find Lightforge Belt and Lightforge Gauntlets. Belt is BoE drop from some mobs, but Gauntlets are drop from Timmy the Cruel in Stratholme.

http://www.wowwiki.com/Timmy_the_Cruel
http://www.wowwiki.com/Lightforge_Armor

Timmy the Cruel doesn't spawn after you kill all Scarlet Crusade NPC in front of Bastion, so you cant farm him and you are unable to finish this quest.

Mentioned here also #715

**Comment by ashido96** [comment]
Will confirm that this in fact the case as I continued a couple runs today to get the gauntlets.

**Comment by n-ghost** [comment]
Still an issue. 

Guys, please, at least consider adding him somewhere inside the instance, there is a script ready at trinity as well, I believe.

**Comment by Rushor** [comment]
Scripts/Stratholme: Implement spawnmechanic for Timmy the Cruel

* updates https://github.com/dalaranwow/dalaran-wow/issues/1817
* commit: 702123bf62bf3b87f270051acbd8b45b7441d863

once all creature with the id: 10420, 10424, 10418 and 10419 at the Courtyard are killed, timmy will spawn at the place: 3696.851f, -3152.736f, 127.661f,

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
Scripts/Stratholme: Implement spawnmechanic for Timmy the Cruel

* closes: https://github.com/dalaranwow/dalaran-wow/issues/1108

**Comment by Pumadyne** [comment]
Hello, i have run about 20 strat runs over the past few days and Timmy hasn't  spawned once. Was there a trigger implemented that i missed somewhere?
