### ISSUE TITLE
[Quest][Cassic] Kibler's Exotic Pets

### ISSUE THREAD

**Issue by Rathyan** [dalaranwow/dalaran-wow#1125]
Quest: http://www.wowhead.com/quest=4729
Item: http://www.wowhead.com/item=12262

The quest item can be used without targetting a Worg Pup, in any place and it instantly rewards the http://www.wowhead.com/item=12263 which completes the quest right away

**Comment by Demlock** [comment]
Confirmed

**Comment by Rushor** [comment]
DB/Quest: Kibler's Exotic Pets - Capture Worg Pup only targets Bloodaxe Worg Pup

* closes https://github.com/dalaranwow/dalaran-wow/issues/1125
* commit: ca6561baa37fec76d934bbdfadd05c69be9cf9b4
* commit: b9fc857a9e0629a954b9b2b8f633ee5e9cdcf6fa

![GitHub Logo](http://i.imgur.com/hhf99tK.jpg)
![GitHub Logo](http://i.imgur.com/bpHPG92.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
