### ISSUE TITLE
[Quest][Classic] Rescue OOX-22/FE!  [2767]

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#1127]
**Issue:** There is a glitch on the waypoints, as the robot falls down to textures at some point of the escort. It happens only once, just about here:

![asddas](https://f.cloud.github.com/assets/5057942/1978238/0771ce0e-83a1-11e3-9691-572ad639e948.png)

To proceed and complete the quest, you have to wait patiently until the NPC comes back up.

http://wotlk.openwow.com/npc=7807

**Comment by Rushor** [comment]
this whole quest must be reworked because the quest was shortened in wotlk

http://www.wowhead.com/quest=2767/rescue-oox-22-fe#comments:id=799559

As of 3.2, now just requires escort out of feral scar vale to the road immediately north. it then does an awesome green-flame-trail rocket takeoff. turn in still appears to be at the robot chicken guy in booty bay.
completed just now on my 50 mage, was very surprised because i did it a few weeks back with a rogue and had to follow it all the way to the coast.

**Comment by Rushor** [comment]
Scripts/Kalimdor: Quest OOX-22/FE! - Update to WotlK version

* closes https://github.com/dalaranwow/dalaran-wow/issues/1127
* the escortpath is way shorter now and the chicken should no longer fall below the texture/ground
* commit: f237b9b235c31332762c9cb8cb27f5026a75b417
* the summoned creatures should also attack the chicken now

![GitHub Logo](http://i.imgur.com/6kezaNu.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
