### ISSUE TITLE
[World Events] Stranglethorn Fishing Extravaganza

### ISSUE THREAD

**Issue by Rathyan** [dalaranwow/dalaran-wow#1134]
NPC: http://wotlk.openwow.com/npc=15077
Quest: http://wotlk.openwow.com/quest=8193
Achievement: http://wotlk.openwow.com/achievement=306

Riggle Bassbait is not shouting across the zone whenever the event starts or someone wins it. Whenever someone wins the event, he/she can turn in the quest as many time as he/she wants while being able to get both the rewards.

**Comment by Golganeth** [comment]
Confirmed. Also the event starts at 15:00 (one hour late)

**Comment by Rushor** [comment]
DB/Event: Implement "Stranglethorn Fishing Extravaganza"

* Riggle Bassbait will now yell the start of the event 
* Riggle Bassbait will now announce the winner of the event and will despawn after this
* closes https://github.com/dalaranwow/dalaran-wow/issues/1134
* commit: bd40b05503c466f0334d41433e436a0370f1e079

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
