### ISSUE TITLE
[Quest][Classic] The Challenge

### ISSUE THREAD

**Issue by medan** [dalaranwow/dalaran-wow#1135]
http://www.wowhead.com/quest=9015/the-challenge
http://www.wowwiki.com/Quest:The_Challenge

When you enter Ring of the Law in BRD you have to stay in the middle of arena, target NPC High Justice Grimstone imediately when he spawn and place the banner (quest item). But then nothing happen. He just spawn bosses and opens next door as usual. He should not ingore the banner and start some event where you have to fight with another bosses to obtain Top Piece of Lord Valthalak's Amulet.

GM need to autocomplete to be able to continue this quest chain.

**Comment by Rushor** [comment]
DB/Quest: The Challenge - Add spawnevent for Banner of Provocation

* closes https://github.com/dalaranwow/dalaran-wow/issues/1135
* commit: 6754432560d498f78ca68408729d01ddb6a9336a

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
