### ISSUE TITLE
[Quest][Outland] Nexus-Prince Razaan

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#114]
http://www.wowhead.com/npc=21057
This NPC is a Quest NPC for the quest Show Them Gnoem Mercy - http://www.wowhead.com/quest=10675
The NPC should spawn from the gate, after seweral Razaani ethereals are killed nearby, but He is Spawned without killing the ethereals around.
And after its death and object should spawn above the corpse floating
http://www.wowhead.com/object=185033 but thats not happening.

**Comment by Daveonx** [comment]
Currently it seems Nexus-Prince Razaan spawns regardless if players are on the quest or not. Also several animations are missing, from when Razaani ethereals are killed, there [souls](http://www.wowhead.com/npc=20845/blades-edge-deadsoul-orb) should also go inside a tube near the gate where he should spawn, letting players know how many more are needed. As for the oject [Collection of Souls](http://www.wowhead.com/object=185033/collection-of-souls) it spawns after death and despawns correctly after a few seconds.

**Comment by Rushor** [comment]
DB/Quest: Show Them Gnoem Mercy - Implement spawnevent for Nexus-Prince Razaan

* closes: https://github.com/dalaranwow/dalaran-wow/issues/114
* commit: fba0c7798994b880c2b997f7caf69a0dcc6c034d

![GitHub Logo](http://i.imgur.com/XjfZbHl.jpg)
![GitHub Logo](http://i.imgur.com/xfAzBFO.jpg)
![GitHub Logo](http://i.imgur.com/AC5y5yB.jpg)
![GitHub Logo](http://i.imgur.com/1pyL797.jpg)
![GitHub Logo](http://i.imgur.com/7XNWm0l.jpg)
![GitHub Logo](http://i.imgur.com/LXMdice.jpg)
![GitHub Logo](http://i.imgur.com/FxAdb7V.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
