### ISSUE TITLE
[Black Morass] Wrong Portaltimer

### ISSUE THREAD

**Issue by Jazex** [dalaranwow/dalaran-wow#1141]
Portals should open one by one until you have cleared all 18 portals and thus 'Opened the Dark Portal'. However the first 7 portals all open at once (which means a lot of adds will spawn while you're closing the portals one by one). Also the 18th portal spawns a normal portal + the final boss, the count will then also say '19/18'.

**Comment by ashido96** [comment]
There is still a 90-100 second gap between all portals starting with the break between portals 7 and 8.

**Comment by Rushor** [comment]
First fix was:

Scripts/TheBlackMorass: Fix first 7 rifts spawn timings
* commit: 6f98e4106e6a8e03c0319dbb552c1b61bf47d9f3 (already on PTR and live)

The issue left that needs to be fixed is only this:

> There is still a 90-100 second gap between all portals starting with the break between portals 7 and 8.

**Comment by Rushor** [comment]
Scripts/TheBlackMorass: Update Timer for portalspawn

* after portal 7 there will be no longer a waittime of 120000 milliseconds
* only after portal 6 and 12 there will be a 120000 milliseconds waittimer because of the bossspawn (this is blizzlike)
* closes https://github.com/dalaranwow/dalaran-wow/issues/1141
* commit: 5c0a8e86041352a6cdcc030c72fc91d58cdf2c13

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
