### ISSUE TITLE
Quest / NPC: Escape Through Stealth / Volcor

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#1149]
**Quest** - Escape Through Stealth _(ID:995)_
**NPC** - Volcor _(ID:3692)_
- **Issue (1) present:** Once you reach the destination, Volcor will not give you credit for rescuing him at all. 
- **Issue (2) present:** Volcor will not despawn on the end and reset, making him permanetly stuck in one spot until the server restarts or crashes completely.
- **How it should work:** Volcor should also give the credit on the end of the escort and he should reset properly after quest is done.

---

http://www.wowwiki.com/Quest:Escape_Through_Stealth
http://www.wowhead.com/quest=995/escape-through-stealth
http://www.wowwiki.com/Volcor

---

Related quests: #1148 - the only difference in quests is the loot, the process and method is exactly the same.
_Also, player CAN NOT do both of the quests, he can do only one._

**Comment by Stihii** [comment]
Bug still reproduces (05 June 2016).

**Comment by Rushor** [comment]
d290279e197fe38960bca430639b2a6615c19bc4
- he will now properly give the questcredit and despawn and reset after despawn
- testable on ptr

**Comment by Golganeth** [comment]
Gives quest credit but Volcor doesn't attack any enemy, and doesn't say any quote.

**Comment by Golganeth** [comment]
Gives quest credit but Volcor doesn't attack any enemy (he tries to but instantly evades back and forth), and doesn't say any quote on start/end escort.

**Comment by Rushor** [comment]
the escortpath should be reduced + texts: https://www.youtube.com/watch?v=y5AMXINUv3Q

**Comment by Rushor** [comment]
DB/Quest: Escape Through Force + Escape Through Stealth - Rework both questevent

* Volcor will no longer try to do the "sit" emote during the escortpath
* Volcor will become hostile to the furbolgs (he can attack them now)
* updated Volcor's starttext once the quest was accepted
* closes https://github.com/dalaranwow/dalaran-wow/issues/1149
* closes https://github.com/dalaranwow/dalaran-wow/issues/1148
* commit: d290279e197fe38960bca430639b2a6615c19bc4
* commit: 31f6af1fa0ef30570d49f92e99a1baab220ccad7

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
