### ISSUE TITLE
[Quest][Classic] What Is Going On?

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#1163]
**Issue:** What is going on? Well, nothing at all.

**How it should work** : Once you pick up the quest, waves of Elite mobs should appear.

This is the more detailed info I could find so far, regarding the waves. WH comment (Patch 2.4.3):

> _waves of elite soldiers enters the room. This might call a wipe if not threated properly. You might want to clear the hallway first of mobs before talking to Gorshak. When the troopers enters the room, have your warrior/priest/warlock fear them before they get in the room. Eliminate them one by one. CC the rest as your group can.
> A second wave of elite guards will appear too and might do before you're not finished with the first ones._

http://wotlk.openwow.com/quest=3982

**Comment by Demlock** [comment]
This is still an issue

**Comment by DrFuler** [comment]
[21/05/2015] - Still bugged.

**Comment by Anecho** [comment]
This is still an issue.

**Comment by InshadowsAlgalon** [comment]
2016-11-26 still bugged

**Comment by Rushor** [comment]
DB/Quest. Implement:  What Is Going On?

* closes https://github.com/dalaranwow/dalaran-wow/issues/1163
* after accepting the quest, some waves of elite creatures will spawn and attack the player. If you killed all creatures, the quest will be completed.
* commit: dee9c0cc6997bda9873da54cdbd66e2408bd0de5

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
