### ISSUE TITLE
[Game Object] Giant Softshell Clam no loot

### ISSUE THREAD

**Issue by wonopon** [dalaranwow/dalaran-wow#1200]
Giant Softshell Clam (http://wotlk.openwow.com/object=177784) should have a 100% chance of having a soft-shelled clam (http://wotlk.openwow.com/item=15874) according to (https://wotlk-twinhead.twinstar.cz/?item=15874#dropped-by).

After opening around 10, not one of them had any loot whatsoever.

**Comment by Rushor** [comment]
DB/Quest: Clam Bait - Gameobject will always contain "Soft-shelled Clam" now

* closes https://github.com/dalaranwow/dalaran-wow/issues/1200
* commit: b6537c3599aafd8c5aa1eb2c6eff6a3d95deb53a
* note: the http://wotlk.openwow.com/item=15874 will only contain the http://wotlk.openwow.com/item=15924 if you are on the quest http://wotlk.openwow.com/quest=6142
* http://www.wowhead.com/object=177784/giant-softshell-clam#comments:id=112358

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
