### ISSUE TITLE
[NPC] Slitherblade Sorceress and Slitherblade Sea Witch unscripted

### ISSUE THREAD

**Issue by wonopon** [dalaranwow/dalaran-wow#1201]
Both Slitherblade Sorceress (http://wotlk.openwow.com/npc=4712) and Slitherblade Sea Witch (http://wotlk.openwow.com/npc=4719) cast none of their abilities.

**Comment by Rushor** [comment]
DB/Creature: Add abilities for Slitherblade Sorceress and Slitherblade Sea Witch

* closes https://github.com/dalaranwow/dalaran-wow/issues/1201
* commit: 6b46887ba39b3141b0ced7ad2a93e216b644831b

Slitherblade Sorceress - Out of Combat - Cast 'Frost Armor'"),
Slitherblade Sorceress - In Combat - Cast 'Frostbolt'");
Slitherblade Sea Witch - Out of Combat - Cast 'Frost Armor'"),
Slitherblade Sea Witch - In Combat - Cast 'Blizzard'")

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Everything works as intended on ptr, with exeption of Sea Witch's  'Blizzard', which i didn't saw at all.

**Comment by Rushor** [comment]
going to replace the blizzard spell with https://wowgaming.altervista.org/aowow/?spell=6141
