### ISSUE TITLE
[NPC] Franclorn Forgewright

### ISSUE THREAD

**Issue by Gordin508** [dalaranwow/dalaran-wow#1202]
**NPC ID**: 8888
Location: Blackrock Mountain
Link: http://www.wowhead.com/npc=8888/franclorn-forgewright

**Issue Present**: This NPC should only be visible to dead players (--> Player has to be in ghost form), yet at the moment, he is visible and interactable for living players, but not for players in ghost form.

Sidenote: Living players can accept and complete his quests, so this is only a minor issue.

**Comment by Demlock** [comment]
Confirmed.

**Comment by M0dinstaller** [comment]
Still bugged.

**Comment by Rushor** [comment]
DB/Creature: Franclorn Forgewright - should only be visible for dead player

* closes https://github.com/dalaranwow/dalaran-wow/issues/1202

![GitHub Logo](http://i.imgur.com/vUCJHEf.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on ptr.
