### ISSUE TITLE
[Hunter] Aspect exploit

### ISSUE THREAD

**Issue by wonopon** [dalaranwow/dalaran-wow#1216]
You can have one aspect active on your character and a different aspect active on your pet. So for example, you can have aspect of the hawk while your pet has aspect of the beast.

To reproduce: call your pet, activate an aspect (say, aspect of the beast), dismiss your pet, change your aspect (say, aspect of the hawk), call your pet. Your pet will have aspect of the beast and you will have aspect of the hawk.

**Comment by Winstrol** [comment]
confirmed, still bugged.

**Comment by Rushor** [comment]
Game/Player: Hunter - Remove aspect of the beast from pet if owner do not have the aura

* close https://github.com/dalaranwow/dalaran-wow/issues/1216
* commit: da1be1bdcf75047a2d153ed4b7626a4defd1d2c0

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on PTR.
