### ISSUE TITLE
[Love is in the air] [Quest] [Horde] Pilfering Perfume doesn't work while mounted

### ISSUE THREAD

**Issue by wonopon** [dalaranwow/dalaran-wow#1218]
Pilfering Perfume (http://wotlk.openwow.com/quest=24541) works fine if you accept the quest while unmounted, but if you are on a mount, the quest is problematic. When you ride by the goblin npcs they throw you a crate but you do not get the "carrying crate" buff (sorry, can't find a link to the buff).

**Comment by Rushor** [comment]
DB/Quest: Pilfering Perfume - Inspector/Detective Snip Snagglebolt should always dismount the player on quest accept

* involved quests: http://wotlk.openwow.com/quest=24541 and http://wotlk.openwow.com/quest=24656
* closes https://github.com/dalaranwow/dalaran-wow/issues/1218
* commit: 8b3fd415a5c2053cb8b6a2fa99a6a69e080be64f

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
