### ISSUE TITLE
[Quest][Classic] An Unusual Patron

### ISSUE THREAD

**Issue by wonopon** [dalaranwow/dalaran-wow#1228]
The quest An Unusual Patron (http://wotlk.openwow.com/quest=9457) can be completed, but it is not properly scripted. The summoned npc Naias
(http://wotlk.openwow.com/npc=17207) should spawn in front of the altar, and also say some text.

I found these two videos of how the quest should work: 
http://www.youtube.com/watch?v=JmRdm2ls6s4
http://www.youtube.com/watch?v=HWp_PvLtKlA

**Comment by AgeAgainst** [comment]
As of 17 January 2014, was able to complete this quest. Naias doesn't spawn in front of the altar.  He spawns approximately 20.5, 23.

**Comment by Rushor** [comment]
DB/Quest: An Unusual Patron - Add spawnevent for Naias

* once Naias was summoned he will talk a sentence
* the summonposition of Naias was moved to the altar
* added a spellcooldwon for the item of 30 seconds
* added a restriction that you cannot use "Gift of Naias" if there is a Naias in 100 yards range
* closes https://github.com/dalaranwow/dalaran-wow/issues/1228
* commit: 02cfd2ce88234f573ae75e45c0d583832fe3a0f8

![GitHub Logo](http://i.imgur.com/wpZLbRR.jpg)
![GitHub Logo](http://i.imgur.com/E0i42TL.jpg)
![GitHub Logo](http://i.imgur.com/FXFgpQi.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
