### ISSUE TITLE
[NPC] Skullsplitter Spiritchaser unscripted

### ISSUE THREAD

**Issue by wonopon** [dalaranwow/dalaran-wow#1233]
Skullspitter Spiritchaser (http://wotlk.openwow.com/npc=672) is not casting any of its abilities.

**Comment by Rushor** [comment]
DB/Creature: Skullsplitter Spiritchaser - Add SAI

* closes https://github.com/dalaranwow/dalaran-wow/issues/1233

"Skullsplitter Spiritchaser - Between 0-40% Health - Cast 'Healing Wave'"),
"Skullsplitter Spiritchaser - In Combat - Cast 'Lightning Bolt'"),
"Skullsplitter Spiritchaser - In Combat - Cast 'Mana Burn' (No Repeat)");

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on ptr.
