### ISSUE TITLE
[Quest][Classic] Catch and Release

### ISSUE THREAD

**Issue by grugsy** [dalaranwow/dalaran-wow#1238]
credit not given for tagging scouts

**Comment by Daveonx** [comment]
Credit is now given when tagging the [Blacksilt Scout](http://www.wowhead.com/npc=17326/blacksilt-scout), although there is a minor issue, they don't despawn when the debuff [Tag Murloc](http://www.wowhead.com/spell=30877/tag-murloc) expires from them. This allows player to be able to tag the same scout multiple times.

**Comment by Rushor** [comment]
DB/Creature: Blacksilt Scout - Add despawn on spellhit of Tag Murloc' after 30 seconds

* closes https://github.com/dalaranwow/dalaran-wow/issues/1238
* commit: e9802016ec781509dd816049944849c6e8dcc8e7

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
