### ISSUE TITLE
Bloodmyst Isle- Amberweb Pass all screwed up

### ISSUE THREAD

**Issue by grugsy** [dalaranwow/dalaran-wow#1240]
scripting/location is jacked up for all the websacs/webbed creatures. named spider that should be at end of path is found in a websac instead. websacs also wander around? lol

**Comment by n-ghost** [comment]
Webbed Creatures won't move around anymore, but still somehow can pop every named hostile mob encountered before on the island (including Zarakh, a spider that you need to kill for the quest nearby).

Probably should be looked into.

**Comment by n-ghost** [comment]
Also, Webbed Creatures give exp upon killing and drop some stuff like Coarse stones, which shouldn't be the case.

**Comment by Rushor** [comment]
DB/Creature: Webbed Creature - Remove Movement, Remove Loot, Remove XP-Gain

* closes https://github.com/dalaranwow/dalaran-wow/issues/1240
* commit: a57042345e9be2c2ce5f1d5db3cd74d6cf437d24

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
