### ISSUE TITLE
[Mechanic] Guard damage is too low

### ISSUE THREAD

**Issue by Hatebugs** [dalaranwow/dalaran-wow#1246]
[NPC] Goblin Bruisers Severely + City Guards Underpowered

One issue that I keep noticing is the Goblin Bruisers (http://www.wowwiki.com/Goblin_Bruiser) protecting the Steamwheedle Cartel towns are far, far weaker than they should be. People are exploiting that fact to grief the opposing faction by killing flight masters, bankers, and auctioneers as well as attacking other players with impunity. This is compounded by the fact that the Bruisers lack their Shoot ability (or just don't use it), allowing players to exploit line-of-sight and/or jump into the water to avoid being attacked.

Booty Bay and Gadgetzan have the most frequent occurrences. I have repeatedly seen level 40 players surviving being attacked by 5+ level 77 Bruisers. A single level 80 character can clear out the entire town of guards and NPCs without suffering any loss of health whatsoever.

Yes, I realize this is on a PvP server, but unless you're max level with a pretty good gearset, attacking someone in sight of five guards should be almost an instant death sentence.

They also pull out guns and start knocking you back when they are unable to reach you by foot. The knock-back is considerable. This is not shown on the wowhead website.

Booty Bay Bruiser damage: 256-349
http://wotlk.openwow.com/npc=4624
Gadgetzan Bruiser: 666-907
http://wotlk.openwow.com/npc=9460
Everlook Bruiser: 384-524
http://wotlk.openwow.com/npc=11190
Ratchet Bruiser: 94-129
http://wotlk.openwow.com/npc=3502

**Comment by Rushor** [comment]
**[NPC] Goblin Bruisers Severely + City Guards Underpowered**

One issue that I keep noticing is the Goblin Bruisers (http://www.wowwiki.com/Goblin_Bruiser) protecting the Steamwheedle Cartel towns are far, far weaker than they should be. People are exploiting that fact to grief the opposing faction by killing flight masters, bankers, and auctioneers as well as attacking other players with impunity. This is compounded by the fact that the Bruisers lack their Shoot ability (or just don't use it), allowing players to exploit line-of-sight and/or jump into the water to avoid being attacked.

Booty Bay and Gadgetzan have the most frequent occurrences. I have repeatedly seen level 40 players surviving being attacked by 5+ level 77 Bruisers. A single level 80 character can clear out the entire town of guards and NPCs without suffering any loss of health whatsoever.

Yes, I realize this is on a PvP server, but unless you're max level with a pretty good gearset, attacking someone in sight of five guards should be almost an instant death sentence.

**Issue 2 :**
[PVP] Attack power of Guard in City is too weak to player

The Attack power of Guard in City is too weak to player.
In honorhold of outland, two lv 60 DKs can kill all of honorhold guard if they want.
I suggest increase the damage of guard. it should be same as retail at least.

**Comment by Rushor** [comment]
DB/Creature: Increase Damage for Booty Bay Bruiser, Gadgetzan Bruiser, Everlook Bruiser and Ratchet Bruiser and add combatspells

* closes: https://github.com/dalaranwow/dalaran-wow/issues/1246
* commit: 40837dbd7676c103adc19366fec36eca4369a215

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.


Please research the entries of the guards that should have increased damage in the capital cities/outland etc. I only fixed the damage for the goblin guards now.

**Comment by Rushor** [comment]
http://wowwiki.wikia.com/wiki/Guard this could be helpfull, however that list is still missing the entries of the guards from outland (like th ones in honor hold)
