### ISSUE TITLE
[Warrior] Sword and Board talent  -Proccissues

### ISSUE THREAD

**Issue by Gendori** [dalaranwow/dalaran-wow#1255]
Sword are Board partly works. There are a few different things that can happen:

A. Sword and Board procs, and your above 20 rage. It might not consume the proc, and use the 20 rage as normal for Shield Slam.

B. Sword and Board procs, and your below 20 rage. It might not let you use Shield Slam at all.

C. Sword and Board Procs, and your exactly at 20 rage. It might do either of the above two.

D. Sword and Board procs, it works as it should, no rage, free, CD reduction Shield Slam.

The problems are upon A, B, and C.

**Comment by taralej90** [comment]
Confirmed. This talent only works when it's in a good mood, it seems.

Sometimes the buff is not consumed, sometimes rage is used when S&B has procced, sometimes you can't use Shield Slam when you're under 20 rage even though you have S&B, and sometimes it just works properly...

**Comment by taralej90** [comment]
Hello, after the update it seems Sword and Board still has these issues. Shield Slam sometimes ignores Sword and Board's proc, not consuming it and costing rage. Are we working on a solution for this?

**Comment by robinsch** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/542

**Comment by Rushor** [comment]
same problem with "omen of Clarify"

Fix from robin is already on PTR:

[3.3.5] Core/Spells: Omen of Clarity

by @robinsch; closes #3088.

Purpose: make the Omen of Clarity druid buff (http://wotlk.openwow.com/spell=16864) work as intended.

This change is an addition to @Shauren's commit 37145b6.
Before this change, spell mod auras lose charges when they are unable to be cast
as mentioned in the issue. As an example: Omen of Clarity loses its charge
when Shred can not be used, because it requires the caster to behind the target.

This change will restore the spell mod if CheckCast returns false for the initial cast.

* commit: 07df574b432c641c37691b43d199daa4f69b2602

**Comment by TeridanDW** [comment]
Can't reprocude A or B or C after the fix anymore, works as intended on ptr.

**Comment by TeridanDW** [comment]
> Can't reprocude A or B or C after the fix anymore, works as intended on ptr.
