### ISSUE TITLE
Profession: Fishing issues

### ISSUE THREAD

**Issue by aldaan** [dalaranwow/dalaran-wow#1275]
**Issue present:**
It seems to me that junk items like http://wowpedia.org/Driftwood can't be fished up. Instead, when the player's skill is too low for the zone, many attempts would fail, giving the message "Your fish got away!".

**How does it work currently:**
I am able to fish in any zone regardless of skill level, as it should work, but whenever I fish in an area that's too high for me, I often get the message "Your fish got away!", and I get no skill points from these attempts.

**How it should work:**
According to http://wowpedia.org/Fishing:

"The mechanics of fishing skill level were changed significantly in Patch 3.1. Prior to 3.1, each zone had a minimum skill requirement to be able to cast in that zone, and a cap where you achieved a 100% catch rate in that zone. In between there was a chance your fish could "get away"; you would catch nothing and receive no skill-up for that cast.
As of 3.1, there is no longer a minimum skill requirement to fish in any zone, and all casts will catch something and award a chance for a skill-up. However, if your skill level is too low for a zone, you will catch mostly vendor trash items. The skill level required to guarantee "no junk" catches is equivalent to the old "no get away" level."

**Comment by n-ghost** [comment]
Is it happening D:?

![wowscrnshot_071415_150328](https://cloud.githubusercontent.com/assets/8515510/8672729/d0a1f6ce-2a39-11e5-9174-58bb7a5d213f.jpg)

**Comment by Golganeth** [comment]
Quoting Demlock: - (#2420)
> This bug is present pretty much everywhere you fish. Sometimes it just happens so that you can't at all fish up from this blubber. I usually just recast it, without waiting for the message.

**Comment by Golganeth** [comment]
Quoting Demlock: - (#2420)
> "This bug is present pretty much everywhere you fish. Sometimes it just happens so that you can't at all fish up from this blubber. I usually just recast it, without waiting for the message".

Quoting Glitterlance: - (#2513)
>"While fishing occasionally there is a message "no fish are hooked" right after I open the loot window." (and can't loot)

**Comment by Golganeth** [comment]
Quoting @Demlock: - (#2420)
> "**This bug is present pretty much everywhere you fish. Sometimes it just happens so that you can't at all fish up from this blubber. I usually just recast it, without waiting for the message".**

Quoting @Glitterlance: - (#2513)
>"**While fishing occasionally there is a message "no fish are hooked" right after I open the loot window." (can't loot afterwards)**

Quoting @Niaseer - #3220 
>"**sometimes when you click the fishing bobber you won't get any fish and then it'll time out leaving the bobber behind; Then if you cast out again you'll have two bobbers up at the same time and either could catch a fish but if the previously bugged one splashes you won't be able to catch the fish.**"

**Comment by Rushor** [comment]
> "The mechanics of fishing skill level were changed significantly in Patch 3.1. Prior to 3.1, each zone had a minimum skill requirement to be able to cast in that zone, and a cap where you achieved a 100% catch rate in that zone. In between there was a chance your fish could "get away"; you would catch nothing and receive no skill-up for that cast.
As of 3.1, there is no longer a minimum skill requirement to fish in any zone, and all casts will catch something and award a chance for a skill-up. However, if your skill level is too low for a zone, you will catch mostly vendor trash items. The skill level required to guarantee "no junk" catches is equivalent to the old "no get away" level."

This system was implemented now.

Game/Player: Update Fishing to a progressive skillup system and adjust the skill formula to Patch 3.1

* closes https://github.com/dalaranwow/dalaran-wow/issues/1275
* commit: 2d73e19adc3acd1eb47bcaa464a0410836704a39

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
some more infos on this:

Skill ups are based on the number of fish (or junk items) caught and nothing else!
http://wowwiki.wikia.com/wiki/Fishing?oldid=2265049#Increasing_fishing_skill

Don't forget, in patch 3.3.0 you never catch trash from fishing pools, regardless of skill.
https://web.archive.org/web/20091031133520/http://blue.mmo-champion.com/1/11155811788-2610-northrends-new-kaluak-fishing-derby.html
http://wowwiki.wikia.com/wiki/Patch_3.3.0_%28undocumented_changes%29#cite_ref-7

**Comment by Rushor** [comment]
The remaining issue with player unable to click on the bait will be handled in https://github.com/dalaranwow/dalaran-wow/issues/3531
