### ISSUE TITLE
[Item] Toy Train Set and Wind-Up Train Wrecker

### ISSUE THREAD

**Issue by elliotthehobo** [dalaranwow/dalaran-wow#1323]
The Toy Train Set doesn't cause the players standing around it to spam /train.
This is a core feature of the Wrath of the Lich King expansion and should be fixed as soon as possible to avoid new players leaving because of the lack of this feature.

**Comment by Rushor** [comment]
Item/Misc: Implement Toy Train Set and Wind-Up Train Wrecker.

* closes https://github.com/dalaranwow/dalaran-wow/issues/1323
* Ref: https://github.com/TrinityCore/TrinityCore/pull/16218
* commit: 38a0c81060dec45b5d59edf36672e712c9d96982

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
