### ISSUE TITLE
Herb spawns

### ISSUE THREAD

**Issue by Maloreon** [dalaranwow/dalaran-wow#1345]
I think any herbalist on the server would agree that herb spawns are not blizzlike and can be very difficult to find.  I am sorry if this is too ambiguous but there is something very off about herb spawns, respawns, locations, or rates on this server leading to a MAJOR shortage.  Notable zones would be all of Northrend.  Lower level herbs can be difficult to find.  Also there are massive over-spawns of herbs where there will be 5-10 of an herb within 20 yards including zones like Redridge (Bruiseweed) and Burning Steppes (Mountain Silversage, Dreamfoil, Black Lotus, etc.).  Hope this helps.  The first issue to look at would most likely be the Northrend zones as this is bottle necking the endgame crafting professions tremendously right now.

**Comment by M0dinstaller** [comment]
So what's being done about this ? It's been 1 year.

I've had problems leveling herbalism through all vanilla zones. Thanksfully Alterac is stuffed with dozens and dozens of herb nodes so that's been my salvation ... but now I'm looking at outland and there are barely any nodes. I went to SMV in search of nightmare vines for the potion mastery quest. I circled through the whole zone and found none. There aren't any nightmare vines in this server. This item is near unobtainable ...

I also think there's a problem about northrend zones ... Zul'drak seems fine, but grizzly hills for example is devoid of any herb node. I found around 10 in total in the whole zone ... is this Blizzlike ?
I can't say for sure since I've never played wotlk retail but really, 10 nodes in a zone seems a bit exaggerated.

**Comment by thereaverofdarkness** [comment]
It's two bugs: the original game had individual herb nodes each possessing a variety of locations in which they could spawn in order to make their placement look random, but statistics processing databases perceived every location as a separate node, thus leading to huge numbers of herbs. The second bug is that sometimes a used node fails to respawn. This causes a region to gradually become devoid of herb or ore nodes. The server must force a reset of these nodes periodically as a temporary fix, until they figure out how to solve the problem permanently. The best thing you can do right now is let the admins know when this happens, so they can force a reset. And don't wait up for a fix,I think it's already been fixed on later private server engine models, but for these old ones it's more trouble than it's worth so probably will never be fixed.

**Comment by Rushor** [comment]
moved to general issue https://github.com/dalaranwow/dalaran-wow/issues/1208
