### ISSUE TITLE
High drop rate [Algalon]

### ISSUE THREAD

**Issue by swagsloth** [dalaranwow/dalaran-wow#1356]
I believe the drop rate is way higher than it should be.

A total of 5 epic's on chars under lvl 40. Two of them droped in a SINGLE dungeon.
Even in a high populated server you don't see as much epics on the AH...

**Comment by Demlock** [comment]
Confirmed. This may be due to wrong formulas for drop chance. In any case, rares and epics drop way too often. This not only lowers the price of such items to the point that some items are sold on the AH for less gold than an NPC shop assistant would give you for it but also causes your bags to be filled with items faster than usual.

**Comment by Rushor** [comment]
The rates for such drops can only be modified from the server-owner. On PTR the reates are X1 and blizzlike.
