### ISSUE TITLE
[Profession#Leatherworking][Outlands][Spells/Auras] Drums of Restoration

### ISSUE THREAD

**Issue by Joana123** [dalaranwow/dalaran-wow#1374]
Drums of restoration - http://www.wowhead.com/item=29531/drums-of-restoration

Right now, they work for 80+. I tested in-game and recieved the mana/health points. As the tooltips say, they shouldnt work for level 80s. I haven't tried "Drums of war" but I'd only assume since they're both TBC drums that don't work at lvl 80, the other drum might work since drums of restoration do.

**Comment by Rushor** [comment]
DB/Spell: Drums of Restoration + Drums of War + Drums of Battle - Only targets player equal or lower level 79

* closes https://github.com/dalaranwow/dalaran-wow/issues/1374
* commit: 50c5ec771b1772fa19bfd3173320c46eb06f5c98

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
