### ISSUE TITLE
[Hunter] Pet Talent : Improved Cower

### ISSUE THREAD

**Issue by asdmlfld** [dalaranwow/dalaran-wow#1385]
Hey there i was respeccing the talents of my Pet and i found out that talent that reduces the movement speed penalty of the "Cover" spell, does not reduce the movement speed penalty of the "Cover" spell of my pet.
I tried it out by running in a line and letting the pet follow, with my Aspect of the Cheetah and the pet should be able to follow me, but it walked alot slower then me when i used "Cower".
there for the spell is not working.

**Comment by Rushor** [comment]
Scripts/Spells: Hunter Pet - Add script for Pet's Cover

* closes https://github.com/dalaranwow/dalaran-wow/issues/1385
* commit: d72cb1a52f42c4c72f49e3bc8740b1bb0cb2baa0

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on PTR.
