### ISSUE TITLE
[Battlegrounds] Spell: Spirit Heal (44535)

### ISSUE THREAD

**Issue by Rathyan** [dalaranwow/dalaran-wow#1422]
NPC: http://wowhead.com/npc=13116
Spell: http://wowhead.com/spell=22012
Bugged Effect: http://wowhead.com/spell=44535

When you get ressed by the Spirit Guide you get the buff Spirit Heal (44535) which allows you to cast any spell or ability free of cost. Currently this works only for spells that cost mana. Rage, energy and runic power abilities still cost resources

**Comment by Rushor** [comment]
http://forum.buffed.de/index.php/topic/145428-geistheilung/

Wenn man im BG oder 1k stirbt bekommt man ja für 5sec nachm wiederbeleben den Buff "Geistheilung" (verringert Kosten von Zaubern um 100%), der, höchstwarscheinlich, dazu da ist um sich zu buffen.
Jetzt würde ich gerne mit meinem Krieger Befehlsruf buffen, aber bekomme immer gesagt ich hätte nicht genug Wut, obwohl ich durch Geistheilung ja eigentlich keine brauche.
Hab dann ein Ticket geschrieben, und später ingame-Post bekommen: Sie haben mein Problem genau untersucht und keinen Fehler gefunden. Wieso kann ich dann keinen Befehlsruf buffen?
Was sagt ihr dazu? Nochmal Ticket schreiben? Oder gibts sonst irgendwo Bugreports? 

Translation to english: The dude from the forum tells us that teh cannot use his spell Commanding Shout with the buff Spirit Heal because he has to less rage.

===
The issue is blizzlike then
