### ISSUE TITLE
[Mechanic] Mind Control Effects and related Movement of the target

### ISSUE THREAD

**Issue by Draculle** [dalaranwow/dalaran-wow#1451]
Mind Control from The Burning Crusade AREA and Dungeons,being MC'ed and after i've Used my Trinket, or killed the NPC still returning to the Same spot where he died or i was MC'ed before

This is the Screen shot i've made after i defeated the NPC and still bugging in the air as a Hacker : http://postimg.org/image/atkvu1i7z/ ...

**Comment by Rushor** [comment]
people should no longer run around once the charm fades away (so the chamed unit should no longer walk back to the position where the charmer died)

Game/Unit: Clear Motion on remove of Charm Effects

* closes: https://github.com/dalaranwow/dalaran-wow/issues/1451
* commit: 85770846f66f7e9e2f011b86ea85a6e69f2d8e48

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.


PS: Moreover the whole charm system will be reworked and the related issue should be fixed once https://github.com/TrinityCore/TrinityCore/commit/4e4b2b9a138650ebe6087e18dc392f08dafe4e37 is merged on the live realm.
