### ISSUE TITLE
[NPC] Anachronos not despawning at 20%

### ISSUE THREAD

**Issue by Joana123** [dalaranwow/dalaran-wow#1471]
On "http://www.wowwiki.com/Anachronos" under "Trivia" it says "If you try to kill him, he will despawn at 20% and say: "A terrible and costly mistake you have made. It is not my time, mortals."

Anachronos at 21%: http://i.imgur.com/uXQvVCO.jpg
Anachronos at 20%: http://i.imgur.com/IeeIvLB.jpg
Anachronos at 19%: http://i.imgur.com/BA35Fu3.jpg
Anachronos at 0%: http://i.imgur.com/n9TYc7B.jpg

Yeah... So it should despawn at 20% but doesn't. Thanks for reading.

**Comment by Rushor** [comment]
DB/Creature: Anachronos - Add despawn and text at 20 % health

* closes https://github.com/dalaranwow/dalaran-wow/issues/1471
* commit: 4e592bb94e08ee21d17c8bd635c09526a1bf17db

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
This was fixed together with: https://github.com/dalaranwow/dalaran-wow/issues/2800
