### ISSUE TITLE
[Quest][Classic] Intercept The Reinforcements

### ISSUE THREAD

**Issue by Jazex** [dalaranwow/dalaran-wow#1474]
This is broken again, copied this from the former (closed) issue, since it's the same problem again.

http://www.wowhead.com/quest=11542/intercept-the-reinforcements
http://www.wowhead.com/quest=11543/keeping-the-enemy-at-bay

These two have the same objectives and:

Here's how to complete the quest:

1) Go over to the Dragonhawk flight master (the same one you start the bombing run over The Dead Scar). (works)
2) Select the bombing run option. (works)
3) Make sure you have the bomb in your bag and ready to fire. (works)

4) You fly by each ship (as seen in the screenshot). Throw one bomb onto each ship. One bomb will give you credit for the ship. (DOES NOT WORK - no credit is given for targeting and hitting the ships)

5) Once you land, start killing the Reservists on the ship. If one ship is entirely full, try one of the other two. (works, killing them gives credit)
6) Once done, go back to the original ship you landed on. There will be a Dragonhawk there. Talk to it, and select "Take me back". (works as well)

**Comment by ashido96** [comment]
From a couple other threads saying this was fixed, step 4 as described above still does not work.

**Comment by sixele** [comment]
Both quests still do not work, same issue with the bombs.

**Comment by Rushor** [comment]
most likeley the credit is given by the creature on death with a spell. but since the player is on a taxi, the spell will not be casted on the player (invalid target). someone can confitm this?

**Comment by Braniacz** [comment]
Both quests still do not work, same issue with the bombs and ships

**Comment by Rushor** [comment]
DB/Quest: Intercept The Reinforcements + Keeping the Enemy at Bay

* increase range for spell "Quest - Sunwell Daily - Ship Bombing Run Bomb", you can easier spellhit the triggers on the ship now
* questcredit on spellhit of the triggers on the ship will now be rewarded
* the gossipoption from Unrestrained Dragonhawk to fly back to the island will also be displayed if you have the quests already completed
* closes https://github.com/dalaranwow/dalaran-wow/issues/1474
* commit: 242ab002c7b2d6e33d6eef8d43a380defceffe77

![GitHub Logo](http://i.imgur.com/3S06F1I.jpg)
![GitHub Logo](http://i.imgur.com/akZZt9X.jpg)
![GitHub Logo](http://i.imgur.com/OzqVZDx.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by joki8** [comment]
This doesn't work again.

**Comment by Rushor** [comment]
It's only on PTR for now
