### ISSUE TITLE
[Mechanic] Special Professions Save and Switch (Blacksmithing/Gnome Engineering)

### ISSUE THREAD

**Issue by ReaverB** [dalaranwow/dalaran-wow#1483]
After becoming an Armorsmith or Weaponsmith in Org you are able to switch between them by speaking to the trainer and dropping one you picked for 10 gold. This works as it did on retail.

You are then able to switch by talking with the other specialty Blacksmithing trainer. This also works.

This change does not persist through a logout and the original specialty will be active again. Also if you had gear equipped that required the new specialty they are removed from your toon and mailed to by customer support.

I tested this by dropping Armorsmithing and acquiring Weaponsmithing then relogging, and also by simply dropping Armorsmithing and relogging. The results were the same.

This could affect other profession specialties too.

**Comment by Rushor** [comment]
http://www.wowwiki.com/Gnome_Engineering

To become a proud engineer of gnomish wonderworks player must:
- get a 200 skill in Engineering;
- complete the quest: http://www.wowwiki.com/Quest:Gnome_Engineering ;
- complete the following quest: either http://www.wowwiki.com/Quest:The_Pledge_of_Secrecy_%28Ironforge%29 (for IF trainer, obviously) or http://www.wowwiki.com/Quest:The_Pledge_of_Secrecy_%28Stranglethorn_Vale%29 (for STV trainer);
- complete http://www.wowwiki.com/Quest:Show_Your_Work_%28Gnome%29 afterwards and get a specialization as a reward;

Only after that player should get the access to all the schematics that his specialization offers.

Currently any alliance player can get Gnome Engineering recipes from Tinkmaster Overspark regardless of any requirements (save for skill level), which severely compromises security of Gnomeregan as whole.

Need to be tested with Horde\Goblin engineering trainers as well.

**Comment by Rushor** [comment]
**[Blacksmithing] - You can learn weaponsmith recipes while being armorsmith.**

**Current behaviour**: You can learn weaponsmith recipes while being armorsmith.

**Expected behaviour**: You shouldn't be able to learn weaponsmith recipes while being armorsmith.

**Steps to reproduce the problem**:

1. Finish the quests to be an armorsmith and go talk to the weaponsmith in dalaran or any other city where there is a weaponsmith trainer.
2. Learn what he has to offer you (some of those recipes can be learned and that's correct but recipes like "Light Earthforged Blade" which does require you to be weaponsmith shouldn't be learnable)

In the following link it explains how only a blacksmith who have learned the weaponsmithing specialty can learn this recipe.
http://wowwiki.wikia.com/wiki/Light_Earthforged_Blade

While on this link it tells you that prior to 2.0.3 you had to have the weaponsmith specialty to learn the recipe.
http://wowwiki.wikia.com/wiki/The_Shatterer

**This fix should be applied to all recipes which have a specialty requirement on the crafted item**

**Comment by Kookaburra129** [comment]
Currently facing the issue of not being able to train Gnomish Engineering.
The quest needed to start the chain (in Undercity for Horde players) isn't available and neither are any of the quests that come later on.

Figured this is a related issue so posting here, this is being faced by many players afaik.

**Comment by Lothloryen** [comment]
Hello there,

This will be now working fine after the next maintenance.
