### ISSUE TITLE
[Quest][Classic] The Wayward Apprentice and Saltheril's Haven

### ISSUE THREAD

**Issue by Prljoman** [dalaranwow/dalaran-wow#1485]
Hello! There is a problem with 2 quests (mentioned above in title) which should be obtainable by NPC Magistrix Landra Dawnstrider. The Wayward Apprentice can't be turned over to the Apprentice Mirveda because you can't talk to Mirveda at all (when you take quest from Landra it automatically says Objective complete, maybe that has to do with anything...), neither does she have question mark. When you complete it on retail, Mirveda gives you 2-3 quests...
Saltheril's Haven isn't even obtainable from Landra. I tried reloging and reloading UI, but that didn't solve the problem for both of those quests. If I see any other bugged quest in this zone, I'll report it (I apologize if this issue has been already reported). Thank you for reading.

Magistrix Landra Dawnstrider and her quests: http://www.wowwiki.com/Magistrix_Landra_Dawnstrider

**Comment by ashido96** [comment]
Gonna go ahead and say that you still can't obtain the quest "Saltheril's Haven" from "Magistrix Landra Dawnstrider"

**Comment by Demlock** [comment]
Yes, this quest is still bugged.

**Comment by DeSis** [comment]
Tried, the npc can't be interacted

**Comment by sspecterr** [comment]
This topic was created one year ago and still bugged. WTF, guys?

**Comment by Ryan295** [comment]
This is still an issue. Specifically with the NPC Apprentice Mirveda. She is still stuck underneath the ground and cannot be interacted with.

**Comment by Rushor** [comment]
DB/Creature: Apprentice Mirveda - Set creature active on queststart and move the spawnlocation to a better mapposition

* closes https://github.com/dalaranwow/dalaran-wow/issues/1485
* closes e8d154f1c3215d48de472e7a8dbf5ae9523f5167
* moved the creature to a better maparea, where she cannot drop so easy under the ground
* also set her active in order to prevent stucking if the player leaves the area during the questevent

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
