### ISSUE TITLE
[Mage] Brain Freeze

### ISSUE THREAD

**Issue by pascagabriel** [dalaranwow/dalaran-wow#1486]
Brain Freeze has no internal cooldown allowing Frostfire Bolt to proc the talent back to back.
"Patch 3.3.3 (2010-03-23): This talent now allows your next Fireball or Frostfire Bolt to be instant and cost no mana. There is a small internal cooldown to keep the Frostfire Bolt from immediately triggering Brain Freeze again."

**Comment by Rushor** [comment]
DB/Spell: Mage - Brain Freeze - Add 3 seconds internal cooldown

* closes https://github.com/dalaranwow/dalaran-wow/issues/1486
* commit: 82d3272f08ba55b8f0f7c2d33a5ebeb2614e930a

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
@AttendantTock I think it still procs from the instant Fireball or Frostfire Bolt (does no honor the 3 sec internal CD), but I want second opinion.

**Comment by AttendantTock** [comment]
Hello,

I did some tests using Frostfire Bolt, but I wasn't too sure. The travel time and the cooldown are giving the impression it doesn't respect the 3s iCD.

So I ran another series of test, using Cone of Cold and a macro (off GCD spell to spam and a lot of dummies to near-guarantee the proc).
I found that the 3s iCD is respected, whether the proc is consumed (1st half of video) or refreshed (2nd half).
