### ISSUE TITLE
[Item] Iron Boot Flask - Missing spelcast for Electric Discharge

### ISSUE THREAD

**Issue by Cinderhelm** [dalaranwow/dalaran-wow#1491]
The buff seems to get removed randomly before the promised duration expires upon taking damage.

Moreover, the passive effect of the flask does not trigger. It should randomly hit mobs with http://www.wowhead.com/spell=29151 . Additional information on how it works may be needed here.

**Comment by Rushor** [comment]
http://www.wowhead.com/spell=29151/electric-discharge#comments:id=988943

It procs off damage taken. Confirmed this while grinding netherwing rep. Basicly it makes no difference at all (150-300 dmg) But seeing as i got like 4-5 procs off in about 5-6 minutes of the flask duration it should be able to proc around once or twice per minute. So if you're tanking i'd say popping this flask might just add that tiny bit extra threat. Who knows?

**Comment by Rushor** [comment]
Game/Spells: Electric Discharge - Enable spellcast in meleerange

* closes https://github.com/dalaranwow/dalaran-wow/issues/1491
* commit: c811be77e08dd40d9d268ac3ec260182d128894e

![GitHub Logo](http://i.imgur.com/qkalCG1.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
