### ISSUE TITLE
Quest: Springing the Trap

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#150]
http://www.wowhead.com/quest=11969
The quest item Raelorasz' Spark does not lights the signal fire, but knocks the player down
http://www.wowhead.com/item=44950

**Comment by Lothloryen** [comment]
Hello there,

This quest shall be working as it should after tomorrow's morning maintenance.

Thank you very much.

**Comment by Mantigora** [comment]
nice job, guys! Ty for nice scripting it :)

**Comment by Zibathy** [comment]
Still bugged on Kirin Tor.
![wowscrnshot_011617_201613](https://cloud.githubusercontent.com/assets/7729864/22005446/da7b9f4a-dc28-11e6-8da2-ef0c1483d886.jpg)
![wowscrnshot_011617_201620](https://cloud.githubusercontent.com/assets/7729864/22005448/da8890d8-dc28-11e6-9fbe-44f092fafcb9.jpg)
![wowscrnshot_011617_201738](https://cloud.githubusercontent.com/assets/7729864/22005447/da7d5722-dc28-11e6-83cb-151a07cfc677.jpg)

**Comment by Rushor** [comment]
test it on algalon

**Comment by Raulfin** [comment]
Still knocks the player down on KT.

**Comment by Aridam** [comment]
Works on Algalon, albeit in need of improvements with the provided video used as the pointer.

1. Keristrasza flies on the ground instead of landing and walking at the start;
2. Quest gets tagged as completed from the very moment you use the Quest Item (haven't attempted to go hand it in having noticed that though -- to see the rest of the script off, which leads to the following);
3. At the end, the script doesn't seem to finish -- there _was_ a Mob nearby that upon landing from being on Keristrasza's back that attacked me at that point so perhaps that interrupted it(?), but the exchange between her and Malygos didn't happen for me.
