### ISSUE TITLE
[Item] Curious Crate - Outland fishing

### ISSUE THREAD

**Issue by ReaverB** [dalaranwow/dalaran-wow#1508]
http://www.wowhead.com/item=27513/curious-crate#comments

http://www.elsanglin.com/fish/curious_crate.html

The drop rates seems correct, 5% from fishing nodes.

However I've only gotten Knothide Leather scraps. In Patch 3.3.2 they were upgraded/replaced with Knothide Leather.

Small bug, but annoying when you need an alternative method to gather mats.

**Comment by Rushor** [comment]
http://www.wowhead.com/item=27513/curious-crate#comments:id=998060

It seems Knothide Leather Scrap has been replaced by Knothide Leather in these curious crates. I've been farming Highland Mixed Schools in Outland, and the only leather I found inside the crates was Knothide Leather, between 1 and 3 units each time.

**Comment by Rushor** [comment]
DB/Item: Curious Crate - Remove  Knothide Leather Scrap loot

* closes https://github.com/dalaranwow/dalaran-wow/issues/1508
* commit: 5065f65213c022d73c59d968aaf4c32129fa05d4

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
