### ISSUE TITLE
[NPC] Tunneler in Great Fissure in Hellfire

### ISSUE THREAD

**Issue by Ceora** [dalaranwow/dalaran-wow#1527]
Tunneler mobs in the Great Fissure are stuck in a "burrowed" state. Mobs are able to attack the player but cannot be attacked or interacted with even by AoE/Cleave abilities. Mobs aggro and chain properly other than that. Other worms in Hellfire seem to be acting properly.

Tried multiple characters/restarts and disabled all 3rd party addons as well with no change.

**Comment by Rushor** [comment]
DB/Creature: Tunneler - Update combatscript

* closes https://github.com/dalaranwow/dalaran-wow/issues/1527
* commit: 4e5217929dd496b62813964f1b38910c7eff4d18

![GitHub Logo](http://i.imgur.com/Qfa2cIA.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
