### ISSUE TITLE
[Quest][Classic] The Perfect Stout

### ISSUE THREAD

**Issue by Daingean** [dalaranwow/dalaran-wow#1528]
http://www.wowhead.com/quest=315

This quest does not appear to be obtainable.

**Comment by Golganeth** [comment]
Confirmed what @Augur89 said. The quest itself is available but not in the right order.

**Comment by Booshki** [comment]
Tested it, you can accept the Quest [Shimmer Stout] but don't complete it if you wish to complete [The Perfect Stout].

To get acces to [The Perfect Stout] you only need to hit Level 8, so that Tharek Blackstone will offer you the Quest [Rejold's New Brew], which you need to get access to [The Perfect Stout]. As mentioned above, the Quest order is messed up here.

Any Information on a fix on the Quest order (or maybe lowering the required level of 8 to 7 for [Rejold's New Brew], so people don't need to skip any quest or else this quest is unable to complete)?

**Comment by Rushor** [comment]
this was fixed by https://github.com/TrinityCore/TrinityCore/issues/17269 and https://github.com/TrinityCore/TrinityCore/commit/cb419fe2185ef4b971a5b335b4615f1760f7259a

**Comment by Rushor** [comment]
DB/Quest: The Perfect Stout - Update prevquestorder

* closes https://github.com/dalaranwow/dalaran-wow/issues/1528
* quest 315 now does not have a prevquest
* quest 415 now has the prevquest 315
* commit: 3b4c951ec97fbafa5e0f00b94e2ebf378f1e005c

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
