### ISSUE TITLE
Warlock: Summoning new pet

### ISSUE THREAD

**Issue by Warlockboss** [dalaranwow/dalaran-wow#1539]
**Issue present:** Summoned pet is actually not "new" and fresh. It keeps whatever health it had, buffs and debuffs.

**How it should work:** Summoned pet should be with full health, without buffs and debuffs.

**The following applies only to arena:** resummoning pet should reset it cooldowns. Using normal summon or fel domination does not matter, mages also can reset water elementals frost nova by using cold snap and summoning a new pet.

Read quote from user Danishz if unsure: http://www.arenajunkies.com/topic/143356-vileroze-and-other-mld-players/page__st__40

**Quote:** _/shrug I wouldn't be too hard on him, I personally didn't know that fel domming a new felhunter would reset its spell lock CD only inside arenas. I can see how if you test things outside arenas that you would assume they don't work inside arenas as well, if I was dueling people with a water ele used pet nova, cold snapped a new pet and the nova CD didn't reset in the duel I wouldn't attempt it in arena._

_Obviously the analogy isn't rock solid but its pretty comparable. Theres no reason for people to assume that things work differently in arenas than in general gameplay settings._

**Comment by Rushor** [comment]
should be fixed with:

Game/Pet: Change order of aurapply after resummon

* closes https://github.com/dalaranwow/dalaran-wow/issues/3963
* commit: 4167d2cb1450fafb90636c94b9f30b9078243563

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
