### ISSUE TITLE
NPC / Items: Withered Troll / Unliving Choker / Writhing Choker

### ISSUE THREAD

**Issue by nt32** [dalaranwow/dalaran-wow#1554]
According to https://github.com/dalaranwow/dalaran-wow/issues/365 last post (I couldnt test it myself yet) these items require you to finish quest chain ending with "Cleansing Drak'Tharon" ( http://www.wowhead.com/quest=12238/cleansing-draktharon ) which shouldnt be required for items to drop. So I thought I should re-open it.

**Comment by Demlock** [comment]
I haven't gotten to this part jet, but I know thos drop is a part of condition. One type of choker is supposed to drop ONLY once you complete the Cleansing of Drak'tharon Keep, while other requires this quest to not be completed. This is because they both open the same quest chain albeit with different text flavour.

**Comment by taralej90** [comment]
I've been farming Writhing Trolls for the past half hour now. Nass probably forgot my face by now, especially having in mind his numbness. I got around 80 Drakkari Offerings and still can't get the, SUPPOSEDLY, 10% chance Unliving Choker. So yeah, it would be nice if you could do something about it, since it's one of the main quest lines in Zul'Drak and it also counts for the Guru of Drakuru achievement... 

http://www.wowhead.com/item=38660/unliving-choker

**Comment by taralej90** [comment]
Completed "Cleansing Drak'tharon", after which I went to try my luck again on the Withered Trolls.

100% drop on Writhing Choker.

In other words, Unliving Choker is gone and doesn't drop at all and Writhing Choker works normally. Now you know where the problem is.
