### ISSUE TITLE
[Quest][Classic] Audience of the king

### ISSUE THREAD

**Issue by Shiveria** [dalaranwow/dalaran-wow#1558]
i found a bug a text bug with the quest Audience of the king it should say You are to be commended for the service you have done for Stormwind, , , If VanCleef had been successful in his machinations, he would no doubt have done considerable harm to the kingdom--something we must obviously avoid.

Take this, , as a token of the my appreciation.

now in dalaran wow when you turn it in the king says he wishes he could give it to you himself but the funny thing is he is on a diplomatic mission. thats kinda weird for the king to tell you he is on a diplomatic mission and cant give u the symbol.

**Comment by Golganeth** [comment]
There is nothing wrong.

http://wotlk.openwow.com/quest=396

**Comment by Golganeth** [comment]
Confirmed. 
http://www.wowhead.com/quest=396/an-audience-with-the-king#comments

> Since patch 3.0, you get an audience with the real King.

Completion text should be as follows:
> You are to be commended for the service you have done for Stormwind, $name. If VanCleef had been successful in his machinations, he would no doubt have done considerable harm to the kingdom--something we must obviously avoid.

> Take this, $class, as a token of the my appreciation.

**Comment by Rushor** [comment]
DB/Quest: Audience of the King - Update rewardtext to patch 3.0 version

* closes https://github.com/dalaranwow/dalaran-wow/issues/1558
* commit: f6d1d2985c0b54ed2c58da2930e76a5227ce5397

![GitHub Logo](http://i.imgur.com/oqD4LcU.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
