### ISSUE TITLE
Warrior : Threat

### ISSUE THREAD

**Issue by Vepar90** [dalaranwow/dalaran-wow#1559]
The issue i have is the warrior sometimes not being able to keep up with threat 
(doesnt happen always ... but it DOES happen)

MY EXPERIENCE 
"I Don't know whats going on ... Sometimes the THREAT that the warrior makes is Insanely high.... sometimes something Buggs out and he can barely keep threat from anyone

Like earlier today we were doing Naxx25 (i was on my alt warrior) 4050 GS so its not badly geared

Normally i have no problems But today every single thing was out-threating me 
Charge in and do Heroic + shield slam combo (that's the bigges threat generator on the warrior) 1 sec later everyone starts out-threating 

and the best example

On Patchwerk ... 3 tanks ... Druid paladin and Warrior ....
Spending my rage like mad ... heroic strike on every auto atk / shildslam and revenge on Cooldown ... the works ... and on fights like that u have nearly infinite rage so that was never a problem...

the paladin and Druid hand in hand with threat ... warrior ... less than 1/2 of what they were doing. Barely over the rest of the DPS

I Repeat ... its not always like this ... sometimes it works normaly..."

TESTING:

After a few Hours of testing here are the numbers i got ... compared to tankspots numbers as they should be... and ull see why warriors are lacking atm

80 Warrior with 2500 AP, 1500 Block (TANKSPOT)

Devastate 1 1042
Devastate 2 1253
Devastate 3 1475
Devastate 4 1711
Devastate 5+ 1961
Revenge 4522
Shield Slam 7242

This should give u a general idea 

80 Warrior with 2800 AP, 1400 Block (My Warrior with some Downgraded Gear)
Its as close as i can get to the Tankspot's Test warrior.

Devastate 1 1700*
Devastate 2 2100
Devastate 3 2500
Devastate 4 2900
Devastate 5+ 3100
Revenge 5500*
Shield Slam 5300*

NOTE
*Devestate numbers of my warr are a bit higher Because my atk power is a bit higher than the Tankspot's warrior (using the same weapon)
Threat Formula for Devestate should be = damage + 5% of AP
- Revenge Number is again a bit Higher than Tankspot's because of the higher AtkPower of my warrior
  Threat Formula = damage + 121
- Shield Slam is where the warriors threat Problems Come From in my oppinion
  The number is MUCH Lower than the ones Provided by Tankspot
  Formula should be = damage + 770

As u can see it should be Doing almost 2x more threat than Revenge ... But its doing Even less ... so 

Perhaps you can do something with this ... perhaps not ...

**Comment by Akkalevil** [comment]
I can confirm this warrior threat problem.

Did a Naxx10 with a mostly Naxx25, gemmed and enchanted geared tank. The OT was a paladin in blue gear without gems or enchant. I was doing massively more damage than him (to give an idea, I was second overall damage-dealer in the whole raid), and yet he was constantly pulling aggro without taunt, and some DPS managed to often steal aggro too.
In fact I instinctively checked several time if I was actually in Defensive Stance (I was) because it was just bewildering.
My auto-attacks were my 5th damage-dealing abilities, so it's not like I was being stingy on devastate/shield slam/heroic strike/revenge, so I strongly think it's a big bug problem.

Suggestion : maybe the inherent threat bonus of defensive stance (which should be something like 175-200 % bonus threat) isn't correctly implemented ?

**Comment by Akkalevil** [comment]
Can we hope for a fix someday ? It's barely possible to keep threat from DPS if they have even a tad more gear than you, and it definitely isn't how it was on retail. It's just ridiculous and it's a pretty MAJOR core issue...

**Comment by Rushor** [comment]
any chance to reproduce the problem?

**Comment by Golganeth** [comment]
If it's so MAJOR of an issue, I'm sure you will be able to provide some kind of proof, how it should work, and steps to reproduce the problem. Or check aggro guides

**Comment by Rushor** [comment]
no reproduction, no spellids, no propper calculation examples, no references to the calculation from wowwiki.

/closes

Plese use the template from https://github.com/dalaranwow/dalaran-wow/issues/new to report the issue in a propper way. Thank you.
