### ISSUE TITLE
[Classic][Items][Ashenvale] Waterlogged Footlockers

### ISSUE THREAD

**Issue by Akkalevil** [dalaranwow/dalaran-wow#1560]
There should be Waterlogged Footlockers all over the Zoram Strand, I couldn't find a single one after a thorough search.

http://www.wowhead.com/object=179487#comments

**Comment by Rushor** [comment]
http://wotlk.openwow.com/object=179487

There should be spawned some more in both areas + the respawntime should be reduced to 300 seconds

**Comment by Rushor** [comment]
DB/Gameobject: Spawn several Waterlogged Footlockers in Redridge Mountains and Ashenvale

* closes https://github.com/dalaranwow/dalaran-wow/issues/1560
* commit: ce50edce18eb07c7d7d83276e00bf86197657b24

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
