### ISSUE TITLE
[Children's Week] Quest: Back To The Orphanage (Dalaran)

### ISSUE THREAD

**Issue by Rathyan** [dalaranwow/dalaran-wow#1561]
http://wowhead.com/quest=13959
http://wowhead.com/quest=13960

After completing one of these quests the player should recieve a mail with the Oracle (46545) or the Wolvar (46544) pet attached to it. I've done this quest more than 28 hours ago and still nothing, same goes for everyone I've asked in global

From www.wowhead.com/quest=13960#comments:id=810409 : (Patch 3.2.0) As soon as you complete this quest you get a Curious Wolvar Pup in the mail.

**Comment by AgeAgainst** [comment]
Will this be awarded at a later date?

**Comment by Augur89** [comment]
Oh well.. I really wanted my wolvar pet but I see I'm not getting it this year at least.

If the developers can't fix this issue maybe you can consider putting them on the vote shop?

**Comment by Rushor** [comment]
DB/Quest: Back To The Orphanage (Dalaran) - Add mailrewards

* after completing quest 13959 or 13960, you will get the item 46545 or 46544 after 900 seconds in your mail
* closes https://github.com/dalaranwow/dalaran-wow/issues/1561
* commit: b975b499cb8ecccc54d566aa5ebd01797115443d

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
