### ISSUE TITLE
[Item] Sundial of the Exiled 

### ISSUE THREAD

**Issue by Lanrutcon** [dalaranwow/dalaran-wow#1568]
## Sundial of the Exiled

Problem:
Currently it's proccing on healing spells...

---

How should work:
As the tooltip says...it should only proc on harmful spells...

Screenshot:
http://i.imgur.com/9lrTiC2.jpg
((Flash Heal >> Now is the time!))

More info:
http://www.wowhead.com/item=40682 --- Item
http://www.wowhead.com/spell=60063 --- Proc buff

**Comment by Rushor** [comment]
DB/Spell: Now is the Time! from item "Sundial of the Exiled" should only proc on damaging spells 

* closes https://github.com/dalaranwow/dalaran-wow/issues/1568
* commit: 5818fa329d0358c842c51a693b6648f64c3ce08d

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
