### ISSUE TITLE
[NPC] Hezrul Bloodmark Quest

### ISSUE THREAD

**Issue by Paot** [dalaranwow/dalaran-wow#1573]
I went around looking for him for awhile, when I found him he was frozen, just below the southern most centaur camp. I got the quest, but the group of them don't move.

**Comment by Rushor** [comment]
DB/Creature: Hezrul Bloodmark - Add pathing and formation for his two guards

* closes https://github.com/dalaranwow/dalaran-wow/issues/1573
* commit: e9f660168290de85d4d1d5953a7359d951efa202

![GitHub Logo](http://i.imgur.com/ZYspqRl.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
