### ISSUE TITLE
[NPC] Sky Terrors don't attack

### ISSUE THREAD

**Issue by fizzl** [dalaranwow/dalaran-wow#1578]
Zul'Drak, The Argent Stand.

When you attack a sky terror, it will just keep happily flapping about, instead of attacking you.

**Comment by Rushor** [comment]
DB/Creature: Sky Terror - enable combatbehaviour

* closes https://github.com/dalaranwow/dalaran-wow/issues/1578
* commit: ea58d27c76ee0f8e6a2b52f4fbff499e0550976f

![GitHub Logo](http://i.imgur.com/qYn4cZh.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TheRealestMcCoy** [comment]
@Rushor I know you fixed the combat behavior. But does this also cause them to fly down and pick up the Argent crusader's?

**Comment by Rushor** [comment]
only the combat behaviour was fixed here, i could not found a reliable source on the event with the Argent crusader's (video)

**Comment by TheRealestMcCoy** [comment]
I will see what i can find since there are a lot of npcs missing here starting a tracker for it now.
