### ISSUE TITLE
[Druid][Quest] The Raven Stones

### ISSUE THREAD

**Issue by BenBezac** [dalaranwow/dalaran-wow#1584]
Hi,

The following quest is bugged.

http://www.wowhead.com/quest=10988/the-raven-stones

The Cenarion Sparrowhawk does nothing.
But i can complete the quest anyway by looking for the stones by yourself^^

**Comment by Rushor** [comment]
DB/Quest: Implement quest "The Raven Stones"

* the Cenarion Sparrowhawk will now spawn and follow the player
* if the Cenarion Sparrowhawk comes close to the "Skettis - Invis Raven Stone" if will run towards it and summon the lootable Gameobject 'Raven Stone Fragment' for 60 seconds
* also removed the old static spawns for the Gameobject 'Raven Stone Fragment' 
* closes https://github.com/dalaranwow/dalaran-wow/issues/1584
* commit: f79207cef6794f9094cfa996a4e49e64fdd3dd8a

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
