### ISSUE TITLE
Spotted Fish (lakeshire) Murlock bug

### ISSUE THREAD

**Issue by magicbist** [dalaranwow/dalaran-wow#1599]
Murlocs are bugged , they dont move , but they can attack you  and when they are on low helts they move.

fix that

regards

**Comment by Rushor** [comment]
DB/Creature: Murloc Scout - Increase repeattimer for 'Poisonous Stab' + only cast 'Poisonous Stab' if this aura is not already on the victim

* closes https://github.com/dalaranwow/dalaran-wow/issues/1599
* commit: 12b69065af79aba2855508c2d3f6f709f49dc2fc

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
http://wotlk.openwow.com/npc=578
