### ISSUE TITLE
Northrend Cooking Recipe drops.

### ISSUE THREAD

**Issue by Cinderhelm** [dalaranwow/dalaran-wow#1601]
http://wotlk.openwow.com/item=43508
http://wotlk.openwow.com/item=43509
http://wotlk.openwow.com/item=43510
http://wotlk.openwow.com/item=43507

The following recipes seem to be having a much lower droprate than blizzlike. Normally those would drop as often as http://wotlk.openwow.com/item=39152 ,which is currently not the case.

This issue makes it hard for achievement hunters to get Northrend Gourmet > Chef title.

**Comment by Klala** [comment]
True, I remember in retail those things would drop often in raid trash\dungeons. But I ran into dungeons and raids so many times now and never seen it drop even once.

**Comment by fsironman** [comment]
For people trying to farming them:

http://wotlk.openwow.com/npc=24642
drops http://wotlk.openwow.com/item=43510 and http://wotlk.openwow.com/item=43507
and 
http://wotlk.openwow.com/npc=25668
drops http://wotlk.openwow.com/item=43508

Dropchance is 2.4 %

For http://wotlk.openwow.com/item=43510 there are only as few unique mobs (not really farmable) with dropchance of about 1% or mobs with really low chance if you wanna farm it check a default TDB.
 

Nevertheless this should be **fixed**.

**Comment by Rushor** [comment]
DB/Item: Increase chance for Northrend Cooking Recipe drops to 2 percent

* closes https://github.com/dalaranwow/dalaran-wow/issues/1601
* commit: 9dece401ebef6613560abb6d9986fd003db0fc5b

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by galgnu** [comment]
Could this please be added to next release! I've been farming and farming without any luck just to find this which was fixed over a year ago!!

**Comment by galgnu** [comment]
Please remember this for next update!
