### ISSUE TITLE
Quest:Eitrigg's Wisdom

### ISSUE THREAD

**Issue by mjpwn** [dalaranwow/dalaran-wow#1604]
http://www.wowwiki.com/Quest:Eitrigg%27s_Wisdom
Eitrigg has no dialog options/ you cant council with him...

**Comment by Demlock** [comment]
Confirmed.

**Comment by Khronos-** [comment]
Confirmed.

**Comment by DrFuler** [comment]
[20/05/2016] - Still bugged.

**Comment by Rushor** [comment]
fix inc.

**Comment by Rushor** [comment]
DB/Quest: Implement "Eitrigg's Wisdom"

* closes https://github.com/dalaranwow/dalaran-wow/issues/1604
* commit: bdaa2e6885db89b9ca5fb14139cb5319f7787430

![GitHub Logo](http://i.imgur.com/GPkQCVF.jpg)
![GitHub Logo](http://i.imgur.com/EobfqJZ.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
