### ISSUE TITLE
Quest: Skywing

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#161]
Quest Skywing - 10898
NPC - 22424
Issue: The NPC doesn't want to start to move if you pick up the quest. If you kill him and respawn him, then it works and he starts flying.

Also he doesn't aid you at all to fight mobs when traveling / escorting him.

Quest is though doable and completable, you can escort him and quest counts.

http://wotlk.openwow.com/quest=10898
http://wotlk.openwow.com/npc=22424

**Comment by Demlock** [comment]
Confirmed!

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/issues/15228

**Comment by Rushor** [comment]
94166e2403b053e6468dad2095a3a4a7bb1c2343
- rewoked the whole escortevent
- added endbossfight

**Comment by Golganeth** [comment]
The NPC keeps dropping below the ground on the PTR so can't really test the escort properly, it heavily bugs out its waypoints (I'm assuming this is because of PTR incorrect maps). So I couldn't test if the whole event / emotes are working.

Nonetheless Skywing speed should be increased. Reference: https://www.youtube.com/watch?v=Vqi0YAwgOsk

**Comment by Rushor** [comment]
kay bumb myself
