### ISSUE TITLE
Pet bar: Druid, Force of Nature

### ISSUE THREAD

**Issue by Milton3450** [dalaranwow/dalaran-wow#1616]
The talent Force of Nature summons 3 treants to attack enemies. Problem is that the pet bar doesn't go away after the treants die. It only grays out. Happens when they attack something and die from expiration. Tried to delete cache without luck.

**Comment by Rushor** [comment]
should be fixed with:

Core/Pet: Fix pet action bar after reloading UI

* closes https://github.com/dalaranwow/dalaran-wow/issues/3242
* commit: 10372bb1fc33648f6dd38eaee64003c0285d5541

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
Already on PTR.
