### ISSUE TITLE
[Spell] Orb of the Blackwhelp

### ISSUE THREAD

**Issue by Cinderhelm** [dalaranwow/dalaran-wow#1617]
Effect is supposed to be a buff and should be removable by right clicking on it, but it is a debuff as a current. Minor issue, but still isn't the way it should work.

**Comment by Rushor** [comment]
Game/Spells: Spellinfo - Transformation - Blackwhelp - must be a positive effect 

* closes https://github.com/dalaranwow/dalaran-wow/issues/1617
* commit: c80d2b0fbf5eedec7136e198f45848ce1e2a45b3

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
