### ISSUE TITLE
Resurrect Button

### ISSUE THREAD

**Issue by ReaverB** [dalaranwow/dalaran-wow#1620]
Doesn't work on Kirin Tor when your body is LOS.

This happens when you're body falls into the ground during death. It happens more often than it should. Upon returning to where you died the "Resurrect now? Accept" button lights up, but does not function.

This is a huge pain in the ass.

**Comment by Golganeth** [comment]
Works fine. Sounds like an odd problem only with your character. A quick relog and/or deleting your Cache folder should fix it.

**Comment by fizzl** [comment]
Just got similar weird problem with Accept button. I'm near my corpse. I can see it. The accept button lights up but doesn't work. Reload/Reload/Cache doesn't help.

Only thing I could think of that was weird, was that I died to another bug: The Valiant Charge quest target hits suddenly the character instead of the horse, causing and insta death. 

Sorry about necroing and old bug. I'll add information if I figure out a workaround or real reason.

**Comment by fizzl** [comment]
This happened yet again, while trying to complete "Changing the wind's course". I died while trying to kill The North Wind. When I get back to my corpse, the "Accept"-button does nothing.

Please re-open.
