### ISSUE TITLE
[Quests][Classic] kodo roundup

### ISSUE THREAD

**Issue by erikhios** [dalaranwow/dalaran-wow#1641]
this quest doesn,t count the kodo,s you have tamed.

it still stays on 0/5

**Comment by Sagrath** [comment]
The Tamed Kodos (#11627) are neutral and attackable.
The Tamed Kodos are supposed to be friendly and unattackable.
If killed, awards quest credit

**Comment by Rushor** [comment]
DB/Quest: Kodo Roundup - tamed kodos must be friendly to all

* closes https://github.com/dalaranwow/dalaran-wow/issues/1641
* commit: 74248f31df436ca8a5ca8f0b501b4910473225e3

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
