### ISSUE TITLE
[Quest][Classic] Decoy!

### ISSUE THREAD

**Issue by Shanghi** [dalaranwow/dalaran-wow#1646]
**The problem:**
Using the item "Bag of Gold" doesn't work, giving the error "Requires Drop-Off Point" no matter where you are on the hill. I've tried at the exact coordinates of http://wotlk.openwow.com/object=180660 and all around that area.

**What should happen (according to a wowhead comment):**
Once the Bag of Gold has been planted, a gyrocopter called Doctor Weavil's Flying Machine makes an approach from the east, eventually touching ground. Doctor Weavil disembarks and walks over to the bag, whereupon the following little monologue takes place:

[58:19]Doctor Weavil says: No hello for your old friend, Narain? Who were you expecting?
[58:25]Doctor Weavil eyes you suspiciously.
[58:27]Doctor Weavil says: So... You thought you could fool me, did you? The greatest criminal mastermind Azeroth has ever known?
[58:35]Doctor Weavil says: I see right through your disguise, <race>. Number Two! Number Two kill!
[58:46]Number Two says: KILL!

immediately after which Number Two, the enormous gorilla, appears from the gyrocopter and attacks you.

**Links:**
Quest: http://www.wowhead.com/quest=8606/decoy
Bag of Gold: http://wotlk.openwow.com/item=21041 / http://www.wowhead.com/item=21041
Number Two: http://www.wowhead.com/npc=15554/number-two

**Comment by Golganeth** [comment]
It's lacking scripts but currently you can spawn 'Number Two' once you place the quest item. The NPC has crazy attack speed but it's not big deal because it hits really low.

**Comment by Rushor** [comment]
DB/Quest: Decoy! - Add missing RP Event for Doctor Weavil

* closes https://github.com/dalaranwow/dalaran-wow/issues/1646
* commit: 7ddbdf785ac1a82eaa505ac62d558e159a790720

![GitHub Logo](http://i.imgur.com/jAsP455.jpg)
![GitHub Logo](http://i.imgur.com/HglM8F1.jpg)
![GitHub Logo](http://i.imgur.com/UtOpX4A.jpg)
![GitHub Logo](http://i.imgur.com/ImPK1k7.jpg)
![GitHub Logo](http://i.imgur.com/Jch2sX9.jpg)
![GitHub Logo](http://i.imgur.com/KsPhbDA.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
