### ISSUE TITLE
[Quest]Attunement to Dalaran

### ISSUE THREAD

**Issue by killer240495** [dalaranwow/dalaran-wow#1658]
after defeating Arcanimus. and i used the Ley Line Attunement Crystal. Nothing happens.

**Comment by warcraftgeekygamer** [comment]
I can confirm that the quest called Attunement to Dalaran (for Alliance) is still broken.

The fix from github is posted here: --> https://github.com/TrinityCore/TrinityCore/issues/4747
http://old.wowhead.com/quest=12172 --> The Quest
http://wotlk.openwow.com/?quest=12172 --> Quest
http://old.wowhead.com/item=37006 --> The Object
http://old.wowhead.com/npc=26673 --> The NPC

Disapointed to see Northrend quests, npc's and dungeons not working since you pride yourself on hosting an AWESOME x1 WotLK server. Please fix asap!
http://old.wowhead.com/zone=65 --> Dragonblight zone

**Comment by Archcry** [comment]
I can confirm that this quest is in fact still bugged, when I stand in the pit the item gives me the error that I have to be under the surge needle.

**Comment by Lothloryen** [comment]
Hello there,

This quest was working only once after a realm restart - it has been corrected already. It will be active on the live server after the next maintenance.

Thank you.
