### ISSUE TITLE
Item: Bog Lord Tendril

### ISSUE THREAD

**Issue by Daingean** [dalaranwow/dalaran-wow#1659]
Hello -

Wowhead lists the drop rate of this item to be 34% from 'Starving Fungal Giants' (http://www.wowhead.com/item=24291) but after 60 kills (see screenshot, tooltip left side) I have not gotten a single tendril.

Issue #753 also noted that this item drop rate was poor, though a response in that same thread seems to imply that the problem was fixed. Clearly, it was not.

![wowscrnshot_060314_003037](https://cloud.githubusercontent.com/assets/4252626/3156893/eb087aa0-eae9-11e3-8a54-230b8cdcbfa1.jpg)

**Comment by trincore** [comment]
Gathered 6 Bog Lord Tendril items in about 15 minutes. Gathering place - Quagg Ridge, Zangamarsh. Around coordinates you can see in screenshoot.

![wowscrnshot_021715_123959](https://cloud.githubusercontent.com/assets/10964125/6227022/6a6f225a-b6a3-11e4-8fe3-dabe2ee795ff.jpg)

**Comment by Girion11** [comment]
As Mantigora stated - "if you are not on a [Natural Enemies] quest, items does not drop". This seems to be the issue, I've completed the Natural Enemies quest ( http://www.wowhead.com/quest=9743/natural-enemies ) and the item dropped - it still seemed to have a bit low drop rate to me (actually, all quest items seem to have that as well), but it could be farmed. Without that quest in the log, the q item doesn't drop, therefore repeatable quest More Tendrils! ( http://www.wowhead.com/quest=9744/more-tendrils ) can not be completed as this quest is not accepted to quest log, it can only be turned in once you have enough tendrils.
The Sporregar reputation can be achieved nonetheless, but the repeatable quest does in fact count to Zangarmarsh quest achievement (ofc only one time), so it would be nice to fix that. It also should't be that hard, editing a few numbers in DB would do.
Thanks.

**Comment by Rushor** [comment]
DB/Item: Bog Lord Tendril - Item should also drop if you don't have the quest: "More Tendrils!" or "Natural Enemies"

* closes https://github.com/dalaranwow/dalaran-wow/issues/1659
* commit: cb90e6beb88b0b638e2bdc0d12e5e62057b77abb

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
