### ISSUE TITLE
[Quest][Classic] The Bloodsail Buccaneers

### ISSUE THREAD

**Issue by VictorTyne** [dalaranwow/dalaran-wow#1673]
Issue:

In Stranglethorn Vale, the Bloodsail Charts and Bloodsail Orders pickup items needed for the quest are on the wrong respawn timer, taking ~15 minutes to respawn (the same respawn timer as the Solid Chest sitting right next to them).

How it should work:

These items should respawn instantly, or be on the same respawn timer as mobs.

**Comment by Rushor** [comment]
DB/Gameobject: Bloodsail Charts and Bloodsail Orders - Reduce spawntime to 1 second

* closes https://github.com/dalaranwow/dalaran-wow/issues/1673
* commit: 6d731c9ccc5b11b096dfe52c2001f75561c7b7ce

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
