### ISSUE TITLE
Quest / NPC: Bring me the Egg / Windroc Matriarch

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#169]
Quest Bring me the Egg - 10111
NPC Windroc Matriarch - 19055

Issue: When you summon the creature, he does fly down to the ground.
If you attempt to kill him, he will not resist or use any kind of attacks at all (he is completely behaving as a dummy npc) - he should have the following skills: Demoralizing Screech and Eagle Claw according to http://wotlk.openwow.com/npc=19055

After you kill him, his corpse will magically fly up into the air where the corpse is not even lootable unless a player is flyhacking or you're a Game Master.

Quest: http://wotlk.openwow.com/quest=10111
NPC: http://wotlk.openwow.com/npc=19055

**Comment by Rushor** [comment]
6fbef9006a1ad6223df5e3645133b2f4bba4a702
- creature should behave agressive now (no longer passive)

**Comment by Golganeth** [comment]
Once you attempt to steal the egg, wrong "Emote blabla" is displayed instead of the actual emote "Mysterious Egg cracks open, filling the nest with york."
https://www.youtube.com/watch?v=al1yyrEzuWQ

The Jump-a-tron 4000 doesn't properly knock players into the egg, usually knocks them to the opposite direction no matter what angle you are using to face the Jump-a-tron. You can get there easily with flying mount though.
