### ISSUE TITLE
Elwynn Forest report

### ISSUE THREAD

**Issue by HugDaBlock** [dalaranwow/dalaran-wow#1700]
Greetings Dalaran WoW.

I just recently started on your server, and I've decided to do as many bug reports as possible, while I level from 1 to 80. I am a human paladin, and my adventure will therefore start in the Elwynn Forest, where I have noticed following bugs:
- When doing the Princess quest (you have to kill a boar at the Brackwell Pumpkin Patch), then I noticed that her guards will not come to her aid when attacked. I don't think she is patrolling either, which she is supposed to.
- The kobolds in this area will not try to run away, when having a little amount of life left. This is also seen when fighting defias npcs.

I hope that my report will come in handy, and this is properly not the last :)

Regards

Snothvalp, Algalon

**Comment by Demlock** [comment]
>The wandering salesmen (and baker) is not patrolling the roads corectly, or they don't (I meet em twice standing still).

This is an issue with most wandering NPCs in the game

**Comment by Rushor** [comment]
since patch 2.3 there should be only one helping pig http://old.wowhead.com/quest=88

**Comment by Rushor** [comment]
DB/Creature: Elwynn Forest changes

* Kobold Vermin and Kobold Worker now Flee For Assist at 15 % HP
* Added pathing and reactionsupport for Princess and Porcine Entourage
* removed one Porcine Entourage 
* closes https://github.com/dalaranwow/dalaran-wow/issues/1700
* commit: 756dbd11be598edd5eb1f0dc815dc2795bc1e4ea

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
