### ISSUE TITLE
[NPC] Elite Immunity to Death Knight Diseases

### ISSUE THREAD

**Issue by roblockster** [dalaranwow/dalaran-wow#1704]
Following up on this report (I apologize if there is another follow up to this which I missed):
https://github.com/dalaranwow/dalaran-wow/issues/1624

On numerous elites, Death Knight diseases do not seem to be resisted or anything of the sort, but rather simply do not affect bosses. The spells hit, but the disease debuffs never go up, the NPCs do not take dieases damage, and the DK abilities dependent on diseases for effects do not get those effects. This includes almost all non-instance elites I have encountered, including all Northrend rare elites encountered, as well as other 70+ elites such as the capital city bosses (Wrynn, etc.)

EDIT: I am finding more elites who don't get diseases: Doomwalker, Illidari Centurions, Ashtongue Primalist, Ashtongue Battlelord, Ashtongue Channeler (Shade of Akama fight) and some other Black Temple mobs. Even instance bosses are immune, such as Brutallus. 

As there is no reason for a 73 Elite to be immune to the diseases of a level 80 DK when the spells hit and with no evidence in the combat log, this is obviously a bug. Rather than list all the city bosses and rare elites, I think it would be easier to list the rare Northrend elites I've found that can be affected by diseases: none.

Searching the internet, I have not found anything indicating this should be the case. There were some retail bugs involving one pre-WOTLK content elite (Curator) being immune to DK diseases, but that's it.

**Comment by taralej90** [comment]
Basically half of the elites in Outland are immune to diseases, which I cannot understand why...

**Comment by Johanes022** [comment]
I can add that Horde city leaders are also immune to death knights deseases.
Also ive done Maghteridon Lair, hes also immune.

**Comment by Rushor** [comment]
for northrend it is correct i think. i will remove the immunity for all creatures in outland, since dks were not available in 2.x lol

**Comment by Rushor** [comment]
DB/Creature: Remove immunity to infections from creatures in expansion 1 (bc)

* closes https://github.com/dalaranwow/dalaran-wow/issues/1704
* commit: 9d8aa711dd4a3b262c6271ddd6b85f4ee5fa0544

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
