### ISSUE TITLE
[Blade's Edge Mountains] Kaliri Totem not despawning

### ISSUE THREAD

**Issue by VictorTyne** [dalaranwow/dalaran-wow#1727]
There seems to be an issue in Veil Lashh with Kaliri Totems either over-spawning or not despawning at the circles of power in the Veil. I would guess it's a despawning issue, since their despawning seems to be governed by a spell effect.
http://www.wowhead.com/spell=37013/despawn-kaliri-totem
![wowscrnshot_070414_072520](https://cloud.githubusercontent.com/assets/7576380/3482940/b06a1c12-0387-11e4-945a-96c22da4bd03.jpg)

**Comment by Rushor** [comment]
DB/Quest: Scratches - Add itemcooldown + remove useless eventscript

* commit: 98a8e675d67e37eda019a61769ad56fd9b0f9675

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
