### ISSUE TITLE
Death Knight: Blood Tap

### ISSUE THREAD

**Issue by freecrack** [dalaranwow/dalaran-wow#1728]
If you have two blood runes and you use Blood Tap, it will convert one to a Death rune as intended. Although if you have one blood rune and one death rune, the skill will have absolutely no effect, regardless of whether they're on cooldown or not. I believe it should activate the blood rune that is on cooldown.

Also, if you have two death runes on cooldown and you use blood tap, it will have no effect. It won't even take the death runes off cooldown. I am not sure if this is intentional or not.

**Comment by MrAndersonX** [comment]
Seems to be working fine now.

**Comment by Rushor** [comment]
Scripts/Spells: Death Knight runes should always be usable after use of "Blood Tap"

* closes https://github.com/dalaranwow/dalaran-wow/issues/3921
* commit: a35a2d954cf5f780f14d6a16ae2ec168b9046c63

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by MrAndersonX** [comment]
Yeah, it seems Death Runes bug the hell out of the utility of the other runes. Alot of times if a Death Rune has a cd or smth, it won't let me utilize the other blood/frost/unholy runes until that Death Rune has finished it's cd and vice-versa.
