### ISSUE TITLE
Item: Illustration of the Dragon Soul & Sif's Remembrance- Restoration Druid [Algalon] (Same Issue)

### ISSUE THREAD

**Issue by Convertabull** [dalaranwow/dalaran-wow#1745]
Item: Illustration Of The Dragon Soul
ID:40432
Class/Spec: Restoration Druid

What it does: Rejuvenation, Lifebloom and Wild Growth are not generating any stacks on cast.

What it should do: All damage and healing spells should generate 1 charge from the item on cast.

http://wotlk.openwow.com/item=40432
http://www.wowhead.com/forums&topic=117574/healing-and-tanking-trinket-questions

Edit: Original item link changed to openwow from Wowhead as this item currently displays it as is on retail with the stat nerf, giving it incorrect information relevant to this expansion.

**Comment by Rushor** [comment]
http://wotlk.openwow.com/item=40432
http://wotlk.openwow.com/item=45929

DB/Spell: Item: Illustration of the Dragon Soul & Sif's Remembrance- Restoration Druid - Update procbehaviour

* closes: https://github.com/dalaranwow/dalaran-wow/issues/1745
* commit: d5e1207b79f328b7819529bf09ff0100b40b565f

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
all remaining issues with the trinkets listed above will be fixed here https://github.com/dalaranwow/dalaran-wow/issues/2120

The procbehaviour should be improvead now for http://wotlk.openwow.com/item=40432, http://wotlk.openwow.com/item=45929)
