### ISSUE TITLE
[NPC] Gelkis Clan Centaur

### ISSUE THREAD

**Issue by che0522** [dalaranwow/dalaran-wow#1750]
The reputation cap for Gelkis Clan Centaur from killing mobs should be 11999/12000 instead of 0/12000.

http://www.wowwiki.com/Gelkis_clan

**Comment by Demlock** [comment]
Confirmed. A minor bug, though.

**Comment by Rushor** [comment]
DB/Creature: Increase max Gelkis Clan reputation

* closes https://github.com/dalaranwow/dalaran-wow/issues/1750
* commit: 93ff9001186d8852907f94b09e76b8b505e312ba

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
