### ISSUE TITLE
The Shattered Necklace Droprate is incorrect

### ISSUE THREAD

**Issue by che0522** [dalaranwow/dalaran-wow#1752]
I'm not even sure it drops. I cleared the entrance area for many times already and have not seen one drop. Doesnt seem right to me.

http://wotlk.openwow.com/quest=2198

**Comment by n-ghost** [comment]
Issue is confirmed.

The necklace will drop just fine for horde characters (they have a quest as well, albeit starting not from the necklace, but in Orgrimmar).

For alliance though it either never drops, or drop rates are horribly messed up. Spent like 5 hours x2 on my hunter outside Uldaman, tens of thousands of ammo, got things like Citrine, Recipe: Elixir of Detect Lesser Invisibility, Pendant of Myzrael (!) drop, but no necklace.

Link for the reference: http://www.wowwiki.com/Shattered_Necklace

The drop chance for both factions should be 5% for the mobs outside the Uldaman and 8% for Stonevault Oracles inside.

Would be good if somebody confirmed if they got it on alliance toon after all.

**Comment by n-ghost** [comment]
Still an issue.

**Comment by gotnoface** [comment]
Just confirmed myself today. Horde drops. Alliance doesn't. Even after farming for 2 hours, no drops.

**Comment by Jindra555** [comment]
Confirmed, doesn't drop for Alliance, the item is with all probability set as an exclusive quest item for the Horde quest. This bug previously existed on TC1.

**Comment by Rushor** [comment]
DB/Item: Shattered Necklace - should be tootable from alliance too

* closes https://github.com/dalaranwow/dalaran-wow/issues/1752
* commit: c4f4ef682faa374c4cd108b4328fee166d01c9d1

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
