### ISSUE TITLE
[Quest] Indurium nodes in uldaman yield nothing

### ISSUE THREAD

**Issue by che0522** [dalaranwow/dalaran-wow#1753]
I tried to mine them but nothing drops.

**Comment by Rushor** [comment]
problem: you cannot accept the quest and get it in the questlog

**Comment by Rushor** [comment]
DB/Gameobject: Indurium Ore - always enable mining

* closes https://github.com/dalaranwow/dalaran-wow/issues/1753
* commit: cf6fc1cf5bb6f6c4e6e7e87be2f38f7bc6b5026e

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
