### ISSUE TITLE
[GO] The Lost Supplies

### ISSUE THREAD

**Issue by che0522** [dalaranwow/dalaran-wow#1754]
Lost Supplies should be inside the scatted crates in swamp of sorrow. I tried to loot many of them but all of them are empty.

http://www.wowwiki.com/Lost_Supplies

**Comment by Rushor** [comment]
UPDATE `gameobject_loot_template` SET `ChanceOrQuestChance`=100 WHERE `entry`=3597 AND `item`=6172;

**Comment by Rushor** [comment]
DB/Gameobject: Scattered Crate - should always contain one item

* closes https://github.com/dalaranwow/dalaran-wow/issues/1754
* commit: 9f12653abf621b1134942b08d93a58cd2e095e06

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
