### ISSUE TITLE
[Quest][Northrend] A Soldier In Need

### ISSUE THREAD

**Issue by VictorTyne** [dalaranwow/dalaran-wow#1760]
The item spawn for the quest A Soldier in Need to pick up the [Hawthorn's Anti-Venom] is on the 5min mob spawn timer. The respawn on this item should be instant.

**Comment by Rushor** [comment]
DB/Gameobject: First Aid Supplies - Reduce spawntimeseconds to 1 second

* closes https://github.com/dalaranwow/dalaran-wow/issues/1760
* commit: 699f66536f591b8eb86d0db02b4a25465673f123

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
