### ISSUE TITLE
[Classic][Quest][Dustwallow Marsh] Mana Surges

### ISSUE THREAD

**Issue by Akkalevil** [dalaranwow/dalaran-wow#1769]
The mana surges spawn infinitely at a breakneck rate and never stop.
I mean, in the likes of THOUSANDS.

![manasurges](https://cloud.githubusercontent.com/assets/6848735/3713622/4cc1f6dc-1578-11e4-8033-53a668c285df.jpg)

**Comment by Rushor** [comment]
ed7447d8bc27337a9dba328c793f88a58b1b0995
- the creature will now depawn automatically after 600000 milliseconds
- moreover the creature will no longer spawn, if the player finished the quest

**Comment by Golganeth** [comment]
They stop spawning indeed once completed indeed, but too many spawn in the first place. You need 12 and if you complete it normally you get 20-25 spawns.

There's also internal ways to exploit it and spawn hundreds.

**Comment by Edzero** [comment]
Every time a mana surge dies, 3 more will spawn. This keeps happening until the player completes the quest. Potentially you can get over 30 mobs spawned at once from this.

Once the quest is completed they will stop respawning. The exploit to get infinite spawns seems to be fixed. Tried doing this on two accounts at once to see if it would be possible to cause infinite spawns but that doesn't seem to be the case. 

Working well apart from the 3 spawning at every death thing. A normal player can become overwhelmed with mobs due to this.

**Comment by Rushor** [comment]
well which solution do you propose? reduce the spawn of the ghost on dead from 3 to 1? if the mainproblem was fixed i would like to set the status to "on-Ptr" @Edzero

**Comment by Edzero** [comment]
@Rushor I think changing it from 3 to 1 would be the best solution overall personally but I'll respect your decision either way. :)

**Comment by Rushor** [comment]
DB/Quest: Mana Surges - Only summon one 'Mana Surge' in order to prevent exploits

* closes https://github.com/dalaranwow/dalaran-wow/issues/1769

commitorder:
* ed7447d8bc27337a9dba328c793f88a58b1b0995
* 42b74df4e6f230ca3b728b8541a176253ead6656
* 15e918cae68b3f0fae01d9bda1401b34b0baf32d

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
