### ISSUE TITLE
[TBC] [Item] [Karazhan] Sealed Tome

### ISSUE THREAD

**Issue by Drekz** [dalaranwow/dalaran-wow#1772]
The sealed tome drops 4 items:
http://www.wowhead.com/item=23864
http://www.wowhead.com/item=23865
http://www.wowhead.com/item=23862
http://www.wowhead.com/item=23857

Each provides a buff which has increased effects on level 80 characters and should not work outside of Karazhan.

Here they do and lately more and more people have been abusing these items to get silly amounts of DPS using them.

**Comment by Rushor** [comment]
DB/Item: Sealed Tome - No longer usable outside of karazhan

* closes https://github.com/dalaranwow/dalaran-wow/issues/1772
* commit: 8e6787ec79ef17f3812806c7ed20f8df99b65fe2

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
