### ISSUE TITLE
[Rogue][Talents] Master Poisoner

### ISSUE THREAD

**Issue by crosik** [dalaranwow/dalaran-wow#1782]
Talent is getting bugged by palas judgement. After being hit by it envenom starts eating deadly poison stacks again

also if you poison an enemy, he doesn't get a debuff from the talent (at least not a visible one).

**Comment by Esunnaxqt** [comment]
Bump, this single bug is killing an entire spec in PvP.

**Comment by Esunnaxqt** [comment]
and forgot to say its still bugged, since it got closed...

**Comment by Golganeth** [comment]
Don't know where you see it's closed.

**Comment by Mazz312** [comment]
Was this bug ever addressed? Along with the other bug of the talent that is wasn't properly adding 3% crit?

**Comment by Rushor** [comment]
DB/Spell: Implement Master Poisoner

* closes https://github.com/dalaranwow/dalaran-wow/issues/1782
* commit: 2c3bf75fb01597e994c5e34587fccc34acef44bf

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on PTR.
