### ISSUE TITLE
[GO] Dreaming Glory

### ISSUE THREAD

**Issue by n-ghost** [dalaranwow/dalaran-wow#1822]
http://www.wowhead.com/object=181271
http://www.wowhead.com/item=22786

When players successfully attempts to loot the node, a following buff should be cast on him for 15 minutes: http://www.wowhead.com/spell=28694
Also, the buff should be refreshed to full duration every time player loots up another Dreaming Glory node.

Currently, player recieves no buff whatsoever when looting Dreaming Glory nodes.

**Comment by Rushor** [comment]
DB/Gameobject: Dreaming Glory - Add positive buff after looting

* closes https://github.com/dalaranwow/dalaran-wow/issues/1822
* commit: e3f9c52a80b89e09580f4e996498aa927ee6e723

![GitHub Logo](http://i.imgur.com/qJYVkZo.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
