### ISSUE TITLE
Shaman Totems Problem. (cleansing & wrath)

### ISSUE THREAD

**Issue by beefyjonez** [dalaranwow/dalaran-wow#1862]
Hey Staff!

If you specc elemental, pop Totem of Wrath, specc something else.. you will keep the spellpower buff (100 spellpower).

Thats all i have at this moment.
Cheers

**Comment by Rushor** [comment]
This was fixed toegther with several other auras/spells of classes in:

Scripts/Custom: Add spellchecks for all specs in TalentSpecializationChange

* closes https://github.com/dalaranwow/dalaran-wow/issues/3910
* commit: 09c49d49d4178adad2effd8db17adfdf546675ca

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
Fixed tohether with: 38646fdbd3e52d8e3071ba826d83f4c29f453d79
