### ISSUE TITLE
[Item] Belbi's Eyesight Enhancing Romance Goggles / Beer Goggles

### ISSUE THREAD

**Issue by Stealthmate** [dalaranwow/dalaran-wow#1891]
**How it should work**: The goggles (http://www.wowhead.com/item=33047), when equipped, should cast a buff on you ( http://www.wowhead.com/spell=42156 ) which should turn every game model into a gnome male model. And according to a comment on http://www.wowhead.com/item=33047 , ("My biggest lol has been seeing the spirit healer as a gnome. That is all."), the effect probably should persist through death, thus making the spirit healer model a gnome too. Either that OR, it should recast itself every time you resurrect.

**How it works**: When the player equips the goggles he does get the buff, however on death the buff is lost. When the player resurrects, the buff is NOT recast on them, although it can be reobtained by unequipping and then equipping the goggles again.

**Comment by Rushor** [comment]
also an issue for http://www.wowhead.com/item=34008/blixs-eyesight-enhancing-romance-goggles

**Comment by Rushor** [comment]
Game/Spells: Beer Goggles - should be death persistent

* closes https://github.com/dalaranwow/dalaran-wow/issues/1891
* commit: e4bf988c6a3bf1f70167ccbca7e0fa5405cb960d


![GitHub Logo](http://i.imgur.com/aCKdGwm.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
