### ISSUE TITLE
[NPC] Vendor in Bloodhoof has nothing to sell. 

### ISSUE THREAD

**Issue by aracnaphobia** [dalaranwow/dalaran-wow#1905]
There is a vendor in the Inn in Bloodhoof village named Magrin Rivermane that has nothing in his shop to sell to you, however you can still sell items to him and buy them back.

**Comment by Rushor** [comment]
he should not be a vendor at all. this was already fixed with https://github.com/TrinityCore/TrinityCore/issues/14121

**Comment by Rushor** [comment]
DB/Creature: Magrin Rivermane  - Remove vendorflag

* closes https://github.com/dalaranwow/dalaran-wow/issues/1905
* commit: 72658894342116a7ce1ec153503a0226943f079d

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
