### ISSUE TITLE
[Quest] Misplaced quest text: A Boaring Time for Grulloc

### ISSUE THREAD

**Issue by n-ghost** [dalaranwow/dalaran-wow#1926]
When you attempt to turn said quest (http://www.wowhead.com/quest=10721) to Baron Sablemane (http://www.wowhead.com/npc=22103), he says the same thing you read when accepting the quest. I.e.:

"< name >, I have a pet boar named Huffer. He wants to help you to have some fun with one of the nearby sons of Gruul.

Grulloc inhabits a place known as the Cursed Hollow. When you get there, let Huffer loose. The gronn will have a fine time chasing him around, and you will retrieve the bag that he guards and deliver it to Baron Sablemane.

To get to the Cursed Hollow, head down the northern ramp and east through Dragons' End. The hollow is on the eastern edge. "

Completion text should be like this instead:

"< Baron Sablemane peers inside the gronn's sack and seems satisfied >.

Very well, you have upheld your end of the bargain. With that price paid, I will give Rexxar what he seeks. "

**Comment by Rushor** [comment]
DB/Quest: A Boaring Time for Grulloc - Add correct offer reward text

* closes https://github.com/dalaranwow/dalaran-wow/issues/1926
* commit: 4380acb5ee60c338832d47d0a43b8210c540ed20
* remember to delete the cache before testing

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
