### ISSUE TITLE
[GO] Demon Portal (Desolace)

### ISSUE THREAD

**Issue by Zindai** [dalaranwow/dalaran-wow#1933]
Object: <b>Demon Portal</b> - <a href="http://www.wowhead.com/object=177243">Wowhead</a>
Quests affected: <b>Portals of the Legion</b> - <a href="http://www.wowhead.com/quest=5581/portals-of-the-legion">Wowhead</a> / <a href="http://www.wowwiki.com/Quest:Portals_of_the_Legion">WoWWiki</a> - and its Alliance equivalent of the same name - <a href="http://www.wowhead.com/quest=14374/portals-of-the-legion">Wowhead</a>

<b>The quest</b> (working as intended):
You use <a href="http://www.wowhead.com/item=14547">Hand of Iruxos</a> on a Demon Portal. It spawns a <a href="http://www.wowhead.com/npc=11937">Demon Portal Guardian</a> that you kill in order to close the Demon Portal.

<b>The issue</b>:
Demon Portals currently do not despawn after killing their Demon Portal Guardian.
Demon Portals should despawn for 2-3\* or 5\* minutes after killing their Demon Portal Guardian.

*Based on different Wowhead comments.

<b>Sources</b>:
<a href="http://www.wowhead.com/object=177243#comments:id=321360">First<a>: "<i>Use the Hand of Iruxos to close the Demon Portals. When you do this, a level 37 or 38 Demon Portal Guardian appears to stop you. They deal melee damage. <b>Kill it and the portal will close</b>. This is for the quest Portals of the Legion.</i>"
<a href="http://www.wowhead.com/quest=5581/portals-of-the-legion#comments:id=51259">Second<a>: "<i>Pretty easy quest i completed it as a lvl 36 warlock. Its easier if u just find 3 portals and loop and <b>they spawn in maybe about 2-3 min</b>. The coordinates for the 3 portals r 50,74/50,70/49,77. u dont really need to kill the mobs there but just make sure u dont get aggro by them just pull the portal guard sumwhere isolated from the mobs.</i>"
<a href="http://www.wowhead.com/quest=5581/portals-of-the-legion#comments:id=4488">Third<a>: "<i>Run to Mannoroc Coven and use the big ring portals near the road. A level 38 Doomguard appears and attacks you. Defeat him to seal the portal. <b>The portals respawn after about five minutes</b>, so if you don't want to explore the coven, locate three portals and make a loop. Be careful of patrols, several Infernos, Summoners and Doomguards have long patrol routes that take them right next to several portals.</i>"

**Comment by Demlock** [comment]
Confirmed. Portals remain in the game.

**Comment by Rushor** [comment]
DB/Gameobject: Add despawn for Demon Portal

* closes https://github.com/dalaranwow/dalaran-wow/issues/1933
* the portal wil become unusable after the demon was summoned and the portal will despawn after around 30 seconds then. After further 5 minutes it will respawn and will be usable again.
* commit: a35d0ef3ebba44d57e7304f3880db5213e05ec98

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
