### ISSUE TITLE
[Quest] text: Return to Witch Doctor Uzer'i

### ISSUE THREAD

**Issue by Zindai** [dalaranwow/dalaran-wow#1945]
Quest: <b>Return to Witch Doctor Uzer'i</b> - <a href="http://www.wowhead.com/quest=3122/return-to-witch-doctor-uzeri">Wowhead</a> / <a href="http://www.wowwiki.com/Quest:Return_to_Witch_Doctor_Uzer'i">WoWWiki</a>
Quest giver: <b>Xerash Fireblade</b> - <a href="http://www.wowhead.com/npc=36208">Wowhead</a>
Quest completer: <b>Witch Doctor Uzer'i</b> - <a href="http://www.wowhead.com/npc=8115">Wowhead</a>

<b>The progress text currently says</b>:
<code>Have you spoken to Neeru?</code>

<b>It should say</b>:
<code>Have you spoken to Xerash?</code>

**Comment by Rushor** [comment]
DB/Quest: Update requestitemtext for: Return to Witch Doctor Uzer'i

* closes https://github.com/dalaranwow/dalaran-wow/issues/1945
* remember to delete the cache before testing on ptr
* commit: 3b4d408bdc9947aae624a3ab1dd9596354b4b678

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
