### ISSUE TITLE
[Ulduar] XT-002 Deconstructor - Tympanic Tantrum Damage calculation

### ISSUE THREAD

**Issue by AlgalonEnd** [dalaranwow/dalaran-wow#1958]
Rogue feint does not reduce damage of Ground pound by 50%
Also hunter and warlock pets seem to take full damage.

**Comment by Rushor** [comment]
http://www.wowhead.com/spell=62775/tympanic-tantrum

**Comment by Rushor** [comment]
Scripts/Ulduar: XT-002 - Tympanic Tantrum damage can be reduced with some talents/spells 

* closes https://github.com/dalaranwow/dalaran-wow/issues/1958
* commit: dce6fda20b0768a50a4e1246acf8ddaf8d30dec5

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
