### ISSUE TITLE
[Item] Fire Seed

### ISSUE THREAD

**Issue by Canderous** [dalaranwow/dalaran-wow#2033]
Fire Seed was removed in patch 3.0.8, thus the object Firethorn should only yield Fire Leaf.

http://www.wowhead.com/item=39969#comments

**Comment by kalvindeane** [comment]
Bumping since this still happens.

So far, 50% of my herbs from firethorn have been the fire seeds and are totally useless.

Hardly anybody ever gets fire leaf here and it's very rare to see it on the  AH. It makes resistance flasks hard to come by.

**Comment by Rushor** [comment]
DB/Gameobject: Remove Fire Seed from loot template and set dropchance of Fire Leaf to 100%

* closes https://github.com/dalaranwow/dalaran-wow/issues/2033
* commit: 94ad5bb66540eda8e7a24cfe69d7a41635065ffb

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
