### ISSUE TITLE
[NPC] Durn the Hungerer

### ISSUE THREAD

**Issue by Canderous** [dalaranwow/dalaran-wow#2043]
He should be immune to crowd control and movement impairing effects, but he is not.

"Kiting is no longer possible since patch 2.1 He moves fast and is immune to any sort of crowd control, root, or snare. "
http://www.wowwiki.com/Durn_the_Hungerer

**Comment by Rushor** [comment]
DB/Creature: Durn the Hungerer - should be immune to crowd control and movement impairing effects

* closes https://github.com/dalaranwow/dalaran-wow/issues/2043
* commit: 3362ff243787b0aa57b9c006302e575540efcafd

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
