### ISSUE TITLE
[Item] Pandora's Plea not proccing on instant casts.

### ISSUE THREAD

**Issue by ghost** [dalaranwow/dalaran-wow#2065]
Currently:
- Pandora's Plea (http://wotlk.openwow.com/item=45490) does not proc from instant casts - at least heals. Tested by spamming some priest/paladin spells through a full mana pool with the item not being on internal cooldown (waited before starting)
- It does proc from channeled spells or spells with cast time.

How it should be:
- Instant healing/damage spells should proc it.

In it's current state at least discipline priests suffer a lot from this bug if they're using the trinket.

**Comment by Rushor** [comment]
DB/Item: Pandora's Plea - Should proc from instantcasts

* closes https://github.com/dalaranwow/dalaran-wow/issues/2065
* commit: 7b327299bacd441a6bcba70ee783d4c725d85784

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
