### ISSUE TITLE
Item:  Crudely-written Log

### ISSUE THREAD

**Issue by Naidira** [dalaranwow/dalaran-wow#207]
The item "Crudely-written Log" (http://wotlk.openwow.com/item=12842) does not drop from High Chief Winterfall during the quest "High Chief Winterfall" (http://wotlk.openwow.com/quest=5121).  The drop rate is supposed to be 100% while you have the quest active as it provides the "wrap up" for the Winterfall quest chain.

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/commit/e6571f9869ec725fb7d50c568f704d150a11b216

merged long time ago.

what was the problem?


The item currently has illogical conditions.

It requires http://www.wowhead.com/quest=5128/deprecated-words-of-the-high-chief to be rewarded in order to drop but that quest is obtained after a quest that starts by the item, so it never drops.

According to comments it should drop while http://www.wowhead.com/quest=5121/deprecated-high-chief-winterfall is taken (player has quest in log but not yet rewarded)
