### ISSUE TITLE
[Quest] Finding the Antidote

### ISSUE THREAD

**Issue by Xehpo** [dalaranwow/dalaran-wow#2090]
The following Horde/Kalimdor quest is bugged:
Finding the Antidote
Quest Id: 813
Open-WoW Link: http://wotlk.openwow.com/quest=813

What's the problem?
This is a follow-up quest of "Need for a Cure", Quest Id: 813 (http://wotlk.openwow.com/quest=812).
You can only get and complete the quest if you started "Need for a Cure".

But here the quest is ALWAYS available, and I can repeat it endlessly - even after completing the whole quest chain, and delivering the antidote.
The quest needs to be enabled only if you have the quest "Need for a Cure".

Thanks for reading and all your help and efforts!
Kind regards,
Xehpo

**Comment by Rushor** [comment]
DB/Quest: Finding the Antidote - Only show quest if player has quest: 'Need for a Cure' taken

* closes https://github.com/dalaranwow/dalaran-wow/issues/2090
* commit: 3b3ed14636b63996aaffad9448b14b80f12f490b

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
