### ISSUE TITLE
[NPC] Problem with the heroic dummy in main cities

### ISSUE THREAD

**Issue by yoyosan** [dalaranwow/dalaran-wow#2098]
Hello.

I'm a rogue and I can't get aggro on the heroic dummies, in all major cities. It acts as I'm out of LOS. I need to attack it for 2-3 minutes before I can start my rotation.

This happens for other classes like Elemental shamans.

Cheers.

**Comment by Rushor** [comment]
Scripts/World: Allow Damage for training dummies and add healthreset every 5 seconds

* closes https://github.com/dalaranwow/dalaran-wow/issues/2098
* there was a problem, that the training dummies litereally never took damage (this disabled the normal combat behaviour. 
* now the training dummies can take damage and set the health back to FULL every 5 seconds. I also increased the HP-Pool for every training dummie.
* commit: 39f2997da11c6c8ab3dfcc21a871d980dbc708f0

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
