### ISSUE TITLE
[Mage] Faerie Fire and Immunity Spells

### ISSUE THREAD

**Issue by Esunnaxqt** [dalaranwow/dalaran-wow#2127]
Casting Ice Block will not remove Faerie Fire. It should.

**Comment by Milton3450** [comment]
Confirmed. Anonying as hell.

**Comment by Rushor** [comment]
DB/Spell: Mage Ice Block cancels Faerie Fire and Living Bomb

* closes https://github.com/dalaranwow/dalaran-wow/issues/2127
* commit: 611755467fd638f28e454d0065323d98c7c38ca1

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on PTR.
