### ISSUE TITLE
[Warlock] Shadowfury vs notLoS

### ISSUE THREAD

**Issue by keki88** [dalaranwow/dalaran-wow#2165]
You cannot cast that not line in sight. That works fine.
But if you cast it LoS then enemies should be stunned/damaged NOT LoS too. Like any other AoE.

**Comment by pascagabriel** [comment]
Are you sure you tested it properly? All targeted AoE effects only interact with targets that are in LoS of the center of the AoE effect.

**Comment by keki88** [comment]
"All targeted AoE effects only interact with targets that are in LoS of the center of the AoE effect."
Yes, it's true, but shadowfury doesnt work like this. It doesnt work with the center of AoE, it checks YOU, not the center.
Tested in PVE.

**Comment by Golganeth** [comment]
Confirmed. I've been trying to reproduce the same problem with similar spells like Blizzard or Mass Dispel to no avail. 
Tagged as Warlock, but if you notice it also happens with any other targeted AoE, please let us know.

**Comment by Golganeth** [comment]
Confirmed. I've been trying to reproduce the same problem with similar spells like Blizzard or Mass Dispel to no avail. 
Tagged as Warlock, but if anyone notices that it also happens with a different targeted AoE, please let us know.

**Comment by Rushor** [comment]
Already on PTR:

Core/Spells: Fixed LoS checks for spells like shadowfury
commit: e4d6d34f6ec1440647d4f10df74bca4a7da2c199

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
already on PTR.
