### ISSUE TITLE
[Vehicle] Cycloneable Vehicles

### ISSUE THREAD

**Issue by Esunnaxqt** [dalaranwow/dalaran-wow#2170]
SotA and wintergrasp vehicles should be immune to cyclone.
Maybe more vehicles are missing the immunity but i didnt test.

**Comment by Lothloryen** [comment]
Corrected with the next server restart, thank you.

**Comment by Golganeth** [comment]
Vehicles are still vulnerable to cyclone. Re-opening for now

**Comment by Rushor** [comment]
Game/Vehicle: Apply immunity against MECHANIC_GRIP, SPELL_EFFECT_HEAL_MAX_HEALTH and Cyclone

* closes https://github.com/dalaranwow/dalaran-wow/issues/2170
* commit: 170fd0ff5e6875c264648ad51a365a863b8ec223

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
