### ISSUE TITLE
[Spell] Shadowmeld

### ISSUE THREAD

**Issue by Esunnaxqt** [dalaranwow/dalaran-wow#2175]
Shadowmeld has currently two major bugs that weaken it in PvP. 

The first is related to the lack of spell delay, described in https://github.com/dalaranwow/dalaran-wow/issues/1630 .
Since there is no spell delay, on dalaran you cant avoid any spell by shadowmelding it in the right time. It is supposed to have similiar mechanics to vanish, wich can be seen on this video: https://www.youtube.com/watch?v=TTDbFBbNgyw

The second bug is that it is giving combat in PvP, when it should work exactly the other way around: It should ALWAYS remove combat.

**Comment by Golganeth** [comment]
#1069 - After you use Shadowmeld, your character should stop doing any kind of attacks / auto-attacks.

**Comment by Esunnaxqt** [comment]
Just noting that shadowmelding incoming projectiles is currently working (example Lightning Bolt, Frostbolt, Chaos Bolt, Wrath...)

Hopefuly if you had spell delay, shadowmelding non traveling spells will be fixed too. (Blind, Psychic Scream, Polymorph...)

**Comment by KobalAlgalon** [comment]
Spell [Shadowmeld] don't reset combat in PvP. (I first use "stopattack", after [shadowmeld] or killed player and use [shadowmeld] and combat reset after 7 seconds.) 
In PvE vs mob's - all good. Please view screenshot.
![wowscrnshot_070515_214647](https://cloud.githubusercontent.com/assets/13100570/8761230/b9cf1b2c-2d4d-11e5-8fb2-abd8fac7442a.jpg)

**Comment by Vaxsysl** [comment]
You are right about PvP combat - it should instantly be reset and allow drinking. However, in PvE, it is not supposed to drop combat, it more acts a threat-pause. Check patch notes.

**Comment by warcraftgeekygamer** [comment]
@Vaxsysl 

You said, "in PvE, it is not supposed to drop combat" - which is entirely false.

http://wotlk.openwow.com/spell=58984
http://wowwiki.wikia.com/Shadowmeld

As you can see from the links I've provided Shadowmeld is supposed to temporarily* (see notes in wikia link) drop Night Elves out of combat - read the notes from the wikia link for more information.

*Using shadowmeld will temporarily remove you from combat. When you cancel the effect, all aggro that was held towards you is restored if you are still close to hostile mobs.

So if Kobal is still close to hostile mobs, then combat will be restored to him ONLY if Shadowmeld is cancelled. In the picture he attached, you can clearly see that Kobal is still in Shadowmeld and stuck in combat - which should not happen.

**Comment by Isuel** [comment]
report opened since 12 jan 2015, and still no fix? this is quite an important spell...

**Comment by Rushor** [comment]
If you fight against a boss with script (real bossencounter f.ex. in naxx, ulduar etc.)  Shadowmeld will not remove you from combat. Else in pvp it will remove you from combat now. It will also stop auto shoot after cast.

Scripts/Spells: Shadowmeld - Clear Combat in PvP-Interactions

* closes https://github.com/dalaranwow/dalaran-wow/issues/2175
* commit: 0bb32eae9ccfed90b4d48b524181e5a7691b378e

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
