### ISSUE TITLE
Fear Ward during arena preparation

### ISSUE THREAD

**Issue by Esunnaxqt** [dalaranwow/dalaran-wow#2183]
Fear Ward cooldown keeps resetting one or two times during arena preparation, and it resets one last time when arena opens.
This bug gives priest teams a HUGE advantage against fear / dispel comps and is being abused on this server right now, with GM's saying its legal (topkek).

How do i prove fear ward cooldown should not reset in arena preparation? Just watch any priest arena movie / tournament and you will see fear ward cooldown never resets like that. It should be a cooldown like all other regular cooldowns.

**Comment by keki88** [comment]
Gm's wrong. CD resets after teleporting to the arena. If you use a spell in arena preparation, it has a CD. It doesnt reset at start.
Before the start: no mana cost, instant maximum hp.
At the start: if buff timer <= 30 second then the buff disappears. debuff NOT. check priest shield.

**Comment by Esunnaxqt** [comment]
Some buffs dont disappear when arena opens, including fear ward.

The bug here is that its cooldown is getting reset a couple times for no reason during arena prep.

**Comment by keki88** [comment]
I know. I just mentioned some information about arena preparation. :)

**Comment by Lothloryen** [comment]
Thank you very much for the report, I will take a look, will keep you updated.

**Comment by Eulerw** [comment]
There are two kinds of... I mean... @keki88 "legal" doesn't mean "intended" so if you don't know the meaning of a word then look it up or u can look like a fool ;)

@Esunnaxqt I guess they say so because you can't just force a priest to not use Fear Ward on prep phase. Some players are used to do that against some setups with poor or lack of dispels. Also if you use it asap during the prep phase, its cooldown will come up earlier throughout the fight.

**Comment by Esunnaxqt** [comment]
Good point Eulerw, but using it once on prep phase isnt the abuse, the abuse is using it on yourself, your partner, your partner pet and use it again when arena starts as soon as i dispel it.

http://imgur.com/a/unARq#0

**Comment by Golganeth** [comment]
Merge with #2325
