### ISSUE TITLE
[Death Knight] Scourge Strike - Shadow damage

### ISSUE THREAD

**Issue by AraelWindwings** [dalaranwow/dalaran-wow#2192]
Scourge strike: http://wotlk.openwow.com/spell=55090

Deals 70% weapon damage, plus 12% of physical damage done as shadow damage for each of the death knight's diseases on the target.

The shadow damage should double dip from damage modifier.

http://www.mmo-champion.com/threads/836983-scourge

The Shadow damage can only be buffed, since it is essentially already reduced by the physical mitigation, resilience or other defensive effects.
NOTE: The Shadow part of the damage should never be decreased additionally to the physical damage. It should not "double dip" from damage reduction modifiers.

Right now it's a fixed 36% with 3 diseases. It should be able to be raised by modifiers (Blood presence, rage of Rivendare and more)

Example:

Three diseases, Blood presence (+15%) and Rage of Rivendare 5/5 (+10% on spells):

(12+12+12)*(1,15+1,10) = 45% Shadow damage based on physical damage.

How should it work:
The Shadow part of the damage should still be increased additionally by talents and anything else that buff Shadow damage. It will "double dip" in the DKs favor. 

Like this the Skill often loses about 5% to 20% of the damage it should really deal.

**Comment by Rushor** [comment]
Game/Spells: DK - Scourge Strike - Allow Dmgmods

* closes https://github.com/dalaranwow/dalaran-wow/issues/2192
* commit: c66ddffe594809147e0dd19d27939e61ecceb67f

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by tripleslash** [comment]
Is this live on PTR right now?

**Comment by Lothloryen** [comment]
Hello there, not yet, we will update the labels when this is testeable on the PTR. It should be soon.
