### ISSUE TITLE
[NPC] Grimtotem Geomancer not casting

### ISSUE THREAD

**Issue by Blangas** [dalaranwow/dalaran-wow#2194]
Hello.
I farming Grimtotem Geomancers for some recipe and noticed they don't use they skill. I think they should use Lava Burst (http://www.wowhead.com/spell=79886/lava-burst) instead of running to you and hitting with they staff.

**Comment by Rushor** [comment]
http://wotlk.openwow.com/npc=10760

**Comment by Rushor** [comment]
DB/Creature: Grimtotem Geomancer - Update Combatscript

* closes https://github.com/dalaranwow/dalaran-wow/issues/2194
* Grimtotem Geomancer - In Combat - Cast 'Fireball'
* Grimtotem Geomancer - In Combat - Cast 'Flamestrike'
* Grimtotem Geomancer - Between 0-50% Health - Cast 'Mass Slow' (No Repeat)
* commit: 9c5303f500f06dccfe59f9ae202e37b6bca86a23

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
