### ISSUE TITLE
Feign > Trap combo

### ISSUE THREAD

**Issue by Esunnaxqt** [dalaranwow/dalaran-wow#2196]
This combo (Feign Death > Freezing Trap Arrow) will instantly trap anyone in pvp, without needing to cover the trap with another cc.

There are hunters doing this all the time.

https://github.com/TrinityCore/TrinityCore/issues/10218

Edit: Traps should have an armament time of 1 second if the hunter is in combat, and instant if he is out of combat. Altough the combo Feign Death > Trap shouldnt drop the armament time if you used FD in combat.

**Comment by Kiwago** [comment]
https://www.youtube.com/watch?v=kKZ96TuDOto
The combo you just described occurs at 6:10 in this video
I stumbled across a video about this exact thing from retail wotlk. Unfortunately, there is no real way to prove it is retail because no description of his realm was linked to the video or his comments. The release date of the video and the quality of scripting lead me to believe the validity that this is from retail and accurate. I believe the patch is 3.1 due to shoulders and not having black arrow on his bar.

**Comment by robinsch** [comment]
On PTR.
