### ISSUE TITLE
Grizzly Hills - Multiple Missing/Unobtainable quests

### ISSUE THREAD

**Issue by tom-f** [dalaranwow/dalaran-wow#2199]
Missing:
Secrets of the Flamebinders
Thinning the Ranks
(Final part of these two is obtainable)
A Dark Influence
The Failed World Tree
(Unsure about the chain quests following these)

Unobtainable due to fire wall:
 Dun-da-Dun-tah!

**Comment by Golganeth** [comment]
Please recheck the current reports before opening new ones. Duplicated; #741 and #1996

**Comment by tom-f** [comment]
#1996 is a ticket detailing how the quest should work, not the fact that it is unobtainable due to fire wall.

#741 Speaks of the Voldrune chain, yet not the Vordrasill chain.

Therefore this is not a duplicate.

**Comment by Golganeth** [comment]
#1996 explains how the fire wall might get stuck, which is an issue with the quest itself. The quest is obtainable.

Your report can be easily overlooked since it's 3 in 1 so I kind of forgot to reference this: #433. Escape from Silverbrook is set as auto-complete and it might give troubles to players who attempt to pick it up. Make a ticket in-game and the quest will be added to your log as long as you're on that part of the chain (it leads to the World Tree chain and few other quests).

Thanks!

**Comment by aepoirier** [comment]
As of Oct. 2015 #1996 Dun-da Dun-tah is still not working as intended due to fire wall timer issues.
