### ISSUE TITLE
[Item] Minor bug. Dinossaur Bone wrong target drop

### ISSUE THREAD

**Issue by Hellfingers** [dalaranwow/dalaran-wow#2227]
Minor bug:

Right now Dinossaur Bone for the quest Roll the Bones drop from the Bloodpetal Trapper mob when it shouldn't

Roll the Bones: http://www.wowhead.com/quest=3882/roll-the-bones
Dinossaur Bone: http://www.wowhead.com/item=11114/dinosaur-bone

Proof
![wowscrnshot_020715_180939](https://cloud.githubusercontent.com/assets/10686355/6093227/42beebe2-aef5-11e4-926f-dbe73d943563.jpg)

**Comment by Rushor** [comment]
DB/Item: Remove Dinosaur Bone loot from creatures

* closes https://github.com/dalaranwow/dalaran-wow/issues/2227
* commit: 0dcc6138797856253c0f37080cb267df8b169832

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
