### ISSUE TITLE
Contagion of Rot overstacking

### ISSUE THREAD

**Issue by bition80** [dalaranwow/dalaran-wow#2231]
The title says itself : 

The Contagion of Rot debuff (disease) gave by low-level zones (Duskwood E.g) undead is overstacking, making the spell-casting, attack speed going down really fast (I personnaly reached 4.10 attack speed in cat form as a druid).

Refer to the image bellow : 
![wowscrnshot_020915_175103](https://cloud.githubusercontent.com/assets/10931501/6117784/458056f4-b085-11e4-9b8c-9a25a8c2d2ea.png)

**Comment by Gigusx** [comment]
Still exists:
![wowscrnshot_072115_194246](https://cloud.githubusercontent.com/assets/13439101/8808200/7913e6b2-2fe1-11e5-907f-5f3b0e8f252d.jpg)

Attack speed visible on the left, really surprised simple things like this don't get fixed the first week, or even the first month after they get reported.

**Comment by Rushor** [comment]
DB/Creature: Prevent overstacking for 'Contagion of Rot'

* closes https://github.com/dalaranwow/dalaran-wow/issues/2231
* the stackamount should always be one now
* commit: 32dc425cade27cc8904effac251f2956f9405023

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
