### ISSUE TITLE
[NPC] Rajah Haghazed abilities/script

### ISSUE THREAD

**Issue by taralej90** [dalaranwow/dalaran-wow#2249]
The bounty target for the quest "Leader of the Darkcrest" in Zangarmarsh, this guy is a real pain as he has a Cleave with a knockback, a Mortal Strike and also a Shield Wall. He also switches between a sword + shield and a polearm and is immune to CC.

Well, at least he should. I just killed this pathetic phony and all he did was low-damage auto-attacks - no abilities, no CC immunity, no weapon swapping.

Side note: the elite for the other quest, Leader of the Bloodscale, works fine.

**Comment by Zibathy** [comment]
Yeah I remember I was like "lol free quest completed" when I did this quest. Can confirm this guy's a real pushover.

**Comment by Rushor** [comment]
DB/Creature: Rajah Haghazed - Add abilities and CC immunity

* closes https://github.com/dalaranwow/dalaran-wow/issues/2249
* commit: a1b64cda95627ee4f9737e6ac9f59727b5bb9d26

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
