### ISSUE TITLE
[GO] Cobalt ore in Nagrand

### ISSUE THREAD

**Issue by Neomah** [dalaranwow/dalaran-wow#2267]
cobalt ore in outlands nagrand see screenshot, co ords top left corner

http://s12.postimg.org/rqm57lx59/cobaltnagrand.jpg

**Comment by Rushor** [comment]
DB/Gameobject: Remove Cobalt ore from outland

* closes https://github.com/dalaranwow/dalaran-wow/issues/2267
* commit: c20174882268b0f42406a8152ebcad578ac3c71f

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
