### ISSUE TITLE
Gluth in Naxxramas 10-man / Zombie Chow

### ISSUE THREAD

**Issue by Xehpo** [dalaranwow/dalaran-wow#2279]
Dear Development Team,

currently when you engage Gluth in Naxxramas 10-man, Zombie Chow will spawn randomly from any of the three grates in the room during the encounter.
That is correct for the 25-man version of this encounter.
In the 10-man version, however, Zombie Chow are supposed to just spawn from the *middle* grate in the room - the one Gluth is standing on before the pull.
This significantly changes the dynamics of this fight and the one-man-kiter strategy is not working as intended for this encounter in many cases (mostly only a tank specced paladin will be able to pick up the zombie chow that spawn all over the 3 grates, while if they were spawning correctly, a frost mage or hunter could easily solo-kite them, too).

There are 2 threads labelled "Naxxramas Bug Report" #1392 and "Naxxramas - Official Developer Report #1415 which both state that Zombie Chow was only spawning from the middle grate at the time when the issue was reported, but should spawn from all three grates instead - like stated before, that is *only* true for the 25-man version of this encounter.

In #1392 there is also a video posted about how the encounter should be working, and actually it shows the correct spawning of Zombie Chow in a 10-man raid.

I'd like to link the video again: [please see 0:48+ for the first spawn of zombies.] (https://www.youtube.com/watch?v=HvQHYCpmWvQ)

And I'd like to post a few more videos that show the 10-man version of the fight:
[10-man Gluth / Hunter kiting (PoV)] (https://www.youtube.com/watch?v=lfv5AJUG-hI) starting at 0:30.
[10-man Gluth / How to] (https://www.youtube.com/watch?v=NFgv4fHsqNE) starting at 2:26.
And a more recent video of a [lvl 85 DK soloing Gluth] (https://www.youtube.com/watch?v=BcRiSgD2lhI) starting right from the beginning as he already is in combat at that point and the first Zombie Chow already spawned.

All videos show how Zombie Chow is only spawning from the middle crate like it is intended to in 10-man raids.

Please look into this and check if it can somehow be applied to our current 10-man encounter, too.
Many thanks and kind regards,
Xehpo

**Comment by chaodhib** [comment]
Yep. I also found this video: https://www.youtube.com/watch?v=5zCaNIaenW0&feature=youtu.be&t=8m28s
We can clearly see that each zombie pops at the same spot which is right under the pipe.

Since the code of the "hardest version" is already written, this bug should be fairly easy to fix.

For reference, TrinityCore uses those lines of code to script the zombies summoning (at https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/Naxxramas/boss_gluth.cpp, line 130):

```C++
case EVENT_SUMMON:
    for (int32 i = 0; i < RAID_MODE(1, 2); ++i)
    DoSummon(NPC_ZOMBIE, PosSummon[rand32() % RAID_MODE(1, 3)]); //(1)
    events.ScheduleEvent(EVENT_SUMMON, 10000);
break;
```

with
```C++
Position const PosSummon[3] =
{
{3267.9f, -3172.1f, 297.42f, 0.94f},
{3253.2f, -3132.3f, 297.42f, 0},
{3308.3f, -3185.8f, 297.42f, 1.58f},
};
```

The interesting line here is (1) where `RAID_MODE(1, 3)` equals 1 in 10-man raid and 3 in 25-man raid. So basically `rand32() % RAID_MODE(1, 3)]` always equals 1 in 10-man raid and equals 1, 2 or 3 (with equal chances, 33.3% each) in 25-man raid. Which is a great way to solve our problem.

Thank you for reading me.
Chaodhib

**Comment by miraco** [comment]
/push 
This still istn fixed

**Comment by chaodhib** [comment]
Nop.

And zombies tunnel vision the first person they aggro until hit by decimate. That's also not like the original behavior.

**Comment by Lothloryen** [comment]
This was corrected already - thank you very much.
