### ISSUE TITLE
[Item] Yeh'kinya's Scroll

### ISSUE THREAD

**Issue by daxpedda** [dalaranwow/dalaran-wow#2285]
<ul>
<li>
<b>Issue Present:</b> You can not obtain <a href="http://wowhead.com/item=10818">Yeh'kinya's Scroll</a>.
</li>
<hr></hr>
<li>
<b>How it should work:</b> After finishing the quest <a href="http://wowhead.com/quest=3528">The God Hakkar</a> there should be a dialog option from <a href="http://wowhead.com/npc=8579">Yeh'kinya</a> giving you <a href="http://wowhead.com/item=10818">Yeh'kinya's Scroll</a>. Without it you can't summon the Avatar of Hakkar after completing the quest.
</li>
<hr></hr>
<li>
<b>Proof:</b> You can read about the scroll at <a href="http://wow.gamepedia.com/Yeh%27kinya%27s_Scroll">gamepedia</a> or at <a href="http://wowhead.com/item=10818/#comments">wowhead comments</a>.
</li>
</ul>

**Comment by beregas** [comment]
Just confirmed it today, no option to get the scroll, so can only do the boss if someone in the party's got the egg

**Comment by Rushor** [comment]
DB/Item: Yeh'kinya's Scroll - Add gossipoption to obtain Yeh\'kinya\'s Scroll

* closes https://github.com/dalaranwow/dalaran-wow/issues/2285
* if the player has quest 3528 completed and does not have the item 10818 (in inv. or bank) Yeh'kinya will give you the option to abtain the item.
* commit: 65d285604be48459fe68340d72a94d29f61d49f0

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
