### ISSUE TITLE
[Quest][Icecrown] Assault by Air

### ISSUE THREAD

**Issue by Mantigora** [dalaranwow/dalaran-wow#2286]
**Link:** [Assault by Air (Alliance)](http://wotlk.openwow.com/quest=13309)

---

**Issue:** There is no plane spawned.

---

**How it should work:** you jump on a turret that's on the front of a plane (at ground level) and it flies you to the area to complete the quest

---

**Proof:** Video from Youtube - [Assault by Air](https://www.youtube.com/watch?v=AK-y8x4ti60)

**Comment by ashido96** [comment]
Also, for the horde side of this quest (can complete it and get credit), once the plane reaches its destination it disappears and drops you to your death unless you have a bubble/slowfall mechanic.

**Comment by MrAndersonX** [comment]
Confirmed - bugged.

**Comment by Rushor** [comment]
- use respawn-sai-action to make this work again

**Comment by Rushor** [comment]
DB/Quest: Assault by Air - Enable faster respawn for transports

* https://github.com/dalaranwow/dalaran-wow/issues/2286
* the vehicle will respawn faster now
* commit: a07295d3c0ea374a1304e34165d01ff9ab7562f5

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on PTR.
