### ISSUE TITLE
[Achievement] Looking For More/Many/Multitudes

### ISSUE THREAD

**Issue by ConradSilverwind** [dalaranwow/dalaran-wow#2298]
Problem: Upon finishing a heroic difficulty dungeon via the Dungeon Finder tool, players receive 1 credit for this achievement.

How it should work: Players should get 1 credit for every player in their dungeon group, excluding themselves. Example: for a full group ( five people ) each player is granted 4 credits toward these achievements.

**Comment by Golganeth** [comment]
Confirmed. Each player should get 1 credit towards each non-premade member of the group.
*"...until you have grouped with 50 random players total."*

For example:
- Premade of 4 members + 1 random player; **The 4 members get 1 credit. The random player gets 4 credit**
- Premade of 5 members: **0 credit**

And so on.

**Comment by ConradSilverwind** [comment]
Oh yeah, my bad. I forgot that "pre-made" part.

**Comment by Rushor** [comment]
Ref: https://github.com/TrinityCore/TrinityCore/issues/12187

**Comment by Rushor** [comment]
Scripts/DungeonFinding: Implement Looking For More/Many/Multitudes

* closes https://github.com/dalaranwow/dalaran-wow/issues/2298
* commit: 5442b182d9c300aee6fd65baf2359c5d201a8d3a

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
