### ISSUE TITLE
[NPC] Skreah [Missing Item to Sell] - [Recipe: Transmute Primal Might]

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#2301]
Skreah"Alchemy Supplies" in Shatrath City does not sell - Recipe: Transmute Primal Might

Skreah: http://www.wowhead.com/npc=19074/ http://wotlk.openwow.com/npc=19074
Recipe: http://www.wowhead.com/item=23574/ http://wotlk.openwow.com/item=23574

**Comment by n-ghost** [comment]
He does, bought out recipes just can't be seen in the vendor screen (more of a general issue).

**Comment by Xehpo** [comment]
Like n-ghost said, the recipe will reappear after some time.
But it is intentional that you cannot see a sold out item. You never were able so see the sold out items of a vendor in retail, either. Only after you were buying out an item, you will then see the vendors stock to be 0/x. As soon as you close the vendors window, and reopen it, it will be gone completely.

http://www.wowwiki.com/Limited_quantity_recipes
