### ISSUE TITLE
[Quest][Classic] Take Five Bases

### ISSUE THREAD

**Issue by ConradSilverwind** [dalaranwow/dalaran-wow#2302]
Problem: Quest is obtainable ( and auto-completed ) without having the exalted reputation with The Defilers.

How it should work: Only players who are exalted with those factions can take the quest.

http://wotlk.openwow.com/quest=8122

**Comment by Rushor** [comment]
DB/Quest: Take Five Bases - Add Minrepvalue for faction "The Defilers"

* closes https://github.com/dalaranwow/dalaran-wow/issues/2302
* commit: 962bf0c802caa6c84a7423ba671c2c0c347c911d

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
