### ISSUE TITLE
[Quest][DF] Random dungeon finder exp bug

### ISSUE THREAD

**Issue by Flamethrowerz** [dalaranwow/dalaran-wow#2304]
Where-Any random dungeon find dungeon
What-When I run dungeons through random dungeon finder and clear the last boss which awards satchel of helpful goods it says the amount of xp in my chat in yellow letters but my xp bar doesn't receive it, I've heard people saying it works for people using Recruit a Friend but without it is does not work, Sorry I can't provide any more information, Please fit it and thanks. :)

**Comment by daxpedda** [comment]
As far as I noticed you receive the XP the first time you do RDF in a day, after that it still displays in the chat log but you don't receive them. I remember on Blizzard you should get the XP only one time a day, after that I don't remember exactly what happens.

The <a href="http://wow.gamepedia.com/index.php?title=Dungeon_Finder&oldid=2386607#Rewards">WoWPedia Arictle</a> states the following:
<q>The Daily money and XP rewards depends on the character level. The following table contains the rewards for each levels first random dungeon of the day, any other runs during the same day will yield approximately half the money and experience</q>

**Comment by Rushor** [comment]
this was fixed with https://github.com/TrinityCore/TrinityCore/commit/7905651b0793d47b4ba040ad6ac47231ad3ec9d2


The fix is already on ptr:

Core/Quest: do not save/load Dungeon Finder/daily/repeatable quests as completed (#17458)

* Core/Quest: do not save/load Dungeon Finder/daily/repeatable quests as completed
* commit: f792b6a01a0f78870b86889f90921e6256584405

**Comment by Rushor** [comment]
already on PTR.
