### ISSUE TITLE
[NPC] Wetlands Soldier's

### ISSUE THREAD

**Issue by TheLichWarrior** [dalaranwow/dalaran-wow#2308]
Zone:Wetlands
Location:Dun Modr North near Dam
Dark Iron Rifleman's dont wield Rifle's instead they cary Axe's and dont atack.
Place Gun's and remove axes and make em shoot Thank you.

http://wotlk.openwow.com/npc=6523

**Comment by Rushor** [comment]
```sql
-- Dark Iron Rifleman SAI
SET @ENTRY := 6523;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,4,0,15,1,0,0,0,0,1,0,0,0,0,0,0,7,0,0,0,0,0,0,0,"Dark Iron Rifleman - On Aggro - Say Line 0 (No Repeat)"),
(@ENTRY,0,1,0,0,0,100,0,0,0,2300,5000,11,6660,64,0,0,0,0,2,0,0,0,0,0,0,0,"Dark Iron Rifleman - In Combat CMC - Cast 'Shoot'"),
(@ENTRY,0,2,0,0,0,100,0,16100,16100,20100,32200,11,7891,3,0,0,0,0,5,0,0,0,0,0,0,0,"Dark Iron Rifleman - In Combat - Cast 'Gift of Ragnaros'"),
(@ENTRY,0,3,0,2,0,100,1,0,15,0,0,25,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Dark Iron Rifleman - Between 0-15% Health - Flee For Assist (No Repeat)");
```

**Comment by TheLichWarrior** [comment]
Job well done thank you

**Comment by Rushor** [comment]
that's not on your server already, i think

**Comment by Rushor** [comment]
DB/Creature: Dark Iron Rifleman - Update Combatscript

* closes https://github.com/dalaranwow/dalaran-wow/issues/2308
* commit: 30851899941fe4aef71de31b9f8ef386278ea81c

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
