### ISSUE TITLE
Quest : Bodyguard for Hire 

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#231]
Quest Name: Bodyguard for Hire
Quest ID: 5821
http://www.wowhead.com/quest=5821

Detail what should happen instead of nothing:
Escort the Gizelton Caravan past the Kolkar Centaur village.Talk with Smeed at Scrabblescrew's Camp for your reward.

**Comment by Cone182** [comment]
still bugged, you talk to the npc, get the quest but the npc stops and no event starts.

**Comment by Rushor** [comment]
065f36c4957efbfe18d246bcaa173e3301031cf3
-  added the escortevent

**Comment by Golganeth** [comment]
Can't seem to be able to pick up the quest and start the escort event. The NPCs get stuck on the hut once they finish their path.

**Comment by Rushor** [comment]
http://i.imgur.com/xV0H0z4.jpg
http://i.imgur.com/KNxOP7R.jpg

once they reached the hat, they will wait there 15 minutes, after that they will move on some time to this point http://i.imgur.com/KNxOP7R.jpg. there you can accept the quest and the creatures will move on. same goes for the other quest :)

**Comment by Golganeth** [comment]
Along their way out of the huts, the NPCs may get stuck when trying to get in combat against NPCs. At that point they'll be charging and insta evading. If that NPC is killed, they will be stuck and not move at all anymore, so quests can't be obtained.

Something must be done about it, reopening for now.

**Comment by Rushor** [comment]
DB/Creature: Cork Gizelton + Rigger Gizelton + Gizelton Caravan Kodo - Increase combatdamage

* the creatures should now easier be able to slay the enemies and should no longer evade
* updates: https://github.com/dalaranwow/dalaran-wow/issues/443
* updates: https://github.com/dalaranwow/dalaran-wow/issues/231
* commit: a4cd8398038082d6b8c9240329d61624f02bdadd

DB/Creature: Cork Gizelton + Rigger Gizelton + Gizelton Caravan Kodo - Add threat value for summoned creatures

* updates: https://github.com/dalaranwow/dalaran-wow/issues/443
* updates: https://github.com/dalaranwow/dalaran-wow/issues/231
* commit: 9a999cbcb8ceef208d748272d34ebf0e5f4d03f5

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
Scripts/Desolace: Gizelton - Do not start escortpathevent if the creature is in combat 

* commit: e4fcf15a0758b30b453dde5ec05514dbc514dd5e
* updates: https://github.com/dalaranwow/dalaran-wow/issues/231
* updates: https://github.com/dalaranwow/dalaran-wow/issues/443

With this fix the creatures should always properly start their pathing once the hostile creatures are killed.

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by galgnu** [comment]
Please keep this in mind for next deployment and please include both Super-Seller 680 & Vendor-Tron 1000 they are needed in order to get the  [Chef de Cuisine] achivement. 
Thanks!
