### ISSUE TITLE
[Quest][Classic] Natural Materials

### ISSUE THREAD

**Issue by stromex** [dalaranwow/dalaran-wow#2313]
Hello
The quest works okay up to a point where u have to loot Splintered Log ( http://www.wowhead.com/item=9590/splintered-log ) from Wandering Forest Walker ( http://www.wowhead.com/npc=7584/wandering-forest-walker ). They should have 100% chance to drop the quest item (according to wowhead comments) but they don't. I had to kill this mob 6 times (the only place i found it was 57 73 Feralas) so i can get my 2 pieces of Splintered Log. 
Thanks.

**Comment by xxauroraxx** [comment]
There are other ones available. There is one that can spawn behind Camp Mojache. I THINK I saw one near the Twin Collosi but can't confirm.

**Comment by Rushor** [comment]
DB/Quest: Natural Materials - Increase droppchance of  Splintered Log to 100 percent

* closes https://github.com/dalaranwow/dalaran-wow/issues/2313
* commit: 31d17ae2c915dfe32ddee2e18ed0386572e0471e

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
