### ISSUE TITLE
[Quest] Banish the Demons

### ISSUE THREAD

**Issue by Tarpor** [dalaranwow/dalaran-wow#2314]
### How it is:

NPC **Kronk**_23253_ gives the quest **Banish the Demons**_11026_ after hitting _Revered_ with **Ogri'La**_1038_
### How it should be:

NPC **Kronk**_23253_ should give the quest when you hit _Honored_ , the corresponding quest **A Crystalforged Darkrune**_11060_ is already given at _Honored_ by NPC **Gahk**_23300_

**Comment by Crispybuilt** [comment]
Confirmed, he should give the quest after a player hits Honored and not Revered.

**Comment by Crispybuilt** [comment]
Aside from this, I just want to mention that this quest works flawlessly, I haven't seen a better script anywhere.

**Comment by Rushor** [comment]
DB/Quest: Banish the Demons - min. reputation must be Honored

* closes https://github.com/dalaranwow/dalaran-wow/issues/2314
* commit: d0c3ddc720b937c6c0807c11f7e9805780a30186

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on ptr.
