### ISSUE TITLE
[Achievement] Within Our Grasp

### ISSUE THREAD

**Issue by ConradSilverwind** [dalaranwow/dalaran-wow#2316]
Problem: Players can get this achievement just by winning the battle for Wintergrasp, and even as defenders.

How it should work: Only attackers that win the battle within ten minutes are eligible for the achievement.

**Comment by Rushor** [comment]
Game/Zones: WG - Only reward ACHIEVEMENTS_WIN_WG_TIMER_10 for the attackerteam 

* closes https://github.com/dalaranwow/dalaran-wow/issues/2316
* commit: 15268b06f48eb8db1ca71ff8fde5dc612291c448

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
