### ISSUE TITLE
[Quest][Classic] Arcane Runes

### ISSUE THREAD

**Issue by Jazex** [dalaranwow/dalaran-wow#2317]
http://www.wowhead.com/quest=3449/arcane-runes

You can collect the rubbings without a problem, but in order for the pilot (Xiggs Fuselighter) to be able to pick you up in Azshara he has to give you a flare gun by speaking to him in Ironforge. However there is no script for speaking to him and therefore you are unable to obtain the flare gun and unable to summon him in Azshara to hand in the quest.

**Comment by Rushor** [comment]
DB/Quest: Signal for Pickup (3483) - Should be repeatble, and the player should always be able to get 'Standard Issue Flare Gun' after prev.quest Signal for Pickup  (3451) was rewarded

* closes: https://github.com/dalaranwow/dalaran-wow/issues/2317
* commit: 8c2e1eb9b3299b334a8d2615e71930f2639b78e7

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
