### ISSUE TITLE
[Item] Eye of Broodmother procs

### ISSUE THREAD

**Issue by 1repmax** [dalaranwow/dalaran-wow#2323]
http://www.wowhead.com/item=45308/eye-of-the-broodmother

Doesn't trigger if you are casting Vampiric touch, Devouring plague, Shadow word:Pain, but it should. Also it should apply a stack at initial cast of mind flay(doesn't apply here) and not add extra stacks on each consecutive channeling tick .

**Comment by Vaxsysl** [comment]
Eye of the Broodmother doesn't tick on any periodic damage.

**Comment by 1repmax** [comment]
Devouring plague initial cast isn't a tick for shadow priest. Also it
should proc on first damage of mind flay.

**Comment by Rushor** [comment]
DB/Item: Eye of Broodmother - Also procc from dots

* closes https://github.com/dalaranwow/dalaran-wow/issues/2323
* commit: 824421d0061a7da92ea46637a5a14b8bf1057bd1

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
