### ISSUE TITLE
[Mage] Molten Armor triggers Ignite

### ISSUE THREAD

**Issue by gotnoface** [dalaranwow/dalaran-wow#2327]
As of patch 3.2.0 Molten Armor shouldn't trigger mage talent Ignite. http://www.wowwiki.com/Molten_Armor

**Comment by Illiyara** [comment]
As of now this is still bugged.

**Comment by Rushor** [comment]
Scripts/Spells: Mage Ignite should not proc on Molten Armor

* closes https://github.com/dalaranwow/dalaran-wow/issues/2327
* commit: bd2b34de18eccd0486cbc7e9bc012b4e977edc4a

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on PTR.
