### ISSUE TITLE
[Quest][Classic] Cenarion Circle reputation gains

### ISSUE THREAD

**Issue by Bonham01** [dalaranwow/dalaran-wow#2335]
The reputation gains for Cenarion Circle are off. The repeatable quest "Encrypted Twilight Texts" only gives 250 reputation per turn in instead of the 500 it is supposed to give (http://www.wowhead.com/quest=8319/encrypted-twilight-texts). Also the NPC "Twilight Geolord" only gives 2 reputation when killed instead of 10 like it is supposed to. This seems to be the only Twilight NPC that has this issue. This is a similar issue to the Timbermaw Hold repeatable turn ins #2190

**Comment by ImprezaWoW** [comment]
http://db.vanillagaming.org/?quest=8319

**Comment by Rushor** [comment]
the +2 rep is right, see the old wowiki entries: http://wowwiki.wikia.com/index.php?title=Twilight_Geolord&diff=2432666&oldid=2269032

**Comment by Rushor** [comment]
DB/Quest: Encrypted Twilight Texts - Increase reputationrewar to 500

* closes https://github.com/dalaranwow/dalaran-wow/issues/2335
* commit: 88ef263de883f1417b5c773ef1203a3d00b75564

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
