### ISSUE TITLE
[Quest] Darkmoon Faire Minor Prize

### ISSUE THREAD

**Issue by vivalagrunt** [dalaranwow/dalaran-wow#2337]
In the Darkmoon Faire when selecting "5 Tickets - Minor Darkmoon Prize" nothing is received upon opening the box. I am playing on the Kirin Tor server.

**Comment by Rushor** [comment]
problem: the item needs a refernce loot entry to drop at least 1 item

**Comment by Rushor** [comment]
DB/Item: Minor Darkmoon Prize - Move loot to reference_loot_template, it should always contain at least 1 item now

* closes https://github.com/dalaranwow/dalaran-wow/issues/2337
* commit: 3d8ebe43094c0537a436931db5a838291e54e54f

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
