### ISSUE TITLE
Using auto-unstuck while dead bugs you

### ISSUE THREAD

**Issue by M0dinstaller** [dalaranwow/dalaran-wow#2350]
If you use the auto-unstuck feature while in ghost form after having died, you will stop being able to see most spirit healers and therefore will not be able to res (if you can't reach your body).
Then, if you relog, you will get ported to your race's starting zone still as ghost and while still not being able to see most spirit healers.

I got this twice and fixed it twice by going to a neutral spirit healer (hence why I said you can't see most of them). I didn't try all of them so I'm not sure.

**Comment by Rushor** [comment]
Works fine for me on ptr, for neutral spirit healer and normal spirit healer.

**Comment by Aridam** [comment]
Confirmed -- angrily.

I got ganked by someone but I couldn't see as I was lagging and shortly got DC-ed -- as a result upon relogging I apparently was already a ghost so supposedly indeed ganked or since I must've been in Combat still that DC auto-killed me, but since there's another bug which causes mid-air corpses to stay there instead of falling, I couldn't reach my corpse, but I didn't want Resurrection Sickness; I used Auto-Unstuck, but it didn't work at all, so I went back to get to the Spirit Healer having no remaining choice -- THE SPIRIT HEALERS ARE GONE.

Then I relogged and now I'm in Tirisfal and I can't see ANY Spirit Healers, so now, judging by how this person's problem got resolved by going to a Neutral Spirit Healer, I'm now supposed to go find one myself.

Lovely.
