### ISSUE TITLE
[Item] Recipe Formula: Enchant Shield - Major Stamina

### ISSUE THREAD

**Issue by Leodimas** [dalaranwow/dalaran-wow#2381]
This recipe is sold by madame ruby in shattrath city. It is an essential recipe for enchanters to use while leveling.
According to commends from 2010 on wowhead ( http://www.wowhead.com/item=28282/formula-enchant-shield-major-stamina#comments ) this recipe should be restocking every 10-15 minutes.

As it is not it does not restock more than twice a day. I spend 6 hours of last night chilling shattrath opening a trade window every 5-10 minutes. No result.

Also some comments on the NPC Madame Ruby itself talk about a 10-15 minute timer on all the repices she sells.

**Comment by Rushor** [comment]
DB/Item: Formula: Enchant Shield - Major Stamina - Reduce respawntimer to 15 minutes

* closes https://github.com/dalaranwow/dalaran-wow/issues/2381
* commit: 072b6d032a30310339dd48041b55203f0c731fde

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
