### ISSUE TITLE
[NPC] Alterac Valley Reputation Gains

### ISSUE THREAD

**Issue by ConradSilverwind** [dalaranwow/dalaran-wow#2383]
Problem: 

Reputation gains for Stormpike Guard and Frostwolf Clan are not working the way they should. Players get only reputation for killing the captain (+125), the general  (+350) and burning down the bunkers/towers (+12, should be +64), and get no bonus reputation after the battle is over.

How it should work: 

Killing Enemy General (Drek'Thar, Vanndar Stormpike) (350 Rep) - works
Killing Enemy Captain (Galvangar, Balinda) (125 rep) - works
Killing an Enemy Air Master (5 rep)
Killing any Enemy Guard (caps at "honored") (5 rep)
Killing Enemy Miners and Overseers (caps at "friendly") (5 rep)
Killing Stormpike Owl or Frost Wolf (caps at "friendly") (5 rep)
Killing an Enemy Player (1 rep)
Killing Ivus the Forest Lord or Lokholar the Ice Lord (125 rep)
Destroying an Enemy Tower (64 rep) - partially works
Slidore/Guse (Wing Commanders) (1 rep)
Vipore/Jeztor (Wing Commanders) (2 rep)
Ichman/Mulverick (Wing Commanders) (5 rep)

**Comment by ConradSilverwind** [comment]
Reputation gain for alive allied captain works now.

**Comment by Rushor** [comment]
DB/Creature: Add Stormpike Guard + Frostwolf Clan reputation for creatures in AV

* closes https://github.com/dalaranwow/dalaran-wow/issues/2383
* commit: 0cdab99f37ca05c630ffd38d9ff56ca014ceea30

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
