### ISSUE TITLE
[Quest] Quest text: Tree's Company

### ISSUE THREAD

**Issue by n-ghost** [dalaranwow/dalaran-wow#2399]
http://www.wowhead.com/quest=9531/trees-company

The completion message currently is misplaced. Admiral Odesyus says the quest description message again when you attempt to turn in the quest.

![wowscrnshot_052015_202138](https://cloud.githubusercontent.com/assets/8515510/7732110/fc4453e4-ff2d-11e4-8f53-2797fe170a8a.jpg)

The completion message should be the following instead:

_I can't believe it! It was the gnome all along... I should have known!_

**Comment by Rushor** [comment]
DB/Quest: Tree's Company - Update offer-reward-text

* closes https://github.com/dalaranwow/dalaran-wow/issues/2399
* commit: 0e0eb9009fa969b18b0271f51fcb3d177975deaa

Remember to delete the cache before testing.

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
