### ISSUE TITLE
[Quest] Proving Grounds 

### ISSUE THREAD

**Issue by Zantu** [dalaranwow/dalaran-wow#2439]
http://www.wowhead.com/quest=7161/proving-grounds#screenshots

Quite simple and forward. Enter AV. Go through cave. Pick up banner en the back of the cave in the Island on the frozen lake.
Banner just isn't there :(

**Comment by Rushor** [comment]
http://wotlk.openwow.com/object=179025
http://wotlk.openwow.com/object=179024

DB/Quest: Proving Grounds - Add gameobjectspawns in AV

* closes https://github.com/dalaranwow/dalaran-wow/issues/2439
* commit: 05a1094b48118ad029f5cf13d883c893f24410f6

![GitHub Logo](http://i.imgur.com/SKBJWuW.png)
![GitHub Logo](http://i.imgur.com/JlbmDRa.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
