### ISSUE TITLE
[Spell] Shadowmeld & PvP flag not working properly.

### ISSUE THREAD

**Issue by AgeAgainst** [dalaranwow/dalaran-wow#2441]
Using the ability Shadowmeld will flag a player for PvP.  Replicated on two characters.

It did not flag while in the starting area, but after I left it and ran towards Darnassus, I used the ability and it flagged for PvP.  I also had a second character already in Darnassus and used Shadowmeld and was flagged for PvP

Logging out and back in removes the flag.  

Not sure why a racial is flagging players for PvP.

**Comment by Rushor** [comment]
Game/Spells: Make certain spells (e.g. Mind Control) properly flag the caster for PvP + Disable flagging PvP for selfcast (e.g. Shadowmeld)

* closes https://github.com/dalaranwow/dalaran-wow/issues/2441
* commit: d7ba5b453faa5344cf66ec0ca5fd382c30a89c9e

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
