### ISSUE TITLE
Achievement: Terokkar Turkey Time

### ISSUE THREAD

**Issue by AgeAgainst** [dalaranwow/dalaran-wow#2445]
Terokkar Turkey Time:
<World Events - Pilgrim's Bounty)
Defeat Talon King Ikiss while wearing a Pilgrim's Hat and either a Pilgrim's Dress, Robe or Attire.

Anyone who kills Talon King Ikiss will receive this achievement, regardless of the items you are wearing.

**Comment by ConradSilverwind** [comment]
Confirmed.

**Comment by warcraftgeekygamer** [comment]
I can also confirm this as it happened to my group last night.

**Comment by Demlock** [comment]
Confirmed. Fix please!

**Comment by Rushor** [comment]
DB/Achievement: Terokkar Turkey Time - You need to wear the dress in order to get the achievement

* closes https://github.com/dalaranwow/dalaran-wow/issues/2445
* commit: 72807cd73c69d4394e99514741cc347bafba87ec

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
