### ISSUE TITLE
Tome of Valor not working

### ISSUE THREAD

**Issue by whoan00** [dalaranwow/dalaran-wow#2452]
I can get the quest from Duthorian Rall, but when i get to Daphne Stilwell, she wont let me turn in the quest so the defias attack can begin even though the question mark is shown on the map.

Cheers!

**Comment by n-ghost** [comment]
:||

![wowscrnshot_070615_232327](https://cloud.githubusercontent.com/assets/8515510/8532351/46d16708-2436-11e5-80d3-60da55abcfa3.jpg)

**Comment by n-ghost** [comment]
So, I've done this quest after server reset, and seems like one of these statements is true:

a) Daphne will bug out if players won't engage Defias thugs that spawn outside the orchard (by the way, they are actually meant to run at you, not just stand there).
b) Daphne MIGHT bug out after you successfully protect her, at some point she was inclined to run to the position the players see her usually atm. Stopping her by talking prevents the issue though.
c) Daphne MIGHT bug out if someone wipes on the encounter.

**Comment by Naidira** [comment]
Following n-ghost's suggestions, I found Daphne and she was not broken.  The quest went as described, but the Defias spawned for six consecutive waves.  The nonstop waves were so overwhelming that I had to pause to bandage, causing two lingering Defias NPCs to despawn in the distance.  The waves ceased and Daphne promptly bugged.

Presumably, she will remain that way until a server reset.

**Comment by jonanone** [comment]
We have made some changes to Daphne in order to avoid the issues described above:

- If the player who started the event goes too far away from Daphne while she is out of combat, she will despawn.
- Since Daphne despawns when the event is finishing, if another player tries to start the quest in that moment, it will automatically fail.
- Summoned creatures will despawn if Daphne dies.

These changes will be added to the live realm soon.
