### ISSUE TITLE
[Hunter][Pet] Pet Hit Rating not scaling properly

### ISSUE THREAD

**Issue by kazubla** [dalaranwow/dalaran-wow#2456]
My pet is missing constantly even though I am at 267 (8.14%) Hit rating. 

http://www.huntsmanslodge.com/1871/hunter-hit-cap-perfection/

The pet should be gaining my hit rating as well as that equivalent of expertise so it should not be missing as long as I am over 8%.

This is a parse from the instance Halls of Lightning with my level 80 wolf
![wowscrnshot_053115_114319](https://cloud.githubusercontent.com/assets/12538122/7901649/6b0cea7a-078a-11e5-9b8c-ef23d2a22059.jpg)

Since Halls of lightning is a heroic it should only require a hit rating of 7% and even so my pet misses.

I also tested this on the target dummy recently with the following results

![wowscrnshot_080915_145829](https://cloud.githubusercontent.com/assets/12538122/9155189/33257f60-3ea7-11e5-8d7f-5184b7f670ea.jpg)

![wowscrnshot_080915_145836](https://cloud.githubusercontent.com/assets/12538122/9155190/388e3686-3ea7-11e5-805b-1c2e1bb6fe11.jpg)

As you can see after 1000 hits of auto attack the pet missed around 5% of the time with normal attacks whilst it missed around 8% of the time with it's special ability.
This is not with the focussed aim talent.

I then took off all my gear so my hit was at 0% the results are as follows.

![wowscrnshot_080915_152936](https://cloud.githubusercontent.com/assets/12538122/9155308/f0529aec-3eab-11e5-82b3-fd568a51481c.jpg)

![wowscrnshot_080915_152939](https://cloud.githubusercontent.com/assets/12538122/9155309/f308e6a6-3eab-11e5-8360-dc71bbdae8ed.jpg)

Although I only let my pet attack for around 100 hits a pattern is showing. Since the miss rating is the same it has lead me to believe that there is some issue with the scaling that pets recieve from the hunter since I am fine myself when hitcapped.

**Comment by kazubla** [comment]
Bug still present, updated information and added some testing

**Comment by robinsch** [comment]
On PTR.

**Comment by kalvindeane** [comment]
Results of testing from PTR:

Hit rating, spell hit rating, expertise rating and resistances are scaling correctly to Hunter pets.

**Comment by Edzero** [comment]
Retested this on the PTR:

Hit rating, spell hit rating and expertise rating are scaling to Hunter pets.

Resistances are not scaling to hunter pets even though they were last year. They should scale at a rate of 0.4 to the Hunter's own resistances. When hovering over the Hunter's own resistance in the character sheet the correct amount is shown however this is not translated over to the pet's character sheet.

This also seems to be the case on the live realm. I'll mark this as On Live for now and refer to #3088 in the future for the pet resistances once the fix is pushed to PTR.
