### ISSUE TITLE
[NPC] Fumblub Gearwind

### ISSUE THREAD

**Issue by Rukker** [dalaranwow/dalaran-wow#2458]
When he's dead he should be scavengable with Engineering, not Skinning.

http://www.wowhead.com/npc=32358/fumblub-gearwind

![fumblub](https://cloud.githubusercontent.com/assets/12522162/7902857/5759c378-080b-11e5-95fd-5278812b684f.jpg)

**Comment by Rushor** [comment]
DB/Creature: Fumblub Gearwind - should be scavengable with Engineering

* closes https://github.com/dalaranwow/dalaran-wow/issues/2458
* commit: 8a752909684353aa2d47f8b18e2deda3cfe034db


![GitHub Logo](http://i.imgur.com/vPDv1Gf.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
