### ISSUE TITLE
Can you check "Anatoly Will Talk" quest

### ISSUE THREAD

**Issue by paster2529** [dalaranwow/dalaran-wow#2479]
Please help checking quest "Anatoly Will Talk", I can't ride horse back to White Pine Trading Post

**Comment by Sagrath** [comment]
You are getting auto mounted after usign the quest item on Tatjana

**Comment by Miztiq** [comment]
Dont really understand why this issue is closed. The quest dont work. The NPC Tatjana is not there, i have checked and re-checked. The horse is there though. I can mount it by rightclicking on it, but i cant go anywhere and it doesnt bring me anywhere by auto. When i dismount, using the dismount button, i end up lying under the horse.

**Comment by nowonshere** [comment]
I can confirm this bug, I tried it just now & its like what Miztiq said...

**Comment by Kaporalhart** [comment]
I confirm Miztiq, although the mouse does not change when you pass it on the horsen, you can right click on it to mount it and everything he said happens.
