### ISSUE TITLE
[Quest]'Kaw the Mammoth Destroyer'

### ISSUE THREAD

**Issue by 7193224** [dalaranwow/dalaran-wow#2511]
Kaw and his mount does not spawm at the same time, the respawn time of Kaw is too long

**Comment by Furminator** [comment]
For what I've seen Kaw does not have a long respawn timer, but an incorrent point of respawn. Was helping a friend with the quest and we stood waiting for the respawn. Since nothing happened I thought the same thing but just in case I tried "/tar Kaw" which gave me a result. He got targeted but apparently he was under the floor and far away, couldn't pull him with any skill.

P.S: Using Track Humanoids skill can prove that he is spawned somewhere around Moria (changes places) but can't be seen nor pulled.

**Comment by Sagrath** [comment]
Spawn time correct place seems to be fine too
