### ISSUE TITLE
Sharing quest in group

### ISSUE THREAD

**Issue by Shadesmar** [dalaranwow/dalaran-wow#2534]
When someone in a party starts a quest the whole group get asked if they want to pick up this quest. But clicking yes doesnt have a result when the quest giver is busy talking.
Also error messages are missing for quests that cant be shared.

**Comment by Furminator** [comment]
Confirmed, this bug makes completing things like The Ring of Blood or The Amphitheater of Anguish something really painful, since everyone has to take turns doing it.

**Comment by Cone182** [comment]
Confrmed, tried it today with 4 people, we had to kill every single npc 4 times, and we had to wait for Mogor to respawn 4 times too...

**Comment by Spruitje** [comment]
Probably related, but i've noticed now on many(all?) escort quests while in a group that if a member starts the quest you do get a system dialog asking to confirm if you want to start it too, but in fact upon completion only the starter will get the credit
Also while after clicking yes to join the quest will not show in your questlog
This means when in a 5 man group you must do a certain escort 5 times
However if players seem to be able to 'synchronize' the accept quest button given from the dialog of the NPC itself, you can manage to all be on that quest and complete it together

**Comment by npmusicftw** [comment]
Whenever a player shares a quest with a player who is too far away, in trade, or looking at another quest, the notification “So-and-so is busy.” Appears. However, after So-and-so is no longer busy, that notification continues to pop up. 
Furthermore, a lot of players automatically decline shared quests. Neither the player nor myself understand why this happens, but it should not happen unless specified by some addon or an integrated WoW Interface Option that I am not aware of. 

The only reason a person should automatically decline a quest is an addon or lightning fast reflexes (which involves a desire to decline the quest). People should not be automatically declining quests that they want. 
Also, when a player shares a quest, that quest should appear to them unless the following occurs:
1. The other players' quest log is full.
2. The other player has completed the quest already.
3. The other player is ineligible because they are too low level.
4. The other player is ineligible because they must complete prerequisite quests first.
5. The quest-giver has supplied you with an item that is needed to complete the quest (in which case, the option to share should be grayed out). 

http://wow.allakhazam.com/wiki/share_quest_(WoW)

As of patch 3.0.3 (2008-11-04), Distance restriction for sharing quests was removed. So quests should share no matter when or where. 

Quests can be shared with party members at any distance.
Quests can be shared with part members by linking the quest into party chat.
Quests can be shared in raids but not battlegrounds

http://us.battle.net/wow/en/game/patch-notes/3-0-2  - User Interface – 9 bullets down.

**Comment by Golganeth** [comment]
Merge with #3337. Sharing quest issue part has been corrected and should be applied to the live realm soon.
