### ISSUE TITLE
[Item] Engineering: Mind Amplification Dish

### ISSUE THREAD

**Issue by Rukker** [dalaranwow/dalaran-wow#2569]
Never has any effect.

http://www.wowhead.com/spell=67839/mind-amplification-dish

**Comment by Rushor** [comment]
SPELL_GNOMISH_MIND_CONTROL_CAP = 13181,
SPELL_DULLARD                                      = 67809,

0,285 % > SPELL_DULLARD   on target
0.665 % > SPELL_GNOMISH_MIND_CONTROL_CAP on target
0.05% > SPELL_GNOMISH_MIND_CONTROL_CAP on caster

Scripts/Spells: Implement effects for Gnomish Mind Control Cap and Mind Amplification Dish

* closes https://github.com/dalaranwow/dalaran-wow/issues/2569
* commit: 41c326233277b97a942bee18dd1ca96429d14a47

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
