### ISSUE TITLE
[NPC] Flame Leviathan - Engineering

### ISSUE THREAD

**Issue by Rukker** [dalaranwow/dalaran-wow#2573]
When you "skin" this mob with Engineering he's supposed to drop, among other things, some of the mats for the Mechano-Hog.

Currently he drops nothing, just disappears.

http://www.wowhead.com/npc=33113/flame-leviathan#engineering

**Comment by Vaxsysl** [comment]
Confirmed, I'm engineering him often enough and not once did I get mats for the bike.

**Comment by Rushor** [comment]
DB/Creature: Flame Leviathan - Update skinning loot

* closes https://github.com/dalaranwow/dalaran-wow/issues/2573
* commit: dbd52f038d5ec56f5015206fd4c86fbf37f2e4ea

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
