### ISSUE TITLE
Hunter: Temporary taimed pets for Taiming hunter class quest bug

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#26]
For taiming the Beast hunter quest, all of them (exampe: http://www.wowhead.com/quest=6063/taming-the-beast)
- The pets after taiming keep the hunter in combat
- the pets do not assist the hunter
- the pets do not follow the hunter 
- the quests ARE completable

**Comment by Rushor** [comment]
you must switch between stay - and follow in orther to make the pet follow you. every tamed units stays at their place after the first charme.  i think this was added to prevent further exploits?

**Comment by Darkexecutioner** [comment]
the pets do not assist the hunter. Confirmed.
the pets do not follow the hunter. Confirmed.
the quests ARE completable. Confirmed.

**Comment by Rushor** [comment]
Game/Unit: Force charmed unit to follow their charmer 

* closes: https://github.com/dalaranwow/dalaran-wow/issues/26
* commit: 921e33279e09c30ac19d58a6b9727dcc496c7774

> the pets do not follow the hunter. Confirmed.

This works by default with the fix now.

> the pets do not assist the hunter. Confirmed.

This cannot be fixed at the moment, so only test if the creature now properly follows the charmer.

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
