### ISSUE TITLE
[Ulduar] - 10 Man Razorscale

### ISSUE THREAD

**Issue by Althaloss** [dalaranwow/dalaran-wow#2616]
Hello,
I was in an Ulduar 10 man group on the Algalon server tonight. I believe that the adds that spawn during the Razorscale encounter are in line with the amount of adds that spawn in the 25 man encounter. There just seem to be too many, especially when referenced to this video of the 10 man. 

https://www.youtube.com/watch?v=2JmB87ZphW8

**Comment by Lothloryen** [comment]
Hello there,

This is working as intended.

Thank you.

**Comment by Akkalevil** [comment]
It's intended to have the same amount of adds in 10-man than in 25 ?
We encountered the same problem yesterday...

**Comment by Ekacarbez** [comment]
I'd like to acknowledge that the health on Razorscale is far too high compared to retail. There are instances where 3 drills appear during the 10-man Razorscale fight. This was never the case in retail, and is therefore causing groups who are well overgeared for Uld-10 to fall behind in progression.

**Comment by StheNoble** [comment]
as far as i know, it is common knowledge that many many encounters on dalaran-wow are buffed or pre-nerf states and you cant compare the health values and such to informations you find in wowhead/wowwiki.

some examples are larger health pools for Razor, Ignis, IC etc. in Ulduar or the missing Damage/Health buff for Players in ICC.

this is intentional and aimed to make the content challenging and not follow the Blizzard trend of making everything as easy as possible.

**Comment by Ekacarbez** [comment]
Understood. After some research, I learned I was wrong about the health pools. 

At it stands though, at no point was Razorscale spawning 3 drills during the release of Uld, the buffed, or nerfed state of the content. Even if the health is increased, that can be managed so long as the mechanics are functioning properly. This initial report was about more than 2 drills spawning, and that is still currently the case. 

I do enjoy the server, however if there are going to be buffs, then the mechanics should be working properly. I have opened a new report about the drills.
