### ISSUE TITLE
[Quest Chains Out of Order] - Dustwallow Marsh and the Black Shield quest chains

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#2656]
This is a bit completed so I'm just going to copy a post from wowhead comments and post the bugs in double brackets ->[[such as this]]<-. This is the main thread: http://www.wowhead.com/quest=1273/deprecated-questioning-reethe Also, all the link are readily available via the top comment in a much easier fashion than what I can post here without having to go through the trouble of hyperlinking.

The Shady Rest Inn quest chain can start either at the Inn itself, from the objects, or from Brackenwall Village (37.6,31.7), Dustwallow Marsh.
If the player chooses to start the quest chain in Brackenwall, Krog (36,31) will give the following quest:

```
Inspecting the Ruins
```

This quest completes at Inspector Tarem (29.6,47.5), located just outside of the inn, who will then use powder to help 'illuminate' the "clues." This basically causes purple arrows to appear, pointing at the individual quest objects strewn about the destroyed inn. Obtaining and completing this quest is not necessary, as the quest chains can be started directly from the objects regardless.

From the Shady Rest Inn (29.4,47.5), the quest branches into three paths, each starting when a different item gets looted.
The first quest for each chain will have you bring the three items to Krog in Brackenwall Village.

Loot the Black Shield (29.6,48.6):

```
The Black Shield
The Black Shield
The Black Shield
The Black Shield
```

Loot the Suspicious Hoofprints (29.7,47.7):

```
Suspicious Hoofprints
```

Loot the Theramore Guard Badge (29.8,48.2):

```
Lieutenant Paval Reethe
Questioning Reethe ← You are here!
```

After completing all three quest chains, Krog will offer a fifth The Black Shield quest, asking players to bring the Blackened Iron Shield to Mosarn (55.6,79.6) in Thunder Bluff.
->[[The fifth black shield quest becomes immediately available after the forth without requiring you to complete "Questioning Reeth" but the quest below 'return to krog' becomes available after completing the three chains above, making this quest chain completely disjointed for anyone uninformed]]<-

Mosarn will then volunteer new information regarding the "mystery" and starts the following short chain:

```
Return to Krog
More Than Coincidence and The Grimtotem Plot
```

When these three quests have been completed, Krog will direct you to Tabetha (46.0,57.1) for further progression and conclusion:

```
Seek Out Tabetha
Raze Direhorn Post!
Justice Dispensed
```

**Comment by Rushor** [comment]
DB/Quest: Dustwallow Marsh and the Black Shield quest chains

* closes https://github.com/dalaranwow/dalaran-wow/issues/2656
* commit: 0b4676f7973e1578b75c44ab7f786290bbd0b54b

updated the questchain.

after you complete 1273, quest 1276 will be available. after you completed 1276, quest 11204 will be available.

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
