### ISSUE TITLE
[Quest] Trial of the Naaru: Tenacity [10886]

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#2666]
http://www.wowhead.com/quest=10886/trial-of-the-naaru-tenacity
Your supposed to save Millhouse Manastorm by defeating harbinger Skyriss in heroic Arcatraz in Netherstorm.
http://www.wowhead.com/npc=20912/harbinger-skyriss
http://www.wowhead.com/npc=20977/millhouse-manastorm
You defeat Harbinger Skyriss, talk to Millhouse, no quest completion credit is received when it should be.

**Comment by Drovana** [comment]
bump

**Comment by Rushor** [comment]
going to fix this today

**Comment by Rushor** [comment]
I would like to note, that the whole bossfight between Millhouse Manastorm and Harbinger Skyriss is currently poorly scripted. I'm going to rewrite the whole dungeon in a few weeks. For now i will just add the killcredit upon death of Harbinger Skyriss. Thank you.

**Comment by Rushor** [comment]
Scripts/TempestKeep: Harbinger Skyriss - Reward killcredit for quest: Trial of the Naaru: Tenacity on heroic mode

* closes https://github.com/dalaranwow/dalaran-wow/issues/2666
* commit: e685f30d46c7d44f3a635c0f08c7bc3715aa08df

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by joki8** [comment]
I killed  harbinger Skyriss in heroic Arcatraz with the quest and no q complete.

**Comment by Braniacz** [comment]
Just tried to do the quest Trial of the Naaru: Tenacity and i noticed that quest is not working properly, the mob isnt moving anywhere or gets engaged into the fight. Also u dont get complete quest at the end.

**Comment by Rushor** [comment]
the whole encounter will be rewritten soon.

**Comment by kongfis1** [comment]
The encounter is still not fixed
