### ISSUE TITLE
[GO] Mid-air herbalism node (Stonetalon)

### ISSUE THREAD

**Issue by arvidinge** [dalaranwow/dalaran-wow#2703]
http://imgur.com/a/wIav4
An herblism node in mid-air in Windshear Crag, stonetalon mountains. Coordinates: 72,48

**Comment by Rushor** [comment]
DB/Gameobject: Update position for one Bruiseweed

* closes https://github.com/dalaranwow/dalaran-wow/issues/2703
* commit: b22f4ff8eeb544d23a193a048d7053c1fc8dad2e

Note: The gameobject is pooled, which means that there is no 100 % chance to see it every time. you can check the spawnpoint by typing (.go object 3440) and then (.gobj near)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
