### ISSUE TITLE
[Warlock][Pet] [Spell] SPELL LOCK

### ISSUE THREAD

**Issue by Watterx** [dalaranwow/dalaran-wow#2706]
Spell lock is bugged, it only silences for 3s but doesn't lock the tree for 6s if you interrupt a cast, which is game breaking for lock in arenas.

**Comment by warcraftgeekygamer** [comment]
http://wotlk.openwow.com/spell=19244

**Comment by Lothloryen** [comment]
Hello there,

Thank you very much, this issue has been corrected already, it shall be applied after the next scheduled maintenance.

**Comment by zyzolol** [comment]
Confirmed, all abilities that react in a similar manner react this way. If X is cast on the oLoS target, and if the target is within the area of effect it should produce the same result - as if the target was hit by X ability in LoS.

Source: Every Warlock and Priest PvP movie made since season 2 LOL.
