### ISSUE TITLE
Improved Faerie Fire / Misery

### ISSUE THREAD

**Issue by Vidmantasaf** [dalaranwow/dalaran-wow#2718]
Stacks. 
Ive checked it spamming wrath on 82lvl target with both misery and imp ff up and in 180 tries never missed (0.97^180=0.004 =99.6% accuracy of testing)

**Comment by shaunb19** [comment]
known issue with imp FF and misery stacking.

**Comment by Vidmantasaf** [comment]
known or not its huge issue, it makes a lot of encounters easier since fewer  taunts will fail people won't need hit gear. 
if you can't fix it to work blizzlike can you atleast nerf it ? like make one of them working or make spriest   misery same as improved faerie fire ( and make it not stack) spriests will gain 3% crit buff, but it will be more balanced for whole raid, also it doesn't matter for pvp since a lot of pvp classes like destruction warlocks are bugged in good way anyways.

**Comment by Vaxsysl** [comment]
.... Sorry @Vidmantasaf  but just how THIS make encounters easier if taunts do not miss? Glyph and hit rating are two necessary points a tank must have on taunt-heavy encounters, if not hunter/rogue team ready for threat transfer, and this debuff stacking is not helping that un-tauntability at all since it would still need 3% extra if one had 8% spell hit (~7% melee hit). This bug is not helping tanks' taunt in any way.

**Comment by Vidmantasaf** [comment]
8% taunt glyph is just 8% from 17% required to taunt hte boss, if guy has 0-6% hit he will benefit from this bug

**Comment by Vidmantasaf** [comment]
come on developers, you did that to retribution aura/arcane empowerment just do same to this (now you can not use retribution aura in raid if you got arcane mage)

**Comment by Golganeth** [comment]
#1510
