### ISSUE TITLE
[Item] Formula: Runed Adamantite Rod (25848)

### ISSUE THREAD

**Issue by wilczakadam** [dalaranwow/dalaran-wow#2721]
This recipe has incredibly long respawn time at the vendors. I've read on the forums that ~year ago it was reduced to 30 mins, but now it seems it's back to normal wich is super long (24h I think). It is notoriously camped and since this item is necessary to progress Enchanting it makes it rally unfair for enchanters.

**Comment by Nattaszz** [comment]
Ive been camping for a week now, no luck.. and ive seen atleast 10 different people doing the same without luck.. enchanting is hard enough and this is not funny anymore. Ive seen a new forum that opened a month ago, but im not able to respond to it because of another bug (the site doesn't see my charcters) PLS FIX IT ASAP! i want to play the game and not camp all day, every day.. :(

**Comment by Khronos-** [comment]
It's there.

**Comment by belegija** [comment]
So go there after the restart? Or which black magic should one enchanter use to get the simple recipe?

**Comment by Reechter** [comment]
Respawn timer still not fixed. Been camping this for a long time and it's nowhere to be seen.

Would love to have a fix for this soon, it's preventing a lot of people from leveling Enchanting past 350.

**Comment by budthechud** [comment]
Can we get a clarification on the actual CD of the Formula for each realm (if there is a difference per realm)
