### ISSUE TITLE
[Item] Gnomish Shrink Ray ---> Engeneier Gadget  [10716]

### ISSUE THREAD

**Issue by aoses** [dalaranwow/dalaran-wow#2727]
Gnomish Shrink Ray does not have any effect--->: http://www.wowhead.com/item=10716

**Comment by mniamrodzynka** [comment]
Issue is still not solved.

**Comment by Rushor** [comment]
Scripts/Spells: Implement Gnomish Shrink Ray Effect

* closes https://github.com/dalaranwow/dalaran-wow/issues/2727
* you will either cast http://wotlk.openwow.com/spell=13004 on youself, or http://wotlk.openwow.com/spell=13003 will be casted on the target
* commit: b7337c2c1ec39e10b0cbfa98eb19cef03e3b50b4

![GitHub Logo](http://i.imgur.com/Hb0HZmH.jpg)
![GitHub Logo](http://i.imgur.com/SD9hrqX.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
