### ISSUE TITLE
[quest] Parts for the Job

### ISSUE THREAD

**Issue by Kaporalhart** [dalaranwow/dalaran-wow#2730]
The quest Parts for the job http://www.wowhead.com/quest=11309/parts-for-the-job given by "Hacksaw" Jenny http://www.wowhead.com/npc=24252/hacksaw-jenny Requires 6 Shoveltusk ligaments http://www.wowhead.com/item=33611/shoveltusk-ligament but the drop rate is way too low. I have not counted but i'm at only 4 out of 6 and i have cleared 6 packs of them, collecting 25 Shoveltusk flank and 10 chilled meat.
The quest mobs that drop them are Shoveltusk http://www.wowhead.com/npc=23690 ; Shoveltusk calf http://www.wowhead.com/npc=24791 ; Shoveltusk Stag http://www.wowhead.com/npc=23691.

Issue : Drop rate way too low
How it should work : Drop rate should be around 50 %

**Comment by Kaporalhart** [comment]
The good side is that i got half my level of experience, earned 44 gold 98 silver 7 copper selling trash, and looted 38 shoveltusk flanks and 16 chilled meat.

**Comment by Zoombala** [comment]
Maybe you're just "unlucky"

**Comment by Kaporalhart** [comment]
I had 38 shoveltusk flanks, those have a 52 % drop rate, so i must have killed 80 of them.
If i had had to kill 20 of them it would have been unlucky. you could even say 30 would still have been insanely unlucky. 80 You know this is clearly a bug.

**Comment by arvidinge** [comment]
I have now killed 30 with not a sinlge Ligament drop. I have the quest, not full inventory.

**Comment by arvidinge** [comment]
update: 6/6 in 80 kills

**Comment by npmusicftw** [comment]
Took me 76 kills to get 4/6 to drop. 

Supposed to have a roughly 60% drop rate, according to the comments on WoWhead. They actual drop rate displayed is slightly biased because of the people who have killed the Shoveltusk without having the quest. 

http://www.wowhead.com/quest=11309/parts-for-the-job#comments 

I think the drop rate for these has been mistakenly set to these drop rates below:

http://www.wowhead.com/item=33611/shoveltusk-ligament

**Comment by rinleezwins** [comment]
Nothing changed here, if it wasn't for the fact that I have skinning I would probably give up on the quest.
