### ISSUE TITLE
[Dialog text missing] "Jangdor Swiftstrider", Camp Mojache, Feralas

### ISSUE THREAD

**Issue by arvidinge** [dalaranwow/dalaran-wow#2731]
http://i.imgur.com/Kr5qbyq.jpg

**Comment by Rushor** [comment]
DB/Creature: Jangdor Swiftstrider - Remove wrong pagetext

* closes https://github.com/dalaranwow/dalaran-wow/issues/2731
* commit: 119f02572ca1d1dc024daf14929971f26bd9dd51

The creature will now say it's normal "Greetings, xY"

![GitHub Logo](http://i.imgur.com/X8kW43w.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
More Infos in https://github.com/dalaranwow/dalaran-wow/issues/4904
