### ISSUE TITLE
[NPC] Mana Wyrm [15274]

### ISSUE THREAD

**Issue by leolomi** [dalaranwow/dalaran-wow#2734]
Does not cast http://www.wowhead.com/spell=25602/faerie-fire

**Comment by Rushor** [comment]
DB/Creature: Mana Wyrm - Add ability 'Faerie Fire'

* closes https://github.com/dalaranwow/dalaran-wow/issues/2734
* commit: b3802b34ed6661f4972484819222ee348d8187f1

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
