### ISSUE TITLE
[NPC] Ghostlands Area missing most NPCs

### ISSUE THREAD

**Issue by Varen** [dalaranwow/dalaran-wow#2736]
![78](https://cloud.githubusercontent.com/assets/3650235/8898077/0e026028-341f-11e5-8289-56e52cdd7270.jpg)

The marked area is missing most mobs, making quest completion there rather annoyingly difficult.

**Comment by Khronos-** [comment]
Which quest and which mobs?

I quested in the Ghostlands at the beginning of my toon and completed most of them without any issue.

**Comment by Golganeth** [comment]
#795

**Comment by Rushor** [comment]
DB/Creature: Ghostclaw Lynx & Ghostclaw Ravager & Greater Spindleweb Spawns

* closes https://github.com/dalaranwow/dalaran-wow/issues/2736
* added 90 spawns of Ghostclaw Lynx & Ghostclaw Ravager & Greater Spindleweb 
* commit: b7c92a96f3088f61b1ce3ae33b7051b8d7374876

![GitHub Logo](http://i.imgur.com/sRSFN7u.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on ptr.
