### ISSUE TITLE
[Quest][Outland] Bomb Them Again!\Blade's Edge Bomberman

### ISSUE THREAD

**Issue by Klala** [dalaranwow/dalaran-wow#2739]
While both of these are doable, trying to do both of them was EXTREMELY hard.
Almost in every attempt to throw the Skyguard Bombs I get interrupted with the "Interrupted" error message.
Of course, after so many attempts I got a hint of what's going on. It seems that every time the Legion Flak Cannons try shoot me down I get interrupted. About 80%+ of the times when I started to cast the bombs before they targeted me or started shooting at me, I got interrupted once or even twice!
So my guess is that you get interrupted by getting targeted by the cannons or getting shot by the cannons (not hit and taken down) or worse still, BOTH which would explain why I get interrupted twice sometimes.

In the end though, I managed to make it, so I would call that a minor bug since it's only an achievement through quest which, again, both are working.

Video how it should be working: https://www.youtube.com/watch?v=M8TLbjYWFaw

**Comment by Braniacz** [comment]
Bump

**Comment by Drovana** [comment]
bump

**Comment by DrFuler** [comment]
Bump

**Comment by Rushor** [comment]
http://wotlk.openwow.com/quest=11023

**Comment by Rushor** [comment]
DB/Quest: Bomb Them Again! - Add improved despawn- and spellhitevent for Bombing Run Target Bunny

* Bombing Run Target Bunny will now give the questcredit on spellhit by the bomb. It will then only be usable again after 30 seconds
* Legion Fel Cannon MKII will no longer chase the player. It will cast 'Fel Cannon Blast' on victims instead.
* closes https://github.com/dalaranwow/dalaran-wow/issues/2739
* commit: c31f537fb657052e1c1db2872066f36d0746cccc

![GitHub Logo]()

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
