### ISSUE TITLE
Casters and Range mobs buggded

### ISSUE THREAD

**Issue by Champions2012** [dalaranwow/dalaran-wow#2740]
Hello there, i joined Dalaran wow recently and i like it. While i was leveling i noticed that caster mobs and range mobs are acting really wierd. They would walk around when u attack them like u didnt but still they would shoot you. They wont go after you so u can't drag him away like other melee mobs. If u back away they will stand in place untill u get in close range. This makes it really hard to level up because sometimes i pull 5 mobs on me because that mob won't go after you like it should. Here is the pic of it. He is walking around and throwing stuff on me.

![wowscrnshot_072915_000907](https://cloud.githubusercontent.com/assets/13512234/8945370/11f43350-3587-11e5-8c1b-5a76ff8511ca.jpg)
![wowscrnshot_072915_000932](https://cloud.githubusercontent.com/assets/13512234/8945371/11f47702-3587-11e5-807c-47d5dda751a0.jpg)

Hope you fix this soon.

**Comment by Vission** [comment]
All the caster mobs behave like this. If the caster npc gets interrupted, he should move after his target. If the target of the caster npc get out of it's sight, caster npc should move after the target too. 
That does not happen right now.  It breaks the feeling of a good server, since ppl will see this even from the lowest levels.   
Thanks in advance for the fix.

**Comment by Champions2012** [comment]
Yeah, since i started leveling i have seen this and it is so annoying. It ruins the server reputation.

**Comment by Golganeth** [comment]
#1793
