### ISSUE TITLE
[NPC] Bleeding Hollow Refugee

### ISSUE THREAD

**Issue by arvidinge** [dalaranwow/dalaran-wow#2752]
In Garadar, Nagrand. They speak [common] in chat although they are orcs

**Comment by Rushor** [comment]
http://wotlk.openwow.com/npc=18292

**Comment by Rushor** [comment]
DB/Creature: Bleeding Hollow Refugee - Change language to Orcish

* closes https://github.com/dalaranwow/dalaran-wow/issues/2752
* commit: 87b44cb9b3f6c4335dcb1ef9626fd16408007024

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Also missing combat spell.
``` sql
-- Bleeding Hollow Refugee SAI
SET @ENTRY := 18292;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,1,0,100,0,30000,30000,60000,180000,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Bleeding Hollow Refugee - Out of Combat - Say Line 0"),
(@ENTRY,0,1,0,13,0,100,0,6000,8000,0,0,11,2676,0,0,0,0,0,2,0,0,0,0,0,0,0,"Bleeding Hollow Refugee - On Victim Casting - Cast 'Pulverize'");
```

**Comment by Rushor** [comment]
DB/Creature: Bleeding Hollow Refugee - Add combatability 'Pulverize'

* updates: https://github.com/dalaranwow/dalaran-wow/issues/2752
* commit: ed0554d644259e5705d9e04182b0d87426ca04b1

added

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Aridam** [comment]
Still speaking Common instead of Orcish.
