### ISSUE TITLE
[Quest] Stop the Ascension!

### ISSUE THREAD

**Issue by arvidinge** [dalaranwow/dalaran-wow#2774]
The item that starts this quest either isn't dropping (Vrykul Scroll of Ascension) or it has an insanely low drop chance, I've been farming the vrykuls at Skorn in Howling Fjord for over an hour now and it hasn't dropped yet. I'm an affliction warlock too so I can aggro and kill 6-7 mobs at a time, an hour would be well over 100 mobs at least.

**Comment by Tarpor** [comment]
topcomment of wowhead:

'I've been killing around hundred mobs during night and morning. No drop, made a ticket. I wonder if this quest is still active because such items always have a high drop rate. Especially this one SHOULD have a high drop rate because there isn't a sick reward related to it.

EDIT: The game master couldn't help and said everything was working as intended. So I went further on questing, and I came along the Skorn-quest serie. The third mob I killed whilst I was on those quests, dropped this item. Probably it is necessary to have (or have done) the Skorn-quests.'

Have you done the quests?

**Comment by arvidinge** [comment]
Yes, all of them, i've farmed vrykuls with the quest in my log and after completion, didn't get the scroll. not a big deal, just some bonus xp i missed out on, not essential to any quest chain or so.

**Comment by Naidira** [comment]
The scroll does drop, at the very least.  The quest works as normal when acquired and executed.  So only the drop rate is questionable, but WoWHead comments do point toward it being a very low drop.

**Comment by swiftdeath** [comment]
I got it while doing the quest granted by http://www.wowhead.com/item=33311/westguard-command-insignia.

So it might be a drop rate issue, but it works for sure.

**Comment by rinleezwins** [comment]
As soon as I turned in the other 3 quests talking to the NPC that fights with you, the first mob dropped the scroll.
