### ISSUE TITLE
[Quest] [Grizzly Hills] Chill Out, Mon

### ISSUE THREAD

**Issue by arvidinge** [dalaranwow/dalaran-wow#2783]
The chest containing "Snow of Eternal Slumber" should only be seen when in the "realm of the dead" phase. currently it is the opposite, only visible while alive and not while dead. Not a big issue, just caused some confusion when using a leveling guide telling me to loot the chest, and then ask the troll to resurrect me.

**Comment by Archcry** [comment]
I can confirm this.

**Comment by DalaranLantri** [comment]
Chest is only visible now while under the effects of  http://www.wowhead.com/spell=61611/on-the-other-side. (This debuff seems to be removed at a certain point in the ruins on the prequest http://www.wowhead.com/quest=12121/see-you-on-the-other-side, making it impossible to get to the questgiver currently on the PTR. As mentioned in #643 by @Daveonx

**Comment by Chewy2002** [comment]
You idiots were wrong, the change was made in a later patch for you to be able to loot in both the spirit realm AND while alive. Th quest in it's original form even says in the quest log "Talk to me to return to life THEN***** loot the chest  near me. Because of you illiterate morons I cannot complete the quest.

**Comment by Chewy2002** [comment]
![wowscrnshot_081616_133409](https://cloud.githubusercontent.com/assets/20822839/17715069/67186e14-63b7-11e6-8360-4bdac9ae6d97.jpg)
