### ISSUE TITLE
[NPC] Anachronos - Signet Ring of the Bronze Dragonflight

### ISSUE THREAD

**Issue by Tarpor** [dalaranwow/dalaran-wow#2800]
### How it is:

When you delete the ring, it is gone forever because **Anachronos**_15192_ does not give the option to re-obtain a ring.
### How it should work:

 You can get a new ring by talking to **Anachronos**_15192_

**Comment by Crispybuilt** [comment]
Confirmed.
In case you lose/delete your ring, you can directly ask Anachronos to give you a new one through **gossip/dialog* option. 
I also found wowhead comment: *you must have the ring on you to upgrade it. if you lose it you can take it again from anachronos.*
http://www.wowhead.com/quest=8752/the-path-of-the-conqueror#comments

**Comment by Rushor** [comment]
DB/Creature: Anachronos - Signet Ring of the Bronze Dragonflight - Enable gossips for lost rings

* closes https://github.com/dalaranwow/dalaran-wow/issues/2800
* commit: e64fc4c9d944e96fc22ee8c7e6eb24175125069f

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
