### ISSUE TITLE
[Oculus] Ley-Guardian Eregos - Despawn

### ISSUE THREAD

**Issue by wilczakadam** [dalaranwow/dalaran-wow#2801]
[Heroic] Sometimes after leaving Planar Shift phase, Eregos simply despawns. He won't respawn meaning you won't complete instance nor get any loot.

**Comment by M0dinstaller** [comment]
I'll add that if you are a night elf, get dismounted (your mount gets killed), survive the fall and shadowmeld to exit combat and get on a new mount, upon killing the boss, he'll disappear and you won't get any loot or credit for killing him and won't be able to finish the dungeon until a reset.

**Comment by Golganeth** [comment]
Confirmed.

**Comment by Rushor** [comment]
The real reason for this:

If you summon any dragon during the fight against Eregos, he will simply DESPAWN. This should be removed.

Scripts/Oculus: Remove Despawnaction of Eregos after any of the helpful dragons was summoned

* closes https://github.com/dalaranwow/dalaran-wow/issues/2801 
* commit: c2d268a27e41c6d5fff1c4249cc10935da0aa081

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by arestavo** [comment]
This is still an issue as of May 6th, 2019.

**Comment by Lothloryen** [comment]
Updated.
