### ISSUE TITLE
[NPC] The riding trainer from blood elf

### ISSUE THREAD

**Issue by Artix333** [dalaranwow/dalaran-wow#2819]
The riding trainer from blood elf appears with an repair icon, not a learning one. 
I see an anvil not a book.

**Comment by Tarpor** [comment]
Confirmed

**Comment by Zoombala** [comment]
Took me minutes to find that one and I was right next to him --"

**Comment by Rushor** [comment]
DB/Creature: Perascamin - remove repairicon

* closes https://github.com/dalaranwow/dalaran-wow/issues/2819
* commit: 5f8a58e9d84e7a1f6775b58fe55a64caffe0bccb

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
