### ISSUE TITLE
Quest items that need to be picked from the terrain.

### ISSUE THREAD

**Issue by Vengyr** [dalaranwow/dalaran-wow#2827]
These have ridiculously long respawn time, making group questing extremely frustrating - only one out of the group can actually complete the quest unless you wait for it's respawn for a quite long time.

Example: Tomber's Supplies, quest has a single item that has to be picked up, and that one has a very long respawn rate, definitely above 10 minutes (time we've waited for). I believe it is a bug since other blizzlike server (as well as retail) didn't have such an issue as I remember it.

**Comment by saduss** [comment]
Confirmed, quest items such as Conpendium of the fallen and Beginnings of the Undead Threat have long respawn time. It would be helpful if all quest items have shorter respawn time making group questing less frustrating.

**Comment by Ergates82** [comment]
Experienced this myself with the quest 'Kill them with Sleep Deprivation' in Searing Gorge. Pillows take a solid 15 minutes to respawn. Time on retail used to be around one minute.

**Comment by robinsch** [comment]
@Vengyr @saduss @Ergates82 Please link quest IDs, item IDs and related stuff.

**Comment by Rushor** [comment]
well even on retail those kind of quests were very hard

http://us.battle.net/forums/en/wow/topic/1252365392

Dec 5, 2010
Blizz, please fix quest item respawn times. While leveling alts with my friend, we constantly have to wait for 5+ mins for quest items that need to be picked up from the ground to respawn. I don't understand why you make these items despawn to begin with, since it only slows down questing and wastes our time sitting on a boat killing 4+ waves of enemy respawns waiting for a stupid item.

Like "In with a Bang", Horde Swamp of Sorrows, you have to pick up 3 items from a boat. The enemies have respawned here 5 times, and the items take 5+ minutes to respawn. It's very annoying, and this isnt the only quest that does it, but other quests the items dont even despawn!

This behaviour is blizzlike.
