### ISSUE TITLE
Darkmoon Faire Schedule

### ISSUE THREAD

**Issue by Tarpor** [dalaranwow/dalaran-wow#2849]
'The Darkmoon Faire visits once a month, starting at 00:01 on the Sunday before the 1st Monday of each month.' Taken from http://wowwiki.wikia.com/wiki/Darkmoon_Faire_(old) . 

The first Monday of the month this month is the 7th of September, meaning the Darkmoon Faire should arrive at 00:01 on the 6th of September. However as seen on http://i.imgur.com/5FdVI0a.jpg , it's not correct.

**Comment by ImprezaWoW** [comment]
It currently starts at 1:01 PM ST, just for reference.

**Comment by roblockster** [comment]
It is currently Tuesday, 2 days after the Sunday before the first Monday of the month. DMF has not spawned in any of the locations. 

Perhaps this works on PTR as mentioned in #4378 but the timer apparently does not work correctly on live. I'm not sure why staff couldn't just go on live and see that DMF wasn't up when people posted timely reports on this in the past, but I suggest they do so now.

**Comment by roblockster** [comment]
I just checked the week before proper DMF spawn time and it wasn't up then either.

**Comment by Rushor** [comment]
DB/Event: Update monthly timer for all Darkmoon Faire events (Terokkar Forest, Elwynn Forest, Mulgore)

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4378
* commit: 1abb4a5dc8cecb29702a45d069b19b75b4953929

The issue has been fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
**Only once the issue was marked with "Fixed - On Live Server", you can find the fix on your game server.**
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Eava-1** [comment]
Looking for information on the spawn of Darkmoon Faire on this server and finding it hard to gain any. Is this issue still awaiting a fix? I've been monitoring the DMF on it's supposed spawn dates and in between and never see it up? The fixed waiting for PTR update label has also been removed. Does that mean this issue is no longer being worked on?
