### ISSUE TITLE
[Item] Battered Junkboxes (Pick Pocket) are usually empty

### ISSUE THREAD

**Issue by sokkye** [dalaranwow/dalaran-wow#2879]
Battered Junkboxes that are pickpocketed from low level mobs seem to usually be empty.  Occasionally will have a potion or something similar.  Doesn't seem to contain poisons like it was on retail.

**Comment by nyrpha** [comment]
they often contain poison ingredients, and only some are empty. your sample size may be very small.

**Comment by sokkye** [comment]
I pickpocketed about 15 of these over the last few days.  Half of them contained things like healing potions, pocketwatches, etc...  The other half were completely empty.  No poisons at all.

**Comment by Rushor** [comment]
need to be fixed with a refernce loot template

**Comment by Rushor** [comment]
DB/Item: Battered Junkbox - now always contains between 1 and 3 items

* closes https://github.com/dalaranwow/dalaran-wow/issues/2879
* commit: 62b2409225f045cda119fe66643abc1ad6dc379a

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
