### ISSUE TITLE
Quest: It's a Fel Reaver, But with Heart

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#288]
http://wotlk.openwow.com/quest=10309

**Issue 1:** Scrapped Fel Reaver isn't visible, and the only way to target him is using /target command.
**Issue 2:** After using the provided item on the "invisible" Fel Reaver, he starts to attack you (he should not attack players).
**Issue 3:** The entire event doesn't work plus you can't loot the quest item after killing the NPC.
- *Scrapped Fel Reaver* - http://wotlk.openwow.com/npc=20243

--------------------

**How it should work::** Upon using the item "Fel Zapper" on the Scrapped Fel Reaver (which is provided by the npc), it becomes attackable and an event should start: waves of one Zaxxis Ambusher should keep spawning non-stop until you kill the Scrapped Fel Reaver.
- *Zaxxis Ambusher* - http://wotlk.openwow.com/npc=20287
- *Fel Zapper* - http://wotlk.openwow.com/item=29447

----------------------

**Video of how it should look like:** http://www.youtube.com/watch?v=AHou5obC-DU

**Comment by belegija** [comment]
still broken. after killing the invisible scrapped fel reaver, you are not able to loot it

**Comment by Penguindrum** [comment]
The mentioned problem still exists

**Comment by walkerboh1983** [comment]
solution! /tar scrapped fel reaver at (26, 78) kill scrapped fel reaver, again /tar scrapped fel reaver, then use the "interact" keybind.  you will loot the heart!

**Comment by DrFuler** [comment]
16/12/2015: Can be done.

walkerboh1983's solution is nasty, but it works.

**Comment by MrAndersonX** [comment]
Yeah, still bugged, but it can work with /target and binding the "interact" key :P.

**Comment by jonanone** [comment]
These issues have been fixed. The fix will be applied to the live realm soon.

**Comment by speaker** [comment]
Still broken as of July 27, 2017

**Comment by Rushor** [comment]
DB/Quests/Netherstorm: It's a Fel Reaver, But with Heart.

* Scrapped Fel Reaver is now visible.
* Once the item is used on the Fel Reaver it will become killable.
* Zaxxis Ambushers are now summoned while Fel Reaver is killable.

* Closes https://github.com/dalaranwow/dalaran-wow/issues/288

The issue has been fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
**Only once the issue was marked with "Fixed - On Live Server", you can find the fix on your game server.**
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
