### ISSUE TITLE
Quest: Kill 'em Sleep Deprivation ID:7702

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#2883]
There are a couple issues with this quest. Firstly, there is a missing event script on a timer where Sleepy Dark Iron Workers should spawn, and then a boss. Secondly, there are too few pillows and the respawn timer seems slightly too long (perhaps by about 60 seconds or so).

There is supposed to be a gang of about 10 Sleepy Dark Iron Workers (#14635) spawn a minute or so after you've stolen the first pillow. A couple minutes later, another wave should spawn. A couple minutes after that, Chambermaid Pillaclencher (#14636) should spawn. She has a knock-back abilities.

“Sleepy Dark Iron Work yells: Our pillas! Someone has stolen our pillas!”

"Chambermaid Pillaclencher yells: Thieves! Scallywags! Rapscallions! Come face me gigantic pillas!"

**Comment by jonanone** [comment]
Event has been added:
- Once one pillow is looted the event will start.
- There are 2 waves of 10 Sleepy Dark Iron Workers and finally the boss Chambermaid Pillaclencher.
- Chambermaid Pillaclencher will drop Chambermaid Pillaclencher's Pillow that begins a quest.
- Once the event is started another one can't be started until the boss is killed or 5 mins has passed since the beginning.

These updates will be added to the live realm soon.
