### ISSUE TITLE
[NPC] Nameless Prophet ID:13718 spawn points

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#2890]
He should respawn almost instantly in one of four different places.

“First spawn is right under the bridge as you first enter Maraudon (still in the world map, not the actual instance).
Second location is just a few yards further on a small cliff on the right.
Third location is in front of a statue of a centaur a bit further down.
After going down the set of stairs, you'll have the three way intersection for purple, orange and staff entrances. At this intersection is a makeshift tent, which is where the fourth location was.” - Comments of WoWHead.

http://www.wowhead.com/npc=13718/the-nameless-prophet#comments

**Comment by Rushor** [comment]
DB/Creature: Nameless Prophet - Add pooling

* he will respawn after 6 seconds
* 2a51f5d3905dd07c62377974d43fa91dc823325c

spawnplaces:

![GitHub Logo](http://i.imgur.com/g131RHV.png)
![GitHub Logo](http://i.imgur.com/2YYpQMf.jpg)
![GitHub Logo](http://i.imgur.com/1Hqgc3a.png)
![GitHub Logo](http://i.imgur.com/CUjjP3e.png)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
