### ISSUE TITLE
[Spell] Thrash - Cooldown

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#2891]
This spell is missing cooldown, NPCs with this spell can cast instantly with every hit gaining 2 more extra hits which also can cast Thrash stacking it up to even 10+ hits per 1 hit.

**Comment by Rushor** [comment]
that spell http://wotlk.openwow.com/spell=8876 should be used instead

**Comment by Rushor** [comment]
DB/Creature: Thrash spell replace in SAI

* closes https://github.com/dalaranwow/dalaran-wow/issues/2891
* commit: 3c8da35dad8326c11e694e242537eb11fc3bdfd8

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
fixed together with https://github.com/dalaranwow/dalaran-wow/issues/5357
