### ISSUE TITLE
[Glyph (Warlock)] Glyph of Felguard doesnt work.

### ISSUE THREAD

**Issue by Vojtus** [dalaranwow/dalaran-wow#2909]
Hello,

It should give him 20% of AP but it didn't do anything.

Here is an image with the Glyph inactive:

![wowscrnshot_092315_025208](https://cloud.githubusercontent.com/assets/7840569/10035826/c60f8a22-619e-11e5-8678-50c0395173c9.jpg)

And here is one with the Glyph active (After resummoning Felguard)
![wowscrnshot_092315_025247](https://cloud.githubusercontent.com/assets/7840569/10035833/eee54932-619e-11e5-9c2a-1bbf7b24ee95.jpg)

You can see clearly it hasnt changed anything.

**Comment by Milton3450** [comment]
I think the problem is that no pet except imp scales with stats. So I've heard.

**Comment by Lothloryen** [comment]
Hello there,

Thank you very much. After the release of TOC, I will implement a patch where most of the issues related to the pet scaling will be corrected.

**Comment by Milton3450** [comment]
GJ Loth we know you are busy with ToC.

**Comment by Vojtus** [comment]
Wow, Great :-) way better response than I expected

**Comment by Rushor** [comment]
Game/Unit: Increase bonus-ap for Felguard if owner has Glyph of Felguard

* closes https://github.com/dalaranwow/dalaran-wow/issues/2909
* commit: 36c5efdacd8343acfed16db3e640b0a9edbaacb2

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Lothloryen** [comment]
@TeridanDW Can you please take a look to this if this is still an issue on PTR after the recent pet changes? Thank you.

**Comment by TeridanDW** [comment]
Works as intended on PTR.
Note: The warlock must dismiss the Felguard and resummon it **(not just resummon it)** in order for the glyph to "activate".

![wowscrnshot_102017_190946](https://user-images.githubusercontent.com/6797611/31831095-eb875b18-b5ca-11e7-9221-a6409da0522c.jpg)
![wowscrnshot_102017_191135](https://user-images.githubusercontent.com/6797611/31831098-ed49a604-b5ca-11e7-8477-d2eb5eed9d8a.jpg)

**Comment by Lothloryen** [comment]
Thank you.
