### ISSUE TITLE
[NPC] Chillwind Chimaeras Drop Grey Quality Item When Skinned.

### ISSUE THREAD

**Issue by npmusicftw** [dalaranwow/dalaran-wow#2929]
Chillwind Chimaeras (#7448), when skinned, dropped Chimaera Leather (#15423) , a grey quality item of which one can do nothing with but sell it.

Chillwind Chimaeras stopped dropping Chimaera leather in patch 3.1. They became a grey quality item, and any pattern that used it then was changed to a single Living Essence. They now have very high 89% chance to drop Rugged Leather when skinned. 

http://www.wowhead.com/item=15423/chimera-leather
http://www.wowhead.com/npc=7448/chillwind-chimaera#skinning

**Comment by Rushor** [comment]
DB/Creature: Chillwind Chimaeras - Update skinning loot 

* remove Chimaera Leather and replace it with Thick Hide with a dropchance of 3 percent
* increace change of Rugged Leather to 89 percent
* closes https://github.com/dalaranwow/dalaran-wow/issues/2929
* commit: 15710aebd5b65dce33ee2a66bcdc678424340f32

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
