### ISSUE TITLE
[Quest] The Madness Within

### ISSUE THREAD

**Issue by MrAndersonX** [dalaranwow/dalaran-wow#2933]
Hi,

Tried to do this quest yesterday. The problem is, even after killing every elementals guarding the 5 pylons, the force field for  Immol'thar doesn't come down. Even if he is pulled out of the force field using a pet, Prince Tortheldrin cannot be killed due to the fact that he is friendly, so the quest cannot be completed.

**Comment by DrFuler** [comment]
[06/05/2016] - Also having this problem. The quest is currently not completable.

**Comment by Golganeth** [comment]
Prince Tortheldrin and Immol'thar are both now killable in order to be able to complete the quest. Hotfix applied to the live realm soon.

Conditions for Immol'thar to become attackable are missing (elementals+pylons)
Conditions for Prince to become attackable are missing (it should only be attackable if Immol'thar is dead)

Currently they are both attackable right away, so this needs to be improved in the future.

**Comment by Rushor** [comment]
Scripts/Dire Maul: Prince Tortheldrin - should only be attackable after Immolthar was killed

* also remove passive state from Prince Tortheldrin 
* closes https://github.com/dalaranwow/dalaran-wow/issues/2933
* the fix depends on https://github.com/dalaranwow/dalaran-wow/issues/2503 (this must be applied on live first)
* commit: 2e1ad9d20dc485df3e9defa636403bb108723493

![GitHub Logo](http://i.imgur.com/nfNPdjN.jpg)
![GitHub Logo](http://i.imgur.com/EP1R59T.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
the fix depends on #2503 (this must be applied on live first)
