### ISSUE TITLE
Quest: any escort quest

### ISSUE THREAD

**Issue by blahami2** [dalaranwow/dalaran-wow#2947]
Escort quests do not work in group. It prompts other members of the group, but they do not receive the quest nor reward.

**Comment by nark7** [comment]
Can confirm this.

If you are in a group and one accepts a escort quest, the group members correctly get the popup, if they want to accept it. Clicking on "Yes" (=accepting it) has no effect though, which makes such quests a real pain, due to doing it twice (or more often, based on the number of people in the group).

**Comment by Golganeth** [comment]
Merge #3337
