### ISSUE TITLE
Quest Exploit and how to fix it

### ISSUE THREAD

**Issue by tripleslash** [dalaranwow/dalaran-wow#2951]
Hello,

as you are aware there is currently a quest exploit working on your server (Nobles Decks dupe for instance).

This is how to fix it properly:

in WorldSession::HandleQuestgiverAcceptQuestOpcode find the following line:

```c++
((object != _player && !playerQuestObject->CanShareQuest(questId))))
```

and change it to:

```c++
((!playerQuestObject->CanShareQuest(questId))))
```

Done.

Sidenote: This will not break any quests in WotLK as it seems this check was added as a result of spell-triggered quests which are not used in 3.3.5a.

**Comment by Lothloryen** [comment]
Hello there,

We deployed a correction for this issue yesterday -  it has not been working since then. However, I would like to thank you for your contribution - it is really appreciated.

If you do not mind, could you please contact me via e-mail on dalaran.community@gmail.com?

Thank you very much.

**Comment by tripleslash** [comment]
It is still working on Algalon as of right now :(
