### ISSUE TITLE
[Paladin] - Exorcism + Hand of Reckoning

### ISSUE THREAD

**Issue by Klala** [dalaranwow/dalaran-wow#2952]
Something about either Exorcism or Hand of Reckoning is off, let me explain.
As I played retail wotlk, I leveled and played a lot as a paladin tank. I remember clearly that Exorcism + Hand of Reckoning combo should work as in, you cast Exorcism and immediately when the cast is done you use Hand of Reckoning, meaning the target gets the damage from Exorcism AND Hand of Reckoning both. But in here it's impossible. It's possible on target dummies for obvious reasons but not on a mob.

I'm looking for a video footage to prove my point but for now I have this: http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-exploits/254160-paladin-exorcism-hor.html

"HoR only deals damage if the mob isn't attacking you, and exorcism has a 1.5s cast time; however, I found that if you cast Exorcism and immidiatly hit HoR; HoR will also deal damage!"

Note that it was written in 2009 and some people are stating that they are also using this method.

**Comment by Tarpor** [comment]
Are you serious? It's literaly listed under 'WORLD OF WARCRAFT EXPLOITS', it's even in the link you give and the guy that made the post even said it's an exploit. 

'Reason this is an exploit is that Exorcism isn't a missile spell so when cast it should immidiatly hurt and aggro the mob, causing your HoR to do no damage; but for some reason it does. ' 

Do you even read what you link?

**Comment by Klala** [comment]
First of all relax, I am only reporting things in hope to make a more retail server for all of us.

Second of all, that thread being under a forum called "exploits" doesn't make it an exploit. That's how the game worked in retail and people used it for their benefit.
That's how it was in retail and this is how it should be in a server that seeks to bring content as blizzlike as possible.

**Comment by Klala** [comment]
http://fahrenheit-llane.org/smf/index.php?topic=16184.0

"Pulling Tools:  Being able to get some burst threat on a pull is very important.  Paladins have up to 3 abilities they can use, with some restrictions.

Exorcism:  This ability has a cast time, so it can really only be used when you aren't getting attacked.  On a pull, if you are available to, start by casting this.  You can mash Hand of Reckoning while Exorcism is about to finish casting and actually get the HoR off before Exorcism finishes, getting damage from both."

A better proof that has nothing to do with exploits but a pure tanking guide that someone had made for his guild.

**Comment by pascagabriel** [comment]
I would like to point out that the fact it worked on retail as it did is because back then packets were sent every 400ms, resulting in combat entering/exiting lag, which was also the reason why ambush>sap, for example, was possible. Private servers however work the same way retail does since WoD, meaning they send packets instantly or close to instantly at all times, resulting in no such things as spell delay/combat delay, unless scripted so that packets containing such information are sent client>server side and vice versa at certain intervals, resulting in an artificially created delay. It should be noted that the reason packets were sent every 400ms back on retail was due to their technology back then wouldn't have been able to support such huge traffic (stated by blizzard at some point before WoD launch when they announced the delay removal on their side).
To conclude, I do not argue with your statement that it would reproduce the old blizzlike experience in a more accurate manner if it would be possible to Exorcism>HoR, however I will point out it's like asking the developers/server owners/players not to use a laptop and stick to a typewriter because you're a hipster and that's how you prefer it :).

**Comment by Klala** [comment]
@pascagabriel How do you know how packets were sent in retail servers and whether or not this was changed in WoD? Can you show some evidence?
And I am not forcing my reports on anyone, as I said before, this is merely to have the most accurate experience of gameplay. If this is mechanic cannot be accomplished then I am sure the staff will close this report eventually, with or without giving it too much thought.

**Comment by robinsch** [comment]
Updated

**Comment by Klala** [comment]
So I see all the commotion about this topic and also noticed that the fix has been reverted back to normal.
So the problem with the fix was that exorcism had a traveling time and this made many people confused.
Now, I have thought about it, and maybe traveling time wouldn't be a proper fix (unless you can make it travel really fast, meaning it will take less than 0.5 seconds to hit the target from 30yards).
But here's another option. How about making Hand of Reckoning damage work for only 1-0.5 seconds after the pull? This way you can get the damage without 'feeling' a delay or anything weird going on.

While this topic is still an issue, I have found another evidence that this was legit here:
http://fahrenheit-llane.org/smf/index.php?topic=16184.0

** "Exorcism:  This ability has a cast time, so it can really only be used when you aren't getting attacked.  On a pull, if you are available to, start by casting this.  You can mash Hand of Reckoning while Exorcism is about to finish casting and actually get the HoR off before Exorcism finishes, getting damage from both." **

**Comment by NovaHiros** [comment]
...and now exorcism is bugged again. In my opionion trying to replicate exploits is not the right way fix things. Give paladins a proper exorcism back and stop this nonsense, please.

**Comment by Lothloryen** [comment]
Hello NovaHiros,

Please, do tell which one is the way to fix things, maybe you can be our next incorporation to the development team.

It would be much better if you kindly collaborate with us by providing detailed information so Robinsch can fix it. This kind of comments are not the way to help us fixing things.
