### ISSUE TITLE
New Hunter, bug using ranged attack weapon

### ISSUE THREAD

**Issue by Kioni55** [dalaranwow/dalaran-wow#2956]
I have made two new hunters to see if this bug was just for the Night Elf race,  and neither are showing they have a ranged weapons equipped, even though a bow is equipped on both.  When I go to attack and use the bow, I receive a message stating I must equip a bow.  Also, the bow and ax show up in my utility bar as red question marks.  I tried buying a new bow from the NPC bowyer and it did show up, however the bar was grey because it stated I needed arrows.  I deleted the arrows that were in my bag when I created the toon (also was a red question mark in the quiver) and I purchased new arrows from the bowyer.  When I right clicked on the arrows to put them in the slot where they go,nothing happened.  When I tried to click and drag the arrows in my quiver,  I heard a message saying "I cannot put that there"  The arrows still show up as a red question mark in my quiver.  Basically, I can't use my ranged attack weapon at all as a hunter.  I can only use my ax.  I sure hope this gets fixed soon, as hunters are one of my favorite classes to play.  Thank you

**Comment by tripleslash** [comment]
Try to clear cache and WTF folders.

**Comment by Kioni55** [comment]
I did that, and it's still not working :(

**Comment by Golganeth** [comment]
Screenshot, proof? Can't reproduce this, sounds like an issue on your side indeed. Try to re-install the game from scratch. 

Before doing that, though, make sure you're dragging the correct ammo into the correct slot in your character's panel. Take off your weapon, log off and then re-equip it. Feel free to give us feedback if you sort it out, sadly there is nothing we can really do since it works as intended.
