### ISSUE TITLE
Skinning in Instances

### ISSUE THREAD

**Issue by chichio15** [dalaranwow/dalaran-wow#3000]
Can't skin instance mobs anymore.

**Comment by deasease** [comment]
ye cant skinn on any rhc but can skin normal only, sucks, i heard many ppl trow out skining when they found-out this, tbh now its fucking useless for me as well, its takes so much time to farm leather... as i got extremely limited play time there is very small chance of availability of skinning

**Comment by swiftdeath** [comment]
This is the case on 99% of the private servers. I can't say what's causing it though, all in all it's a big bummer for us skinners.

I highly doubt ths will change soon. I've seen this bug on private servers of over 5 years of age. This one is still rather young, and since they are focusing on the progression raids, I doubt much attention will go to this subject due to a very limited staff.

**Comment by jonanone** [comment]
This has already been fixed and is being tested on the PTR right now. It will be on the live server soon.
