### ISSUE TITLE
[It's the little things...] Plump Turkey and Campfires

### ISSUE THREAD

**Issue by Lukas45** [dalaranwow/dalaran-wow#3011]
[... that makes a server big]
The Plump Turkey doesn't sense its doom when near a campfire

**Comment by Rushor** [comment]
Fixed with a general update:


DB/Misc: Various Fixes

1) SIlithid Invader/Hive Drone Pooling
2) Plump Turkey Script (Keep away from fires) just walks into fire rather than jumping though

* commit: 81a6b2bd5e6106c6b47d78b93cf4961c63e614ac
* commit: 6eb5a3acf6fe30ebbf1b85ee35d7006c60e1c681

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
