### ISSUE TITLE
Taste for Blood

### ISSUE THREAD

**Issue by Vaxsysl** [dalaranwow/dalaran-wow#3024]
Warrior's Taste for Blood talent (3/3 ID: 56638) got bugged at some point. I was notified of it by the start of this week. Logging on my warrior this morning to do JC daily, I did notice it and tested it in Underbelly.

How it should work: Rend ticks every three seconds. First rend tick hapenns we get HFB. Second tick, nothing happens. Third tick happens on 6th second, and we get HFB proc again (be it from that rend or from rend on someone else, as long as its a tick after those 6 seconds).

How it works currently: On single target Rend, we get a tick every 9th second (aka third tick). This makes it impossible for an Arms Warrior to keep the debuff up at all times.

This is quite a critical class bug, just saying.

**Comment by luledebule** [comment]
Can confirm this, basicly getting overpower every 9 seconds instead of 6, its pretty huge, help please.

**Comment by robinsch** [comment]
Can't confirm. I got the proc on 1st tick and 3rd tick.

**Comment by Vaxsysl** [comment]
Proof: http://imgur.com/3hJsc3M
TFB is almost expiring while Rend is still ticking. It did not refresh.

**Comment by robinsch** [comment]
It is procing if you remove the effect, please find me a proof that it should refresh the duration if you don't use it.

**Comment by 161732** [comment]
Refreshing duration: https://youtu.be/__B7aw5Mn5g?t=5m15s

Also it's still not activating every 6s some of the time. Glyphed rend lasts 21s, so I should get the buff on ticks 1, 3, 5, and 7. Instead,  [in this example](https://youtu.be/bvArxngXrbY) it's happening on tick 1, 4, and 6. It's not consistent though, sometimes the I get tick 1, 3, 6, sometimes 1, 4, 7.

**Comment by Aridam** [comment]
Confirming this as bugged -- currently using it and noticed this annoying anomaly.

The Talent specifies that this effect cannot occur more than once every six seconds. That means it can occur once every six minimum seconds -- not shorter than that. Rend ticks every three seconds. Six seconds means two ticks of Rend, so basically it should refresh every second tick each from the previous pair so to speak.

For example the default 18s Rend without the Glyph procs the first TfB at 15s remaining -- the first tick proccing. The second TfB proc should be upon the second tick after the following one, ergo, the third overall tick -- at 9s left. The Buff lasts 9s, but once it drops below 3s it gets refreshed back up to 9s if it's not used up, so it's a tactic to cycle TfB OPs on that last pre-refresh second to avoid wasting procs.

Un-Glyphed Rend (18s duration) TfB procs at: 15s, 9s, 3s -- last tick doesn't proc it since it's only three seconds after -- need to refresh, and it procs again at 15s yet again, and so on.
Glyphed Rend (21s duration) TfB procs at: 18s, 12s, 6s, 0s (last tick) -- complete cycle per Rend, can only disturb it if you refresh Rend before it makes a tick.

So all in all, it's supposed to proc every 6s (every second Rend tick regardless of Glyph), and refresh the Buff if it's not been used once it drops down below 3s left on it, hence waiting on exactly that to be able to use OP twice in a row thanks to that mechanic of refreshing the TfB proc. The usable charge is always one, so in failing to use it on time before the reproc, the preceding one is thus wasted.

https://wow.gamepedia.com/Taste_for_Blood -- added in 3.0.2
http://wowwiki.wikia.com/wiki/Taste_for_Blood -- changed in 3.1.0 to have a respective chance to proc based on Talent Rank, with a 6s ICD.

Retail proof: https://youtu.be/nWUkwISLPPI?t=266 -- pay attention to the Buff section and keep track of Taste for Blood's icon and its timer, and notice as it goes to drop down to 2s left (practically 3s because it counts the "0s" as the last remaining second), it goes back to 8s (practically 9s because of what I just said), evidently failing (or choosing not) to use it, and thus having it refresh on itself the next six seconds.

**Comment by Aridam** [comment]
Also to update, currently the way it goes is that TfB is very much not decisive on when it wants to proc; sometimes it procs every second Rend tick as it should (even if you already have an existing TfB proc about to pass the sixth second running out), and yet sometimes it doesn't -- even if you _don't_ have it procced and unused already.

Annoying.

**Comment by TeridanDW** [comment]
After few test on PTR:
 - The 6 secs internal cd is not honored anymore, meaning talent procs on every rend tick. Player can spam overpower every 3 secs.

**Comment by Aridam** [comment]
Mwelp.

Any progress on the actual fix towards achieving the solid 6s ICD + refresh on preceeding TfB, then?

**Comment by TeridanDW** [comment]
Well you can say that. The refresh happens but the problem is that it happens every 3 secs.

**Comment by Aridam** [comment]
Talk about "overpowered" eh.

**Comment by TeridanDW** [comment]
Talking about spell https://wowgaming.altervista.org/aowow/?spell=60503

**Comment by Aridam** [comment]
I was just making a punny remark -- pardon for my terrible and misplaced humor.

**Comment by TeridanDW** [comment]
Works as intended on PTR.
