### ISSUE TITLE
[Winter Veil] Let me pelt the gnome!

### ISSUE THREAD

**Issue by lowbow** [dalaranwow/dalaran-wow#3056]
Achievement BB King (http://www.wowhead.com/achievement=4437/bb-king) is not obtainable during current event because gnome king couldn't be pelt.

Some players told that last year, during Winter Veil, you made him vulnerable for the time of event, so all could accomplish an achievement!

Could you do that again while event isn't over yet?

**Comment by Lukas45** [comment]
A work around is to get someone with Corrupted Ashbringer there - it makes him attackable

**Comment by Rushor** [comment]
DB/Achievement: Fixup BB King (Horde + Alliance)

* closes https://github.com/dalaranwow/dalaran-wow/issues/3056
* commit: 0faaf07a927c0f8af10c317aa126a0674788429e

![GitHub Logo](http://i.imgur.com/0ZGV39r.jpg)
![GitHub Logo](http://i.imgur.com/6eVXf4U.jpg)
The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
