### ISSUE TITLE
Quest: Troll Patrol: Can You Dig It? (Daily)

### ISSUE THREAD

**Issue by turtleblastoise** [dalaranwow/dalaran-wow#3083]
Quest Troll Patrol: Can You Dig It?

Issue present: The player can stand on the Ancient Dirt Mounds and used the Steel Spade, however, once the action is completed you don't get credit for investigating the dirt mound.

How it should work: Once players use the Steel Spade on the Ancient Dirt Mound, various things should happen. Sometimes spiders spawn and sometimes nothing happens (you still get credit for investigating in both cases).

http://www.wowhead.com/quest=12588/troll-patrol-can-you-dig-it

**Comment by marsalandrei** [comment]
Confirm.

**Comment by DrFuler** [comment]
[19/03/2016] - Still bugged.

**Comment by jonanone** [comment]
The Ancient Dirt Mounds inspection has been fixed and it will be applied to the live realm soon.

**Comment by Zibathy** [comment]
This is bugged on Kirin Tor. Nothing happens when you use the steel spade.
![wowscrnshot_032217_162417](https://cloud.githubusercontent.com/assets/7729864/24221398/2f81a3e2-0f1c-11e7-85f9-38b0d70d3521.jpg)
![wowscrnshot_032217_162418](https://cloud.githubusercontent.com/assets/7729864/24221399/2f864276-0f1c-11e7-9c6d-60f5b04b2341.jpg)

**Comment by Rushor** [comment]
**The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.**

@Zibathy pls don't push this. The fixes will be applied in the future on the realm. They are not pushed on live yet.
