### ISSUE TITLE
[PVP] Strand of the Ancients - Round Change bug

### ISSUE THREAD

**Issue by Naidira** [dalaranwow/dalaran-wow#3085]
Where -- Strand of the Ancients Battleground

What -- Loss of control of player character during Round Changeup can cause players being switched from Defense to Offense to remain in the keep area.

How -- If a player loses control of their character during the swap in Strand of the Ancients, they will be forced back to the position they lost control at after the swap takes place.  This can be achieved by:
- Becoming afflicted by Crowd-Control that causes loss of control of the player character during the round swap.  Polymorph currently known.  Other loss of control type CC not tested due to the precision timing required.

This enables the player to begin assaulting cannons and possibly graveyards within the defending team's area.

I have managed to catch part of one of these instances on video.  Example of being slingshotted back to the point where I was polymorphed.  Unfortunately did not catch the instant of being polymorphed.  In this case, I exited the match to avoid exploiting my position.

https://www.youtube.com/watch?v=OJxkBZtY8MQ

**Comment by Rushor** [comment]
Game/Battlegrounds: SA - Remove CC upon Round Change

* closes https://github.com/dalaranwow/dalaran-wow/issues/3085
* ((1 << MECHANIC_DISORIENTED) | (1 << MECHANIC_FEAR) | (1 << MECHANIC_CHARM) | (1 << MECHANIC_POLYMORPH)); <-- spells with these mechanic will now be removed on round change
* commit: 1a22aefd87412e33a103b982722e69b837896329

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
