### ISSUE TITLE
[Quest] Death Knight starting area speed.

### ISSUE THREAD

**Issue by Anakronism** [dalaranwow/dalaran-wow#3087]
So, after the Eye of Archerus quest, I can run at stupid amounts of speed. Like faster than 280% flying. Here's a gif of me doing so. https://gyazo.com/b833bcc60809f7e672e5ea7ca2f88882

**Comment by Rushor** [comment]
if you cancel the control (with X) of the eye, the speedbuff will not be removed
fixable with spell_linked_spell :)

**Comment by Rushor** [comment]
```sql
-- Eye of Acherus boost
DELETE FROM `spell_linked_spell` WHERE `spell_trigger`= -51852;
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES 
(-51852, -51923, 0, 'Eye of Acherus boost cancel on Eye of Acherus end');
```

**Comment by Rushor** [comment]
DB/Spell: Remove Eye of Acherus boost

* closes https://github.com/dalaranwow/dalaran-wow/issues/3087
* if you cancel the control (with X) of the eye, the speedbuff will not be removed
* commit: d7dd432e7cb4ea1e385df228df29383dc927a048

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
