### ISSUE TITLE
[Mechanic] Leash is absurdly short.

### ISSUE THREAD

**Issue by Akkalevil** [dalaranwow/dalaran-wow#3090]
The leash (how far mob will follow you) is ridiculously, absurdly, comically short.
If I'm at max range with a caster, I can throw a spell, and by just making two or three step away the mob abandon pursuit, which put the leash at about 50 yards at most.

I don't remember it being that bad last year, and it's just stupid. It's not even possible to kite anymore, as the mob abandon and goes in evade as soon as you get out of its ridiculously small leash, even if you just blasted him in the face one second ago.
Mobs should follow you for at least 200 or 300 yards from their initial position, and should be kitable permanently as long as you don't wait too much time between offensive action.

**Comment by gotmilk0112** [comment]
Yeah, this is really obnoxious. Not only does it make it almost impossible to AoE farm mobs, but it makes fighting some elite quest mobs obnoxious.

Elite mobs that have knockbacks are almost impossible to fight by yourself, because they'll knock you way back and then almost immediately reset because you're outside of their tiny leash range.

200-300 yards is a bit far; on retail, the leash range is somewhere around 80-100 yards. But it definitely is way too short on this server, and it boggles the mind why they haven't fixed it yet.

**Comment by Rushor** [comment]
ThreatRadius = 60 (That's the value from ptr)

This value can only be set in worldserverconfig from the serverowner. So it's up to loth to change/adjust it. 
I will close this with a ref. that it is working fine on ptr. Loth will soon review this issue and adjust the value. Thank you.

**Comment by TeridanDW** [comment]
Nothing to test here, it's server side setting.
