### ISSUE TITLE
[Quest][Classic] Abyssal scepters

### ISSUE THREAD

**Issue by Aalhazred** [dalaranwow/dalaran-wow#3094]
The reward of this quest is bugged, according to wowhead the Chest of Spoils should contain certain amount of gold (something between 60-90 gold), however it only has lvl 50ish potions on it, and a few elemental essences

Wowhead thread : http://www.wowhead.com/item=20602/chest-of-spoils

**Comment by krellemeister** [comment]
Considering how the acquisition of the Scepters are currently bugged and easily exploitable, I think it'd be a bad idea to fix the loot of these before fixing the Wind Stones themselves.

**Comment by Aalhazred** [comment]
Is that so? didn't knew it was exploitable, then i guess it's better to wait for a full fix

**Comment by Rushor** [comment]
acquisition of the Scepters were already fixed

**Comment by Rushor** [comment]
DB/Item: Abyssal scepters - Add goldloot (60 - 90 gold)

* closes https://github.com/dalaranwow/dalaran-wow/issues/3094
* commit: 775c60a9c85393efe82934a2e34b75bf7fb491bb

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
