### ISSUE TITLE
[Classic][Instances/Bosses][Quests]The Left Piece of Lord Valthalak's Amulet (Stratholme)

### ISSUE THREAD

**Issue by suzumiyaikari** [dalaranwow/dalaran-wow#3098]
http://wowwiki.wikia.com/wiki/Quest:The_Left_Piece_of_Lord_Valthalak's_Amulet_%28Stratholme%29

Objectives:
Use the Brazier of Beckoning to summon forth Jarien and Sothos and slay them. Return to Bodley inside Blackrock Mountain with the Left Piece of Lord Valthalak's Amulet and the Brazier of Beckoning.

```
Jarien slain
Sothos slain
[Left Piece of Lord Valthalak's Amulet]
[Brazier of Beckoning] (Provided) 
```

Once Brazier of Beckoning is used in The Crimson Throne with Grand Crusader Dathrohan/Balnazzar at Stratholme Scarlet side, Jarien & Sothos appear in the middle of the room but they cannot be attacked saying "Target not in line of sight" despite being in the middle of the room

![wowscrnshot_011816_011136](https://cloud.githubusercontent.com/assets/16735540/12378665/51162d18-bcfa-11e5-9548-28ec1c74e879.jpg)

http://wotlk.openwow.com/npc=16101
http://wotlk.openwow.com/npc=16102

**Comment by Rushor** [comment]
DB/Quest: Implement roleplayevent for The Left Piece of Lord Valthalak's Amulet (Stratholme)

* closes https://github.com/dalaranwow/dalaran-wow/issues/3098
* After they are summoned they will talk their roleplayevent. Once one of them was killed a frienly spirit version of them will spawn. Once both are killed, the Gameobject 'Sothos and Jarien's Heirlooms' will spawn, containing one item.
* commit: 86a8c6900cd921ebd58f2eab0bacf3eb38ebebe9

![GitHub Logo](http://i.imgur.com/ZI4DW8G.png)
![GitHub Logo](http://i.imgur.com/9R52LSN.png)
![GitHub Logo](http://i.imgur.com/jiMnEVJ.jpg)
![GitHub Logo](http://i.imgur.com/UzOd3Ra.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
