### ISSUE TITLE
Failed to get credit for Freya kill

### ISSUE THREAD

**Issue by thagreatk** [dalaranwow/dalaran-wow#3110]
Instance: Ulduar 10 man mode, Raid ID 335 [Algalon server]
Boss: Freya

Issue: When we downed the boss with the people who died mid fight didn't get the achievement.

Me and an other player were dead when Freya got killed. Everyone gotten credit to kill them, but me and the other shaman who died did not get them.

Screenshot
![freya bug](https://cloud.githubusercontent.com/assets/16867439/12538153/9b79ac44-c2d2-11e5-9c7c-22ff311cb60a.png)

**Comment by Kchekrik** [comment]
That's the way it works on this server. You actually have to stay alive to get credit for killing stuff. Maybe its working as intended, maybe it's a bug, if so it's a known bug.

**Comment by lolwtfz** [comment]
Happened to me to.. is there anything that can be done?
Character name : Bolu (Algalon)

**Comment by Kchekrik** [comment]
Yes, don't die. If you died to Freya, then you obviously don't know how to do the encounter and you don't deserve the achievement.
What you can do to fix this "error" is to learn the basic mechanics of this fight. Don't stand on detonating lashers, exploding bombs or near people with natures fury on them.
Just go and kill Freya again and learn the fight so you can actually earn the achievement, instead of having other people carry you.

**Comment by thagreatk** [comment]
Yes, being top dps and not being healed certainly makes me being carried....

**Comment by Golganeth** [comment]
#3093
