### ISSUE TITLE
Reign of the Dead / Shadow Priest

### ISSUE THREAD

**Issue by hellosasquatch** [dalaranwow/dalaran-wow#3116]
I've heard that the trinket doesn't proc off of Mind Flay, pretty huge considering its one of the best trinkets for the current content

**Comment by Lukas45** [comment]
I'm pretty sure Mind Flay counts as a dot?..

**Comment by hellosasquatch** [comment]
It's a channel and it's direct so I would think it counts toward the proc

**Comment by Tarpor** [comment]
'I've heard' , have you actually tested this? prove? anything?

**Comment by hellosasquatch** [comment]
Insanity the spriest has the trinket and told me it doesn't, just Mind Blast and Shadow Word: Death

**Comment by Lukas45** [comment]
I don't think it should.
Most channels are considered as DOTs, since it leaves a debuff on the target which is what does the damage (since Drain Soul procs [Extract of Necromantic Power](http://wotlk.openwow.com/item=40373))
An exception for the channels is ofc Arcane Missiles, since it works differently and is not based off a debuff, but projectiles fired.

I could be wrong on this, but I do believe that is the case

**Comment by hellosasquatch** [comment]
I'm pretty sure the debuff that Mind Flay leaves is a 50% slow that lasts for the duration of the channel. I believe the damage done by the spell and the debuff it leaves are independent of each other

**Comment by Drawsblood** [comment]
Catdawg tested it on a Reign we got. It doesn't proc off Mind Flay, although it should.

**Comment by hAkonf** [comment]
What you should be reporting is the fact that Reign has no ICD.

**Comment by ImprezaWoW** [comment]
Tested now, it DOES proc off Mind Flay. Probably got fixed along the way.
