### ISSUE TITLE
[NPC] Kaye Toogie doesn't sell recipes

### ISSUE THREAD

**Issue by DanteMS** [dalaranwow/dalaran-wow#3144]
I was there more than 5 times and I couldn't even interact with her.

**Comment by Sagrath** [comment]
Whenever you use the engineering Wormhole Generator: Northrend you have a chance of getting an option called "Underground..." along with the other locations available. Upon clicking it you will be teleported in a closed sewer in Dalaran (under the grate to the left as you exit the inn for the horde) where you will find this NPC. 35826
She will have the following recipes, all of them being on (1) Limited Supply:

Schematic: Arcanite Dragonling 16054
Schematic: Mechanical Dragonling 13311
Schematic: Mithril Mechanical Dragonling 10609

The only way to get our from this location will be to teleport out.
Apparently you cannot wait for the recipes to come back as she will not talk to you anymore after a certain period of time (30 mins?). This is probably a way to avoid farming them. So if you're unlucky enough to get there after someone else already cleaned them out you will not be able to buy them until you get the Underground option on your wormhole again.

**Comment by SadhuArch** [comment]
She will still not talk to anyone or sell anything. She just sits there, completely non-interactable. I finally got the "Underground..." option after several weeks of using the Wormhole Generator daily and she doesn't even work. What a complete waste of time.

**Comment by Rushor** [comment]
DB/Creature: Kaye Toogie - Add vendoritems

* closes https://github.com/dalaranwow/dalaran-wow/issues/3144
* note: once someone bought the item, it will not reappear for 1800 seconds
* commit: 017f993783080d951cb347d15ede865acac5f5c8

![GitHub Logo](http://i.imgur.com/sw2z6Bm.png)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Pyrehead** [comment]
As of 25.09.2019, Kaye Toogie is confirmed to still be bugged. This is the third time I got the "Underground..." Wormhole option and each time, she could not be traded with. I have also tested it separately by monitoring her behavior over the past couple weeks.

https://imgur.com/a/usfSJr8

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the report, it will be working after the next maintenance.
