### ISSUE TITLE
Quest: It's all fun and games

### ISSUE THREAD

**Issue by codyflood** [dalaranwow/dalaran-wow#3153]
- The Ocular (creature/eye) regenerates health faster than you can bring it down
- It also drops from the sky when it comes into view
- You can be very close to it but it will say out of range, I've found the only way to hit it (even though it's impossible to kill) is to be a certain distance directly above it

**Comment by Lukas45** [comment]
Workaround:
1. Fly to where it originally spawns
2. Get close enough for it to naturally aggro you on its original location(inside the blue sphere)
3. Get out of its melee range (cuz it hurts), but not far enough for it to reset (around 40yds)
4. Gun it down

While it's aggroed to you, it wont drop from the sky, and wont regenerate health. The disadvantage is that it may (almost) kill you, due to it melee hitting you once - obviously only a really big problem as non-plate.
May not work if the eye is stuck down in The Shadow Vaults

**Comment by codyflood** [comment]
Confirmed the workaround does work, but it is difficult

**Comment by Golganeth** [comment]
Already reported #549
