### ISSUE TITLE
[NPC] [Nagrand] Quartermaster Davian Vaclav (and others) @ Halaa - Not Spawning

### ISSUE THREAD

**Issue by Max0r847** [dalaranwow/dalaran-wow#3161]
Halaa, in the center of Nagrand, is a PvP objective area that can be controlled by the Alliance or Horde. When controlled by a faction, that faction has access to a quartermaster where they can purchase items using special tokens, as well as a questgiver which hands out daily PvP quests.

**How It Is Currently Working**
As far as Alliance goes, two of the NPCs are missing when Halaa is Alliance controlled.

**Missing NPCs when controlled by Alliance:**
Quartermaster Davian Vaclav - http://wotlk.openwow.com/npc=18822
Lakoor - http://wotlk.openwow.com/npc=24866

**Horde NPCs of the same type (don't know if they're missing when Horde controlled)**
Quartermaster Jaffrey Noreliqe - http://wotlk.openwow.com/npc=18821

**How It Should Work**
The missing NPCs, as listed above, should spawn for the faction that controls Halaa. Davian Vaclav and Lakoor for Alliance—Jaffrey Norelige for Horde.

**General Information Links About Halaa**
http://wowwiki.wikia.com/wiki/Halaa

**Comment by Max0r847** [comment]
Good news. I logged in and checked the place again, and I saw the Alliance NPCs there as they should be, while it was Alliance controlled. I don't know if they were manually spawned or if it was automatic. If it was automatic, perhaps this issue is obsolete.

**Comment by Golganeth** [comment]
Perhaps they were killed by the opposite faction and they had to respawn. Closing for now

**Comment by beregas** [comment]
can confirm it today, capped it for alliance and no npc spawning

**Comment by Rushor** [comment]
respawn is completely missing for those creatures. i will add a respawnscript

**Comment by Rushor** [comment]
Scripts/Outland: Halaa - Add Respawn for Halaa vendors

* closes https://github.com/dalaranwow/dalaran-wow/issues/3161
* all vendors should respawn after around 400 seconds now.
* commit: c75237cbdba46973f50e2577c7bb66e0d7ff9687

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
