### ISSUE TITLE
[NPC] Training Dummy & Devouring Plague

### ISSUE THREAD

**Issue by gotmilk0112** [dalaranwow/dalaran-wow#3164]
For some reason, Devouring Plague does only 3 damage to the training dummies in capital cities.

The damage from Improved Devouring Plague works, but the Devouring Plague DoT itself does only 3 damage per tick.

**Comment by paladincnn** [comment]
Confirmed. To be more accurate, the damage on Heroic training dummy seems correct. But it's bugged on the others.

**Comment by Rushor** [comment]
fixed with:

Scripts/World: Allow Damage for training dummies and add healthreset every 5 seconds

* closes https://github.com/dalaranwow/dalaran-wow/issues/2098
* commit: 39f2997da11c6c8ab3dfcc21a871d980dbc708f0

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
Already on PTR.
