### ISSUE TITLE
[GO] Temple of the Moon has no moonwell

### ISSUE THREAD

**Issue by wwrpg** [dalaranwow/dalaran-wow#3167]
Not a critical issue, but when crafting moon cloth / primal mooncloth, it requires a moonwell and apparently the Temple of Moon at Darnassus does not count. I tried inside the water, all around it, up above. I fly over to Darkshore and the little moonwell there worked fine.

A list of all valid Moonwells is listed here http://wowwiki.wikia.com/wiki/Moonwell

**Comment by Rushor** [comment]
DB/Gameobject: Add Moonwell spellfocus in Darnassus

* closes https://github.com/dalaranwow/dalaran-wow/issues/3167
* commit: eeb39ce120f53aa601dc8c2c061ddf021e0bae26

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
