### ISSUE TITLE
Quest: Blueleaf Tubers

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#318]
http://www.wowhead.com/quest=1221/blueleaf-tubers
summoning the npc "Snufflenose Gopher", the item "Snufflenose Command Stick" is not making the npc to search for tubers
Snufflenose Command Stick - http://www.wowhead.com/item=6684
Crate With Holes - http://www.wowhead.com/item=5880

**Comment by Spruitje** [comment]
Did this recently, however the whole experience felt a bit buggy
I summoned too many gophers though and maybe this made things iffy, i think the last gopher should disappear when a new one is summoned, or maybe even disappear after a tuber is found
Took very long to complete this in a group, since all have to loot tubers that are very difficult to find

Quest is completable f patient and persistent but i guess can use some polishing

**Comment by DrFuler** [comment]
So, is it working?

**Comment by Rushor** [comment]
fixed propperly long time ago https://github.com/TrinityCore/TrinityCore/commit/11151f447c6a89157fce8d9d53e3d7c83b531818
