### ISSUE TITLE
[Fishing] Schooner Wreckage

### ISSUE THREAD

**Issue by mariusfuul** [dalaranwow/dalaran-wow#3185]
Schooner Wreckage
This object can be found in Wetlands (50), Ashenvale (31), Hillsbrad Foothills (27), Stonetalon Mountains (6) and Arathi Highlands (5).
Yet, it's nowhere to be found, and it's required for the achievement [The Scavanger], which in turn is required for [Acomplished Angler]

**Comment by Golganeth** [comment]
The objects are spawned correctly so the achievement is completely doable. The locations are random and not all of the objects may be spawned at the same time.

Wowhead information is inaccurate in most of the cases because the website gets revamped with every expansion. You should be browsing Openwow or any other similar source.
**[Schooner Wreckage](http://wotlk.openwow.com/object=180662)** -> *This Object can be found in Wetlands (24), Hillsbrad Foothills (24), Stonetalon Mountains.*

I could spot few of them quite easily. Closing up as there's no real issue on this matter.
