### ISSUE TITLE
my char stuck

### ISSUE THREAD

**Issue by amgad47** [dalaranwow/dalaran-wow#3190]
i went to place that makes my game crash if i used hearth stone or in game unstuck it will be ok but i cant do it because the game wouldn`t open as long as iam this placed s please unstuck my char

**Comment by Golganeth** [comment]
Invalid report. The bug tracker only lists in-game issues with quests, NPCs and such.

This is a client side issue (corrupted files most likely). You should consider getting a normal client and reinstalling the game from scratch in order to avoid such issues.

If you can't log in, make an in-game ticket with another character and provide your name. You'll be moved to one of the main cities of your faction. Changing your location will temporarily fix the problem, but there is a strong chance this will happen to you again in the future if you don't reinstall.

Closing up
