### ISSUE TITLE
Pet Hotbar Disappearing

### ISSUE THREAD

**Issue by Niaseer** [dalaranwow/dalaran-wow#3242]
Hiya,

Every time I type /reload my pet hotbar will disappear. It can be made to reappear when you get a loading screen or by logging out and back in again.

**Comment by Lukas45** [comment]
The pet bar has the thing of disappearing when overwritten or reloaded, like /reload or using Eye of Kilrogg (warlock). I also believe it happens a few times on some quests when you get an NPC pet to control.

Workarounds are to dismiss and resummon the pet (completely dismissing and resummoning, relogging or mount/dismount)

**Comment by Sagrath** [comment]
It is UI issue, check your addons or your Client is corrupted

**Comment by Lukas45** [comment]
I would like to note that this is not only client based, but also caused by something server side.
I tested on Gamer-District, exact same client, exact same addons, settings and all. Worked fine, pet bar was there normally after a /reload

**Comment by Rushor** [comment]
Core/Pet: Fix pet action bar after reloading UI

* closes https://github.com/dalaranwow/dalaran-wow/issues/3242
* commit: 10372bb1fc33648f6dd38eaee64003c0285d5541

**Comment by Rushor** [comment]
The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
Game/Pet: Fix pet action bar after reloading UI

* closes https://github.com/dalaranwow/dalaran-wow/issues/3242
* thanks to dagochen 
* commit: 6b4e6aaf20a1d7afa75cfd47764d4aadaadd3c71

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
Game/Pet: Fix charm action bar after reloading UI

* closes https://github.com/dalaranwow/dalaran-wow/issues/3242
* commit: 1c32870a86be2e33cc9130be8b8eaab94f85873e

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on PTR.
