### ISSUE TITLE
<<quest bug!>>

### ISSUE THREAD

**Issue by saydan** [dalaranwow/dalaran-wow#3244]
in yesterday before server restart, i was made my lvl 3 quests and try to turn in.i disconnected from server than i log in again.my quest items were still in my bag,my xp points was lost .please can you help me for this issue.

**Comment by Lukas45** [comment]
The server often rollsback during crashes, which can cause issues like this. Not much to be done about it, other than higher server stability which is always a work in progress.

If the quest is important, then a ticket is probably the best thing to do. But given it's a level 3 quest, I can't imagine it being that important.

**Comment by Golganeth** [comment]
Invalid report. The bug tracker only lists in-game issues with quests, NPCs and such.

Additionally, I'm sorry but we do not recover lost items caused by rollbacks unless they're crucial progression items/gear (with proof). You should be able to move on without any kind of problem, your quests are still rewarded after a crash so feel free to destroy any remaining quest item in your bags.

Closed
