### ISSUE TITLE
[Temple of Ahn'Qiraj] Ouro

### ISSUE THREAD

**Issue by Tarpor** [dalaranwow/dalaran-wow#3245]
The recent maintenance has fixed a lot in AQ20 and 40 respectively, but **Ouro**15517 is not spawning.

All that is there is a mob called '_Ouro Spawner_' and the usual rubble coming from the ground. On getting close **Ouro**15517 did not spawn, nor on aggroing the '_Ouro Spawner_' , as seen on the image below. Furthermore, he did also not spawn when the 'Ouro Spawner' was slain, so was unkillable at all.

http://i.imgur.com/1YYNFCq.jpg

**Comment by Sagrath** [comment]
Confirmed

**Comment by Rushor** [comment]
Scripts/TempleOfAhnQiraj: Implement Ouro encounter

* Ouro will now spawn if you run into he middle of his room
* Ouro will submerge every 90 seconds, summons scrabs and casts Bolder if noone is in meleerange
* Furthermore the quake will be summoned and Ouro resets if the whole group wiped
* Sweep and Sandblast will be casted every 15 - 20 seconds
* closes https://github.com/dalaranwow/dalaran-wow/issues/3245
* commit: c0a072f569c5b180eb42de05f9b9e54125f1c380

![GitHub Logo](http://i.imgur.com/AgeQOrk.png)
![GitHub Logo](http://i.imgur.com/YReqNT2.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
