### ISSUE TITLE
[Warlock][Spell] Corruption + Other Dots (Immolate,Unstable Affliction,Agony,etc)

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#3248]
**Issue present**: Corruption + Other dots from Warlocks currently tick for way too much damage and it causes warlocks to do insane damage, especially in Raids and PvP aspect. 
The reason for this issue might be because the equation formula is wrong.
This especially scales better if you are Affliction spec-ed.
The retail version of equation should be: 

                      dmg = (base + sp*sp_mod) * dmg_mod

But currently it looks something like this:

                      dmg = (base + sp*sp_mod * dmg_mod) * dmg_mod

**How it should work:**
                    
                      real tick = (1080 + 2645 * 1.86) * 1.45*1.03 = 8960.55195
                      bugged tick = (1080 + 2645 * 1.86 * 1.45) * 1.45 = 12266.95933

                      What the tick is supposed to be: 8960.55195/6 = 1 493,425325
                      What the tick is doing now: 12266.95933/6 = 2044.49322125
 
**Some proof of ticks:**
--
**This is damage on full PvE gear with 0 resilience and no other warlock dots on**
![image](https://cloud.githubusercontent.com/assets/5054924/14854735/23302692-0c91-11e6-84f4-ce4edeb8e2e0.png)

**This is damage on full PvE gear with 0 resilience with warlock dots on in Affliction spec**
![image](https://cloud.githubusercontent.com/assets/5054924/14854841/92c112aa-0c91-11e6-8d7b-04b4ebb2f9a2.png)

7665 Critical strikes from Corruption.

**This is damage on full PvP gear with 1200 resilience with no warlock dots on in Affliction spec.**
![image](https://cloud.githubusercontent.com/assets/5054924/14855087/a06a10c2-0c92-11e6-9a22-1a1d872985fa.png)

**This is damage on full PvP gear with 1200 resilience with warlock dots on in Affliction spec.**
![image](https://cloud.githubusercontent.com/assets/5054924/14855119/c15b9fc6-0c92-11e6-9cb6-f2348f0abd02.png)

**This is damage on full PvE geared DK with 0 resilience with no warlock dots on in Affliction spec.**
![image](https://cloud.githubusercontent.com/assets/5054924/14855917/401738f4-0c96-11e6-99e8-9e3b7a141b54.png)

**This is damage on full PvE geared DK with 0 resilience with warlock dots on in Affliction spec.**
![image](https://cloud.githubusercontent.com/assets/5054924/14855983/749b6bfe-0c96-11e6-8001-cad56a1b2452.png)

**This is damage on a Heroic Dummy in Ironforge with no Warlock Dots on**
![image](https://cloud.githubusercontent.com/assets/5054924/14856274/bc3680ec-0c97-11e6-85f5-d710997cad7e.png)

**This is damage on a Heroic Dummy in Ironforge with full Warlock Dots on**
![image](https://cloud.githubusercontent.com/assets/5054924/14856391/243dbbb0-0c98-11e6-8e00-3c1a9dca9d7c.png)
![image](https://cloud.githubusercontent.com/assets/5054924/14856399/2d416f36-0c98-11e6-9a41-6ca8f302df33.png)
![image](https://cloud.githubusercontent.com/assets/5054924/14856409/353b52ec-0c98-11e6-9965-da1ef4d10a67.png)

-----

Additional info: This is overall problem for all the casters, not only Warlocks but all the other DoT clases such as Shadow Priests, Mages and possibly Moonkins.

----
Comparison to Sunwell Core:
It works more closely to retail values, tested there and confirmed.

**Comment by Coolkira** [comment]
Good job! I hope they fix it .

**Comment by Mike-Hunt** [comment]
Hi, I just want to check some of the numbers you've used, because I'm not getting the same values as you are. 
In your proposed blizzlike formula, you have (1080 + SP x 1.86) x 1.45 x 1.03, I'm assuming this is for Affliction specced warlocks (you didn't specify I don't think). 
I'm unsure where you get your 1.45 value from. From elitistjerks (http://forums.elitistjerks.com/forums/topic/37521-dots-and-you-the-affliction-warlock-thread/), Malediction is the only multiplicative coefficient, the rest are additive. 
From what I can see, Shadow Mastery (0.15), Improved Corruption (0.1), Contagion (0.05), Siphon Life (0.05), Malediction (0.03) will always be present. This would give a modifier of 1.35 x 1.03 at minimum. 
Then you have conditional modifiers: If Spellstone is present +0.01, if Haunt is up +0.2 (0.23 glyphed), if Shadow Embrace is up +0.05/0.1/0.15, if CoE/etc is up +0.13, if FI/SR/AE buff is present +0.03, if target is below 35% hp then Death's Embrace adds +0.12. Can you explain how you got 1.45?

Then I'm also not very certain what the purpose of all of your screenshots are, as they don't seem to confirm your proposed bug which would cause ticks of 2044.5 damage. This might be because you weren't very rigorous in your testing (you tested against a prot warrior, did you account for (Improved) Defensive Stance/Berserker Stance modifiers? Or the 15 resil shoulder enchant? When you tested against the DK, did you account for (Improved) Frost Presence/Magic Suppression modifiers? Was Lilje's spellpower constant at 2645? Did he have lightweave proc/consistent Fel Armor uptime/was illustration always fully stacked/did he have any trinkets that procced spellpower (flare/abyssal rune etc)?). For example, when testing just corruption against Achilles, you have noncrit ticks of 2534 and against Icespear/the training dummy you have noncrit ticks of 2041. What are you trying to prove with the disparity in those tick values exactly?
Since you didn't (deliberately) test out different spellpower values, I don't see how you managed to prove any formulae bugs, as you require more than one point to prove a linear equation.

Finally: 'Comparison to Sunwell Core: It works more closely to retail values, tested there and confirmed.' translates to: 'I tested it on my personal private server and got different values and I think those different values are correct, but I didn't actually demonstrate any proof about how it compares to retail', so I'm not sure what the purpose of that was.

**Comment by PolarCookie** [comment]
Hi, I helped crispybuilt with this ticket, so let me clarify the numbers.
1.86 spell power mod is 1.2 (base spell power mod for 6 ticks) + 0.36 (empower corruption) + 0.3 (everlasting affliction)
1.45 damage mod is 1 (base) + 0.1 (improved corr) + 0.05 (SL) + 0.15 (shadow mastery) + 0.05 (contagion) + 0.1 (tier 9 4 piece bonus, we forgot to mention this part, sorry about that).

the screenshots mostly show that corruption is hitting for very high amounts with different configurations,
but the take away message is that with 2645 spellpower I hit for 2041 on a dummy, no spellstone or damage debuffs included.

**Comment by Mike-Hunt** [comment]
Right, you proved that with 2645 spellpower corruption can tick for 2041, which is close enough to your estimated value of 2044.5 that the difference could be explained due to rounding. But you didn't find any other data points so you didn't actually prove a linear equation, nor did you check if the 10% boost from 4t9 (which I completely forgot about, sorry) was multiplicative or additive (I can't see any sources saying that its supposed to be additive) - if it is multiplicative then it would have an impact on the formula as well.

**Comment by PolarCookie** [comment]
simcraft says T9 4P is additive.

spell power | blizzlike | estimated | dalaran 
--- | --- | --- | ---
707 | 555,045885 | 661,71044475 | 660
909 | 642,118995 | 779,25914325 | 776
1067 | 710,225685 | 871,20317475 | 868
1310 | 814,97205 | 1012,6107675 | 1011
1567 | 925,753185 | 1162,16529975 | 1159
1774 | 1014,98157 | 1282,6236195 | 1279
1930 | 1082,22615 | 1373,4038025 | 1371
2182 | 1190,85201 | 1520,0487135 | 1517
2347 | 1261,976085 | 1616,06621475 | 1613
2445 | 1304,219475 | 1673,09479125 | 1669
2583 | 1363,705065 | 1753,40033775 | 1750
2691 | 1410,259005 | 1816,24815675 | 1814
3069 | 1573,197795 | 2036,21552325 | 2033
3201 | 1630,097055 | 2113,02952425 | 2111

**Comment by Mike-Hunt** [comment]
Alright, this data is far more relevant/useful than the OP. Kudos.

**Comment by dxxa** [comment]
thanks guys, I do not know how long I confirmed that the damage on this server were not normal, good job that you know the formulas.

**Comment by robinsch** [comment]
On PTR. Special thanks to @PolarCookie

**Comment by TeridanDW** [comment]
Missing label here?
