### ISSUE TITLE
[BG - SOTA] Combat Bug from vehicles

### ISSUE THREAD

**Issue by Lukas45** [dalaranwow/dalaran-wow#3251]
If you attack any vehicle in the battleground, either the demolisher's or the defence cannons, you will be stuck in combat until what you attacked is dead, or you die.
This makes the battleground even more painful than what it already is, since you have no chance of catching up to demos that you're trying to kill because they are faster than you (and can't be slowed).

Combat bug just needs to be fixed overall.

Also:
Does this BG have a higher chance of starting compared to the others, because I'm seeing more SOTAs than any other BG from Random Queue

**Comment by Golganeth** [comment]
Directly related to #2652.

SotA should have the same chance as any other battleground included in the random rotation. The battleground can be quite unpleasant because some of the issues. We're aware of that so If you encounter anything that isn't reported yet, please open a bug report so that it can be looked at as soon as possible (general note for everyone).

Closed.
