### ISSUE TITLE
wandering plague

### ISSUE THREAD

**Issue by PolarCookie** [dalaranwow/dalaran-wow#3256]
wandering plague is hitting for too much atm
it is supposed to be a hit equal to the original disease damage
A solution to the problem might be https://github.com/TrinityCore/TrinityCore/issues/1818
The case is that the wandering plague hit is considered a shadow spell on it's own, that is affected by all damage modifiers such as the +13% magic increase debuff.

Test to verify;
specc into wandering plague but not ebon plaguebringer = WP hits the same as the disease
specc into wandering plauge and ebon plaguebringer = WP hits for 283 to frost fevers 251

Black ice also affects WP, with only WP and black ice, frost fever hits for 188 while WP is 206

**Comment by Monziltinks** [comment]
I can confirm. The Wandering Plague damage is supposed to do an 100% additional damage of your diseases as an AoE proc. 
Which means if the Disease ticks for 1500, the Wandering Plague will do an additional 100% which would be another 1500.

How it should be: The disease ticks for 1500 damage, wandering plague procs and does another 100% damage as AoE, dealing 1500 more damage.

Somewhere in the calculations the damage of Wandering Plague is close to doubled but as I do not have a dk or access to the code, I can not pinpoint the issue.

**Comment by Mike-Hunt** [comment]
From what I can tell, the damage modifiers that are double dipping (i.e. Increasing the damage of the disease, then increasing the damage of the wandering plague proc from that disease) are:
•	Black Ice (+10%)
•	 Ebon Plaguebringer/CoE/Earth and Moon (+13%)
•	Blood Presence (+15%)
•	Desolation (+5%)
•	Bone Shield (+2%)
•	Sanctified Retribution/Ferocious Inspiration/Arcane Empowerment (+3%)
•	Light/Dark Essence on the Twin Valkyr encounter (+50%)

Total of 1.1 * 1.13 * 1.15 * 1.05 * 1.02 * 1.03 = 1.577 = 57.7% increased WP damage in a standard raid, and 1.577 * 1.5 = 2.365 = 136.5% increased WP damage (to one target) on the Twin Valkyr encounter.

Snippet from World of Logs:
 
![image](https://cloud.githubusercontent.com/assets/18732159/16592405/e07a9034-4323-11e6-9dce-fd5c00c2fc8c.png)
 
For the first Frost Fever tick that procs WP: 2152 * 1.1 * 1.13 * 1.15 * 1.05 * 1.02 * 1.03 = 3393.4 c.f. 3393
For the Blood Plague ticks that proc WP: 1808 * 1.1 * 1.13 * 1.15 * 1.05 * 1.02 * 1.03 = 2850 c.f. 2849
For the last Frost Fever tick that procs WP on the snobold and Gormok: 
	Gormok: 1861 * 1.1 * 1.13 * 1.15 * 1.05 * 1.02 * 1.03 = 2934.6 c.f. 2933
	Snobold (No Ebon Plaguebringer/CoE debuff present yet): 1861 * 1.1 * 1.15 * 1.05 * 1.02 * 1.03 = 2597 c.f. 2596

On Twin Valkyr: With Dark Essence (+50% damage to Fjola Lightbane and -50% damage to Eydis Darkbane, and no Ret Paladin was present for Sanctified Retribution +3% damage raid buff)
 
![image](https://cloud.githubusercontent.com/assets/18732159/16592410/e808fd0e-4323-11e6-8820-e8d860da41e9.png)

Bone Shield was not active for this snippet, so there is no 2% damage boost from that.
For the Frost Fever ticks that proc WP: 3300 * 1.1 * 1.13 * 1.15 * 1.05 = 4953
 4953 * 0.5 = 2476.5 c.f. 2475; 4953 * 1.5 = 7429.6 c.f. 7428
For the Blood Plague tick that procs WP: 2770 * 1.1 * 1.13 * 1.15 * 1.05 = 4157.6
4157.6 * 0.5 = 2078.8 c.f. 2078; 4157.6 * 1.5 = 6236.3 c.f. 6235



Also, on a somewhat related note, it seems that Death Knights are able to benefit from the Dark/Light Essence damage boost to their diseases on both mobs by using pestilence off the primary target. This is evident in the snippet above, since Frost Fever and Blood Plague are doing the same (50% increased) damage to both targets. I don’t know if that is how it worked on retail or not.

**Comment by robinsch** [comment]
On PTR.

**Comment by Rushor** [comment]
Core/Spell: Fixed Wandering Plague scaling

Issue: https://github.com/dalaranwow/dalaran-wow/issues/3256
commit: aa5b44f4db6a9dd5cc7bb028db889874d1789bd4

**Comment by TeridanDW** [comment]
Work as intended on ptr.

![wowscrnshot_101417_142735](https://user-images.githubusercontent.com/6797611/31575311-6d25517c-b0ec-11e7-8f43-be01576b5b1b.jpg)
Damage of WP is increased by Blood Presence (15%) only now.

**Comment by robinsch** [comment]
This is intended because it's a increased damage effect that gets placed on the target.

**Comment by TeridanDW** [comment]
Alright.
