### ISSUE TITLE
Forgotten password problem

### ISSUE THREAD

**Issue by kodara22** [dalaranwow/dalaran-wow#3288]
My friend, for his own good changed a password that he didnt want to remember becouse he had to study. Now when he wants to and can play again he cant, when trying to recover his password, after clicking "Forgot your password?" the webpage only refreshes. When i try to do it happen the same to me, dont know about you guys. What can he do to recover his pass?

**Comment by kodara22** [comment]
I just realized you cant even create new account, is it all bugged?

**Comment by Golganeth** [comment]
The website is under heavy rework and some features such as password recovery aren't operative. Send an e-mail to dalaran.community@gmail.com with the same e-mail with which you created the account and we'll help you out. In case you don't remember the e-mail you used, add relevant information (IPs, older passwords, etc) in order to prove that you are the legitimate owner of the account you want to recover.

You can create new accounts just fine.

Closed
