### ISSUE TITLE
[Engineering] Reginald Arcfire

### ISSUE THREAD

**Issue by Tarpor** [dalaranwow/dalaran-wow#3299]
This is a recent bug, the auctioneer in Dalaran doesnt recoqnize engineers anymore. Engineers can still however access the auctioneer through a small bar. Non-engineers don't have that bar.

![wowscrnshot_051516_142541](https://cloud.githubusercontent.com/assets/11572687/15333363/9b2d9b10-1c69-11e6-86d2-3f866027508d.jpg)
Engineer on the left, non-engineer on the right.

**Comment by Lukas45** [comment]
Works fine for me.
The message was added/change to show for all some fixes ago, at the same time the Flight Masters began to show "Show me where I can fly" instead of the flight map instantly
![ab4e62f91dd13cdb8b31f3a63adba65c 1](https://cloud.githubusercontent.com/assets/4707702/15337066/0183ac6e-1c7a-11e6-9089-c9054a68bde6.png)

**Comment by Tarpor** [comment]
Does indeed seem to work now, weird, it didn't yesterday. Will close, feel free to comment if anyone has the same issue.
