### ISSUE TITLE
[Ulduar] Door to Kologarn Bugged on 10-man

### ISSUE THREAD

**Issue by scairen** [dalaranwow/dalaran-wow#3313]
Our guild is prevented from progressing to Kologarn's encounter because the door to his chamber is closed when we enter The Antechamber of Ulduar after killing XT. We're not sure what's going on, but after the second week of this bug occurring, we used alts in other guilds to progress with no issue, and it seems like no one we've talked to on the server is experiencing this problem.

Additionally, none of our characters are combat bugged or otherwise flagged for combat.

We can select and aggro Kologarn, our pets can freely move through the door and attack Kologarn.

**Comment by Tarpor** [comment]
Maybe kill Iron Council?

**Comment by ImprezaWoW** [comment]
[IC should not be needed to get to Kologarn.](http://www.gamefaqs.com/boards/534914-world-of-warcraft/51961003)

**Comment by Lukas45** [comment]
While it was not like that on Retail, I'm pretty sure it's intentional to make Iron Council mandatory here.

**Comment by scairen** [comment]
My Guild Leader got in contact with a GM, who came into our instance after the raid disbanded to assess the door issue. Per the GM, the doors should be open and the fact that they were not open is an issue.

**Comment by Golganeth** [comment]
Hey,

@Scairen, Thank you for the report, it will be looked at. I have seen recently some groups killing Kologarn while Iron Council was alive, so this might not be happening everytime. For now, simply killing Iron Council should open the door.

@Lukas45, That would make sense actually, considering we have added some restrictions to keep the progression feeling. However it is not the case, otherwise we would have done the same to Ignis or Razorscale, for example.

**Comment by Lukas45** [comment]
It has been this way ever since I started raiding Ulduar way back in August. I can't see how it's not intended if it stays for this long.
Razor and Ignis makes sense not to have progression on in their current states, where they are no easy pushover, as they're supposed to be for Wing-1 boss, but they are still required for TOC attunement

**Comment by Lothloryen** [comment]
Hello there,

It is not bugged, it was intentionally done this way. We shall reconsider it now, thank you very much for the reports.
