### ISSUE TITLE
[Item] Elixir of Dream Vision

### ISSUE THREAD

**Issue by ImprezaWoW** [dalaranwow/dalaran-wow#3321]
After using [Elixir of Dream Vision](http://www.wowhead.com/item=9197/elixir-of-dream-vision) your body falls asleep and you can explore areas with Dream Vision, however Dream Vision aggros mobs if you run through them and cancels the elixir effect. It is not supposed to aggro them.

**Comment by Rushor** [comment]
http://www.wowhead.com/item=9197/elixir-of-dream-vision#comments:id=1677306

> Can't be aggrod

**Comment by Rushor** [comment]
DB/Creature: Dream Vision - controlled unit should not aggro creatures

* closes https://github.com/dalaranwow/dalaran-wow/issues/3321
* commit: 246226a393a07514815c0a9862156c6b8761f34d

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
