### ISSUE TITLE
Halaa - Spawn + Bombing

### ISSUE THREAD

**Issue by ImprezaWoW** [dalaranwow/dalaran-wow#3346]
All the NPCs in [Halaa](http://wowwiki.wikia.com/wiki/Halaa) tend to spawn multiple times (perhaps after the change of controlling faction). So far I've seen up to 10x of the same NPC stacked one on another. Because of that the area gets quite laggy.

**Comment by Rushor** [comment]
**Description**:
Nothing happens when you try to repair the Wyvern posts.

**Current behaviour**: 
When you right click on either the bomb wagon or the Wyvern post it does nothing. 

**Expected behaviour**: 
Normally you repair some wyvern/griffin posts, then you fly around and bomb Halaa.

**Steps to reproduce the problem**:
1. Go to Halaa.
2. Go to the bombing post
3. Right click on it
4. Observe that nothing happens

**Include proofs for this behaviour**
Sorry, but I don't have the capability to do this :(
Although I assume this just h

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
The zone is Nagrand, in the pvp area. Halaa.

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the report, this has been fixed already.
