### ISSUE TITLE
[ToC] Twin Valkyrs heroic - Touch aoe combat log

### ISSUE THREAD

**Issue by plznoz** [dalaranwow/dalaran-wow#3355]
Currently the _Touch of Light_ and _Touch of Darkness_ **aoe damage** does not show up in the combat log. Note that the touch does show up in combat log for people who has it (but not the aoe around said person).
People still take the damage, but no combat log entry is shown.

Orbs previously had the same issue but this was fixed.

**Comment by Plexieglas** [comment]
To add to that, normally the debuff should get removed when you swap colors. It does not in our case.

"The Twins also gain a new ability called Touch of Light and Touch of Darkness. This is cast on random players during the encounter and causes them to inflict AOE damage to players around them who are of opposite attunement. It can be preemptively removed if the affected player swaps colors. However, Touch of Light/Darkness will not harm players with the same attributes as the Touch, so if the raid is segregated properly this poses little threat."

**Comment by Taverny** [comment]
still not fixed >_<

**Comment by Rushor** [comment]
Scripts/Spells: Twin Valkyrs - Touch of Light and Touch of Dark - Improve Targetselection aand combatlog

* closes https://github.com/dalaranwow/dalaran-wow/issues/3355
* commit: 8789ef45134e49590a180c443be2175cc3d9b0da

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
