### ISSUE TITLE
[BUG] Lazy Peon NPCs in Valley of Trials without axes

### ISSUE THREAD

**Issue by AcadianBacon** [dalaranwow/dalaran-wow#3372]
None of the Lazy Peons in the Valley of Trials have axes in their hands, they're all swinging their empty hands at trees and logs.

**Comment by Rushor** [comment]
http://i.imgur.com/PcLo4FX.jpg true

**Comment by Rushor** [comment]
Scripts/Quest: Work Work! Move Lazy Peon script to SAI

*  Move Lazy Peon script to SAI
*  Lazy Peon will now activate itself every 120000 till 150000 milliseconds
*  Lazy Peon will now play work-sounds
*  Lazy Peon will now display the axe-swing emote
*  Lazy Peon will now kneel in front of the pile, and start cutting in front of the tree
*  Lazy Peon will now use better positions and orientations for the wood pile and the trees
*  Lazy Peon will fall asleep after 80 seconds of working
* closes https://github.com/dalaranwow/dalaran-wow/issues/3372
* commit: 7e4cc473ae0360c1487d2e13268a1793ced8cc2a

![GitHub Logo](http://i.imgur.com/XRhPdL2.jpg)

Also a video for this https://youtu.be/RjmtVksG3cI

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
