### ISSUE TITLE
Darkmoon Faire Barkers

### ISSUE THREAD

**Issue by ImprezaWoW** [dalaranwow/dalaran-wow#3406]
Kruban Darkblade is present in Orgrimmar at all times, saying that the upcoming Darkmoon Faire will be held in Mulgore, regardless of whethere it's true or not. (also related issue [of him being still instead of wandering](https://github.com/dalaranwow/dalaran-wow/issues/1241)), when _he should only available the week before Darkmoon Faire is set up in Mulgore, and during the fair._  [Source](http://wowwiki.wikia.com/wiki/Kruban_Darkblade)
On the other hand, the other Darkmoon Faire Barker, Melnan Darkstone, seems to be non-existant at all in Ironforge, even when he should _be available the week before Darkmoon Faire is set up in Elwynn Forest._  [Source](http://wowwiki.wikia.com/wiki/Melnan_Darkstone)

**Comment by Rushor** [comment]
3f68f0be4ff09060c852ffba4e5f148f04454e4a

melnan added to gamevent 4 (testable with .event start 4/.event stop 4)
Kruban Darkblade added to gameevent 110 
```sql
INSERT INTO `game_event` (`eventEntry`, `start_time`, `end_time`, `occurence`, `length`, `holiday`, `description`, `world_event`, `announce`) VALUES 
(110, '2014-01-02 00:01:00', '2020-12-28 06:00:00', 131040, 4320, 0, 'Kruban Darkblade (Mulgore)- Building Up', 0, 2);
```
testable with .event start 110 / .event stop 110

**Comment by Rushor** [comment]
DB/Creature: Darkmoon Faire Barkers - Kruban Darkblade + Melnan Darkstone - Assign gameevent, add spawnpoint and paths

* closes: https://github.com/dalaranwow/dalaran-wow/issues/3406
* commit: aab2bb12ce3a62f5abd838a466f39c61e73fa4fa

Kruban Darkblade will now spawn and despawn with gameevent 5 and 71. Also added a path for him.

```sql
DELETE FROM `game_event` WHERE `eventEntry` IN (5, 71);
INSERT INTO `game_event` (`eventEntry`, `start_time`, `end_time`, `occurence`, `length`, `holiday`, `description`, `world_event`, `announce`) VALUES 
(5, '2017-01-01 00:01:00', '2020-12-31 06:00:00', 131040, 8639, 375, 'Darkmoon Faire (Mulgore)', 0, 2),
(71, '2013-01-06 01:01:00', '2020-12-31 06:00:00', 131040, 8639, 0, 'Darkmoon Faire Building (Mulgore)', 0, 2);
```

Melnan Darkstone will now spawn and despawn with gameevent 4 and 23. Also added a path for him.

```sql
DELETE FROM `game_event` WHERE `eventEntry` IN (4,23);
INSERT INTO `game_event` (`eventEntry`, `start_time`, `end_time`, `occurence`, `length`, `holiday`, `description`, `world_event`, `announce`) VALUES 
(4, '2016-12-04 00:01:00', '2020-12-31 06:00:00', 131040, 8639, 374, 'Darkmoon Faire (Elwynn Forest)', 0, 2),
(23, '2016-12-01 00:01:00', '2020-12-31 06:00:00', 131040, 4320, 0, 'Darkmoon Faire Building (Elwynn Forest)', 0, 2);
```

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
