### ISSUE TITLE
Quest: The Last Line of Defense

### ISSUE THREAD

**Issue by Kaara** [dalaranwow/dalaran-wow#343]
Hello,

http://www.wowhead.com/quest=13086

This quest is bugged. I took the quest i got phased, but the mobs are not there. And now i cannot see the argent tournament vendor.

**Comment by Watterx** [comment]
Theres no cannons at all now.

**Comment by Mantigora** [comment]
Completed it normally as it should be. I found one cannon on top of tower. One thing - cannons shouldn't be movable and should be only on towers not in field.
![wowscrnshot_030915_202235](https://cloud.githubusercontent.com/assets/10964125/6561605/1dd9af5c-c69b-11e4-9725-0eae9fd2bb8c.jpg)

**Comment by Camarila** [comment]
There's only 3 cannons in the area after getting phased, all of them say' Out of Range'.

**Comment by Augur89** [comment]
The cannons didn't work at all for me. I just killed the 100 Scourge and the 3 Wyrms in hand to hand combat. And guess what? It felt much more epic and rewarding as YOU are the actual last line of defense xD

**Comment by xxauroraxx** [comment]
I was able to get phased with cannons, but then NPCs weren't phased and vice-versa.

**Comment by Klala** [comment]
After trying to spam the interacting keybind and failing everytime I found out another way to do it.
Right now everytime you start the quest you phase out of the battle where the cannons are, when I got close to the cannons i got phased into the battle and the scourge were everywhere but the cannons were nowhere to be seen. After I tried everything I realized that everytime I get into the battle I can abandon the quest and I got phased out of the battle, so I got close to the cannons, abandoned the quest, managed to get on a cannon and place it closer to the quest giver so when I will accept the quest again I could jump on it with ease. When I accepted the quest again I got phased again and the cannon I moved disappeared but when I flew out and into the area again I saw it and started shooting.

Then I encountered the second bug which was the evade thing. But I knew what was wrong, since the mobs have a certain distance to chase you until they go back to their position, and I was shooting from way back, every time they got attacked they instantly got reset because I was too far away. I got around that too, since you can move with the cannons I just went there and shot everything in my path.

So the things that should be looked into are:
1. Making the cannons unmovable.
2. Being able to attack from a long distance without causing evade.
3. Once the quest starts you should be put in the battle phase until completion.

**Comment by Khronos-** [comment]
"xxauroraxx commented on Jul 4
I was able to get phased with cannons, but then NPCs weren't phased and vice-versa."

Getting this exactly.

**Comment by billiamlumbergh** [comment]
This quest is completable, but fairly difficult to get working. There will be a cannon spawned at (85.96, 78.56). If you can manage to interact with it before you phase into the battle, you can move it wherever you would like and use its abilities to kill the scourge in the surrounding area. It will move just as if you were running.

**Comment by npmusicftw** [comment]
Anytime I go past the bridge, I get phased out and can't reach the cannons. No matter if I have the quest or not, the cannons are always JUST out of reach (phase out before contact). 

Extremely frustrating.

**Comment by billiamlumbergh** [comment]
I had a friend who had this problem and since I was in the phase with the cannons (already completed the quest), I could get in the cannon and move it inside the camp for him to use.

**Comment by nyrpha** [comment]
just tried doing this quest. first, the goblin npc giving it was phased out when i tried to get to him. when i was able to interact with him after a bit of flying around, there was 1 cannon active but on the floor of the tower, so that i would shoot into the wooden plank surrounding it, also there were no mobs. only corpses laying on the ground. i took off again and when i came back, there were all cannons active and on a wooden block, elevated slightly above the towers so that you could actually shoot them. there were other players on top of the cannons, and some were driving them around in the field. i shot at the mobs and most of the time they were evading. after a few minutes i would get a kill every now and then. an alliance player shot at me with his cannon, killing me. when i ressed, all the cannons were gone except for one in the field, that i can't mount. it says out of range. currently i have the quest half completed and will check back tomorrow, hopefully completing it. but it is certainly a quest that needs some love in order to function properly. especially since it is locking a lot of other quests in IC through the quest chain thing.

**Comment by Jrizzle23** [comment]
The cannons are bugged they just phase out as you walk up to them after the scourge appear.

**Comment by Akkalevil** [comment]
I managed to get into a cannon and be in a correct phase (phases are really wonky in this quest).
It's possible to do it, but most of the time the scourge just get an "evade" when shot at. Sometimes it works. It's really very random and annoying.

**Comment by MrAndersonX** [comment]
Confirmed - bugged. Needs a fix.

**Comment by DrFuler** [comment]
[26/03/2016] - Confirmed. Still bugged.

But doable if you manage to kill them all normally.

**Comment by Tarpor** [comment]
I believe I've found another **HUGE** issue with this quest. Once a player has picked it up, and does **NOT** complete it, but instead _Abandons_ it, they will get stuck flying into Dalaran. I have 1 confirmation on this currently (player gets stuck flying into Dalaran(seems to happen at random) and has at one point had **The Last Line of Defense** _13086_ in log), and have heard of this bug through 3 people.

**Comment by sianios** [comment]
I managed to complete the quest, what I did.
First I got the quest after standing next to the missing cannon i abandoned it and then when and got the quest again, the cannon was still there and was able to complete the quest. Patience is required.

**Comment by Lothloryen** [comment]
Hello,

Cannons will not be movables anymore, still need to look further into the rest of the issues.

**Comment by Lothloryen** [comment]
Hello there,

After the next realm restart, this quest should be always fine. If anyone experiences any trouble with the cannons being on a different phase, feedback will be appreciated.

Thank you very much.

**Comment by Neelaphoenix** [comment]
This is still buggy (but playable).  The ground units are still evade a lot, but can be hit. The main problem is with the air units (the wyrms) - thye just pat and and don't attack you.  So they very often evade.  You can find some that pat close to the cannons, but you have to esarch for them and wait for respawn to complete quest.
