### ISSUE TITLE
[Quest][Classic] Cenarion Battlegear

### ISSUE THREAD

**Issue by PSAlias** [dalaranwow/dalaran-wow#3435]
**Description**: Quests for Cenarion badge gear are not repeatable, preventing players from obtaining more than one of the rewards from each tier, when all should be available.

**Current behaviour**: The 4 quests offered by Vargus, Volunteer's Battlegear, Veteran's Battlegear, Champion's Battlegear, and Stalwart's Battlegear are offered and implemented correctly, but once completed, are no longer offered to players.

**Expected behaviour**: These quests should be offered an unlimited number of times.

**Steps to reproduce the problem**:
1. Obtain the required number of marks/badges for any of the quests indicated
2. Take that quest from Vargus and then turn it in to him
3. Interact with Vargus again and note that said quest no longer available

**Include proofs for this behaviour**

http://www.wowhead.com/quest=8574/stalwarts-battlegear#comments
http://www.wowhead.com/quest=8573/champions-battlegear#comments

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

NPC:
Vargus: 15176

Items:
Cenarion Logistics Badge: 20800
Cenarion Tactical Badge: 20801
Cenarion Combat Badge: 20802
Mark of Cenarius: 21508
Mark of Remulos: 21515

Quests:
Volunteer's Battlegear: 8548
Veteran's Battlegear: 8572
Champion's Battlegear: 8573
Stalwart's Battlegear: 8574

Zone:
Silithus: 1377

**Comment by Rushor** [comment]
DB/Quest: Quests started by Vargus should be repeatable

* closes https://github.com/dalaranwow/dalaran-wow/issues/3435
* commit: 58324194392cd47729110aa7c27cdb0ea47b0fc4

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
