### ISSUE TITLE
[Quest][Classic] Argent Armaments of Battle

### ISSUE THREAD

**Issue by PSAlias** [dalaranwow/dalaran-wow#3436]
**Description**: Quests for Argent insignia gear are not repeatable, preventing players who have already reached exalted standing from obtaining more than one of the rewards from each tier, when all should be available.

**Current behaviour**: The 8 Armaments of Battle quests are offered by Quartermaster Miranda Breechlock and implemented correctly, but once completed, are no longer offered to players.

**Expected behaviour**: These quests should be offered an unlimited number of times to players at the appropriate reputation.

**Steps to reproduce the problem**:
1. Obtain the required number of insignia for any of the quests indicated, making sure that your reputation is at the level required for that quest, no higher, no lower
2. Take that quest from Quartermaster Miranda Breechlock and then turn it in to her
3. Interact with Quartermaster Miranda Breechlock again and note that said quest no longer available

**Include proofs for this behaviour**

http://www.wowhead.com/quest=9226/superior-armaments-of-battle-revered-amongst-the-dawn#comments
www.wowhead.com/quest=9228/superior-armaments-of-battle-exalted-amongst-the-dawn#comments

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

NPC:
Quartermaster Miranda Breechlock: 15176

Items:
Insignia of the Dawn: 22523
Insignia of the Crusade: 22524

Quests:
Superior Armaments of Battle - Friend of the Dawn: 9222
Superior Armaments of Battle - Honored Amongst the Dawn: 9224
Superior Armaments of Battle - Revered Amongst the Dawn: 9225
Superior Armaments of Battle - Exalted Amongst the Dawn: 9228
Epic Armaments of Battle - Friend of the Dawn: 9221
Epic Armaments of Battle - Honored Amongst the Dawn: 9223
Epic Armaments of Battle - Revered Amongst the Dawn: 9226
Epic Armaments of Battle - Exalted Amongst the Dawn: 9227

Zone:
Eastern Plaguelands: 139

Faction:
Argent Dawn: 529

**Comment by Rushor** [comment]
DB/Creature: Quest from Quartermaster Miranda Breechlock should be repeatable

* closes https://github.com/dalaranwow/dalaran-wow/issues/3436
* commit: f893bf5a170440798ec646f0abdfdf0ca7d701b9

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
