### ISSUE TITLE
Quest: The Lost Mistwhisper Treasure

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#344]
http://wotlk.openwow.com/quest=12575

Warlord Tartek (ID: 28105)
He should spawn on a proto-drake once the player attempts to pick up the treasure, but he doesn't.

**Comment by Khronos-** [comment]
@Golganeth Redirected from #2760.

Managed to complete the quest by AoEing down the Warlord Tartek and looting the item. This time High-Oracle was able to accept my quest as completed. Did you change the ID of the item that was looted or was it just random stuff happening? Also one other bug appears when you abandon the quest: Frenzyhearts cannot be attacked anymore, as stated in #697.

Also I can confirm that after completing that quest, Frenzyhearts were now able to be attacked again by any normal skill. Still to confirm if the issue was fixed permanently for me or only temporary until I leave the zone. Will confirm that in a bit.

**Comment by Lothloryen** [comment]
This issue should be solved after this next maintenance.

Thank you.
