### ISSUE TITLE
[NPC] Ulduar General Vezax should be immune to taunt

### ISSUE THREAD

**Issue by Remidemmi** [dalaranwow/dalaran-wow#3451]
**Description**:

General Vezax in Ulduar should be immune to taunt but isnt currently.

**Steps to reproduce the problem**:

1. roll a class that has a taunt
2. go to vezax in ulduar
3. press your taunt button

**Include proofs for this behaviour**
http://wowwiki.wikia.com/wiki/General_Vezax

**Comment by ashido96** [comment]
Well if you fix this, please fix protection paladin divine plea not giving any mana back. We currently use dps trinkets and ignore half our rotation to be mana efficient for threat generation. So taunting off of a dps that pulls threat because of gimped mana is pretty much a requirement for paladins tanking vezax currently.

"Spell shadow shadowfury  [Aura of Despair]ω ϖ ω ϖ—Prevents mana regeneration from nearly all natural sources. Aspect of the Viper, Judgements of the Wise, Shamanistic Rage, and Spiritual Attunement remain at least partially effective. **Divine Plea** for protection paladins also appears to work too. Also reduces melee attack speed by 20%. "

http://wowwiki.wikia.com/wiki/General_Vezax

**Comment by Golganeth** [comment]
General Vezax in Ulduar should be immune to taunt - Already on PTR

The issue with [Aura of Despair](http://wotlk.openwow.com/spell=64848) and [Divine Plea](http://wotlk.openwow.com/spell=54428) will be looked at.

**Comment by ashido96** [comment]
Great job fixing the taunt and not the mana regen, basically impossible for any raid with paladin tanks to kill vezax now due to this. Please fix this as soon as possible. 

If you have definitive knowledge an issue is going to be created when you fix something, just wait for both things to be fixed, please.

**Comment by Golganeth** [comment]
We'll revert the taunt immunity change as soon as possible, at least until the Mana Plea issue gets taken care of. 

@ashido96 If you encounter such issues please make sure to let us know as soon as possible. Waiting until someone reports the taunt immunity isn't a good option. 

Thank you for the reports

**Comment by Lothloryen** [comment]
Hello there,

This issue has been fully corrected - Divine Plea will now properly grant mana, as well as the Aspect of the Viper during the General Vezax encounter.

Thank you very much for the reports.

**Comment by Klala** [comment]
I have encountered a problem with Divine Plea and energy regeneration.
* If you pull Vezax with Divine Plea on you lose it.
* Energy regeneration from Combat Potency and Relentless Strikes do not proc. This might be the problem for rage and runic generating talents too.

I have not tested it myself but just in case it doesn't work: Fel Mana Potion, Dark Rune and Demonic Rune should all work.
You can view issue 4417 for more info.

**Comment by Rushor** [comment]
for anything related to mana problems with vezax, pls post it in https://github.com/dalaranwow/dalaran-wow/issues/4417
