### ISSUE TITLE
Formula: Runed Adamantite Rod

### ISSUE THREAD

**Issue by fakirakos** [dalaranwow/dalaran-wow#3459]
**Description**:

**Current behaviour**: Runed Adamantite Rod Formula is spawning very slowly
**Expected behaviour**: Recipe should spawn on a 15 mins respawn timer(changed from 24h on 3.0 release on retail)

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Include proofs for this behaviour**

http://www.wowhead.com/item=25848/formula-runed-adamantite-rod#comments:id=771704

**Comment by ImprezaWoW** [comment]
In [3.0 patch notes](http://us.battle.net/wow/en/game/patch-notes/3-0-0) I only see, quote "Several recipes in the 250-300 skill range have been rebalanced, and the reagent requirements have been reduced." The formula mentioned is of level 350. Overall I looked over patch notes from 2.0 to 3.3.5 and I did not find it mentioned anywhere about any respawn time reductions regarding this or any similar subjects. 
If WoWHead comments are to be trusted, you can also see a comment [saying that it's 24h respawn time](http://www.wowhead.com/item=25848/formula-runed-adamantite-rod#comments:id=310741:reply=353543).
If anyone can find any solid proof of the respawn time changing to 15 minutes, that would be great.

**Comment by fakirakos** [comment]
a comment from 2.4.3 while mine is from 3.1.3...how is it that u can use the comments from wowhead as proof but comments from wowhead cannot be used as proof by the rest?? especially comments that are outdated already

**Comment by ImprezaWoW** [comment]
First of all, someone who came to a vendor when the pattern coincidentally respawned is nowhere near enough proof that it has been changed. If I were to come to the vendor and it respawned in 2 minutes, so I could buy it and leave does not mean that the respawn timer is 2 minutes. 
Secondly, usually in WoWHead comments are downvoted when the information provided is innacurate and thus does not contribute at all. 
Moreover, I have linked patch notes from Retail which involves most of the details of any changes - anything at least slightly related to what you said is not in any changelog (unless I missed something, feel free to add then). 
Also, if you checked the duplicate reports, there are Developers saying the respawn time is 24 hours. I'm sure they don't take the timers out of their mind but they have some information on this. 
My WoWHead comment may not be proof (which in the same manner means yours isn't either, since not only it's the only comment saying that, but it also does not really make sense), but there are Developers who say it's 24 hours. 
All in all, please find any reliable sources if you feel like you are correct.

**Comment by fakirakos** [comment]
the only reason i even bothered to try and find proof is because i know for a fact that the cd was low since we used to camp it as a guild in retail...now the fact of the matter remains that if u even try to do the math 24h is impossible for servers with 10-20k active chars like large retail servers were in wrath....do w/e u want im done with this

**Comment by ImprezaWoW** [comment]
As I said, we will act accordingly when we get any actual proof of the respawn timer being different than now.

**Comment by sherndy** [comment]
https://www.wowhead.com/npc=19004/vodesiin#comments:id=913891
is this enough to make it BoP?

**Comment by MightyFlix** [comment]
Doesn't fucking matter how it was on retail if it's generating fucked up behavior on server now...
Shittiest way of handling this. You can talk about this shit when you get 1:1 retail scripting for everything else ¬¬".

**Comment by Chenocide** [comment]
If it was generating fucked up behavior on retail too, then that's the goal.

**Comment by MightyFlix** [comment]
> If it was generating fucked up behavior on retail too, then that's the goal.
Only for horde enchanters? OFC...

Update: Recipe doesn't have empty slot at seller inventory for horde characters anymore.

> First of all, someone who came to a vendor when the pattern coincidentally respawned is nowhere near enough proof that it has been changed. If I were to come to the vendor and it respawned in 2 minutes, so I could buy it and leave does not mean that the respawn timer is 2 minutes.
> Secondly, usually in WoWHead comments are downvoted when the information provided is innacurate and thus does not contribute at all.
> Moreover, I have linked patch notes from Retail which involves most of the details of any changes - anything at least slightly related to what you said is not in any changelog (unless I missed something, feel free to add then).
> Also, if you checked the duplicate reports, there are Developers saying the respawn time is 24 hours. I'm sure they don't take the timers out of their mind but they have some information on this.
> My WoWHead comment may not be proof (which in the same manner means yours isn't either, since not only it's the only comment saying that, but it also does not really make sense), but there are Developers who say it's 24 hours.
> All in all, please find any reliable sources if you feel like you are correct.

Would love to see "devs" relevant proof and info for this
