### ISSUE TITLE
[Quest] Flown the Coop!

### ISSUE THREAD

**Issue by ImprezaWoW** [dalaranwow/dalaran-wow#3466]
**Description**:

**Current behaviour**: 
The Chicken Escapees required for the quest are missing. (you can only see them as a GM)
**Expected behaviour**:
The chickens required for the quest should be seen and caught by players.
**Steps to reproduce the problem**:

1. Take the quest;
2. Search for chicken.

With GM character, you can try:

1. Finding chickens with GM mode;
2. Disable GM mode and watch the chickens disappear.

**Include proofs for this behaviour**

[Flown the Coop!](https://www.youtube.com/watch?v=iN8q-BY-iNY)

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

[Chicken Escapee](http://www.wowhead.com/npc=28161/chicken-escapee) ID 28161
[Flown the Coop!](http://www.wowhead.com/quest=12532/flown-the-coop) ID 12532
[Captured Chicken](http://www.wowhead.com/item=38483/captured-chicken) ID 38483

**Comment by Rushor** [comment]
70558e13b8f110d16e5600a8c7ef155b1d17e339

DB/Quest: Flown the Coop!

* chicken will now be visible during the quest

* closes https://github.com/dalaranwow/dalaran-wow/issues/3466

**Comment by Golganeth** [comment]
They are visible but they can't be picked nor stopped with Chicken Net.

**Comment by dalwow** [comment]
Quest is still bugged, you can't throw nets on nor catch the chickens.

**Comment by orgasmix** [comment]
Confirmed, still not working

**Comment by jonanone** [comment]
Clicking the chickens will give credit now and the net will trap them.
The fix will be applied to the live realm soon.

**Comment by Rushor** [comment]
DB/Quest: Flown the Coop! - Add instant despawn of Chicken Escapee (no longer exploitable spellclick)

* updates: https://github.com/dalaranwow/dalaran-wow/issues/3466
* commit: 8fda72da471164748e3bbf64b9efd70afda06563

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
