### ISSUE TITLE
[WG] NPCs: Arcanist Braedin & Magister Surdiel [32169 / 32170]

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#3477]
Magister Surdiel and Arcanist Braedin shouldn't yell asking for reinforcements after a Wintergrasp battle has ended (more specifically, they do that a few times: 2-5, 10, 15 & 20 minutes after a battle ends). 
They should only do that when a Wintergrasp battle is about to start (works).
The portal of them should only work during the wintergrasp wartime.

[**Arcanist Braedin**](http://wotlk.openwow.com/npc=32169) - _ID: 32169 - (Alliance)_
[**Magister Surdiel**](http://wotlk.openwow.com/npc=32170) - _ID: 32170 - (Horde)_

**Comment by Rushor** [comment]
Scripts/Dalaran: Arcanist Braedin & Magister Surdiel will now yell their texts only 5 minutes before the wartime and during the wartime (every 240 seconds)

* added one missing wintergasp portal
* Wintergrasp Portals will now only teleport the player if the wartime is active, the player is > level 74 and the team of the player is the defender team
* closes https://github.com/dalaranwow/dalaran-wow/issues/3477
* commit: 349e3af81ed5a3a59c9b12fbf6abfb97b0d958d5

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
Already fixed on PTR.
