### ISSUE TITLE
Cant Donate and Cant select Hero on Dalaran Site

### ISSUE THREAD

**Issue by thejokerd3** [dalaranwow/dalaran-wow#3482]
![adadad](https://cloud.githubusercontent.com/assets/20074364/16244026/58314b34-37fa-11e6-97a3-2a7851606db3.PNG)

I have 2 problems.

The first Problem is I cant Donate anymore to the website and get Donate points?! Its been blocked for a while and i dont know what the problem is. "Dear User,

The verification process we have in place is to combat fraudulent activity and to make sure there are no problems. We apologize for all the inconvenience this may have caused.

ID: 02#87094226"

The second problem is

I cant select a hero in the Dalaran Website. It says "No Character have been found"

Hope it can be fixed soon!

**Comment by Golganeth** [comment]
Invalid report, the bugtracker only lists in-game issues.

Your donation problem isn't related to Dalaran-WoW, so you will have to contact the Paymentwall Team in order to get it sorted out.

Currently you must create at least one character on Kirin Tor and select it as your main character. Website is under heavy rework and it's not synced with Algalon yet. We apologize for the inconvenience.

Closed.
