### ISSUE TITLE
Restoration Druid Clearcasting is not working properly

### ISSUE THREAD

**Issue by Ryladen** [dalaranwow/dalaran-wow#3486]
**Description**: Clearcasting is triggered by more spells than it should be

**Current behaviour**: Using spells like Track Mines, Track Herbs etc. triggers Clearcasting, which is a huge advantage when made a macro that uses track herbs with everything (for example) (Where, When, What, Why, Who)

**Expected behaviour**: Spells like track mines, track herbs that doesn't require mana and doesn't trigger global cooldown shouldn't trigger Clearcasting

**Steps to reproduce the problem**:

1. These spells could be removed from the list that triggers clearcasting
2. These spells could trigger global cd so that it doesn't matter

**Comment by Rushor** [comment]
http://www.wowhead.com/spell=16864/omen-of-clarity#comments:id=1099753

Oddly enough, this actually procced for me when I changed spec (with dual spec). =P

http://www.wowhead.com/spell=16864/omen-of-clarity#comments:id=867604
As people have mentioned, this (and other "on spell cast" procs) will proc off of professions, talent switches, and other non-combat abilities. It does this because everything in wow that has a cast time (and a few things that don't) is considered a spell, as an example, look up a craftable item on here, go to its info page, and then click on the name of the item (not the icon), and you'll end up on the page for the spell that creates that item.

proof that it should proc on serveral general things

**Comment by Rushor** [comment]
if you find a proof for your decribed behaviour, just add a proof :)
