### ISSUE TITLE
Steady shot Bug

### ISSUE THREAD

**Issue by danysilva** [dalaranwow/dalaran-wow#3488]
Steady shot wrong damage stack from heirloom gun.

I have been notice that my dps is low with my hunter, so i been checking that my steady shot does not stack with my heirloom gun neither the Ranged haste Rating enchant..

Steady shot damage = 358 + (32)ammo + (186-346) unmodified  weapon= 576-736,

![steadyshot](https://cloud.githubusercontent.com/assets/20100435/16288681/daf38a88-38ee-11e6-93fe-3eba95f02707.png)
![gun](https://cloud.githubusercontent.com/assets/20100435/16288688/e69e938c-38ee-11e6-83af-beb0c902fa64.png)
![damage](https://cloud.githubusercontent.com/assets/20100435/16288720/46b07042-38ef-11e6-9ea9-967ce4cd9d95.png)

**Comment by RazerStylehunter** [comment]
1. Hunter's base 15% haste is not correctly applied to steady shot, so any additional haste on the hunter will never make the steady shot cast time correct, see #3262
2. The range heirloom weapon dmg seems to be calculated using the dmg from the level 1 weapon instead of the current level of the hunter, see #2427

**Comment by Rushor** [comment]
so duplicate, ty @RazerStylehunter
