### ISSUE TITLE
[Quest]What the Cold Wind Brings...

### ISSUE THREAD

**Issue by Mazz312** [dalaranwow/dalaran-wow#3492]
**Description**: There should be an event run on a set timer (30/45 minutes) which spawns several Nerub'ar waves including a named mob. The named mob when killed should drop an item that can be turned in for a quest.

**Current behaviour**: As far as I've seen, this event does not run on this server at all.

**Expected behaviour**: The event starts every 30/45 minutes with the Warsong Captain [npc=25446] yelling an specific emote. The event should consist of several waves of Nerub'ar ending with a named mob Ith'rix the Harvester [npc=25453], who when tagged and killed should drop Ith'rix's Hardened Carapace [item=34777].

**Include proofs for this behaviour**

http://wowwiki.wikia.com/wiki/Quest:What_the_Cold_Wind_Brings... (add ... to the end of the link)
http://www.wowhead.com/quest=11632/what-the-cold-wind-brings

Unfortunately I have no video of the event nor do I know where to find the full event information from the game files.

IDs:
Quest = 11632
Warsong Captain = 25446
Ith'rix the Harvester = 25453
Ith'rix's Hardened Carapace= 34777

**Comment by jonanone** [comment]
A first version of this event has been implemented. It may require some tweaks so I will let the issue open for future reference.

The updates will be applied to the live realm soon.

**Comment by Rushor** [comment]
DB/Quests/Borean Tundra: What the Cold Wind Brings...

The event has been fully scripted:
- Every 30 mins the event will start.
- There are several waves of adds every 30 secs. (18 waves at the moment)
- 10 minutes later the boss will be summoned.
- Once killed, the carapace will appear.
- commit: 8b43d6672de7bf44ffb3bd88fcad89f622e76be5

Closes https://github.com/dalaranwow/dalaran-wow/issues/3492

Card was already moved to "Quest/general fixed 100%"

**Comment by Rushor** [comment]
an other issue: 25451 - should be able to fly around. currently they cannot do that

**Comment by Rushor** [comment]
DB/Creature: Enable fly animation for Nerub'ar Sky Darkener

* updates: https://github.com/dalaranwow/dalaran-wow/issues/3492
* commit: 884a229b578904ee396bf9435b15b9f24d0881ba

**Comment by TeridanDW** [comment]
Hello, just tested this event and i saw few issues that can be improved:
 - npc http://wotlk.openwow.com/npc=25446 should riding a wolf and "spamming" his healing spells more
 - no extra soldiers http://wotlk.openwow.com/npc=25244 are spawned at the begining for the event
 - the adds that spawn during the event should come from the tower infront, instead they spawn directly over the soldiers
 - there is mini event after Ith'rix dies and the gameobject spawns, which is missing because of 2-nd issue

Reference from retail legion:
https://www.youtube.com/watch?v=mGb7lHRbbV4&feature=youtu.be
