### ISSUE TITLE
[Quest][Northrend] Bug on Frenzyheart/Oracle Quest Line

### ISSUE THREAD

**Issue by lencabral** [dalaranwow/dalaran-wow#3507]
I experienced a bug while completing the level 77 quest "Just Following Orders." The game continued me on the quest line ,but it never registered me as having completed the quest. As such I never received the aura to switch my reputation with the Oracles to friendly.  I cannot speak with the Oracles and have no way to compete the quest or complete the achievement "Into the Basin." I believe this bug was caused by a server crash.I worked with the GM 'Norganon' who told me a GM would fix my rep.

The quest "Just Following Orders" is supposed to apply an aura that switches my reputation to hated with the Frenzyheart and Friendly with the Oracles. In order to hand in "Fortunate Misunderstandings," I need to speak to High Oracle Soo-say in Sholazar Basin, but I cannot speak with him because I am still hated with the Oracles.

Hopefully, you can see the situation in the below screenshot.

http://imgur.com/CesmJqR

As you can see on the wowhead page below, the quest is supposed to supply an aura that changes your reputation, but that never happened for me.
http://www.wowhead.com/quest=12540/just-following-orders

My in-game name is 'Lencabral.' Thanks.

**Comment by alexuktc** [comment]
The whole thing is messed up. I had no issue like yours and got to exalted with The Oracles with no issues. However when I got the green Proto Drake and decided to switch to Frenzyheart for the "Mercenary of Sholazar" achievement I went into the cave, did the lich quest properly and even though I am honored with Frenzyheart I do not have daily quests to further increase my reputation.

As far as I know no one has this achievement on this server.

**Comment by alexuktc** [comment]
**Current behaviour: Tell us what happens in detail (Where, When, What, Why, Who)**
The easiest way is to explain what my experience has been. I have been exalted with The Oracles for over 10 months, getting an egg on cooldown. I got the Green Proto Drake so I decided to change to Frenzyheart and get the Mercenary of Sholazar Achievement. I did the Champion of Frenzyheart quest, which requires me to 
![bugg](https://cloud.githubusercontent.com/assets/24550199/22344063/4289391c-e403-11e6-9f4e-457812ea4f63.png)
go kill Artius (the lich in the cave) and kill The Oracles npc. I correctly got the quest and it set me to Honored. I went to the Frenzyheart hub. They are friendly, but do not offer daily quests. Also any frenzyheart mobs outside of that hub are hostile. The oracles are hostile towards me but I cannot put "At War" with them on my reputation panel, meaning that even if I get my dailies working I will only be able to damage them with AoE (non targeted spells).

**Expected behaviour: Tell us what should happen instead**
Once I have completed the Champion of Frenzyheart Quest I have to be honored with them and I should have access to their daily quests. I should also be friendly to the mobs outside of the main faction hub and I should be able to attack mobs from The Oracles normally.

**Steps to reproduce the problem:**

1.  Get a reputation with one of the factions.
2. Try to change the reputation
3. See that you are not able to attack the other faction properly, you are not allied with all the mobs from that faction and that you are not given dailies.

**Include proofs for this behaviour**
I am more than happy to talk to a GM in game and show him proof of what I am posting here. I actually made a ticket and was told I have not read properly, which I assure you is not correct. Contact Alekk in-game if you need further proof.

http://www.wowhead.com/achievement=952/mercenary-of-sholazar#comments - Comments about how it's done on retail, including guides should it "bugg". I have done all that and nothing. Plus it does not apply as I am doing this on WotlK and cannot one shot the lich nor the other 2 npcs.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Jaloot (The Oracles nps) - 28667
Zepik the Gorloc Hunter (Frenzyheart npc) - 28668

I don't believe I can include the IDs for the entire factions' npcs.

https://www.youtube.com/watch?v=JrIbqsJCylY - Pretty much a video of what I did.

**Include Screenshots from the issue if necessary**
You can clearly see that I have the reputation needed with them and that since I am at 1/12000 I have not actually completed any dailies yet. I have the "Low Quest" tracking so there is no way I am not seeing them on the map.

**Comment by fisguinho** [comment]
I'm also suffering from this problem where i changed from oracles to frenzyheart and it simply doesnt give me the dailies, the rep changed but the quests simply dont ever pop

**Comment by Cone182** [comment]
same issue for me too :/

**Comment by Rushor** [comment]
Game/ReputationMgr: Add SetAtWar Exceptions for Frenzyheart Tribe + The Oracles

* updates: https://github.com/dalaranwow/dalaran-wow/issues/3507
* commit: d5494e61a43faf3e9fd875014229cd806dbf24e1

This fixes this issue on PTR https://github.com/dalaranwow/dalaran-wow/issues/697 (it was not fixed on PTR yet)

**Comment by Rushor** [comment]
DB/Quest: Sholazar Basin: Oracles/Frenzyheart switch-quest can now be done multiple times

* updates: https://github.com/dalaranwow/dalaran-wow/issues/3507
* commit: 2add1146b211b0e15ed3668879973246ce08d22f

**Comment by Rushor** [comment]
Okay tested this with the two fixes. 

First of all i completed all quests mentioned here http://www.wowhead.com/quest=12581/a-heros-burden#comments:id=737429

Then i tried to change the faction and killed http://wotlk.openwow.com/npc=28659 again. Then i accepted/completed http://wotlk.openwow.com/quest=12582 and was able to take the quests from the Frenzyhearts and i was able to kill the Orcales.

![wow_2017-03-11_11-56-17](https://cloud.githubusercontent.com/assets/5568820/23822678/fda66dda-0651-11e7-848d-b4dfebb62ab1.png)
![wow_2017-03-11_11-56-50](https://cloud.githubusercontent.com/assets/5568820/23822679/033302cc-0652-11e7-8c01-f1b01e5581e3.png)
![wow_2017-03-11_12-06-30](https://cloud.githubusercontent.com/assets/5568820/23822738/3497e11a-0653-11e7-9104-0c677fc1617f.png)

The next day (i simulated the next day by deleting the daily quest save from my character) i decided to take the faction from the oracles. I killed http://wotlk.openwow.com/npc=28659 again and took the quest: http://wotlk.openwow.com/quest=12689. I was then able to take the dailies from the oracles as well as killing the Frenzyhearts.

![wow_2017-03-11_12-07-29](https://cloud.githubusercontent.com/assets/5568820/23822761/b57b1978-0653-11e7-82bb-1f313a2e3303.png)
![wow_2017-03-11_12-08-30](https://cloud.githubusercontent.com/assets/5568820/23822762/b731e666-0653-11e7-80f5-bcba472f8987.png)
![Uploading Wow_2017-03-11_12-09-18.png…]()

Those 2 commits should fix the issue reatled to accepting the quests/killing the other faction.

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by alexuktc** [comment]
Hello. 

Updating on this. A GM added the missing quest for me so I was able to start the quests for rep with the Frenzyheart. So far all is working properly expect that the Frenzyheart outside of the main hub are still aggressive towards me. A minor issue, seeing how I can properly attack the oracles now and all NPCs related to completing the quests are working properly. 

Great job so far, the 3 quests I tested were:
1. The one with the chickens - definitely doable without issues. As a matter of fact if you're mounted and you net the chicken you can click on it multiple times. I used a single chicken to complete the quest.
2. The one to get some blood thingy and use a Frenzyheart to kill 50 Oracles - I did not see the quest item in my 50 kills but that is irrelevant.
3. The quest to get the water from the Pillar and then kill the big white bird - no issues there.

**Comment by Teridan-dal-wow** [comment]
Regarding:

> The one with the chickens - definitely doable without issues. As a matter of fact if you're mounted and you net the chicken you can click on it multiple times. I used a single chicken to complete the quest.

I remember that quest from retail and keep a lot of "hate" towards it still. Everytime i thowed the net the ******* chickens runned away, that has some really strange movement, its not random or waypoint for sure, and you can chase 1 for a long time/distance.

**Comment by Rushor** [comment]
chicken party was fixed here https://github.com/dalaranwow/dalaran-wow/issues/3466. however the fix still does not fix all the exploits. i will rework it.

**Comment by alexuktc** [comment]
I got Chicken Party again today, so no changes there.
I also got Strength of the Tempest - works exactly as described in WoWHead. 
Tools of War - I did not test the traps as I was able to just walk up to them and kill them. Good enough for me. I'll test next time I get the quest (although that is a time loss for me).

**Comment by Rushor** [comment]
> its not random or waypoint for sure

yep it's fear movement, they have a fear aura for some seconds and round around like.. yeah crazy chicken xd

**Comment by alexuktc** [comment]
New quests today - 
Rejek: First Blood - Works normally.
Secret Strength of the Frenzyheart - easily completable. The only point I can give is that the drink is supposed to reduce the damage you take by 50% and it does not reduce anything. 
http://www.wowhead.com/spell=53355/strength-of-the-frenzyheart 

No issues otherwise. 1 Quest left to check - Hero's Headgear. Let's hope it comes tomorrow.

**Comment by alexuktc** [comment]
Last update - Hero's Headgear works as intended.

**Comment by Craftymind** [comment]
Hello,

I just finished the chain quests to unlock the Oracles reputation dailies, up to the quest "Hand of the Oracles" ( http://www.wowhead.com/quest=12689/hand-of-the-oracles ). But the NPC Jaloot ( http://www.wowhead.com/npc=28667/jaloot ) doesn't give me the last quest "Return of the Friendly Dryskin" ( http://www.wowhead.com/quest=12695/return-of-the-friendly-dryskin ) to return to Rainspeaker Canopy and unlock the dailies.

Here is a screenshot showing my reputation status and me completing the 1st mentioned quest and showing the bug:
![wowscrnshot_040517_141939](https://cloud.githubusercontent.com/assets/19840534/24708621/50c2d5c8-1a0f-11e7-815d-59588cac3078.jpg)

**Comment by TeridanDW** [comment]
> The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
> This means that the issue exists in game at the moment i wrote this message.
> Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
> Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Craftymind** [comment]
Also, the 1st quest mentioned ( http://www.wowhead.com/quest=12689/hand-of-the-oracles ) seems to have not registered as completed: 
![wowscrnshot_040517_154518](https://cloud.githubusercontent.com/assets/19840534/24711301/70aa514c-1a17-11e7-952c-b3e04c199de9.jpg)

**Comment by TeridanDW** [comment]
@Rushor could you add 1 more missing element please.
 - Npc http://www.wowhead.com/npc=28668/zepik-the-gorloc-hunter and http://www.wowhead.com/npc=28667/jaloot are suppose to spawn together with npc http://www.wowhead.com/npc=28659/artruis-the-heartless and not 1 by 1 (depending on their respawn timer).

Possible solution might be add a linked spawn for these 3 creatures based on when artruis spawns and increase the respawn timer of the ofter 2 so they don't spawn on their own.

This issue was reported by @Craftymind in #4660

**Comment by TeridanDW** [comment]
Hm also there seems to be an issue with:

> Game/ReputationMgr: Add SetAtWar Exceptions for Frenzyheart Tribe + The Oracles

and

> DB/Quest: Sholazar Basin: Oracles/Frenzyheart switch-quest can now be done multiple times

so reopening until a solution is found.

**Comment by Lothloryen** [comment]
Hello there,

This issue should be corrected after the next realm restart, players should be able to pick either Return of the Friendly Dryskin or Return of the Lich Hunter with no issues now.

Thank you.
