### ISSUE TITLE
Quest: Steamtank Surprise

### ISSUE THREAD

**Issue by domy20** [dalaranwow/dalaran-wow#351]
Hello

http://www.wowhead.com/quest=12326

In quest i need to enter steamtank to sabotage plagued wagon's and escort some npc,but problem is i cant enter it,if i come close to npc or click on him doesnt work,neither i can manually kill wagons.

**Comment by catta000** [comment]
Quest is working, needed a few tries for the drop off gnome to work.. however I was attacked by the tank when i left it and had to relog..

**Comment by roots84** [comment]
Quest is working but has a few flaws (and advantages?)
1. Dropping of gnomes doesn't always work.
2. Steamtank will attack you once you get out of it. It is still possible to get back in and drive it though.
3. Ice prison won't affect surrounding mobs every time.
4. Steamtank can leave the area it should be usable in. You can basically drive it anywhere in Northrend (didn't try to get over to Kalimdor / Eastern Kingdoms but it probably works too) and kill mobs with it. Mobs will count towards quest kills and will be lootable if attack by a player of the group before killing them with the steamtank. Additionally you can kill Horde players will it. As long as you keep the quest in your Questlog you can do this infinite times.
5. You can jump from Steamtank to Steamtank in the spawn area and they will all follow you everywhere in Northend and attack you. Probably leaves no Steamtanks behind for other players to do the quest. And you have 8 Steamtanks you can use as they will remain mountable even if they attack you.

**Comment by sklivvz** [comment]
More flaws you might need to know about:

1. Sometime tanks won't drop the engineer. More "tries" won't help at all. Try changing the tank, but you probably need a server restart. It's as if a tank won't work anymore once a player finishes the quest with it.
2. If you finish the quest but do not turn it in, once you hop off the tank you won't be able to target or hop back on it. This seems unimportant, until you realize that you can drive the tank very far away from the camp, for example to kill elites, and that the tank will attack you once you are off it. If this happens, kill the client (alt-f4) -- the tank will de-target you and go back to the quest-giver.

**Comment by Rushor** [comment]
DB/Quest: Steamtank Surprise

* closes https://github.com/dalaranwow/dalaran-wow/issues/351
* commit:
ea903077991aa2e5921aad56c39946d75986b94c
e6d0980ff7d9418a646134b02f2357f7dd574075
1532bf12d2dd036e890df61b268be76cc1089288
* Steamtank will no longer attack you once you leaved the vehicle
* Steamtank will despawn if you leave the area
* Steamtank's ability ice prison from ice cannon will always work propperly and increase it's damage against frozen targets

**Comment by TeridanDW** [comment]
Quest works almost perfectly, few small details that i noticed:
 - npc http://wotlk.openwow.com/npc=27163 should be passive, civilian (currently he targets the skeleons nearby)
 - enemy creatures attack the player instead of the vehicle and it's possible that the player can die before the vehicle (which is incorrect)
 - Steamtank still attacks the player if he leaves it (regardless if that was done in combat or out of)
 - Zone condition for the Steamtank isn't working also (player can take the vehicle out of the area which is wrong)
  - when player uses spell http://wotlk.openwow.com/spell=49081 the 2 soldiers and the engineer should be dismounted from the tank, the tank should despawn and the soldiers run inside the mausoleum and despawn (currently nothing of that happens, player just gets credit)
 - spell http://wotlk.openwow.com/spell=49109 is missing a condition, it should be useable only if there is npc http://wotlk.openwow.com/npc=27607 near the player, and if there isn't it should get error and not go on cooldown.
