### ISSUE TITLE
[Aura] Ahune - Summoning Rhyme

### ISSUE THREAD

**Issue by sixele** [dalaranwow/dalaran-wow#3512]
**Description**:
The Summoning Rhyme Aura is not hidden, and the player who completes the quest "Summon Ahune" in the dungeon can see the aura on him among the buffs.
**Current behaviour**: 
The aura is not hidden.
**Expected behaviour**: 
The aura should be hidden.
**Steps to reproduce the problem**:
1. Go to Slave Pens Ahune event through RDF;
2. Complete the dungeon daily to summon Ahune;
3. Check buffs.

**Include proofs for this behaviour**
http://www.wowhead.com/spell=45926/ahune-summoning-rhyme-aura - says "cast time is hidden".

http://wotlk.openwow.com/spell=45926 - says it's rewarded from the daily, and that's true.
**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
[Ahune - Summoning Rhyme Aura](http://www.wowhead.com/spell=45926/ahune-summoning-rhyme-aura) ID 45926

**Include Screenshots from the issue if necessary**
http://imgur.com/y4vYAvJ , http://imgur.com/a/b9FfC - how it currently is in Algalon.

**Comment by Rushor** [comment]
Game/Spells: Ahune - Summoning Rhyme Aura - should not be visible in aura bar

* closes: https://github.com/dalaranwow/dalaran-wow/issues/3512
* commit: ecf09c4752755d7776575c7bf90581febeb8c8fe

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
