### ISSUE TITLE
[NPC] Byancie - Wromng Gossip

### ISSUE THREAD

**Issue by ImprezaWoW** [dalaranwow/dalaran-wow#3514]
**Description**:
Minor issue, when opening the dialogue window of [Byancie the First Aid trainer](http://wowwiki.wikia.com/wiki/Byancie), you see Nissa, so the text has the wrong NPC. Might be related to [Nissa, First Aid trainer in Ironforge](http://wowwiki.wikia.com/wiki/Nissa_Firestone)
**Current behaviour**:
The button in the dialogue window says "I require training, Nissa."
**Expected behaviour**: Tell us what should happen instead
most likely should be "I require training, Byancie."
**Steps to reproduce the problem**:
1. Go to Donalaar;
2. Open dialogue window with Byancie.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Byancie NPC ID 6094

**Include Screenshots from the issue if necessary**
http://imgur.com/25HPcrZ

**Comment by Rushor** [comment]
DB/Creature: Byancie - Update gossipmenu

* closes https://github.com/dalaranwow/dalaran-wow/issues/3514
* commit: 8497e43fbcdabbede3522959b4441809f712df1a

![GitHub Logo](http://i.imgur.com/zErCNes.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
