### ISSUE TITLE
[Event] Feralas Alliance Bonfire

### ISSUE THREAD

**Issue by ImprezaWoW** [dalaranwow/dalaran-wow#3517]
**Description**:
Currently there is one place which could be called an abandoned bonfire place, which confuses a lot of players thinking that the Alliance bonfire in Feralas is bugged, since it has no NPCs.

**Current behavior**: 
There's an abandoned Alliance bonfire next to Feathermoon Stronghold (at around 28;43) without NPCs. And one with NPCs at the Forgotten Coast (around 46;44)

**Expected behavior**: _(Edited)_:
The one in Forgotten Coast should be completely removed and the NPCs should be moved to the Feathermoon Stronghold bonfire.

Feathermoon Stronghold was moved there in Cataclysm, which is why the coords changed on some sites such as wowwiki or wowhead.
![image](https://cloud.githubusercontent.com/assets/5057942/16414940/f951b8c4-3d3a-11e6-91dc-7516348201c1.png)

[Desecrate This Fire! (_Feralas_)](http://www.wowhead.com/quest=11746/desecrate-this-fire#comments) - See comments from 3.3.x or older.

Also, the Ribbon Pole is missing

**Comment by Golganeth** [comment]
No, the one in Forgotten Coast should be completely removed and the NPCs moved to Feathermoon Stronghold.

Feathermoon Stronghold was moved there in Cataclysm, which is why the coords changed on some sites such as wowwiki or wowhead.
![image](https://cloud.githubusercontent.com/assets/5057942/16414940/f951b8c4-3d3a-11e6-91dc-7516348201c1.png)


[Desecrate This Fire! (*Feralas*)](http://www.wowhead.com/quest=11746/desecrate-this-fire#comments) - See comments from 3.3.x or older.

[WoTLK Reference 1m47s](https://www.youtube.com/watch?v=9L4kUspvFBY&t=1m47s)

**Comment by ImprezaWoW** [comment]
My bad then.:(  Nonetheless, one of the two bonfire locations is unneeded, then.

**Comment by Rushor** [comment]
DB/Gameobject: Midsummer Fire Festival - Move creatures and gameobjects from Forgotten Coast to Feathermoon Stronghold

* closes https://github.com/dalaranwow/dalaran-wow/issues/3517
* commit: 4640b6d22d504fd1507749338b0daa3690c82212

![GitHub Logo](http://i.imgur.com/xiCvfJ0.jpg)
![GitHub Logo](http://i.imgur.com/xiCvfJ0.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
