### ISSUE TITLE
"Weakness to Lightning" Quest

### ISSUE THREAD

**Issue by Sigh719** [dalaranwow/dalaran-wow#3524]
**Description**:
Can not complete this quest

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Can not get credit for killing mobs with debuff needed to complete quest.

**Expected behaviour**: Tell us what should happen instead
Should get credit from killing mobs with debuff

**Steps to reproduce the problem**:

1. Accept quest
2. blast mobs with lightning rod
3. kill mob

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

http://www.wowhead.com/quest=11896/weakness-to-lightning

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Golganeth** [comment]
Tested and the quest itself works fine. I'm pretty sure you're playing a class with pet (Death Knight, Hunter, Warlock) and it's related to #1048 (the report mentions that quest).

Closed since it's a general issue but the quest works fine. Make sure to deal enough damage, as well as first and last hit to the creatures.

**Comment by ashido96** [comment]
Hit mobs with lightning rod, kill mob, no credit given, feral druid.
