### ISSUE TITLE
[Item] Preserved Holly

### ISSUE THREAD

**Issue by sixele** [dalaranwow/dalaran-wow#3529]
**Description**:
Didn't find this in the Bug Tracker yet. 
Visual bug when using the item Preserved Holly again after you already have the 60m buff on you.
**Current behaviour**: 
When you use the item Preserved Holly twice (i.e. second time after you gain the Festive Holiday Mount buff), you dismount(at least visually), but remain with the speed boost as if you were mounted. From the side, looks like speedhacking because you're running around with 100% speed boost (tried it with 100% ground mount). Even with the visual bug in theory you still remain mounted - the running speed boost falls off when you enter a building (i.e. dismount) or do actions which normally dismount you. If you do not have auto-dismount when casting spells, it will not let you cast the spell saying "You are mounted."
**Expected behaviour**: Tell us what should happen instead
Most likely if you already have the Festive Holiday Mount buff, the buff duration should renew and that's pretty much it.
**Steps to reproduce the problem**:
1. Mount up;
2. Use the item Preserved Holly;
3. Use the item Preserved Holly again.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

[Preserved Holly](http://www.wowhead.com/item=21213/preserved-holly) ID 21213
[Festive Holiday Mount](http://www.wowhead.com/spell=62061/festive-holiday-mount) ID 62061

**Comment by Rushor** [comment]
DB/Spell: Winter Veil - Casting Preserved Holly will no longer dismount the player before spellcast if the player already has the Preserved Holly aura

* closes https://github.com/dalaranwow/dalaran-wow/issues/3529
* commit: 70ec81e1c297e97bafdf7acbcdbc95b5a317c9b4

![GitHub Logo](http://i.imgur.com/7iYnXlU.jpg)
![GitHub Logo](http://i.imgur.com/IdqLA61.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
