### ISSUE TITLE
[ToC] Northrend Beasts - Snobold Vassal

### ISSUE THREAD

**Issue by Winstrol** [dalaranwow/dalaran-wow#3544]
Current behaviour: They are able to be targeted with aoe spells

Expected behaviour: aoe shouldn't damage them

Steps to reproduce the problem:
aoe them

Include proofs for this behaviour

We were having trouble downing these in 10m heroic tonight. I checked recount and notice that no AOE hits them. Living Bomb's DOT tick hits them but the explosion doesn't appear to do any damage. Blizzard, Flamestrike and Arcane Explosion all did 0 damage to them.

You may "cleave" OFF of them, but not onto them. That goes for normal AoE as well.
http://www.wowhead.com/npc=34800/snobold-vassal#comments

can clearly see them not being aoed down
https://youtu.be/wvrCIwnS154?t=1m17s

you can see divine storm doesnt hit multiple targets on combat text
https://youtu.be/oEcCItDmIz0?t=1m45s

**Comment by Lothloryen** [comment]
Hello Winstrol,

Thank you very much for the report, have this happened before? (I rewrote the Snobold system this last week but, as I can see no change should generate this issue).

Really appreciated.

**Comment by Winstrol** [comment]
as far as i know this has been an issue since the release of toc, and was still and issue last sunday when we did our main raid.

**Comment by Lothloryen** [comment]
Hello again,

Thank you, I shall take a look into it.

**Comment by ashido96** [comment]
current and expected behavior should be swapped in the original post?

**Comment by Winstrol** [comment]
no

**Comment by LoveDalaranWow** [comment]
Speaking of snowblolds, sometimes, either during the fight after Gormok is dead or after a wipe, it might happen that an "invisible" snowbold keeps chasing someone, sometimes bugging out the instance (either impossible to enter or in need of a reset of the instance to fix it), other times bugging out only the former guy who got targeted even in later tries. I noticed that this happens sometimes when people have to use some invulnerability spell (ice block, hand of protection), so it might be related to that, but again sometimes it happens after a wipe without using those spells.

**Comment by Rushor** [comment]
Scripts/TrialOfTheCrusader: Make Snobold Vassal immune against SPELL_EFFECT_PERSISTENT_AREA_AURA

* closes https://github.com/dalaranwow/dalaran-wow/issues/3544
* commit: 4051b002bc6dff33604977664287faadca711074

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
