### ISSUE TITLE
Fury Warrior Titans Grip fix

### ISSUE THREAD

**Issue by Sayzeee** [dalaranwow/dalaran-wow#3546]
**Description**: The damage reduction on Fury warriors doesnt seem to scale correctly or match up

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Bloodthirsts that used to hit for 9-10k hit for around 7-8k 
DPS used to be around 7-8k and now I struggle to hit 6k from a supposedly 10 percent damage reduction on Titans Grip

**Expected behaviour**: Tell us what should happen instead
I dont believe that the 10 percent damage reduction scales correctly. It doesnt make sense that just this reduction can have such a large impact on the warrior dps

**Steps to reproduce the problem**:

1. Check and correct if the damage reduction was placed correctly
2. 
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by robinsch** [comment]
It reduces the damage from following spells after scaling, since you provided no proof (just saying that you are lacking DPS is not a legit proof, do some research.)

+ 78 - Heroic Strike (Rank 1)
+ 284 - Heroic Strike (Rank 2)
+ 285 - Heroic Strike (Rank 3)
+ 694 - Mocking Blow
+ 772 - Rend (Rank 1)
+ 845 - Cleave (Rank 1)
+ 1464 - Slam (Rank 1)
+ 1608 - Heroic Strike (Rank 4)
+ 1680 - Whirlwind
+ 5308 - Execute (Rank 1)
+ 6546 - Rend (Rank 2)
+ 6547 - Rend (Rank 3)
+ 6548 - Rend (Rank 4)
+ 6572 - Revenge (Rank 1)
+ 6574 - Revenge (Rank 2)
+ 7369 - Cleave (Rank 2)
+ 7379 - Revenge (Rank 3)
+ 7384 - Overpower
- 7400 - Mocking Blow (Rank 2)
- 7402 - Mocking Blow (Rank 3)
- 7887 - Overpower (Rank 2)
+ 8820 - Slam (Rank 2)
+ 11564 - Heroic Strike (Rank 5)
+ 11565 - Heroic Strike (Rank 6)
+ 11566 - Heroic Strike (Rank 7)
+ 11567 - Heroic Strike (Rank 8)
+ 11572 - Rend (Rank 5)
+ 11573 - Rend (Rank 6)
+ 11574 - Rend (Rank 7)
- 11584 - Overpower (Rank 3)
- 11585 - Overpower (Rank 4)
+ 11600 - Revenge (Rank 4)
+ 11601 - Revenge (Rank 5)
+ 11604 - Slam (Rank 3)
+ 11605 - Slam (Rank 4)
+ 11608 - Cleave (Rank 3)
+ 11609 - Cleave (Rank 4)
+ 12294 - Mortal Strike (Rank 1)
+ 12809 - Concussion Blow
- 14895 - Overpower
- 17198 - Overpower
+ 20243 - Devastate (Rank 1)
- 20559 - Mocking Blow (Rank 4)
- 20560 - Mocking Blow (Rank 5)
+ 20569 - Cleave (Rank 5)
+ 20647 - Execute
+ 20658 - Execute (Rank 2)
+ 20660 - Execute (Rank 3)
+ 20661 - Execute (Rank 4)
+ 20662 - Execute (Rank 5)
- 21008 - Mocking Blow
+ 21551 - Mortal Strike (Rank 2)
+ 21552 - Mortal Strike (Rank 3)
+ 21553 - Mortal Strike (Rank 4)
- 22427 - Concussion Blow
- 23848 - Test Strike W50 (Rank 4)
- 23850 - Test Strike W35 (Rank 4)
+ 23881 - Bloodthirst
- 23892 - Bloodthirst (Rank 2)
- 23893 - Bloodthirst (Rank 3)
- 23894 - Bloodthirst (Rank 4)
- 24393 - Test Strike
- 24407 - Overpower
- 24816 - Test Mortal Strike (Rank 4)
- 24817 - Test Overpower (Rank 4)
+ 25208 - Rend (Rank 8)
+ 25231 - Cleave (Rank 6)
+ 25234 - Execute (Rank 6)
+ 25236 - Execute (Rank 7)
+ 25241 - Slam (Rank 5)
+ 25242 - Slam (Rank 6)
+ 25248 - Mortal Strike (Rank 5)
- 25251 - Bloodthirst (Rank 5)
- 25266 - Mocking Blow (Rank 6)
+ 25269 - Revenge (Rank 7)
+ 25286 - Heroic Strike (Rank 9)
+ 25288 - Revenge (Rank 6)
- 25710 - Heroic Strike
- 25712 - Heroic Strike (Rank 3)
- 27580 - Mortal Strike (Rank 4)
- 29426 - Heroic Strike
- 29567 - Heroic Strike
+ 29707 - Heroic Strike (Rank 10)
+ 30016 - Devastate (Rank 2)
+ 30022 - Devastate (Rank 3)
+ 30213 - Cleave (Rank 1)
+ 30219 - Cleave (Rank 2)
+ 30223 - Cleave (Rank 3)
+ 30324 - Heroic Strike (Rank 11)
+ 30330 - Mortal Strike (Rank 6)
- 30335 - Bloodthirst (Rank 6)
+ 30357 - Revenge (Rank 8)
- 31827 - Heroic Strike
- 32154 - Overpower
- 32588 - Concussion Blow
+ 34428 - Victory Rush
- 37321 - Overpower
- 41182 - Concussive Throw
- 41975 - Heroic Strike
- 43456 - Overpower
- 44268 - Mortal Strike
- 44949 - Whirlwind
- 45026 - Heroic Strike
+ 46845 - Rend (Rank 9)
+ 46924 - Bladestorm
+ 47449 - Heroic Strike (Rank 12)
+ 47450 - Heroic Strike (Rank 13)
+ 47465 - Rend (Rank 10)
+ 47470 - Execute (Rank 8)
+ 47471 - Execute (Rank 9)
+ 47474 - Slam (Rank 7)
+ 47475 - Slam (Rank 8)
+ 47485 - Mortal Strike (Rank 7)
+ 47486 - Mortal Strike (Rank 8)
+ 47497 - Devastate (Rank 4)
+ 47498 - Devastate (Rank 5)
- 47504 - Mocking Blow (Rank 7)
+ 47519 - Cleave (Rank 7)
+ 47520 - Cleave (Rank 8)
+ 47994 - Cleave (Rank 4)
- 50169 - Flipper Thwack
- 50622 - Whirlwind
- 50782 - Slam
- 50783 - Slam
- 52221 - Heroic Strike
- 52719 - Concussion Blow
- 56513 - Jormungar Strike
+ 57755 - Heroic Throw
+ 57823 - Revenge (Rank 9)
- 57846 - Heroic Strike
- 59607 - Heroic Strike
- 69566 - Heroic Strike
