### ISSUE TITLE
[Quest][Outland] Teron Gorefiend, I am...

### ISSUE THREAD

**Issue by MrAndersonX** [dalaranwow/dalaran-wow#3561]
**Description**:
The finishing quest for a nice and long quest chain line.
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
I started the quest, got transformed into Teron Gorefiend, but the mob/npc I was supposed to kill didn't spawn. Also, my controlled npc died, and the quest giver doesn't show up anymore.
The quest giver showed up again, tho after a time, so his spawn has delay...Donno if that's how it should work. In any case, the mob I was supposed to kill spawned, but attacked my character and killed me, instead of attacking Teron Gorefiend.
**Expected behaviour**: Tell us what should happen instead
The NPC that I am supposed to kill "Karsius the Ancient Watcher" should spawn in front of the Altar of Shadows.
The quest giver should not have a spawn delay I think.
Karsius the Ancient Watcher should attack the controlled npc (Teron Gorefiend) and not the players character.
**Steps to reproduce the problem**:
1. Take the quest.
2. Attack Karsius.
3. 

**Include proofs for this behaviour**
http://www.wowhead.com/quest=10639/teron-gorefiend-i-am
Forgot to take a screenshot. Also made a ticket ingame. Soon enough, a GM contacted me and completed the quest for me because the mob I'm supposed to kill basically 2 shots my charater.
You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Quest id is nr.#10639 I think.
You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment]
because the script for https://github.com/dalaranwow/dalaran-wow/issues/3535 is broken

i will fix both issues in https://github.com/dalaranwow/dalaran-wow/issues/3535

**Comment by Rushor** [comment]
DB/Quest: Teron Gorefiend, I am... - Update questscript

* Ancient Shadowmoon Spirit will now despawn only 30 seconds after questaccept (other player can now faster complete the quest too)
* Karsius the Ancient Watcher can now be attacked an killed
* Teron Gorefiend (summoned one) will now announce himself and walks away on his mount
* closes https://github.com/dalaranwow/dalaran-wow/issues/3561
* commit: 795b85e72d9e5655340dd71cbd38478b86db734d

![GitHub Logo](http://i.imgur.com/9MlnqQ3.jpg)
![GitHub Logo](http://i.imgur.com/fl3ILLO.jpg)
![GitHub Logo](http://i.imgur.com/L0iokKH.jpg)
![GitHub Logo](http://i.imgur.com/Fanilbu.jpg)
![GitHub Logo](http://i.imgur.com/FyYZm3h.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
