### ISSUE TITLE
[Quest][Northrend] Wooly Justice - Zul'Drak

### ISSUE THREAD

**Issue by Igguns** [dalaranwow/dalaran-wow#3571]
**Description**:
Quest in Zul'Drak not working properly. You're supposed to use a quest item to "calm" a mammoth, ride him, and trample some trolls.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
After calming the mammoths, they go friendly and just step around for a little while before going hostile again.

**Expected behaviour**: Tell us what should happen instead
After calming the mammoth I should be able to interact with it to mount and control it to trample some trolls.

**Steps to reproduce the problem**:
1. Find out how I can ride the mammoth please <3
2. Let me ride the mammoth please <3
3. Let me trample some trolls please <3

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by jonanone** [comment]
Mammoth behaviour has been fixed. This update will be applied to the live realm soon.

**Comment by Rushor** [comment]
Thort wrote:

The Medallion of Mam'toth is not working 100% of the time, it rarely is able to calm one of the Enraged Mammoth, not sure what causes it to work and to not work.

When it does work, all the improvements mentioned bellow are working accordingly on the PTR.

**Comment by Rushor** [comment]
http://wotlk.openwow.com/quest=12707

**Comment by Rushor** [comment]
as you can see here https://youtu.be/c0jhYGx0BvU?t=41, you need to charm the Mammoth if it is out of combat. then you will be able to mount on it and use it. Thats works great on PTR.

DB/Quests/Zul'Drak: Wooly Justice.

Mammoth behaviour has been rewritten in order to avoid several bugs.
- Once the Mammoth leaves the Altar area, it will dismount the player and despawn.
- Once the Mammoth is hit by the quest item spell, the mammoth pointer changes to indicate that is controllable.
- The mammoth won't stay in combat while mounted allowing the use of the first ability.
- If the mammoth isn't controlled in 15 seconds, it will become hostile again.
- The controlled mammoth won't attack by himself anymore. It is fully controllable.

Closes https://github.com/dalaranwow/dalaran-wow/issues/3571

commit: bf4c1726b901b9869f1efe775f5f9ccd613b6a41

**Updatetext: The quest Wooly Justice in Zul'Drak can now be completed properly.**
