### ISSUE TITLE
Seal of Command/Seal of Corruption getting double increase from damage percentage modifiers.

### ISSUE THREAD

**Issue by Starshift** [dalaranwow/dalaran-wow#3572]
**Description**:

There is not much to talk here. As the title says both seals scale with double rate from things like Crusade, Vengeance, Sanctified Retribution and any other percentage damage increase sources. This is easily noticeable on fights like Thaddius where seal damage can greatly surpasses the damage of a white swing which should never be the case, even on high armored targets.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

For example: Let's take 3 talents mentioned above (Crusade 3%, Vengeance 9%, Sanctified Retribution 3%) for a total of 15% damage increase, however currently they increase SoC/SoV damage by 30%.

**Include proofs for this behaviour**

I started off with testing Seals of the Pure but this talent seems to be working as intended.

Without Seals of the Pure talent: Avg damage - 532
![wowscrnshot_070916_152545](https://cloud.githubusercontent.com/assets/20371304/16708685/6f5d0e50-45fc-11e6-99fe-de9bf1a4e332.jpg)
Now with it: Avg damage - 608. About 15% increase as intended. 
![wowscrnshot_070916_154305](https://cloud.githubusercontent.com/assets/20371304/16708693/a0e3d09e-45fc-11e6-9029-dd64b713cf56.jpg)
In both these tests I wasn't using any seal damage increasing talents from retribution tree for the purpose of the next test.
![wowscrnshot_070916_154313](https://cloud.githubusercontent.com/assets/20371304/16708725/069706ae-45fd-11e6-8d23-7964fa1b5578.jpg)
On this final screenshot you can see I specced into Crusade, Sanctified Retribution and Vengeance which should be total of 15% damage increase but the results are as follows:
Avg damage - 816, which gives us a total of about 30% damage boost towards our previous test (608).
![wowscrnshot_070916_155756](https://cloud.githubusercontent.com/assets/20371304/16708761/66081302-45fe-11e6-8ea9-3f2a6413299b.jpg)

I unequipped all gear pieces with procs to make test results more accurate.

Two final screenshots of recount taken from Naxx I did some time ago, the max values you see are from Thaddius encounter. Seal damage is higher than white melee swing.

![wowscrnshot_070816_013505](https://cloud.githubusercontent.com/assets/20371304/16708827/2a3471a2-4600-11e6-8d65-e3497fdda5c8.jpg)
![wowscrnshot_070816_013501](https://cloud.githubusercontent.com/assets/20371304/16708830/2ff20280-4600-11e6-919e-927e39974a30.jpg)

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

**20375** Seal of Command
**53736** Seal of Corruption
**31868** Crusade
**31869** Sanctified Retribution
**20057** Vengeance
**20113** Two-Handed Weapon Specialization

I've been experiencing this bug on my TBC server aswell. It has probably something to do with sources increasing both physical and holy damage. SoC/SoV scale with weapon damage (physical) but do holy damage themselves.

**Comment by robinsch** [comment]
Proof needed that it shouldn't double dip on retail.

**Comment by PolarCookie** [comment]
Tentative proofs it should not double dip:

http://worldoflogs.com/reports/d8v2pu8v534k331y/details/13/?s=166&e=689 (Naline, dalaran)
http://worldoflogs.com/reports/81eia26l3k2b6xku/details/0/?s=495&e=609     (Vanazir, retail)

Naline white hits for 2671.0 avg and 1987.9 vengeance avg, vengeance is 74,4% of white hits.
Vanazir white hits for 5372.8 avg and 2834.2 vengeance avg, vengeance is 52,75% of white hits.
The sample size is small, and I'm assuming both 5xSunder and CoE effect on the target.

I looked into the log browser and found a white hit + vengance proc for both players.
Naline:
[10:19:34.951] Naline hits Gormok the Impaler 1976
[10:19:34.951] Naline Seal of Vengeance Gormok the Impaler 1798
vengance = 91% white damage

Vanazir:
[18:15:58.212] Vanazir hits Lord Marrowgar 3878
[18:15:58.529] Vanazir Seal of Vengeance Lord Marrowgar 2681 (R: 264)
vengeance = 75,94% white damage

again, the sample size is small and since I can't know the ArP it does make things difficult.
Also could be real unlucky that I picked the Naline pair of low white, high vengeance and the opposite for Vanazir.


I looked into the simcraft source code and the relevant parts are (edited for clarity for retribution):
Line 287:
```
struct paladin_attack_t : public attack_t
{
  paladin_attack_t( ... ) :
      attack_t( ... )
  {
    ...
    if ( p -> talents.crusade )
    {
      int r = sim -> target -> race;
      bool crusade_race = ( r == RACE_HUMANOID || r == RACE_DEMON || r == RACE_UNDEAD || r == RACE_ELEMENTAL );
      base_multiplier *= 1.0 + 0.01 * p -> talents.crusade * ( crusade_race ? 2 : 1 );
    }
  }

   virtual void player_buff()
  {
    paladin_t* p = player -> cast_paladin();
    attack_t::player_buff();
    if ( p -> talents.two_handed_weapon_spec )
    {
      if ( weapon && weapon -> group() == WEAPON_2H )
      {
        player_multiplier *= 1.0 + 0.02 * p -> talents.two_handed_weapon_spec;
      }
    }
    if ( p -> talents.vengeance )
    {
      player_multiplier *= 1.0 + 0.01 * p -> talents.vengeance * p -> buffs_vengeance -> stack();
    }
    if ( p -> buffs_avenging_wrath -> up() ) 
    {
      player_multiplier *= 1.20;
    }
  }
};
```

Line 1250:
```
struct seal_of_vengeance_proc_t : public paladin_attack_t
{
  seal_of_vengeance_proc_t( paladin_t* p ) :
    paladin_attack_t( "seal_of_vengeance_proc", p, SCHOOL_HOLY )
  {
    weapon            = &( p -> main_hand_weapon );
    weapon_multiplier = 0.33;

    base_multiplier *= 1.0 + ( p -> talents.judgements_of_the_pure      * 0.05 +
                               p -> talents.seals_of_the_pure           * 0.03 + 
                               p -> set_bonus.tier10_4pc_melee()        * 0.10 );
  }
};
```
(sanctified retribution is handled elsewhere, but it's another multiplicative)

Unravelling all that gives us a vengeance proc that is:
weapon * 0.33 * jugements of the pure * sanctified retribution * crusade * 2H-spec * vengeance stacks [* avenging wrath] (did I miss something?)
weapon * 0.33 * 1.15 * 1.03 * 1,03 * 1.06 * 1.09 [* 1.20]


Testing on a 80 dummy:
Equipment is a lvl 5 axe (http://wotlk.openwow.com/item=4562) and heroic tank gear giving 1876ap.

Result is 337 avg white hits, 241 avg vengeance hits
My untalented damage is 446-456, the addon drdamage says I have 38,98% damage reduction to armor against the dummy and it expects 338 avg white hits and 210 vengeance hits.

The equation from simcraft would have given me 209,8 vengeance hits
If we assume sanctified retribution, crusade and vengeance stacks are double dipping it's 242,6 vengeance hits.

I haven't tested each talent individually, but assuming 2h spec doesn't double dip got me closest to dalaran.

Tentative conclusion: sanctified retribution, crusade and vengeance stacks are double dipping and it shouldn't be like that.

**Comment by Starshift** [comment]
@PolarCookie, thanks for contributing to this report.

Just to be absolutely clear: Talents mentioned above aren't a main problem here and shouldn't be touched in my opinion as they work fine on everything except SoC and SoV. I used them merely to show off the bug.
The core of the problem lies within the seals only. There is more things that double-dip just SoV and SoC, like Avenging Wrath for example. That doesn't mean AW is bugged and should be changed in any way.

**Comment by robinsch** [comment]
@Lothloryen Can't confirm, working fine on PTR. Also for Seal of Command.

https://i.gyazo.com/5ec4d1f2106cb2e7dba7aef22933acd7.png

**Comment by Aridam** [comment]
Is this still an issue on Live?

**Comment by StheNoble** [comment]
yes it is. One of the classic examples where something is "allready working" on ptr wich means, they cant create a fix that get ported to live, they just hope there exist some other code fixes that get ported to life someday/maybe that also will fix this. but untill then we players are stranded with a non-reproducible bug due to diffrences between their dev environment and the life system.

**Comment by StheNoble** [comment]
yes it is. One of the classic examples where something is "allready working" on ptr wich means, they cant create a fix that get ported to live, they just hope there exist some other code fixes that get ported to life someday/maybe that also will fix this. but untill then we players are stranded with a non-reproducible bug due to diffrences between their dev environment and the life system.

**Comment by robinsch** [comment]
Don't blame us, we're not responsible for porting things to live.

**Comment by StheNoble** [comment]
no blame on you at all. and i didnt intend to offend with my post. its just my interpretation of the situation. maybe you can shed light on my assesment, do you see any feasable way to produce a fix for something you cant reproduce on the dev realm?

Does loth grant you access to the actual code on live? maybe difs between live and dev realm could help to identify what code has to be ported... ?

do you have any idea how to improve your ability to provide fixes (that you would share publicly)?

**Comment by robinsch** [comment]
No we work on a different branch and the current live version is months behind our development branch. So if something is broken on live we might have fixed it in the meantime already.

It's more or less a communication issue and that I'm gone for almost 4 months now due to university stuff and other projects. If I find time the next weeks I will take a look on what was left behind, but no promises.

**Comment by Aridam** [comment]
Bump.

This is still present -- it's been over a year.

**Comment by Aridam** [comment]
Second bump.

This is gamebreaking in PvP because it's doing ridiculous Damage.

Its proc is supposed to inherit Melee Stats, so it can Miss, be Blocked, Parried and Dodged -- none of this works, as it always hits no matter what.
Its Damage is supposed to inherit Spell Stats, so it deals 2x Damage on Crits rather than 1.5x as with Melee and Ranged, but it should also be subject to Resists due to lack of Spell Hit VS the Target (normally happens when fighting something too high-Level for you) -- currently only the 2x Crit DMG works, Resists don't seem to happen, so it's always doing full Damage.
It's also still true that the Damage is affected twice by Damage-increasing effects -- Avenging Wrath, Vengeance, BG Berserk Buff, and so on, which means it can just go to ridiculous numbers.

Proof regarding how it's supposed to work:
https://www.wowhead.com/forums&topic=22419#p434695
http://blue.cardplace.com/cache/wow-realm-test/391.htm -- this shows that the patch 1.3.0 change to SoComm got reverted, which is evident with the other links showing mentions of this present up to Wrath.
https://www.wowhead.com/forums&topic=113265#p1302754

Proof regarding how ridiculous it is on Dalaran-WoW:

**Comment by Aridam** [comment]
Third bump.

Look at this crap.

Avenging Wrath + Vengeance x3 + Berserk BG Buff.

One hit. JUST ONE.

https://imgur.com/a/sZubAbd

This thing deals as much Damage as its own separate Ability, and about three times more than Seal of Righteousness.

FIX THIS.

**Comment by Golganeth** [comment]
Hello @Aridam,
We are aware about the current state of SoC (both dmg modifiers and proc amount) and we will hotfix this pretty soon.

**Comment by donniDevito** [comment]
Has it been hotfixed already?

**Comment by Skipslegdays** [comment]
This is still happening. Fix this please. PvP is the only reason me and some of the other old players still play here. You leave this unfixed and new players are gonna stop queueing after they get one shot. And I'll stop playing cause BG aren't happening.

![image](https://user-images.githubusercontent.com/64817317/124333454-3f49a100-db62-11eb-921b-58bda31bdf97.png)
![image](https://user-images.githubusercontent.com/64817317/124333463-48d30900-db62-11eb-99f1-ff5da3d564af.png)
