### ISSUE TITLE
[Naxxaramas] Instructor Razuvius - No Player Loot

### ISSUE THREAD

**Issue by budthechud** [dalaranwow/dalaran-wow#3579]
**Description**: During raid instance 925 of Naxx10 the Mind Controlled units landed the killing blow on the boss which meant none of the participants got loot

**Current behaviour**: Currently the players are at risk of not getting loot if the bosds is not killed by a player.  This behavior also appeared in several quests involving summoned units in Storm Peaks and Icecrown.  Possible resolution in adding a flag that so long as a player deals 1 damage to the unit they are eligible for loot?

**Expected behaviour**: Boss should be slain by either players or MC'd units and raid is still eligibile for loot

**Steps to reproduce the problem**:
1. Naxx 10 (Unsure of if problem exists in 25) - Instructor Razuvious
2.  Let on of the Death Knight Understudy units get killing blow on Boss. 

**IDs**
Boss (10m) - http://www.wowhead.com/npc=16061/instructor-razuvious
Death Knight Understudy (aka, mind controllable units) - http://www.wowhead.com/npc=29941/death-knight-understudy

Zone - http://www.wowhead.com/zone=3456/naxxramas (Military Quarter)

**Comment by Lukas45** [comment]
There is actually already a flag for that out in the world (must do at least 50% of HP dmg for it to be your kill), but for some reason it doesn't apply to Instructor Razuvious

**Comment by budthechud** [comment]
Yea I have no clue - I know that they rolled out a fix for a bug I ran into in Storm Peaks for something VERY similar in that way so... lol

**Comment by Rushor** [comment]
Scripts/ : Razuvious - Damage done by the controlled Death Knight understudies should also count toward damage done by players

* closes https://github.com/dalaranwow/dalaran-wow/issues/3579
* commit: 583a0f22918b8f792c42b8c42a8a31e6cc4129dd

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
It's already on PTR.
