### ISSUE TITLE
[Spell] Wintergrasp/Ulduar Siege/Demonlisher Cannon Ball Visual Bug

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#3581]
**Description**: Currently the Cannon balls that you shoot from any vehicle that has them, they will for some reason SLOWLY move towards their target.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
The Cannon Balls are visually bugged and they slowly fly towards their target. That shouldn't be the case.
**Expected behaviour**: Tell us what should happen instead
Cannon ball should visually drop right away after being shot from a cannon. Simple as that.
**Steps to reproduce the problem**:
1. Drive a Siege/Demolisher in Ulduar or Wintergrasp
2. Shoot the Cannon to reproduce the Balls
3. Look at them flying around like baloons XD

**Include proofs for this behaviour**
https://www.youtube.com/watch?v=rUM_t2-cMWk&feature=youtu.be

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment]
Game/Spells: Fire Cannon - Increase speed

* closes https://github.com/dalaranwow/dalaran-wow/issues/3581
* commit: 4cead2281c255024ac004789fa4973a672818ab5

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Aridam** [comment]
This doesn't seem to be _just_ a visual issue, because I'm currently in the process of shooting using a Wintergrasp Cannon at the Fortress, and I fail to hit people with it immediately -- it's like they actually _are_ flowing at a slower speed to their destination and as thus, _then_ do Damage to them.

Either way, reconfirming the visual bug but also requesting re-evaluation because it seems to be not _just_ a visual bug.
