### ISSUE TITLE
[Magister's Terrace] Sunblade Mage Guard

### ISSUE THREAD

**Issue by MrAndersonX** [dalaranwow/dalaran-wow#3583]
**Description**:
Mobs dmg is bugged. Sunblade Mage Guard for example hits 4-5 times in a row in 1 attack, or better said they hit continously in 1 second.
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
I tried entering the dungeon to attempt to do it as far as I can. The moment I got attacked, my pet and I got 1 shoted. At least, that's what it seemed like...hits for 2-3k+ each in a instant. After a while I realized they were glaive hits, so I thought they just bounced off my pet...so I forced the pet to stay put in a corner, to avoid gettng hit from glaive to see if it would still hit me multiple times in 1 shot...and it did. While solo aggroing the mob, I got 4-5 hits usually in 1 hit.
**Expected behaviour**: Tell us what should happen instead
They should have a internal cooldown or something on attacks, so they perform a lower number of attacks per action/second/hit.
**Steps to reproduce the problem**:
1.  Enter the dungeon.
2.  Attack the first 2 mobs guarding it.
3. 

**Include proofs for this behaviour**
https://s32.postimg.org/qoo4nj7j9/Wo_WScrn_Shot_071216_155046.jpg
https://s32.postimg.org/3q0yh5j2t/Wo_WScrn_Shot_071216_155122.jpg
https://s31.postimg.org/8evrcec0r/Wo_WScrn_Shot_071216_155134.jpg
https://s32.postimg.org/d3sfjz5ph/Wo_WScrn_Shot_071216_155421.jpg
https://s31.postimg.org/dcdxbf3ff/Wo_WScrn_Shot_071216_155452.jpg
You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
http://www.wowhead.com/zone=4131/magisters-terrace
**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Instance/Dungeon ID is 4131 I think.
You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment]
DB/Creature: Update combatscript for Sunblade Mage Guard

* closes https://github.com/dalaranwow/dalaran-wow/issues/3583
* commit: e23d3b462197443afd8257bda6c92fe76c0e035a

* Sunblade Mage Guard - Within 10-60 Range - Cast 'Glaive Throw' (Normal Dungeon)
* Sunblade Mage Guard - Within 10-60 Range - Cast 'Glaive Throw' (Heroic Dungeon)
* Sunblade Mage Guard - In Combat - Cast 'Magic Dampening Field' (No Repeat)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
