### ISSUE TITLE
[GO] Ethereum Prison Respawn

### ISSUE THREAD

**Issue by Steev23** [dalaranwow/dalaran-wow#3657]
**Description**:
The Ethereum prisons used for Outland reputation gains only seem to respawn on server restart.  

**Current behaviour**: 
Checked on them over the course of a few hours whilst doing other things in the zone and never saw any appear.  Did this over a few days to ensure I wasn't just getting unlucky and missing them.   When I first did the quest there was four of them there, I used one of them and left the area for a while.  When i came back there was still three there, and I had some more keys so I opened all of them and haven't seen any spawn since.

**Expected behaviour**: 
I couldn't find any information on how long the respawns are meant to be, but searching through comments on wowhead and a couple of other forums I couldn't see anyone complaining about a long respawn or even having to fight anyone for these prisons either, so I don't imagine the time is meant to be very long.

**Steps to reproduce the problem**:
1. Go to the Ethereum Staging Ground in Netherstorm
2. Open prisons.
3. Wait a long time.

Ethereum Prison Key: http://wotlk.openwow.com/item=29460

**Comment by Rushor** [comment]
Scripts/Gameobject: Ethereum Prison - Enable respawn and reputationreward

* closes https://github.com/dalaranwow/dalaran-wow/issues/3657
* commit: dd11de74e467dfcf5af5979db29faf669c549753
* The objects will now respawn after 180 sec and always reward the reputation

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
