### ISSUE TITLE
Primed Key Mold

### ISSUE THREAD

**Issue by Kirishiki** [dalaranwow/dalaran-wow#3712]
Primed key mold was dropped today from Coilfang emissary (rare mob) in zangamarsh and gm told its a bug. Its a quest item for quest i didnt even have.

**Comment by Golganeth** [comment]
Confirmed.

**Comment by Rushor** [comment]
DB/Item: Primed Key Mold - should not drop by Coilfang emissary

* closes https://github.com/dalaranwow/dalaran-wow/issues/3712
* commit: b09819b5aaa0c7bc9a2854231c52719d673376b6

The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on ptr.
