### ISSUE TITLE
Zul'Gurub: Bloodlord Mandokir

### ISSUE THREAD

**Issue by SadhuArch** [dalaranwow/dalaran-wow#3734]
**Description**: After a wipe, Bloodlord Mandokir (ID:11382) is supposed to position himself where the Vilebranch Speaker (ID:11391) was prior to killing him to trigger the encounter. The boss has to reset and place himself below the stairs.
Also, a minor bug with him yelling _"I'm keeping my eye on you, player!"_ when casting Threatening Gaze (ID:24314) but he is supposed to yell _"player! I'm watching you!"_.

**Current behaviour**: When a wipe occur, Bloodlord Mandokir starts to run away from his platform and goes outside his "room" and starts running around the next zone only to come back again to despawn.
He is also yelling the wrong thing when casting Threatening Gaze.

**Expected behaviour**: Upon a wipe he should reset the encounter and run to the bottom of the stairs. Meaning he should reset his health back to full and respawn his mount, Ohgan (ID:14988), which he then mounts and the fight can start again when attacked. 

**Steps to reproduce the problem**:
1. Kill the Vilebranch Speaker at the bottom of the stairs.
2. Attack Bloodlord Mandokir.
3. Die.
4. Wait to see him run around and eventually despawn or release and run back inside and he has despawned.

**Proofs for this behaviour**
Video from Dalaran-WoW showing his behaviour after a wipe: https://www.youtube.com/watch?v=IGRkUHVQCbo
Picture from Dalaran-WoW showing him yelling "I'm keeping my eye on you, player!": http://i.imgur.com/j2b7ya6.jpg

**Proofs for how his behaviour is expected to be**
Video from Vanilla that shows a full group wipe and his behaviour after everyone has died: https://www.youtube.com/watch?v=joaWY0wjOXI
Video from retail Wrath of the Lich King where you see him yell _"player! I'm watching you!"_: https://www.youtube.com/watch?v=SYr2_CA47u8
Another video showing the same thing as above, also from Wrath of the Lich King: https://www.youtube.com/watch?v=AGg9eJXz_vA

**Comment by Rushor** [comment]
Scripts/ZulGurub: Mandokir - should reset in front of the stairs + adjust textemote for Threatening Gaze 

* closes https://github.com/dalaranwow/dalaran-wow/issues/3734
* commit: 8a148a390b86f9ec3284aa516352187e5bc08ccb

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
Reference: https://github.com/dalaranwow/dalaran-wow/issues/4124
