### ISSUE TITLE
Hunter Pet summon issue

### ISSUE THREAD

**Issue by Pentex11** [dalaranwow/dalaran-wow#3741]
If a Hunter's Pet dies, the player can mount, dismount, and the pet will get back to life.

**Comment by KazJR** [comment]
Pets that die during a raid encounter can also be resummoned after their corpse fades away. However, the first summon will only bring the pet back to life, it will not do anything. A 2nd summon will bring the pet back with full functionality.

**Comment by robinsch** [comment]
Note: You can no longer call dead pets. If they are dead and despawned you can use Revive Pet.

**Comment by Serpentsting** [comment]
https://youtu.be/kv_mNNewROg

**Comment by Serpentsting** [comment]
BUMP. Does anyone want to start fix these bugs or wut?

**Comment by Rushor** [comment]
@Serpentsting there is already a fix for it, it will be tested from the team on ptr.

**Comment by Rushor** [comment]
The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Lothloryen** [comment]
Deployed already, thank you everyone.

**Comment by KerDW** [comment]
Pets are not resurrecting properly in the BG's Spirit Guides sometimes. Check #4373 for a more detailed report.
