### ISSUE TITLE
[Warlock] Voidwalker: Movement breaks consume shadows

### ISSUE THREAD

**Issue by nemmjuuk** [dalaranwow/dalaran-wow#3742]
**Description**:

**Current behaviour**: When the voidwalker casts "consume shadows" any voidwalker movement will break the casting. 

**Expected behaviour**: As soon consume shadow is casted, the voidwalker should stay in it's place and not move until the cast is finished. 

**Steps to reproduce the problem**:
1.  Warlock summon voidwalker. Have voidwalker use consume shadow
2.  Warlock moves, voidwalker follows instead of staying in place. 
3.  Movement cancels consume shadow, warlock is sad about wasted mana

**Include proofs for this behavior: Been playing locks on retail up to Cata. Voidwalker never moved while casting.

**Comment by Rushor** [comment]
Scripts/Spells: Warlock - Consume Shadow - Stay on Cast 

* closes https://github.com/dalaranwow/dalaran-wow/issues/3742
* movement will no longer cancel consume shadows
* commit: 5ddd46b57359f8989f4676e3c85833b37d966a40

**Comment by Rushor** [comment]
this fix does not work - needs to be fixed in a general way

**Comment by Rushor** [comment]
Core/Spell: Interrupt creature's spell casting if moving

* commit: 47fdbf7fe037316af25c9c28e3b3e704d92d00e0
* commit: 60225ba933b2eb50610f33f3a82324228466c2e5
* commit: 60225ba933b2eb50610f33f3a82324228466c2e5

by @robinsch 

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
