### ISSUE TITLE
Warlock Fel hunter: Metamorphosis bugs out fel intelligence pet skill

### ISSUE THREAD

**Issue by isn14AC** [dalaranwow/dalaran-wow#3747]
**Description**: Apparently, putting a point into Metamorphosis talent (This is my guess however, because that's when I noticed it, but I cannot reproduce it) bugs out fel intelligence pet skill, after which it just infinetly loops through wind up sound/animation, but never applies effect. Reseting/Respec'ing doesn't fix the problem (Todays server restart however fixed it until i respec'ed demo again). Playing with fel hunter is now very annoying simply because of the sound it makes. There's this other bug, where some pet skills are always on invisible autocast (No visual border on skill, but pet casts them anyway) after new dungeon join or dismount. switching on/off fixes the problem until the next dismount/dungeon join. So every time I dismount I have to switch fel intelligence pet skill on/off in order for it to be somewhat playable.

**Current behaviour**: A point is given into warlock demonology talent - metamorphosis, after which warlocks pet fel hunter doesn't apply the fel intelligece effect, just loops infinitely through wind-up sound and animation.

**Expected behaviour**: metamorphosis talent shouldn't affect pet skill fel intelligence in any way.

**Steps to reproduce the problem**:
1. Dave a deep demonology spec`ed warlock (with metamorphosis)
2. Cast pets fel intelligence (http://wotlk.openwow.com/spell=57567)

**Include proofs for this behaviour** One other demonology warlock confirmed the issue

**Comment by isn14AC** [comment]
**Additional Info**: Today I was checking whether Demo talent tree reset will fix the problem, and it did. After which I decided to check if my guess about metamorphosis was correct, so I spec'ed same way it was before, but now the aura effect applies correctly. Mounting/Dismounting, talent switching between dual spec doesn't trigger the bug. I'm was sure that talent reset doesn't fix the bug because I did one reset about a weak ago where I wasn't dual spec'ed, and changed from demo to affliction - broken fel intelligence remained. Now I can confirm following:

1. Metamorphosis doesn't trigger this bug
2. Talent reset can fix this bug

I guess this issue can be closed until I notice what exactly triggers the bug.

**Comment by Taverny** [comment]
it doesnt stack with priests spirit buff, so if u die u wont have buff while ur pet will still have it, thats why pet cant cast it.

**Comment by isn14AC** [comment]
I don't know if you're saying this is the way to trigger the bug, or you're implying, that I noticed it fail to apply once, and ran here crying and reporting. The real story is I had this bug for about a week. It think it just was a coincidence, that I've noticed it first time i put a point into metamorphosis. But never the less for me fel hunter was bugged for somewhat close to a week, which means multiple relogs, client closes, pet deaths, pet disbands, my deaths and so on... happened - nothing worked. Everytime in combat my fel hunter was charging enemy sounding like a machine gun spraying those orange/red bubbly particles from his antenas. I assume it was the animation part of the spell on the fast loop. Spell icon also indicated, that the spell is being constantly casted (even tho autocast was off for it). It took me a week of this bs, till I couldn't take it no more, and decided to report the issue - I did asked in the global chat about this, and one warlock confirmed, that he has the same issue. So that's a more complete background story

**Comment by Niukka** [comment]
Old bug that also applies to Blood Pact. It has to do with autocasting due to the fact that on Dalaran the autocast settings reset every time you summon a new pet. You can either manually turn autocasting off from your spellbook (it has to be done via spellbook, turning autocast off from the pet bar will not work) or use this macro:

`/petautocastoff spellname`

I just added that line to my all my macros for the abilities I use the most.

**Comment by Dartheus** [comment]
This issue is a sorta bug that happens when the overriding of auras with 'lower' ones is correctly implemented.

If an aura of the same type is affecting raid already, the pet will go into an infinite autocast loop, because they will try to apply the aura, but are denied as it is usually less good than the 'class one' (eg Blood Pact vs Commanding Shout, Fel Intellect vs Dalaran Intelligence / Prayer of Spirit)

**Comment by Rushor** [comment]
hm this sould be fixed with:

DB/Spell: Implement spell_group from Sunwell.pl

Issue https://github.com/dalaranwow/dalaran-wow/issues/1510
*commit: 424ed6af17475e0984dcda50ff1598607ef21796

Try it out :) 

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
Already on PTR.
