### ISSUE TITLE
[Quest] Secret of the Circle

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#375]
Quest Secret of the Circle - 3447

Issue: After using / clicking on all the "Atal'ai Statues" in Sunken Temple, you do get the quest complete credit, but the object where you have to turn in the quest doesn't spawn. The object should appear down below in the "arena" and you are able to interact with it and turn the quest in.

http://wotlk.openwow.com/quest=3447
http://www.wowhead.com/quest=3447/secret-of-the-circle
![image](https://f.cloud.github.com/assets/5054924/909950/ce58377c-fdcf-11e2-9665-60e23bd6693c.png)
![image](https://f.cloud.github.com/assets/5054924/910004/e2662df4-fdd0-11e2-85c9-a030f2b1a582.png)

**Comment by n-ghost** [comment]
Quest is obtainable again, but upon clicking on statues you get no credit, nor any altar will spawn down there in the water.

**Comment by MrAndersonX** [comment]
Yeah, no altar spawns. You click on the altar on the text but nothing happens.

**Comment by Rushor** [comment]
af8432792f88dc3eb4b95df71977aafc27e79995
fd5481835cbaf0e79ddf30e9653aac5fa68332a0
- once all statues are clicked, the altar will spawn and you can complete the quest

**Comment by Golganeth** [comment]
- You are able to click all the statues but they will not activate (and show a green beam) unless you're doing it in a certain order. If a certain order should be followed, then you shouldn't be able to use them in the wrong order.
- Once you have used all the statues, a boss spawns. Once the boss dies, it takes too long for the Idol of Hakkar to spawn (around 30-40 secs).

**Comment by PSAlias** [comment]
Those issues seem to be corrected now. Mind you, the pathing on Atal'arion is awful. He keeps running to the outer ledges on the arena.

**Comment by Zibathy** [comment]
Everything I looked up online didn't really seem to have a clear picture of what is supposed to happen compared to what actually happens ingame. So I'm just going to say what I experienced twice:

1. Atal'whatever spawns before you interact with anything, as does the Altar of Hakkar.
2. The text on the Altar is broken. (can't interact)
3. Activating the six statues appears to do nothing. 
4. Can't complete the quest Secret of the Circle.

I wouldn't care about any of these if the quest just completed at least so I can get my loremaster achievements. That would be nice.

![wowscrnshot_111816_212652](https://cloud.githubusercontent.com/assets/7729864/20452712/717568c6-add6-11e6-8d6e-eeb29addcc25.jpg)
![wowscrnshot_111816_212709](https://cloud.githubusercontent.com/assets/7729864/20452713/71770ffa-add6-11e6-98d9-8ab009a213d8.jpg)
![wowscrnshot_111816_212730](https://cloud.githubusercontent.com/assets/7729864/20452714/7178c26e-add6-11e6-8094-3c2b81f1fc69.jpg)

**Comment by Rushor** [comment]
going to recheck it, as soon as i rewrote the dungeon

**Comment by Rushor** [comment]
DB/Quest: Secret of the Circle - Update script for Altar of Hakkar

* Altar of Hakkar now becomes invisible for several seconds once the gossip was selected (no longer spammklick possible)
* Atal'alarion should spawm instantly the object Idol of Hakkar after death
* closes: https://github.com/dalaranwow/dalaran-wow/issues/375
* commit: af8432792f88dc3eb4b95df71977aafc27e79995
* commit: fd5481835cbaf0e79ddf30e9653aac5fa68332a0
* commit: f15ee2b8e64f3c6676a526ed8c04ac5272e0f0d8

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
