### ISSUE TITLE
[Item] Mind Flay and Illustration Trinket

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#3788]
Shadow Priest spell mindflay does not proc illustration of the dragon soul trinket.
mind flay: http://wotlk.openwow.com/spell=15407
illustration: http://wotlk.openwow.com/spell=60485

That is all.

**Comment by robinsch** [comment]
On PTR.

**Comment by Edzero** [comment]
It only procs once on Mind Flay rather than once per tick for 3 total. Also issues with several other abilities related to this trinket and other similar trinkets.

#1745 #2120 and #2130 are all related and are waiting on PTR Update.

**Comment by Rushor** [comment]
Not on PTR yet 

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
Already on PTR.
