### ISSUE TITLE
[Hunter] Viper Sting

### ISSUE THREAD

**Issue by Serpentsting** [dalaranwow/dalaran-wow#3791]
must drain 4% of mana and energize hunter 300% of drained mana, btw, energize hunter only for 100% drained mana

founded on wotlk wowhead
"Buff
Viper Sting Poison
Drains 1% mana every 2 seconds, restoring 300% of the amount drained to the Hunter.
8 sec remaining"
	
https://youtu.be/llJHOWvbV9s
as we see, shaman have 19566 mana
should be drained 195.66 mana each 2 seconds, should be restored 586,98 mana each 2 seconds
what we have: drained 145 mana per 2 seconds, restore 145 mana per 2 seconds

**Comment by Edzero** [comment]
Your calculations are incorrect.

Tested this on the PTR as I don't have a Hunter on the live realm and it works just fine there.

In your case the Shaman has 19,566 mana and 4% of that is 782.64 mana, or 195.66 mana per tick. However, Kys has a lot of HP in that video so I am under the impression that he is wearing PvP gear. Resilience from PvP gear will reduce the effects of mana drains which is why the amount you are leeching from him is lower than you expected.

Your scrolling battle text add-on is showing 145 mana but I believe this is actually a bug with the add-on. Since your mana is so close to full I can't monitor it properly in the video. Try doing this again in-game against a character who has no resilience or other effects which reduce mana drain effectiveness. This time though, do it with your mana bar nearly empty and keep your combat log open. You should find that the amount of mana you are gaining is actually correct in the logs and that it's just the addon giving you an incorrect reading.

I'll close this for now but if you make another video with the suggestions above and things are still not adding up, I'll re-open it. Feel free to contact me in-game if you need assistance.
