### ISSUE TITLE
road sign in silverpine forest bug

### ISSUE THREAD

**Issue by w00tnoway** [dalaranwow/dalaran-wow#3816]
**Description**: road sign in silverpine forest is floating in the air please see screenshot

**Current behaviour**: road sign in silverpine forest, the board on it that says ''deep elem mine'' is floating in the air

**Expected behaviour**: road sign is supposed to be connected to the pole instead of floating in the air

**Steps to reproduce the problem**:

1. go to the road sign

**screenshot**
http://imgur.com/a/Cmv5w

**Comment by Rushor** [comment]
DB/Gameobject: Update position of Deep Elem Mine

* closes https://github.com/dalaranwow/dalaran-wow/issues/3816
* commit: 35f082355f988f14f4bde8d01579dac18e3fb919

http://i.imgur.com/V19JmgJ.jpg
The issue is fixed on the PTR Realm. The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please see and watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
