### ISSUE TITLE
minimap bug

### ISSUE THREAD

**Issue by w00tnoway** [dalaranwow/dalaran-wow#3818]
**Description**: minimap shows parts of underground level in front of undercity please see screenshots

**Current behaviour**: when standing in front of undercity outside the gate the minimap shows parts of the lower level

**Expected behaviour**: lower level not visible on minimap at upper level of undercity

**Steps to reproduce the problem**:

1. go outside of undercity as shown on screenshots

**screenshots**
http://imgur.com/a/jz5Zf
http://imgur.com/a/yp1tq

**Comment by Rushor** [comment]
That's not an issue. The minimaps wasn't scripted well back in wotlk. With the Cata expansion they reworked the whole layout of cities due to the fact that you can reach everything with the flying mount.

So no, this is a client-side "issue" and cannot be fixed.

See https://www.youtube.com/watch?v=YnRzuMz0nnY f.ex. as proof that this issue also existed on retail wow back from 2008 till 2010.
