### ISSUE TITLE
Quest: Among the Champions

### ISSUE THREAD

**Issue by Kaara** [dalaranwow/dalaran-wow#382]
Hello,

http://www.wowhead.com/quest=13790

This quest is bugged, i get on the mount i go talk to them,but i cannot fight them for the marks.

**Comment by Spruitje** [comment]
Have issues with this quest too, i'm already champion with my home city and working on undercity.
I try to do the daily, but only the first win will give me credit, no matter how many times i win afterwards
Abandoning this quest and retaking it again only gives me credit for the 1st win.
Also is it normal that the champions take aggro from other random competitors and if you lose they keep attacking you untill you A) managed to run away far enough or B) get killed?

**Comment by ZiggyMoonshine** [comment]
It seems that there's still a problem getting a credit (=Marks of the Champion) for defeating champions, and I suspect the reason is that the credit for defeating goes to the MOUNT and not the character. Normally when you win the tournament you get the mark of victory and a debuff that prevents you challenging the same champion again. But I noticled that when the match bugs out, the mount gets the debuff.

**Comment by Lothloryen** [comment]
Working properly since long time ago.
