### ISSUE TITLE
Quest starter:Shattered Necklace

### ISSUE THREAD

**Issue by w00tnoway** [dalaranwow/dalaran-wow#3820]
**Description**: Shattered Necklace shows quest icon but when right clicked emits an ''error'' sound and a quest window does not appear whilst the item is required to finish a quest that Dran Droffers in Orgrimmar gives

**Current behaviour**: please see description

**Expected behaviour**: should supposedly not show a quest icon as this quest obtained by right clicking the item can not be accepted by the majority of horde race's? 

**Steps to reproduce the problem**:

1. right click the Shattered Necklace

**screenshot**
http://imgur.com/a/cYPEp

**IDS**
http://www.wowhead.com/search?q=shattered+necklace
http://www.wowhead.com/npc=6986/dran-droffers

**Comment by Rushor** [comment]
Horde chatacters cannot accept the quest that the necklace itself gives,
http://www.wowhead.com/item=7666/shattered-necklace#comments:id=4948

RedwoodElf on 2009/01/29 (Patch 3.0.8)
More like "Speciesist" - Azeroth races are actually different species, not differing skin colors of the same speicies like on Earth. The actual error message should be "This quest cannot be taken by Horde characters."
http://www.wowhead.com/item=7666/shattered-necklace#comments:id=331433:reply=384459


That issue is blizzlike and correct. Due to the fact, that the issue is blizzlike, Dalaran WoW will not fix it.

Please follow these instructions in order to do the quest:

**By TheOnyx (75,425 – 25·143·483) on 2006/11/28 (Patch 1.12.2)		
Horde chatacters cannot accept the quest that the necklace itself gives, but they can take the necklace to the salvage shop in Orgrimmar to start a quest chain that takes you back inside Uldaman.

The salvage shop is inside the Drag. Coming from Thrall's chamber, it'll be the the first building you can enter on the left side.**

**Comment by w00tnoway** [comment]
okay but it didnt show me the error message :o


________________________________
Van: Rushor <notifications@github.com>
Verzonden: woensdag 9 november 2016 11:15
Aan: dalaranwow/dalaran-wow
CC: w00tnoway; Author
Onderwerp: Re: [dalaranwow/dalaran-wow] Quest starter:Shattered Necklace (#3820)


Horde chatacters cannot accept the quest that the necklace itself gives,
http://www.wowhead.com/item=7666/shattered-necklace#comments:id=4948

RedwoodElf on 2009/01/29 (Patch 3.0.8)
More like "Speciesist" - Azeroth races are actually different species, not differing skin colors of the same speicies like on Earth. The actual error message should be "This quest cannot be taken by Horde characters."
http://www.wowhead.com/item=7666/shattered-necklace#comments:id=331433:reply=384459

That issue is blizzlike and correct. Due to the fact, that the issue is blizzlike, Dalaran WoW will not fix it.

Please follow these instructions in order to do the quest:

**By TheOnyx (75,425 - 25·143·483) on 2006/11/28 (Patch 1.12.2)

Horde chatacters cannot accept the quest that the necklace itself gives, but they can take the necklace to the salvage shop in Orgrimmar to start a quest chain that takes you back inside Uldaman.

The salvage shop is inside the Drag. Coming from Thrall's chamber, it'll be the the first building you can enter on the left side.**

-
