### ISSUE TITLE
[Quest][Outland] Planting the Banner

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#383]
Quest Planting the Bannert - 10518
Issue: The event has to start upon you place the banner on top of the tower:
It has to summon
- 2 orcs
- 3 orcs
- 3 orcs
- Gurn Grubnosh

Once you kill Gurn Grubnosh, you are able to loot the quest item needed to complete the quest.

Temporary fix: I spawned Gurn Grubnosh (20116) with 5 minutes Re-spawn timer, so the players can atleast complete the quest by their own.

http://www.wowhead.com/quest=10518/planting-the-banner

**Comment by Daveonx** [comment]
Confirmed, the Bloodmaul and [Gurn Grubnosh](http://www.wowhead.com/npc=20116/gurn-grubnosh) spawn at the bottom of the tower and stay there static, not moving unless engaged.

**Comment by Rushor** [comment]
easy fix would be to change the summonposition - but that's not blizzlike

**Comment by Rushor** [comment]
DB/Quest: Planting the Banner - Summoned creature will now walk upstairs on top of the tower

* closes https://github.com/dalaranwow/dalaran-wow/issues/383
* commit: 3193546ae0f46c08022fa6a190cd5545d5e86126

![GitHub Logo](http://i.imgur.com/rPpJqOP.jpg)
![GitHub Logo](http://i.imgur.com/2eHsyzj.jpg)
![GitHub Logo](http://i.imgur.com/t5Ybym9.jpg)
![GitHub Logo](http://i.imgur.com/PjYqvuZ.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
