### ISSUE TITLE
[NPC] Warsong Swine - Experience Scale

### ISSUE THREAD

**Issue by Morens-D** [dalaranwow/dalaran-wow#3848]
http://wotlk.openwow.com/npc=25362

Creature grants huge amount of experience to lowlevel players.

**Comment by Rushor** [comment]
DB/Creature: Remove XP gain for Warsong Swine

* closes https://github.com/dalaranwow/dalaran-wow/issues/3848
* commit: 8f1f9303eed7c31963cd71fba6b8bbc6d6277503

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on ptr.
