### ISSUE TITLE
[Quest] Recover the Key!

### ISSUE THREAD

**Issue by Morens-D** [dalaranwow/dalaran-wow#3893]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**:
Quest [Recover the Key! ](http://wotlk.openwow.com/quest=7846) is repeatable, so players cannot  proceed quest line to [Return to Primal Torntusk](http://wotlk.openwow.com/quest=7847)

**Comment by Morens-D** [comment]
Fixed.

**Comment by Rushor** [comment]
DB/Quest: Recover the Key! - Make quest not repeatable
* commit: ff35a2374bedb8adcc823dd578668e91ac1dd979

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by goldenpipes** [comment]
how long before the update? I am currently on this quest chain.

**Comment by Rushor** [comment]
The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.


i cannot give an exact time on "how long"

**Comment by TeridanDW** [comment]
This is not working ptr, the quest is still repeatable, also npc http://wotlk.openwow.com/npc=10802 does NOT stop her path when she engaged in combat (casting while moving, which is wrong).

**Comment by Rushor** [comment]
okay the questfix needs to be reapplied then on ptr. going to fix the attackissue now

**Comment by Rushor** [comment]
DB/Creature: Hitah'ya the Keeper - Stop waypoint movement and attack invoker on aggro

* updates: https://github.com/dalaranwow/dalaran-wow/issues/3893
* commit: c6f74de1d5cf234a94fd919673f0cd30656081d9

![wow_2017-03-30_13-36-25](https://cloud.githubusercontent.com/assets/5568820/24503732/9f5e205e-1553-11e7-826d-a1224066a62d.png)


The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Virmire** [comment]
Tested on 2nd of July, quest is still repeatable

**Comment by Rushor** [comment]
The issue was fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Aridam** [comment]
Quest still repeatable.
