### ISSUE TITLE
[Instance][ToGC] Burning Bile

### ISSUE THREAD

**Issue by Horvic** [dalaranwow/dalaran-wow#3933]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description:**
Burning Bile damage evades after Dreadscale has been killed.

**Current behaviour:**
Once Dreadscale has been killed Burning Bile no longer damages the player or any others in close proximity. 
This currently prevents you from removing paralytic toxin from players once Dreadscale dies.

**Expected behaviour:**
Burning Bile should continue dealing damage after Dreadscale is dead until the debuff expires.

**Steps to reproduce the problem:**

Get Burning Bile.
Kill Dreadscale.
Check combat log/text for Burning Bile damage.

OverDoZer - Algalon

http://www.worldoflogs.com/reports/ftb0wg5gkfa9vpw7/spell/67623/?s=97&e=520

The source of the damage seems to shift to the afflicted player after Dreadscale dies and just returns evade.
You can see 42 evade hits on Circles.

http://www.worldoflogs.com/reports/ftb0wg5gkfa9vpw7/log/?s=97&e=520
Log query:
 [{"spellNames": ["Burning Bile"], "eventTypes": [2]}, {"eventTypes": [5], "targetNames": ["Dreadscale"]}]

You can see Dreadscale's death followed by each Burning Bile evade.

**Comment by Rushor** [comment]
http://wotlk.openwow.com/?search=Burning+Bile

**Comment by Rushor** [comment]
needs to be fixed with triggers.

**Comment by Rushor** [comment]
Scripts/TrialOfTheCrusader: Paralytic Spray + Paralytic Bite + Burning Spray - move spellscript for these debuffs to triggers

* with this addition, dots will also be casted even if the caster (Dreadscale, Acidmaw) are dead
* closes https://github.com/dalaranwow/dalaran-wow/issues/3933
* commit: 1a20ad351d4a91f6d4b0e02a041515ef68c2726b

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
