### ISSUE TITLE
[TBC] [Karazhan] [Boss] Hyakiss the Lurker

### ISSUE THREAD

**Issue by Edzero** [dalaranwow/dalaran-wow#3934]
Currently he will not spawn even when the requirements are met.

Rushor has already made an issue for this on Trinity Core here:
https://github.com/TrinityCore/TrinityCore/issues/15756

Quoting from that issue since it is already made:

"rev: b2575a0

http://www.wowhead.com/npc=16179/hyakiss-the-lurker#comments:id=37735

By huntergenwedar (2,138 – 4·15) on 2007/02/18 (Patch 2.0.8)
This boss is one of three random bosses that can spawn in the basement (Servants Quarter) of Karazhan once you have killed all of the spiders, bats and hounds in the area. You must kill ALL of them and have the entire area clear, no respawns for one to spawn.

The other bosses are:

http://www.wowhead.com/?npc=16181#z0z (hound, Rokad the Ravager)
http://www.wowhead.com/?npc=16179#z0z (bat, Shadikith the Glider)

Some datatypes are already set in the instancescript, but there is NO script at all for the summon.
https://github.com/TrinityCore/TrinityCore/blob/3bc3b67a8fae059e1019446b09882dfa7fcd11a0/src/server/scripts/EasternKingdoms/Karazhan/instance_karazhan.cpp#L121

I think the stuff must be handled like the script for 'the wild eck' in gundrak. if all pre-adds are defeated a boss summons (aka if there is no guid left, npc xy spawns). Here we have the additional difficulty that there is a possiblity that there will be no bossspawn at all. This must be implemeted too."

**Comment by Rushor** [comment]
yes yes, i will fix it

**Comment by Rushor** [comment]
Scripts/Karazhan: Implement Optional Boss Spawn

* closes https://github.com/dalaranwow/dalaran-wow/issues/3934
* commit: 0b211ac828a12b5af0ea1c73240f8e50d0ebc2f8
* once 50 of the creatures:

```c++
NPC_COLDMIST_WIDOW              = 16171,
    NPC_COLDMIST_STALKER            = 16170,
    NPC_SHADOWBAT                   = 16173,
    NPC_VAMPIRIC_SHADOWBAT          = 16175,
    NPC_GREATER_SHADOWBAT           = 16174,
    NPC_PHASE_HOUND                 = 16178,
    NPC_DREADBEAST                  = 16177,
    NPC_SHADOWBEAST                 = 16176
};
```
are dead ONE of the bosses:

```c++
NPC_HYAKISS_THE_LURKER          = 16179,
    NPC_ROKAD_THE_RAVAGER           = 16181,
    NPC_SHADIKITH_THE_GLIDER        = 16180,
```

will spawn at following place:

```c++
const Position OptionalSpawn[] =
{
    { -10960.981445f, -1940.138428f, 46.178097f, 4.12f  }, // Hyakiss the Lurker
    { -10899.903320f, -2085.573730f, 49.474449f, 1.38f  }, // Rokad the Ravager
    { -10945.769531f, -2040.153320f, 49.474438f, 0.077f } // Shadikith the Glider
};
```

NOTE: There are 56 spawns for all trash creatures. but in the script, the boss will already spawn after 50 trash creatures are killed. I made it like this, because maybe some creatures will stuck in the map/fall below the map during the raid. I just want to be on the save side.

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
