### ISSUE TITLE
Leviathan MKII - Plasma blast

### ISSUE THREAD

**Issue by Dartheus** [dalaranwow/dalaran-wow#3940]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: The channeling of Plasma Blast can be broken by taunting the boss

**Expected behaviour**: Leviathan MKII should finish the cast, then attack the player that taunted

**Steps to reproduce the problem**:

1. Go to Mimiron
2. Start encouter and wait for Leviathan MKII to start channeling Plasma Blast on tank
3.  Have another player taunt, breaking the channel

**Include proofs for this behaviour**
WoWWiki states in all the strategy guides (and tankspot does too), that the damage has to be healed through

IDs:
33432 - NPC ID of Leviathan MK2
For some reason, WOWHead doesn't list his Plasma Blast in the abilities :(

**Comment by Rushor** [comment]
fix inc

**Comment by Rushor** [comment]
Scripts/Ulduar: Leviathan MKII - Add Tauntimmunity during EVENT_PLASMA_BLAST

* closes https://github.com/dalaranwow/dalaran-wow/issues/3940
* commit: fcaa77b2814402f700f8356c5ed5b91fd61ba5d1
* you are no longer able to taunt Leviathan MKII during the channel of Plasma blast

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
