### ISSUE TITLE
[Ulduar] Auriaya - Sentinel Add

### ISSUE THREAD

**Issue by Dartheus** [dalaranwow/dalaran-wow#3941]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Players are able to bug out the sentinel add after it dies for the first time by LoS'ing, eliminating it from the fight (as it just stands there)

**Expected behaviour**: Players should be able to use LoS to avoid the 'Feral Pounce' ability, but the NPC should be active throughout the fight.

**Steps to reproduce the problem**:

1. Start Auriaya encounter, wait for her to summon Feral Defender
2. Kill Feral Defender
3.  Break LoS on the dead feral defender
4. Feral defender revives, but doesn't rejoin the fight

**Include proofs for this behaviour**

https://www.youtube.com/watch?v=j21Fa6gpSug

34035 - Feral Defender (NPC)
64478 - Feral Pounce (Spell)

**Comment by Rushor** [comment]
Scripts/Ulduar: Auriaya - summoned add Feral Defender should always rejoin the fight

* also disable meleeattack for ferla defender while jumping
* closes https://github.com/dalaranwow/dalaran-wow/issues/3941
* commit: bc04e6170b7503af43df179e86edb368924a80b4

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by datbunneh** [comment]
@TeridanDW @Lothloryen This exploit is still on live, people avoid killing defender more than once by moving away and out of LoS after killing it.
