### ISSUE TITLE
Ragnaros spawns without any bosses dead and respawn after 60 minutes

### ISSUE THREAD

**Issue by SadhuArch** [dalaranwow/dalaran-wow#3947]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Ragnaros (ID: 11502) will spawn even if no boss has been killed. All you need to do is run towards Baron Geddon (ID: 12056) and right before you enter the next "zone" inside Molten Core, right beside a Dark Iron Deposit, Ragnaros will start screaming that Majordomo Executus (ID: 12018) has awakened him too soon. You know, the normal speech when Ragnaros is being summoned.

If you kill him and leave the instance for 60 minutes he will respawn and you can kill him all over again. This makes it way to easy to obtain the Eye of Sulfuras (ID: 17204) or any other item you would want from him.

**Expected behaviour**: Tell us what should happen instead
Ragnaros should only spawn/be able to be summoned when all other bosses are dead and Majordomo Executus has been defeated.

Ragnaros should only be able to be defeated once a week.

**Steps to reproduce the problem**:

1. Enter Molten Core
2. Run towards Baron Geddon
3. Just when you pass the Dark Iron Deposit leading into the next "zone" Ragnaros will spawn

**Include proofs for this behaviour**
As can be seen from this picture, I am not saved to Molten Core (thus not killed a single boss), yet Ragnaros has still been summoned. And had my cursor been seen it would have shown the "Attack" icon.
http://i.imgur.com/iXTNXOS.jpg

**Comment by Rushor** [comment]
Scripts/MoltenCore: Executus - Only summon Ragnaros if Executus was defeated

* closes https://github.com/dalaranwow/dalaran-wow/issues/3947
* commit: 6eca17c9beafaee9bdbcf0b364b049852974c2bf

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Jindra555** [comment]
This happened during a run in may 2018.
