### ISSUE TITLE
[NPC] High Admiral "Shelly" Jorrik

### ISSUE THREAD

**Issue by ImprezaWoW** [dalaranwow/dalaran-wow#3962]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
The NPC is not implemented in the game.
**Expected behaviour**: Tell us what should happen instead
He should be implemented at around 10.6;76 of Dun Morogh (Newman's Landing) and give the following reputations when killed (being the only NPC in the game that will continue to offer reputation with the Bloodsail Buccaneers all the way to 999/1000 Exalted):
+5 Bloosail Buccaneers
-25 Booty Bay
-12,5 Ratchet
-12,5 Gadgetzan
-12,5 Everlook
Or he should be available as a vendor (offers repair service) if you have the appropriate reputation with the Steamwheedle Cartel.

He _should_ be accompanied by two Booty Bay Bruisers, which are also missing.

**Include proofs for this behaviour**

http://wow.gamepedia.com/High_Admiral_%22Shelly%22_Jorrik
http://wowwiki.wikia.com/wiki/High_Admiral_%22Shelly%22_Jorrik

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
[High Admiral "Shelly" Jorrik](http://www.wowhead.com/npc=26081/high-admiral-shelly-jorrik) NPC ID 26081
[Booty Bay Bruiser](http://www.wowhead.com/npc=4624/booty-bay-bruiser) NPC ID 4624

**Comment by Rushor** [comment]
DB/Creature: Spawn High Admiral "Shelly" Jorrik (26081) with 2 Booty Bay Bruiser (4624)

* closes https://github.com/dalaranwow/dalaran-wow/issues/3962
* commit: 53030a7c44a57293308007092db7ceeff2b66295
* commit: baf30eb4aa00399f793b5a6d599a2f771bef0276

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
[![https://gyazo.com/5dce3c435078bd7f1a4f546b197e48cd](https://i.gyazo.com/5dce3c435078bd7f1a4f546b197e48cd.gif)](https://gyazo.com/5dce3c435078bd7f1a4f546b197e48cd)
