### ISSUE TITLE
[Death Knight] Unholy - Raise Dead/Ghoul Health bug

### ISSUE THREAD

**Issue by Frostflakes** [dalaranwow/dalaran-wow#3963]
**Description:**
As unholy death knight: summoning ghoul via. Raise Dead spell, ghoul appears with around 26 % health instead of 100 %

**Current behaviour**:
When i summon ghoul, with the above mentioned spell, it appears with around 26 % health, this happens consistently, whether i consume corpse dust, or a humanoid corpse. 
This seems only to affect ghouls that are spawned as pets with the "Master of Ghouls" talent active in the unholy talent tree.

**Expected behaviour**: 
The ghoul should appear with 100 % health.

**Steps to reproduce the problem**:
1. Have a death knight, with talent-setup as below:
2. Have humanoid corpse present or corpse dust in inventory.
3. Cast "Raise Dead". - Ghoul (pet) spawns with around 26 % health

**Proof of behaviour**:
https://youtu.be/G9qwqRoX7g0 

spell=52150 - ID for Raise Dead

![image](https://cloud.githubusercontent.com/assets/24523102/21099606/5b6b1bba-c06f-11e6-9753-a3716a8619f2.png) - This is the current talent setup i use.

**Comment by Rushor** [comment]
Reason: HP modifying auras are calculated after summon not before.

**Comment by Frostflakes** [comment]
It is not from HP modifying auras. 
The spell without investing talents in unholy tree, spawns the ghoul with around 11k hp, here it spawns with 5k. Even so, it should still spawn with 100 % hp.

**Comment by Rushor** [comment]
okay, going to add this feature " summon pets come with full health when called, but not when they are current"

**Comment by Rushor** [comment]
Game/Pet: Change order of aurapply after resummon + Set pethealth to max after initial summon

* closes https://github.com/dalaranwow/dalaran-wow/issues/3963
* commit: 4167d2cb1450fafb90636c94b9f30b9078243563

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by robinsch** [comment]
Merged with other issues.
