### ISSUE TITLE
[Ulduar] Flame Leviathan Fight and "Line of Sight"

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#3964]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
When demolishers fire their "fireball" or blue pyrite if another vehicle (only seen with siege tanks myself, nothing else is every close enough to flame leviathan for typical testing) is close to the boss and in the path the pyrite projectile takes then the demo's attacks wont hit flame leviathan.

There shouldn't be any kind of "line of sight" errors occuring, though it could be something weird like the siege's having a really tall hitbox and intercepting the projectiles or some weird shit like that, no real way to tell as far as I know player side.

**Steps to reproduce the problem**:
Hop in demo, fire pyrite at flame leviathan with a siege tank close to flame leviathan and inbetween the demo and flame leviathan. Proceed to not hit flame leviathan with pyrite and lose your stacks. 

**Include proofs for this behaviour**
Live Server? I don't have a decent way to get video (free recommendations?)

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

http://www.wowhead.com/npc=33109/salvaged-demolisher
http://www.wowhead.com/npc=33113/flame-leviathan

**Comment by Rushor** [comment]
Game/Spells: Flame Leviathan - Remove "Line of Sight" issues with Pyrit

* closes https://github.com/dalaranwow/dalaran-wow/issues/3964
* this hopefully fixed the spell http://wotlk.openwow.com/spell=62490. @Tester If the fix works, tell me the other spellids that need this "Line of Sight" adjustment and i will add them to the whitelist. Thank you
* commit: 109ce9482e40a141fc18eb816317c4230620e2cb

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
