### ISSUE TITLE
[Achievement] Argent Confessor

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#3972]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
No credit is given for any of the memories when defeating argent confessor paletress
http://www.wowhead.com/achievement=3802/argent-confessor
http://www.wowhead.com/achievement=3802/argent-confessor

**Comment by Rushor** [comment]
you did this on heroic?

**Comment by Rushor** [comment]
Scripts/TrialOfTheChampion: Implement Achievement Argent Confessor

* note: the instance is totally different on PTR then on live, so you cannot test this fix on PTR. Only loth can apply and test the fix on the live realm
* closes https://github.com/dalaranwow/dalaran-wow/issues/3972
* commit: e39f54ccce402291c4c862c01262b9a4ae46c7b9

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
