### ISSUE TITLE
[GO] Heavy Iron Portcullis + The Violet Hold + Workshop Door + The Shattered Halls + The Shadow Labyrinth lever isn't working

### ISSUE THREAD

**Issue by Klala** [dalaranwow/dalaran-wow#3973]
**Current behaviour**: Shadow Labyrinth door lever isn't working or touchable

**Expected behaviour**: Shadow Labyrinth door lever should be interactable and working to open the door from inside

**Steps to reproduce the problem**:

1. Go to the shadow labyrinth (before entering through the portal)
2. Notice the lever is not interactable.

**Comment by Rushor** [comment]
this issue also affects the levers for:

Heavy Iron Portcullis + The Violet Hold + Workshop Door + The Shattered Halls + The Shadow Labyrinth

**Comment by Rushor** [comment]
DB/Gameobject: Several Doors are now longer usable while using the lever 

* this fixes Heavy Iron Portcullis + The Violet Hold + Workshop Door + The Shattered Halls + The Shadow Labyrinth
* also make the lever of The Shadow Labyrinth intractable
* closes https://github.com/dalaranwow/dalaran-wow/issues/3973
* commit: ac764adbb9d56847ce0151d1c65bd9081d5fec5f

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
