### ISSUE TITLE
[Ulduar] Freya trash not respawning properly

### ISSUE THREAD

**Issue by Dartheus** [dalaranwow/dalaran-wow#3993]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Trash in Conservatory of Life doesn't respawn

**Expected behaviour**: Trash should respawn both on 'hardset timer' (~2hours) (you can see this eg. after the first mob is killed, DBM will start counting down the respawn. It should also respawn of 30minute soft reset (when at least 30minutes noone has been in the instance)

**Steps to reproduce the problem**:

1. Kill Freya trash
2. Wait
3. Trash doesn't respawn

**Include proofs for this behaviour**

www.mmo-champion.com/threads/1079628-Freya-s-Elders-Bug

http://www.elitepvpers.com/forum/wow-guides-templates/262270-solo-farming-freya-trash-shitload-frost-lotus.html

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

I will add all the mob IDs when i get home :'(

**Comment by Rushor** [comment]
-33430
-33431
-33528
-33525
-33526
-33527
-33355
-33354

**Comment by Rushor** [comment]
Scripts/Ulduar: Respawn Freya Trash every 2 hours if Freya wasn't killed

* closes https://github.com/dalaranwow/dalaran-wow/issues/3993
* commit: cdefbaffec6ad48bbbe88c1d7b89c1fcd61a982d

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
