### ISSUE TITLE
[Ulduar] Conservatory of Life - Herb Farming

### ISSUE THREAD

**Issue by Dartheus** [dalaranwow/dalaran-wow#3995]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Herbalism nodes respawn in CoL even after Freya is defeated

**Expected behaviour**: They should only respawn until Freya is defeated (like the trash) 

**Steps to reproduce the problem**:

1. Go to Ulduar
2. Defeat Freya encounter
3. You can farm CoL for herbs since they respawn

**Include proofs for this behaviour**

http://www.wowhead.com/forums&topic=102318/conservatory-of-life

https://www.youtube.com/watch?v=vIRkD7oogQU

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

n/a

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment]
Scripts/Ulduar: Freya - Herbs in Conservatory of Life will no longer be available if Freya was defeated

* closes https://github.com/dalaranwow/dalaran-wow/issues/3995
* commit: a2d78fb5741fdc6395a5c88b4f4ae1a1dce64601

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
