### ISSUE TITLE
[Quest][Northrend] Rescue from Town Square

### ISSUE THREAD

**Issue by stauner42** [dalaranwow/dalaran-wow#4000]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: When trying to complete the quest, I kill the Geists and am not receiving any credit for doing so. -NOTE- this is on a hunter if that makes a difference.
**Expected behaviour**: Obviously, I should be getting credit for doing so.

**Steps to reproduce the problem**:

1. I've tried killing the mobs up close to the people to be rescued
2. I've tried without using a pet
3. Every time it gives me their little "thank you!" speech and they run off and i never receive credit

**Include proofs for this behaviour**

Not entirely sure what to do here... I've provided screenshots of the geist dying, the villager doing the "thank you!" speech, etc.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Quest ID: 12253, NPC ID: 27359 (villagers), 27370 (geists)

**Include Screenshots from the issue if necessary**

![wowscrnshot_122216_020524](https://cloud.githubusercontent.com/assets/24712488/21419155/8fa2956a-c7eb-11e6-9325-80acf441b9e1.jpg)
![wowscrnshot_122216_020530](https://cloud.githubusercontent.com/assets/24712488/21419156/8fa439b0-c7eb-11e6-92ac-b2f2788aa5b7.jpg)

Also, i hope i did alright in the formatting. I've never done this before. lol

**Comment by Rushor** [comment]
The issue was fixed in https://github.com/TrinityCore/TrinityCore/commit/3e4b83bb33a32a9a5d832573d2c78c5aa1dc9354 back in the days.

**Comment by Rushor** [comment]
http://wotlk.openwow.com/quest=12253

**Comment by Rushor** [comment]
DB/Quest: Add script for 'Rescue from Town Square'

* closes https://github.com/dalaranwow/dalaran-wow/issues/4000
* commit: 0dfe720e3d01f29f332a1aa3c4eb47c2bd466316

![GitHub Logo](http://i.imgur.com/L4s8kbC.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
