### ISSUE TITLE
[Instance] - Old Hillsbrad Foothills

### ISSUE THREAD

**Issue by Klala** [dalaranwow/dalaran-wow#4019]
**Current behaviour**: If you wipe in the instance while escorting thrall and thrall dies, he respwans after a while in his cage correctly but you cannot talk to him to restart the escort

**Expected behaviour**: Thrall should have the gossip talk to restart the escort if the party wiped.

**Steps to reproduce the problem**:

1. Go into Old hillsbrad foothills (might be only in heroic but I assume in happens in normal too)
2. Kill the first boss and proceed to talking to thrall. While you escort him, die and walk back, wait for him to respawn and try to talk to him.
3. Notice that the gossip windows doesn't open up.

**Comment by Rushor** [comment]
Scripts/EscapeFromDurnholdeKeep: Thrall - set active on start of escortevent

* closes https://github.com/dalaranwow/dalaran-wow/issues/4019
* commit: 60b96c6555c5dd3656b8b7a67b27f675704919f7

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
