### ISSUE TITLE
[Quest][TBC] Dragonmaw Race: Wing Commander Mulverick

### ISSUE THREAD

**Issue by datbunneh** [dalaranwow/dalaran-wow#4033]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Range check is too harsh

**Expected behaviour**: Range check should allow longer distances

Sometimes he gets a boost in speed and it's simply impossible to keep up on 280% mount. Moreover it get harder cause he has some mistuning in his waypoints and at some points he starts suddenly flying in opposite direction and after a couple of seconds turns around once again. The last thing can be actually applied to other quests from these series as well.

**Steps to reproduce the problem**:

1. Get this quest
2. Get a little bit behind
3. Get your "Quest Failed" message

**Include proofs for this behaviour**

https://www.youtube.com/watch?v=Lkn3PARLpPE

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Quest - 11070

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment]
DB/Quest: Dragonmaw Race: Wing Commander Mulverick - Only fail quest if player is at least 100 yards away from Mulverick

* closes https://github.com/dalaranwow/dalaran-wow/issues/4033
* commit: 0845ce67b44fc15222131e490b03e9531ca019eb
* range was increased from 55 to 100 yards.

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by magicbunneh** [comment]
@Rushor Thanks!

**Comment by Rushor** [comment]
too much bunnehs in this bugtracker xd

**Comment by datbunneh** [comment]
@Rushor, damn, it was wrong account. And you're wrong - there are never enough bunnehs! :P

**Comment by alexuktc** [comment]
Hello. 

I know this issue is closed, but I do not know what you mean when you say that it is fixed. Here is my take on the issue (counting what Bunneh mentioned).

1. I have a 310% mount and I can barely keep up. Sometimes they slow down, sometimes they speed up incredibly. Anyway, this is doable by doing this several times and memorizing the path to a point where you're no longer following him. 
2. THE real issue - the projectiles for ALL riders are way too fast. And I mean WAY too fast. 
The easiest way would be for you to test it yourselves on Algalon and compare with this video I will provide for you. Granted the video is from a later patch, but apart from the change where you're no longer dismounted there have been no changes to this quest line. 
A millisecond of not paying absolute attention and you are thrown from your mount, quite possibly to your death. And unlike retail you have to follow him very closely, as he gets random speed boost which fail the quest for you. 

https://www.youtube.com/watch?v=Lkn3PARLpPE - Shows how the quest should be done.

**Comment by Rushor** [comment]
on PTR you no longer get dismounted by the spellhit, that was fixed an an other issue here - the fix needs to be moved to the live realm.
