### ISSUE TITLE
[ToC][Boss] Anub'arak missing a boss emote

### ISSUE THREAD

**Issue by zykadelic** [dalaranwow/dalaran-wow#4100]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

### Current behaviour
Anub'arak doesn't give the "emerges from the ground!" boss emote, causing Deadly Boss Mods timers to never show up for the second submerge or any of the adds after the first submerge. An excerpt from the chat log, where Anub had 1 submerge before reaching phase 3:

*[00:03] Anub'arak yells: This place will serve as your tomb!
**[00:04] Anub'arak burrows into the ground!
[00:04] Anub'arak's spikes pursue Dassemultor!**
[00:04] Anub'arak yells: Ahhh, our guests have arrived, just as the master promised.
**[00:04] Anub'arak's spikes pursue Morhgodt!
[00:04] Anub'arak's spikes pursue Korigosa!
[00:05] Anub'arak's spikes pursue Bajer!
[00:06] Anub'arak unleashes a Leeching Swarm to heal himself!**
[00:06] Anub'arak yells: The swarm shall overtake you!*

### Expected behaviour
Anub'arak should give the "emerges from the ground!" boss emote, causing DBM timers to correctly trigger. The emote can be seen in [this video from retail](https://www.youtube.com/watch?v=N7sZ1C-1Bv4&t=3m30s).

### Steps to reproduce the problem  
1. Engage Anub'arak
2. See him give the "burrows into the ground!" boss emote upon burrow
3. See him *not* give the "emerges from the ground!" boss emote upon emerge

**Comment by Rushor** [comment]
yes the emote is in the DB and it's defined in the script, but it's not called in EVENT_EMERGE

**Comment by Rushor** [comment]
Scripts/TrialOfTheCrusader: Anub'Arak - Enable Emerge Emote in script

* closes https://github.com/dalaranwow/dalaran-wow/issues/4100
* commit: 0fbbb9357b1ccf2acb38514975abbb4599e76f74

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by zykadelic** [comment]
Thanks @Rushor!
