### ISSUE TITLE
Flight Master Nethestrasz at Wyrmrest Temple is below the ground

### ISSUE THREAD

**Issue by SadhuArch** [dalaranwow/dalaran-wow#4108]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
The flight master (Nethestrasz (ID: 26851)) at Wyrmrest Temple in Dragonblight is below the ground and it is not possible to talk to him.

**Expected behaviour**: Tell us what should happen instead
He should be above the ground and players should be able to use his flight services.

**Steps to reproduce the problem**:

1. Visit Wyrmrest Temple
2. Try to speak to Nethestrasz

**Include proofs for this behaviour**
![wowscrnshot_010317_102352](https://cloud.githubusercontent.com/assets/4154311/21603770/cdc58ce0-d19f-11e6-888b-811107034863.jpg)

**Comment by Rushor** [comment]
DB/Creature: Flight Master Nethestrasz - should no longer drop below the ground

* closes https://github.com/dalaranwow/dalaran-wow/issues/4108
* commit: 432ef4947220f600c04d91858909ab0423005b57

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
