### ISSUE TITLE
Quest: Sabotage the Warp-Gate!

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#413]
http://www.wowhead.com/quest=10310

**Issue:** The NPC doesn't move upon picking up the escort quest.

**How it should work:** You have to escort the NPC to the warp-gate at "Invasion Point: Destroyer" and protect him while he attempts to sabotage it.

Drijya - http://www.wowhead.com/npc=20281

**Comment by ashido96** [comment]
When this quest nothing happens and when you attempt to turn in quest without completion status as described above it is not able to be turned in. (Most likely broken in the recent large update)

**Comment by Demlock** [comment]
Confirmed. Still not working.

**Comment by catta000** [comment]
Still not working.. NPC does not move and quest can not be completed.

**Comment by DrFuler** [comment]
17/12/2015: Still not working.

**Comment by MrAndersonX** [comment]
Confirmed - bugged.

**Comment by Zibathy** [comment]
Still bugged,

**Comment by Rushor** [comment]
048da1910b1712998eda40459911a5ef4a461de2
- added the whole escortevent

**Comment by Rushor** [comment]
DB/Quest: Sabotage the Warp-Gate! - Move script to database

* updates: https://github.com/dalaranwow/dalaran-wow/issues/413
* commit: 048da1910b1712998eda40459911a5ef4a461de2
* commit: dbfd9cb260619cedc6cca13c456afecc9899a2a5

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
