### ISSUE TITLE
[ToC] Twin Val'kyr's not sharing health correctly

### ISSUE THREAD

**Issue by SadhuArch** [dalaranwow/dalaran-wow#4168]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
This happened in Trial of the Grand Crusader 10-man. At the exact same time as Fjola Lightbane died, Eydis Darkbane used her shield. This made the fight bug in the following way:

All the light portals despawned together with the light buff that players had taken, only the dark portals and dark buff (on players) were left. Also all the orbs that fly around disappeared, both light and dark.

This creates a couple of secondary issues, mainly that it's hard, if not impossible to destroy the shield because no one has the correct buff and the ones that do have a buff have the wrong one. In this case the dark buff which happened to be the one that makes players do reduced damage against the target that was still alive (Eydis Darkbane).

**Expected behaviour**: Tell us what should happen instead
They should share health pool, health point for health point, if one of them dies both should die.

**Steps to reproduce the problem**:

1. Kill one of them just as the other one pops her shield ability (Shield of Darkness (10HC spell ID: 67257) / Shield of Lights (10HC spell ID: 67260)

**Include proofs for this behaviour**

These screenshots and short clip was taken after the shield and her (Eydis Darkbane (NPC ID: 34496)) heal (Twin's Pact (spell ID: 67305). Fjola Lightbane (NPC ID: 34497) can be seen lying there dead while her twin is still alive.
http://i.imgur.com/4PJwOHj.jpg
http://i.imgur.com/rJeOwwa.jpg
https://www.youtube.com/watch?v=mLXH_1fAmog

**Comment by Rushor** [comment]
Scripts/TrialOfTheCrusader: Twin Valkyr - Rework the whole encounter (HP Share should work correctly now)

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4168
* commit: 254967ae48ae48431ca13209e53360e1eb5deb82

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
