### ISSUE TITLE
[Item] Goblin Gumbo

### ISSUE THREAD

**Issue by ImprezaWoW** [dalaranwow/dalaran-wow#4193]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
The buff Goblin Gumbo from the consumable Goblin Gumbo which comes from Goblin Gumbo Kettle has no visual or sound effect. 
**Expected behaviour**: Tell us what should happen instead
[Quoting:](http://www.wowhead.com/item=33219/goblin-gumbo-kettle#comments:id=137547)
>This effect from the actual Gumbeaux may trigger while mounted or on a taxi. The buff is a poison effect, and causes the user to burp green smoke similar to that from Fiery Festival Brew ( //www.wowhead.com/?item=23246 ).

**Include proofs for this behaviour*
https://www.youtube.com/watch?v=5hju9GTvKEo
**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Goblin Gumbo consumable item ID 33218

**Comment by Rushor** [comment]
fix incoming

**Comment by Rushor** [comment]
Scripts/Spells: Implement Goblin Gumbo Kettle

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4193
* commit: 0dddb6737dccafc00bb077f56b7660f88aed5f09

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
