### ISSUE TITLE
Druid: Swipe (Bear)

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#420]
**Issue:** "Swipe (Bear)" is usable regardless the distance there is between the druid and his target. If there is more than 8 yards distance, then it will consume rage but it won't deal any damage unless there are any nearby mobs.

The spell should be usable only if your target is maximum 8 yards away.

**Comment by robinsch** [comment]
https://www.youtube.com/watch?v=-vt1gim7obQ
5:35

Indicator is still white even tho nobody is within 8 yards. Also TARGET_CASTER_COORDINATES, TARGET_ALL_ENEMY_IN_AREA should not check if a target would be hit by the spell in order to cast it. This is the same logic for Arcane Explotion.

Closing this - if you want to reopen it please post a valid proof.
