### ISSUE TITLE
[Boss] - Pyroguard Emberseer

### ISSUE THREAD

**Issue by Klala** [dalaranwow/dalaran-wow#4228]
**Current behaviour**: Currently Pyroguard Emberseer gives 250 reputation with Hydraxian Waterlords at Honored.

**Expected behaviour**: Pyroguard Emberseer gives 20 reputation with Hydraxian Waterlords at Honored.

**Steps to reproduce the problem**:

1. Go to UBRS and kill Pyroguard Emberseer while you are honored with Hydraxian Waterlords.
2. Notice you get 250 reputation.

http://wowwiki.wikia.com/wiki/Pyroguard_Emberseer?oldid=1884739

**Comment by Rushor** [comment]
DB/Creature: Pyroguard Emberseer - Update reputationreward

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4228
* commit: d8eec7e15b4a0f220bc63eb60ac28c49aa40fedb

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
