### ISSUE TITLE
Trial of the Sea Lion (Horde) Objective Missing

### ISSUE THREAD

**Issue by Zibathy** [dalaranwow/dalaran-wow#4266]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

Hello once again,

I am unable to acquire the second part of the pendant for the quest Trial of the Sea Lion (Horde). It is simply not there. I did nothing special that I am aware of other than be on **Kirin Tor**, which is where the bug is present. This was previously reported and closed because it was "working as intended", but the world object does not exist in the world as far as I can tell.

![wowscrnshot_011817_191601](https://cloud.githubusercontent.com/assets/7729864/22089784/0a74aecc-ddb3-11e6-8d5a-34c2b3cf3c41.jpg)
![wowscrnshot_011817_191606](https://cloud.githubusercontent.com/assets/7729864/22089785/0a775b68-ddb3-11e6-96ab-150d880d5bbc.jpg)

These three are taken at almost the exact same angles and locations as in the youtube video (~3:01, ~3:12, ~3:18):

![wowscrnshot_011817_193121](https://cloud.githubusercontent.com/assets/7729864/22090061/ea6b3964-ddb4-11e6-88d0-10e115da43cc.jpg)
![wowscrnshot_011817_193136](https://cloud.githubusercontent.com/assets/7729864/22090063/ea6ee7da-ddb4-11e6-93de-f512ce0bbecd.jpg)
![wowscrnshot_011817_193149](https://cloud.githubusercontent.com/assets/7729864/22090062/ea6b83c4-ddb4-11e6-8eeb-6fa522606d72.jpg)

Video of where the second piece of the pendant should be/reference: 

https://www.youtube.com/watch?v=VW6Rm7XVLEM

Thank you,

zibathy

**Comment by Rushor** [comment]
yes the object is indeed missing. However you can currently complete the quest if you use that object http://wotlk.openwow.com/object=177792.

But you are right, the object and the Bubbly Fissure must be spawned in Silverspine Forest too.

**Comment by Rushor** [comment]
DB/Gameobject: Add spawn for Strange Lockbox + Bubbly Fissure in Silverspine Forest

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4266
* commit: 163ce92721c8c6989776f9c965648036582f60bf

![GitHub Logo](http://i.imgur.com/0CKTOJq.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Zibathy** [comment]
Thank you very much!
