### ISSUE TITLE
[NPC][WotlK] Ironwool Mammoth, Part 1, mini event

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4272]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Ironwool Mammoth http://wotlk.openwow.com/npc=29402 has a mini event that is missing on the server.
![wowscrnshot_012017_145108](https://cloud.githubusercontent.com/assets/6797611/22151704/eead095c-df27-11e6-8e25-97d54e7f5595.jpg)

**Expected behaviour**: I have recored a video from current retail, but i will also add the missing elements here:
1) Ironwool Mammoth should be spawned dead. (currently he is spawned alive and moving)
2) The Savage Hill Brute http://wotlk.openwow.com/npc=29623 (next to the mammoth) should be constantly chopping the dead mammoth.

The other npcs in the area are ok. Here is the video from retail legion from 20.01.2017:
https://www.youtube.com/watch?v=wvxcjplMrZs

**Comment by Rushor** [comment]
really nice report, ty!

**Comment by Rushor** [comment]
i will fix it this evening mate

**Comment by Teridan-dal-wow** [comment]
Thanks for the swift answer Rushor, that motivates me to more.

**Comment by Rushor** [comment]
DB/Creature: Ironwool Mammoth - Update Emotestate and Creature Addon

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4272
* commit: 795165bd8e5fb66e4fbe87bb0c1866c4c6398460

![GitHub Logo](http://i.imgur.com/8pe2mGp.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Teridan-dal-wow** [comment]
Feedback for this report from TrinityCore rev. 02633a332cf7 2017-02-09.
Works exacly like on retail, Thanks for your work!
