### ISSUE TITLE
[NPC][Classic] Caer Darrow's Citizens

### ISSUE THREAD

**Issue by Klala** [dalaranwow/dalaran-wow#4277]
**Current behaviour**: Currently there are no citizens in Caer Darrow, also Magnus Frostwake is visible to everyone.

**Expected behaviour**: There should be citizens in Caer Darrow and Magnus Frostwake should be invisible to anyone who doesn't have the Spectral Essence equipped.

**Missing NPCs**: http://wowwiki.wikia.com/wiki/Caer_Darrow?oldid=2302176#Specters_of_Caer_Darrow

**Steps to reproduce the problem**:

1. Go to Caer darrow, put on your "Spectral Essence" (which must be on you to be able to see them.)
2. Notice that the only npc that is currently correctly becomes visible is Magister Marduke

http://wowwiki.wikia.com/wiki/Magnus_Frostwake?oldid=2370854
https://www.youtube.com/watch?v=CsyIL5bcqqQ
https://www.youtube.com/watch?v=Fi-b8BBcqdY
https://www.youtube.com/watch?v=5KplwEDKdQc
https://www.youtube.com/watch?v=3DZ3p8VdkeU

Videos are from retail cataclysm, however as a retail veteran I can assure you these patrol routes and npc locations are correct for wotlk version.

Also I should note that Artist Renfray is indeed part of the Caer Darrow's ghosts but does not require you to have the Spectral Essence equipped since she is also a quest giver and currently works fine, there is no mention of people having trouble to find her for her quest related sections in the wowhead comments too so I'm assuming I am correct.

**Comment by Rushor** [comment]
@Klala 

DB/Creature: Caer Darrow's Citizens - Add Spawns, Paths and Events with Melia and Sammy

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4277
* commit: 7ff3153bf92ff06a80c79d4d14b34f04d42c1f4d

![GitHub Logo](http://i.imgur.com/XfHzgT5.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
