### ISSUE TITLE
[NPC][WotlK] Snowblind Devotee, missing emote, wps

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4287]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 
Part 1-Npc Snowblind Devotee http://wotlk.openwow.com/npc=29554 is missing his emotes:
![wowscrnshot_012217_124724](https://cloud.githubusercontent.com/assets/6797611/22181974/960d310c-e0a1-11e6-83b9-ea772c47dfeb.jpg)

Part 2-Npc Snowblind Devotee http://wotlk.openwow.com/npc=29554 is missing a mini event around the teleporter(check the video below)

Part 3-Npc Snowblind Devotee http://wotlk.openwow.com/npc=29554 is missing a patrole route (check end of video below).

Part 4-Npc K3 Snow Runner http://wotlk.openwow.com/npc=29546 is spawned dead(but he is standing and walking around).
**Expected behaviour**: Video from retail legion from 22.01.2017:
https://www.youtube.com/watch?v=pBqZwKIAIOs

**Comment by Rushor** [comment]
really nice report, ty so much!

**Comment by Rushor** [comment]
alright some data on this for scripting it this evening:

attack:
Emote ID: OneShotAttack1H (36)

caster:
Emote ID: OneShotSpellCast (51)

**Comment by Rushor** [comment]
DB/Creature: Add missing emote and waypoints for Snowblind Devotee

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4287
* commit: db4440806ec559d097d9c1d1f6d3c599fac08654

![GitHub Logo](http://i.imgur.com/VvlitPf.jpg)
![GitHub Logo](http://i.imgur.com/xrJ1OsU.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Teridan-dal-wow** [comment]
Feedback for this report from TrinityCore rev. 02633a332cf7 2017-02-09.
Works exacly like on retail. Thank you for your work!

**Comment by Rushor** [comment]
DB/Creature: Snowblind Devotee - simplify GUID script with new `saiscriptflag`

* updates: https://github.com/dalaranwow/dalaran-wow/issues/4287
* commit: 36580eb060e069c2995d6137867c2fe1642c83d1
