### ISSUE TITLE
[NPC][WotlK] Injured Goblin Miner, missing emote

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4294]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Npc Injured Goblin Miner http://wotlk.openwow.com/npc=29434 is standing currently on the server.
![wowscrnshot_012317_121913](https://cloud.githubusercontent.com/assets/6797611/22200138/88b2783a-e166-11e6-8e7a-c6a646c97808.jpg)

**Expected behaviour**: He should be lying down on the ground. Screenshot from retail:

![wowscrnshot_012317_121920](https://cloud.githubusercontent.com/assets/6797611/22200229/e7f3017a-e166-11e6-9e10-34da26540a7e.jpg)

**Comment by Rushor** [comment]
the emote will look in wotlk a bit different, cuz the models were changed, but i will add it :)

**Comment by Rushor** [comment]
Scripts/Storm Peaks: Injured Goblin - Add Emotestates on Reset and remove them on quest accept

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4294
* commit: 81ac8b748273361e5d0b6e71213d4fa57335313c

![GitHub Logo](http://i.imgur.com/S98RifS.png)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Teridan-dal-wow** [comment]
This fix is not added to Trinitycore, so i cant give any feedback :(
