### ISSUE TITLE
[NPC][WotlK] Hyldnir Overseer and Overseer Syra, missing path, spawn

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4304]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Area relevent to this report:
![wowscrnshot_012417_113217](https://cloud.githubusercontent.com/assets/6797611/22241891/f18ddd68-e229-11e6-966d-9449c797d7ba.jpg)

 - Part 1: Npc Hyldnir Overseer http://wotlk.openwow.com/npc=29426 has its path missing and there should be 2 of them patroling the cave, currently on the server we have 1 and she is just standing.
![wowscrnshot_012317_140508](https://cloud.githubusercontent.com/assets/6797611/22241979/453fab4e-e22a-11e6-8ba2-0e4f03f0ae1b.jpg)

 - Part 2: Npc Overseer Syra http://wotlk.openwow.com/npc=29518 has an incorrect path and respawn timer.
![wowscrnshot_012417_113302](https://cloud.githubusercontent.com/assets/6797611/22242058/9a2b01e4-e22a-11e6-82ac-04d2fbd76f25.jpg)
 She is not suppose to go upstairs and her respawn timer is higher than it should be.
Proof for respawn timer: https://www.youtube.com/watch?v=wy7nzIl0OhY

**Expected behaviour**: Video from retail legion from 24.01.2017:
https://www.youtube.com/watch?v=wnQfnfWO8ts

**Comment by Rushor** [comment]
perfectly sniffed, thanks a lot!

**Comment by Rushor** [comment]
DB/Creature: Storm Peaks - Hyldnir Overseer and Overseer Syra- Add missing path, spawn

* add one missing Hyldnir Overseer spawn + 2 paths
* correct Path of Overseer Syra
* reduce respawntimer of Overseer Syra
* closes: https://github.com/dalaranwow/dalaran-wow/issues/4304
* commit: 41b8dc3e7b4669dae7f1fbb8e67cd4d0908f8c99

![GitHub Logo](http://i.imgur.com/jsTRn5T.jpg)
![GitHub Logo](http://i.imgur.com/B2KH9wW.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Teridan-dal-wow** [comment]
Feedback for this report from TrinityCore rev. 02633a332cf7 2017-02-09.

Found a bug here:
 - This Hyldnir Overseer that you have already added a path
![453fab4e-e22a-11e6-8ba2-0e4f03f0ae1b](https://cloud.githubusercontent.com/assets/6797611/22840921/18537578-efd8-11e6-863a-127b81039674.jpg)
 has a wrong faction (i asume) as he is attacking the exhausted vrykul here:
![wowscrnshot_021017_213226](https://cloud.githubusercontent.com/assets/6797611/22841041/98ba1e56-efd8-11e6-8b98-901439696790.jpg)

Works exacly like on retail. Thank you for your work!

**Comment by Rushor** [comment]
yes that faction issue was fixed on dalaran-wow only (not on tc)
