### ISSUE TITLE
[NPC][WotlK] Stormforged Tracker, missing paths

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4310]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Npc Stormforged Tracker http://wotlk.openwow.com/npc=29652 has its paths missing.
![wowscrnshot_012417_173602](https://cloud.githubusercontent.com/assets/6797611/22254091/52544f6a-e25c-11e6-82e5-2dd200fdc651.jpg)

**Expected behaviour**: Video from retail legion from 24.01.2017:
https://www.youtube.com/watch?v=c5XzO9JziWE

**Comment by Rushor** [comment]
perfectly sniffed, great!

**Comment by Rushor** [comment]
DB/Creature: Stormforged Tracker - Add missing Paths in Stormpeaks 

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4310
* commit: 96b38b71b3e4a475fa558d9e0b77a624c5301bad


![GitHub Logo](http://i.imgur.com/C1LmM8P.jpg) - The blue points are the new added paths

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
