### ISSUE TITLE
[NPC][WotlK] Son of Hodir, missing emote

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4314]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Npc Son of Hodir http://wotlk.openwow.com/npc=30262 has an attack emote that is missing.
Emote should happens every 30 secs.
Note: This is relevent only for the Sons of Hodir in Dun Niffelem:
![wowscrnshot_012517_104552](https://cloud.githubusercontent.com/assets/6797611/22283606/d6d34c70-e2eb-11e6-8564-660c3fe4047b.jpg)

**Expected behaviour**: Video from retail legion from 25.01.2017:
https://www.youtube.com/watch?v=9dKlyaED2NA

**Comment by Rushor** [comment]
lol blizz made a mistake, they even do the emote while running xd

well we well script it like that :)

**Comment by Rushor** [comment]
![](https://i.gyazo.com/ed21e1c80a9f367b21ab3c8c060329cc.gif)

**Comment by Rushor** [comment]
DB/Creature: Storm Peaks - Son of Hodir - Add Attackemotespell

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4314
* commit: 9219d75d46991af8807716f9bfa8f8282439bbea

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Teridan-dal-wow** [comment]
Feedback for this report from TrinityCore rev. 02633a332cf7 2017-02-09.

Works exacly like on retail. Thank you for your work!
