### ISSUE TITLE
[NPC][WotlK] Plains Mammoth, missing emote

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4316]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Npc Plains Mammoth http://wotlk.openwow.com/npc=30448 has a missing emote.
Emote should happens every 45 secs.
![wowscrnshot_012517_121718](https://cloud.githubusercontent.com/assets/6797611/22286534/3e5bbcd6-e2f8-11e6-8bd6-466da05a51da.jpg)

**Expected behaviour**: Video from retail legion from 25.01.2017:
https://www.youtube.com/watch?v=bKg5MumJLy4

**Comment by Rushor** [comment]
DB/Creature: Storm Peaks - Plains Mammoth - Increase Randommove + Add script for emote

* Plains Mammoth  will now do the emote the first time after 4 - 12 seconds and after that repeats it every 45 seconds
* closes: https://github.com/dalaranwow/dalaran-wow/issues/4316
* commit: fd195d61a569e8b7746aeca4ea9565e716539cd3

![GitHub Logo](http://i.imgur.com/O34bxzV.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Teridan-dal-wow** [comment]
I missed that 1 of these Mammoths has a path, here is it:
Part 2- https://www.youtube.com/watch?v=R1l2iuNA6ck
