### ISSUE TITLE
[NPC][WotlK] The Iron Watcher, missing emote

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4321]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Npc The Iron Watcher http://wotlk.openwow.com/npc=30142 is missing an emote when you engage him.
![wowscrnshot_012617_100212](https://cloud.githubusercontent.com/assets/6797611/22323944/b34be3ca-e3ae-11e6-94b3-5b2b5d5ddfcd.jpg)

**Expected behaviour**: He should use:
![wowscrnshot_012617_094422](https://cloud.githubusercontent.com/assets/6797611/22323952/cfb6ea6e-e3ae-11e6-9b12-ac9527777fc4.jpg)

Emote:
[09:43:16] Creaking echoes off of the nearby structures as the Iron Watcher comes to life.

**Comment by Rushor** [comment]
I love all you work man - keep it up! :)

**Comment by Rushor** [comment]
DB/Creature: Stomrpeaks - The Iron Watcher - Add Emote on Aggro

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4321
* commit: f91dd69cc826e4288f576a0b7009d93ccaf76730

![GitHub Logo](http://i.imgur.com/DaowGgt.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
