### ISSUE TITLE
[NPC][WotlK] Iron Sentinel <Servant of Loken>, missing spawn

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4323]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Npc Iron Sentinel <Servant of Loken> http://wotlk.openwow.com/npc=29984 has 1 missing spawn location here:
![wowscrnshot_012617_112937](https://cloud.githubusercontent.com/assets/6797611/22326326/dbdf4906-e3ba-11e6-935e-27e9fd84f0c8.jpg)

**Expected behaviour**: Screenshot from retail:
![wowscrnshot_012617_112942](https://cloud.githubusercontent.com/assets/6797611/22326349/eeb921f0-e3ba-11e6-91b2-dd26d5da79d4.jpg)

**Comment by Rushor** [comment]
DB/Creature: Stomrpeaks - Iron Sentinel - Add one missing spawn

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4323
* commit: 944430e7a6ad4d86380503f3a07048bff5b3ecdf

![GitHub Logo](http://i.imgur.com/m5Sutp8.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Teridan-dal-wow** [comment]
Just a small note, he is facing the wrong direction on your screenshot :)

**Comment by Rushor** [comment]
@Teridan-dal-wow yes because it was a handmade spawn. would you like to fly to this guy again and sniff it pls? then i can add the correctly xyz and orientation data! thank you

**Comment by Teridan-dal-wow** [comment]
Sure, file will be up in 1 min.

**Comment by Teridan-dal-wow** [comment]
Done

**Comment by Rushor** [comment]
k done, thx!

![GitHub Logo](http://i.imgur.com/at0pHaY.jpg)

**Comment by Teridan-dal-wow** [comment]
Feedback for this report from TrinityCore rev. 02633a332cf7 2017-02-09.

Works exacly like on retail. Thank you for your work!
