### ISSUE TITLE
[NPC][WotlK] Library Guardian and Databank, missing spell, wrong movement

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4324]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Part 1: Npc Library Guardian http://wotlk.openwow.com/npc=29724 is:
 - missing a channeling spell http://wotlk.openwow.com/spell=55134 when out of combat (chech video below)
 - having too small random movement radius
![wowscrnshot_012617_114452](https://cloud.githubusercontent.com/assets/6797611/22326796/e219d050-e3bc-11e6-967d-d186f94a5df8.jpg)

Part 2: Npc Databank http://wotlk.openwow.com/npc=29746 is randomly moving, however it shouldn't move at all.
![wowscrnshot_012617_120347](https://cloud.githubusercontent.com/assets/6797611/22327383/96e60754-e3bf-11e6-8a0e-4b6edead0cf2.jpg)

**Expected behaviour**: Video from retail legion from 26.01.2017:
https://www.youtube.com/watch?v=QXGWLEx8YaY
 - Library Guardian uses the channel spell http://wotlk.openwow.com/spell=55134 once every 60 secs (they are not sync-ed with other guardians).
 - Library Guardian uses randomly 1 of these speeches before he channels (1 sec delay between speech and start of channel):
[12:02:29] Library Guardian says: Assessing database integrity ...
[12:02:13] Library Guardian says: Running a level three diagnostic ...
[12:01:37] Library Guardian says: Verifying encryption key ...
[12:01:16] Library Guardian says: Defragmenting swap file ...
[12:00:33] Library Guardian says: Assessing database integrity ...
[12:00:17] Library Guardian says: Running a level three diagnostic ...
[11:59:28] Library Guardian says: Assessing database integrity ...
[11:59:11] Library Guardian says: Implementing new security protocols ...
[11:58:28] Library Guardian says: Attempting to restore lost data ...
[11:58:10] Library Guardian says: Assessing database integrity ...
[11:57:25] Library Guardian says: Implementing new security protocols ...
[11:57:11] Library Guardian says: Assessing database integrity ...
[11:56:24] Library Guardian says: Assessing database integrity ...
[11:56:15] Library Guardian says: Assessing database integrity ...
[11:55:28] Library Guardian says: Implementing new security protocols ...
[11:55:08] Library Guardian says: Attempting to restore lost data ..

Note: The player needs to be very close to the guardian in order to "see" what they are saying.

**Comment by Teridan-dal-wow** [comment]
Npc Databank http://wotlk.openwow.com/npc=29746 is a flyer.

**Comment by Rushor** [comment]
DB/Creature: Stormpeaks - Library Guardian and Databank - Add missing Event

* increase rndmmovement for Library Guardian
* remove movement for Databank + enable flying
* Add text and spellevent for Library Guardian (it will only be executed in 30 yards range to the Database + rndmmovement will be stopped while the event is running)
* closes: https://github.com/dalaranwow/dalaran-wow/issues/4324
* commit: deb446778bc8d57ba53339612581eb8e614b4586

![GitHub Logo](http://i.imgur.com/p0CUW7o.jpg)
![GitHub Logo](http://i.imgur.com/WGfObox.jpg)
![GitHub Logo](http://i.imgur.com/DtnIMpO.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
+ one missing text added :o

**Comment by Teridan-dal-wow** [comment]
Feedback for this report from TrinityCore rev. 02633a332cf7 2017-02-09.

Works exacly like on retail. Thank you for your work!
