### ISSUE TITLE
[NPC][WotlK] Valkyrion Aspirant, missing spawn locs, paths

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4328]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Npc Valkyrion Aspirant http://wotlk.openwow.com/npc=29569 have few wrong and few missing spawn locations, and 5 missing paths.
Missing and wrong spawn locations:
![wowscrnshot_012617_153838](https://cloud.githubusercontent.com/assets/6797611/22334565/e7c1d7a6-e3e3-11e6-8bc4-0bfc21d6400d.jpg)
![wowscrnshot_012617_153845](https://cloud.githubusercontent.com/assets/6797611/22334563/e7c0bd80-e3e3-11e6-8991-e5418ecdd980.jpg)
![wowscrnshot_012617_154835](https://cloud.githubusercontent.com/assets/6797611/22334561/e7c03c98-e3e3-11e6-9b32-ad3927239bda.jpg)
![wowscrnshot_012617_155139](https://cloud.githubusercontent.com/assets/6797611/22334564/e7c1d490-e3e3-11e6-81f4-3648b9f7771b.jpg)
![wowscrnshot_012617_155144](https://cloud.githubusercontent.com/assets/6797611/22334562/e7c07348-e3e3-11e6-97b2-b414c2ca460b.jpg)
![wowscrnshot_012617_155344](https://cloud.githubusercontent.com/assets/6797611/22334560/e7bf2ec0-e3e3-11e6-9d15-fae4e3b78dce.jpg)

**Expected behaviour**: Video from retail legion from 26.01.2017:
Part 1- https://www.youtube.com/watch?v=9OcqWlFv0qo
Part 2- https://www.youtube.com/watch?v=KqZOg6h-j1Q

**Comment by Rushor** [comment]
i will repost and remove pics to order what i already fixed and so on

Missing and wrong spawn locations:
![wowscrnshot_012617_153838](https://cloud.githubusercontent.com/assets/6797611/22334565/e7c1d7a6-e3e3-11e6-8bc4-0bfc21d6400d.jpg)
![wowscrnshot_012617_153845](https://cloud.githubusercontent.com/assets/6797611/22334563/e7c0bd80-e3e3-11e6-8991-e5418ecdd980.jpg)
![wowscrnshot_012617_154835](https://cloud.githubusercontent.com/assets/6797611/22334561/e7c03c98-e3e3-11e6-9b32-ad3927239bda.jpg)
![wowscrnshot_012617_155139](https://cloud.githubusercontent.com/assets/6797611/22334564/e7c1d490-e3e3-11e6-81f4-3648b9f7771b.jpg)
![wowscrnshot_012617_155144](https://cloud.githubusercontent.com/assets/6797611/22334562/e7c07348-e3e3-11e6-97b2-b414c2ca460b.jpg)
![wowscrnshot_012617_155344](https://cloud.githubusercontent.com/assets/6797611/22334560/e7bf2ec0-e3e3-11e6-9d15-fae4e3b78dce.jpg)

**Comment by Rushor** [comment]
DB/Creature: Valkyrion Aspirant - Add missing spawn locs and paths

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4328
* commit: 29e0a91091f374122cd9d84f7b2b9ec982d3ea5f

![GitHub Logo](http://i.imgur.com/XftP07S.jpg)
![GitHub Logo](http://i.imgur.com/XIC79RQ.jpg)
![GitHub Logo](http://i.imgur.com/6xUhEQX.jpg)
![GitHub Logo](http://i.imgur.com/kyGbDcs.jpg)
![GitHub Logo](http://i.imgur.com/AYOvaho.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Teridan-dal-wow** [comment]
Feedback for this report from TrinityCore rev. 02633a332cf7 2017-02-09.

Works exacly like on retail. Thank you for your work!
