### ISSUE TITLE
[NPC][WotlK] Garm Watcher and Snowblind Devotee, missing paths/emotes, wrong spawns

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4342]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**:
-  Part 1:
Npc Garm Watcher http://wotlk.openwow.com/npc=29553 and Snowblind Devotee http://wotlk.openwow.com/npc=29554 are missing paths and emotes.
- Part 2:
 Npc Snowblind Digger http://wotlk.openwow.com/npc=29413 is incorrectly spawn at the entrance of the cave (they shouldn't exist in that cave at all, openwow is wrong about that).
![wowscrnshot_012717_181509](https://cloud.githubusercontent.com/assets/6797611/22379057/6de65d3e-e4c0-11e6-949a-2ad42d2e7b6f.jpg)
![wowscrnshot_012717_184028](https://cloud.githubusercontent.com/assets/6797611/22379063/71c18258-e4c0-11e6-9011-d5f6370b7820.jpg)

**Expected behaviour**: Video from retail legion from 27.01.2017:
https://www.youtube.com/watch?v=ZBF44KbHlS8

**Comment by Rushor** [comment]
DB/Creature: Stormpeaks - Garm Watcher and Snowblind Devotee - Add missing paths/emotes, remove wrong spawns

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4342
* commit: 0a8048364e83d438bc5c12f633eb72b675af4390
* 8 paths added and several emotes

![GitHub Logo](http://i.imgur.com/RVjzPrf.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
DB/Creature: Garm Watcher - simplify GUID script with new `saiscriptflag`

* updates: https://github.com/dalaranwow/dalaran-wow/issues/4342
* commit: 542f6e88533a22637c1a706cac9ebe15f0ddf423
