### ISSUE TITLE
[NPC][WotlK] Thorim and Column Ornament, wrong state

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4348]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Part 1: Npc Thorim http://wotlk.openwow.com/npc=30295 is sitting (he should be standing). Area relevent for this report:
![wowscrnshot_012817_125543](https://cloud.githubusercontent.com/assets/6797611/22396083/1e2ff7b6-e559-11e6-8446-89bb6c844b21.jpg)

Part 2: Npc Column Ornament http://wotlk.openwow.com/npc=29754 is currently "clickable", it should not be.
![wowscrnshot_012817_123639](https://cloud.githubusercontent.com/assets/6797611/22396090/487e1c50-e559-11e6-93d8-6e81f42be0e2.jpg)

Note: Column Ornament is relevent to quest The Drakkensryd http://wotlk.openwow.com/quest=12886 as the player should be able to click on them and get pulled to the platform.

**Expected behaviour**: Video from retail legion from 28.01.2017:
https://www.youtube.com/watch?v=hTrlqkUawW4

**Comment by Rushor** [comment]
DB/Creature: Thorim and Column Ornament - update state 

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4348
* commit: 8ea8de932c559f1bcc302b8d6a06d0ce34b20277

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
