### ISSUE TITLE
Quest: You, Robot!

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#435]
**Quest You, Robot! - 10248**

- Issue: Upon accepting the quest and using the quest item Scrap Reaver X6000 Controller *(ID: 28634)*, nothing happens.

- How it should work: When you use the item on the specific location, you should be able to control the following NPC: Scrap Reaver X6000 *(ID: 19849)* and defeat the evil Negatron.
___________________________________________

You have to use the following abilites to complete the quest: 

**Repair - 34619**
**Slam - 34620**
**Smash - 34618**

- To complete the quest, you have to defeat the following NPC which will spawn after taking control of Scrap Reaver:
**Negatron** *(ID: 19851)*

Negatron can be only triggeable with the machine and not by normal player or his spells.

- **Minor issue that could be present after fix:** Remember to reset Scrap Reaver X6000 Controller when player does the quest back to its original position once player does the quest.

- **Temporary fix you could add for now:** You could spawn Negatron somewhere near that area and make him triggerable by players, currently he is neutral and non-interactive.

WoWwiki description how it should work: 
*While this is a three man group quest, it can be soloed or two-manned. It is preferable to have a healer or be a healing class as it is hard to get bandages to get past more than a few ticks. Melee classes can DPS Negatron to help the fight go faster.
Negatron will automatically aggro on you once he becomes fightable so you'll want to attack with the Scrap Reaver X6000 and use the Reaver's ability that does 3000-5000 damage and produces ~4500 threat. If you are a healer or you have one in your group, it is imperative to keep the Reaver's threat up. Each of the Reaver's abilities have a 10 second cooldown on them.

Every 20-25 seconds Negatron will do an Earthquake. Earthquake does ~550 damage per second to everyone in melee range. To stop this, use the Scrap Reaver X6000's "Slam" ability to stun him for 2 seconds and stop the earthquake damage. Your own stuns will not affect him. Close to the end of the fight, Negatron will enrage, upping damage done to the Reaver.

Make sure to keep the Scrap Reaver X6000 healed up and give it some buffs. This fight shouldn't be too hard once you have the rotation down of doing 3000-5000 damage/4500 threat, stunning during earthquake, and attacking. Druids should have little to no problems soloing this quest.*

![image](https://f.cloud.github.com/assets/5054924/923924/d34fa0a4-ff59-11e2-82e1-05ff5a6cfffd.png)
![image](https://f.cloud.github.com/assets/5054924/923926/e059fef2-ff59-11e2-86b3-86f1d3f56462.png)

________________
http://wotlk.openwow.com/npc=19849 - Abilities
http://www.wowwiki.com/Quest:You,_Robot
http://wotlk.openwow.com/quest=10248

**Comment by ashido96** [comment]
As of right now the visual for the fel reaver is spawned but non-interactible, basically just like another book case and the quest-item has no function.

**Comment by Demlock** [comment]
Confirmed. This quest is not doable. You can use the item at the specific spot but once you do use it, nothing happens.

**Comment by DrFuler** [comment]
17/12/2015: Still not working.

**Comment by MrAndersonX** [comment]
Confirmed - still bugged.

**Comment by Zibathy** [comment]
Still bugged.

**Comment by jonanone** [comment]
Negatron now is killable and comes to the quest area once the quest item is used to control the Scrap Reaver X6000. The fix will be applied to the live realm soon.

**Comment by Golganeth** [comment]
- When you control the Scrap Reaver for the very first time and call Negatron, he'll be attackable to players and if you cast any spell that doesn't deal direct damage (DoT, consecration, faerie fire, etc etc - similar to Wintrader Marid in Troublesome distraction) he will reset. If you deal direct damage however, it will aggro and attack the player.

- If a player starts the quest and controls the Scrap Reaver while Negatron is dead (because someone has done it recently, for example) Doctor Vomisa will say its quote but absolutely nothing will happen - I assume when someone does the quest both Scrap Reaver and Negatron should despawn and share respawn timer.

- You can bring Scrap Reaver really far away of his default position. You can also use Scrap Reaver abilities on all the NPCs around and kill them. The controlling buff only lasts 5 minutes so you only have that amount of time to use him (you can't refresh the control right on the spot because the quest item requires being in the Proving Grounds), but you can just go back to his spot and control him again.(If really far away, when resetting back to his spot, he will only walk if there's a player/GM in the screen, otherwise he'll stand still)

- You are able to kill Negatron in your own without using the pet at all and still get credit towards "Scrap Reaver test complete"
