### ISSUE TITLE
[NPC][WotlK] Slosh <Food & Drink> ,wrong movement and wps

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4361]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Npc Slosh <Food & Drink> http://wotlk.openwow.com/npc=32478 has wrong wps and has random movement enabled (which is incorect) and leads to this on the server:
![wowscrnshot_012917_121615](https://cloud.githubusercontent.com/assets/6797611/22403382/109653d2-e61e-11e6-8f6a-ec043204e4c9.jpg)

**Expected behaviour**: Video from retail legion from 29.01.2017:
https://www.youtube.com/watch?v=mFyx-aLNDaQ

**Comment by Rushor** [comment]
DB/Creature: Stormpeaks - Slosh - Add Pathing - Movement

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4361
* commit: eee358d16c2148aeecfe02ce0b0b00c726604501

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Teridan-dal-wow** [comment]
Feedback for this report from TrinityCore rev. 02633a332cf7 2017-02-09.

Works exacly like on retail. Thank you for your work!

**Comment by Rushor** [comment]
https://github.com/dalaranwow/principal/commit/c42f8ef0ac9ed821d118f1cdd92a99b86c1195a4
