### ISSUE TITLE
Goblin Mortar and The Mortar: Reloaded 

### ISSUE THREAD

**Issue by Klala** [dalaranwow/dalaran-wow#4364]
**Current behaviour**: You can't learn the Goblin Mortar and The Mortar: Reloaded recipes from the goblin engineering trainers.

**Expected behaviour**: You should be able to learn the Goblin Mortar and The Mortar: Reloaded recipes from the goblin engineering trainers.

**Steps to reproduce the problem**:

1. Be a goblin engineer
2. go see a goblin engineering trainer and try to find The mortar recipes.
3. Notice that there are no such recipes available to learn.

http://wowwiki.wikia.com/wiki/Goblin_Mortar
http://wowwiki.wikia.com/wiki/The_Mortar:_Reloaded

**Comment by Rushor** [comment]
DB/Creature: Add Goblin Mortar and The Mortar: Reloaded spells for Goblin Engineering trainer 

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4364
* commit: c2d53b2244600ac3e1f73c65ecd3ea0d13ad48ca

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by ErasmusHereticus** [comment]
The issue has actually been there for about as long as the bug of not being able to change between Goblin/Gnomish specializations, there's no reason not to implement either, it's been years.

And being unable to complete professions is inexcusable.

**Comment by ErasmusHereticus** [comment]
Not fixed on the live server.

**Comment by ErasmusHereticus** [comment]
@Lothloryen Adding these to the game shouldn't be that hard, should it?

**Comment by Rushor** [comment]
already on PTR.

```sql
-- Goblin Mortar and The Mortar: Reloaded, requires Goblin Engineering
DELETE FROM `npc_trainer` WHERE `ID` = 201015 AND `SpellID` IN (12716, 13240);
INSERT INTO `npc_trainer` VALUES(201015, 12716, 1500, 202, 205, 0);
INSERT INTO `npc_trainer` VALUES(201015, 13240, 1500, 202, 205, 0);
```
