### ISSUE TITLE
[ToC][Anub'arak] Leeching swarm triggers on-attack spells

### ISSUE THREAD

**Issue by plznoz** [dalaranwow/dalaran-wow#4370]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**:
Leeching swarm is considered a physical attack, and triggers molten armor for mages, enrage for warriors, water shield for shamans, etc.

**Expected behaviour**:
Leeching swarm should not be considered a physical attack.

**Steps to reproduce the problem**:
1. Engage Anub'arak as a mage with molten armor active
2. Get to phase 3
3. See that leeching swarm triggers molten armor

**Include proofs for this behaviour**
**Dalaran**:
http://www.worldoflogs.com/reports/tn957pgbtmwlnsth/sum/damageDone/?s=2800&e=3226
Mages do about 40k damage with Molten Armor.

**Live**:
http://www.worldoflogs.com/reports/dta08cx33i1g8unm/sum/damageDone/?s=7277&e=7740
Log from 2010-01-28 (live) where the fire mage has 0 dmg done with Molten Armor. No enrage for dps warriors. Shamans have 100% uptime with water shield.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
http://wotlk.openwow.com/?search=leeching+swarm#npc-abilities
http://wotlk.openwow.com/?search=molten+armor#spells
http://wotlk.openwow.com/?search=enrage#talents
http://wotlk.openwow.com/?search=water+shield#spells

**Comment by Johanes022** [comment]
It also fills up runic power as DK when using anti magic shell, so  its magical damage (too?)

**Comment by Nikvet** [comment]
It should be nature damage.

**Comment by Rushor** [comment]
it's nature damage in dbcs SpellSchoolMask = 8 (SPELL_SCHOOL_MASK_NATURE)

we need to add checks for this manually

**Comment by Rushor** [comment]
Scripts/Spells: Bone Shield, Shaman Shields, Molten Armor, Enrage - Prevent spells from proccing on Anub'arak leeching swarm

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4370
* commit: b9a2a12ddc371efe98d3d82eaa2b47bd7c72b518

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
