### ISSUE TITLE
[Item][Classic] Can't learn the Blue Firework schematic

### ISSUE THREAD

**Issue by Klala** [dalaranwow/dalaran-wow#4413]
**Current behaviour**: Schematic: Blue Firework can be purchased from alliance verdors and sold in the neutral auction house for horde players, however, when I tried to learn it it gave me the "You can never use that item"

**Expected behaviour**: The Schematic: Blue Firework should work for both horde and alliance.

**Steps to reproduce the problem**:

1. Try to learn the Schematic: Blue Firework as a horde player.

http://wowwiki.wikia.com/wiki/Blue_Firework

Note: This might be also the case for alliance players, I haven't checked that part yet.

**Comment by Rushor** [comment]
DB/Item: Red/Blue Firework schematic - Can now be used by players

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4413
* commit: 77d70eaf17d9f283d8bf6fcc4957808f2df264dd

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by ErasmusHereticus** [comment]
As of January 23rd 2018, the issue has yet to be resolved.

Currently it is impossible to obtain, or at least learn all Engineering recipes. Which is just great for those of us who bothered going through hoops to obtaining them.

**Comment by ErasmusHereticus** [comment]
@Lothloryen Well it's still waiting for a fix...

**Comment by Klala** [comment]
Contrary to what it says in the changelog, this item is still unlearnable.

**Comment by Lothloryen** [comment]
Hello there,

Try it after the next restart, please.

Thank you.
