### ISSUE TITLE
[ToC][Anub'arak] Leeching Swarm affects pets

### ISSUE THREAD

**Issue by plznoz** [dalaranwow/dalaran-wow#4452]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Pets are affected by Leeching Swarm.

**Expected behaviour**: Tell us what should happen instead
Pets should not be affected by Leeching Swarm at all.

**Steps to reproduce the problem**:
1. Engage Anub'arak with pets
2. Push phase 3
3. Check combat log for pet's Leeching Swarm

**Include proofs for this behaviour**
**Dalaran behaviour**:
http://www.worldoflogs.com/reports/ilfjla9k6figdqn0/log/?s=2852&e=3255
{"spellNames": ["Leeching Swarm"]}
![dalaranbehaviour](http://i.imgur.com/KJSSJ75.png)

**Live behaviour**:
{"spellNames": ["Leeching Swarm"]}
http://www.worldoflogs.com/reports/dta08cx33i1g8unm/log/?s=7277&e=7740
(Live log dated 2010-01-28)
![livebehaviour](http://i.imgur.com/QDzBEyy.png)

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
http://wotlk.openwow.com/?search=leeching+swarm#npc-abilities
http://wotlk.openwow.com/?search=anub%27arak#npcs

**Comment by Rushor** [comment]
Scripts/TrialOfTheCrusader: Anub'Arak - Leeching Swarm Damage and Healeffects should only target players

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4452
* commit: 9dea02c67e55aa7fc496863339d16a40ab1abace

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
