### ISSUE TITLE
Molten Core Hydraxian Waterlords

### ISSUE THREAD

**Issue by Klala** [dalaranwow/dalaran-wow#4464]
**Current behaviour**: Currently all mobs in Molten Core including all bosses reward 5 times more reputation than they should. For some reason, lower level characters (non human) gain a little more reputation.

**Expected behaviour**: The reward for all mobs in Molten Core and a few others should be as seen [here](http://wowwiki.wikia.com/wiki/Hydraxian_Waterlords?oldid=2366322)

**Steps to reproduce the problem**:

1. Go into Molten Core
2. Start killing mobs
3. Notice you're getting more reputation than intended.

http://wowwiki.wikia.com/wiki/Hydraxian_Waterlords?oldid=2366322

**Comment by Rushor** [comment]
DB/Creature: Update Hydraxian Waterlords Reputation Reward for WotlK for all creatures

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4464
* commit: dae131f42f6a1aee386c9a89b6df33903d60e630

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
