### ISSUE TITLE
[NPC] The Missing Diplomat - Missing Attackstop

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#4468]
Description:
In the Missing Diplomat quest chain (quest id 1447)
the Old Town Thug (entry 4969) (http://www.wowhead.com/npc=4969/old-town-thug)
who spawns in the fight do not disengage fighting and become friendly
after you defeat Dashel Stonefist (entry 4961) (http://wotlk.openwow.com/npc=4961).

Current behaviour: (Tell us what happens.)
The Old Town Thugs (entry 4969) who spawn in the fight do not disengage fighting or become friendly after you defeat Dashel Stonefist (entry 4961).

Expected behaviour: (Tell us what should happen instead.)
The Old Town Thugs (entry 4969) should become green/friendly after Dashel Stonefist says: "It's okay, boys. Back off. You've done enough. I'll meet up with you later."

**Comment by Rushor** [comment]
DB/Quest: The Missing Diplomat - Stop Attack for Old Town Thug once Dashel Stonefist was defeated

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4468
* commit: b51127adb55fbd2508f1a1b4f6ab196a8cebb7e9

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Hello, after few tests on PTR this:

> DB/Quest: The Missing Diplomat - Stop Attack for Old Town Thug once Dashel Stonefist was defeated

works as intended.
But what happens if the player runs away from the fight with these npcs or dies. They don't despawn and Dashel doesn't turn friendly. This is a problem for low level players that just pass near that spot.
Also when a player reengage them this should not be possible:
![wowscrnshot_102417_130331](https://user-images.githubusercontent.com/6797611/31937100-266408c8-b8bc-11e7-8cff-8ff92bfdb0cc.jpg)

If 1 of them is engaged the other 2 should assist.

**Comment by Rushor** [comment]
okay so an option would be: 

On Evade - change faction + despawn adds 

adds - on aggro - call for help
