### ISSUE TITLE
[NPC][TBC] Bloodscale Elemental, wrong spawns

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4479]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Npc http://wotlk.openwow.com/npc=20792 is not suppose to have static spawns (openwow is wrong here). Currently there are alot of static spawns around this area:
![image](https://cloud.githubusercontent.com/assets/6797611/23331127/235cfdb8-fb68-11e6-98b9-9c086792f392.png)

**Expected behaviour**: Npc http://wotlk.openwow.com/npc=20792 is spawned only by spell http://wotlk.openwow.com/spell=35593 which is part of spell http://wotlk.openwow.com/spell=35594 which is cast by http://wotlk.openwow.com/npc=18044
Proof from retail:
![image](https://cloud.githubusercontent.com/assets/6797611/23331142/78cf73de-fb68-11e6-8ef0-5bfdbb6a77ec.png)
And from wowhead:
http://www.wowhead.com/npc=20792/bloodscale-elemental#screenshots

My suggestion:
``` sql
DELETE FROM `creature` WHERE `guid` BETWEEN 86734 AND 86743;
DELETE FROM `creature_addon` WHERE `guid` BETWEEN 86734 AND 86743;
```

**Comment by TheRealestMcCoy** [comment]
Are the Wrekt Slaves connected to the Overseer. And if you kill the Overseer does slaves turn yellow and run alway?

**Comment by Rushor** [comment]
DB/Creature: Bloodscale Elemental - Remobe wrong static spawns

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4479
* commit: 6163d5288663c6f0da26ce969d95ba5ca406f964

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.


Thanks!
