### ISSUE TITLE
[NPC] Emperor Dagran Thaurissan, pull issue

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4486]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Npc http://wotlk.openwow.com/npc=9019 doesn't always pull the entire room on aggro.

**Expected behaviour**: Npc http://wotlk.openwow.com/npc=9019 should pull the entire room in all cases on aggro. Also the packs near the entrace are not pulled.

**Steps to reproduce the problem**:

Video of how to reproduce the problem:
https://www.youtube.com/watch?v=i8hjeb5hlys&feature=youtu.be

**Comment by Rushor** [comment]
could be fixed with:

```c++
case EVENT_CALL_FOR_HELP:
                        {
                            std::list<Creature*> AggroList;
                            me->GetCreatureListWithEntryInGrid(AggroList, NPC_TWILIGHT_HAMMER_AMBASSADOR, 150.0f);
                            me->GetCreatureListWithEntryInGrid(AggroList, NPC_SHADOWFORGE_SENATOR,        150.0f);
                            me->GetCreatureListWithEntryInGrid(AggroList, NPC_DOOMFORGE_DRAGOON,          150.0f);
                            me->GetCreatureListWithEntryInGrid(AggroList, NPC_ANVILRAGE_CAPTAIN,          150.0f);
                            if (!AggroList.empty())
                                for (std::list<Creature*>::iterator itr = AggroList.begin(); itr != AggroList.end(); itr++)
                                    (*itr)->AI()->AttackStart(me->GetVictim());
                            break;
                        }
```

so the event handles the attackstart now. also works if you pull moira first

![GitHub Logo](http://i.imgur.com/1hDSGJT.jpg)

**Comment by Rushor** [comment]
Scripts/BlackrockDepths: Emperor Dagran Thaurissan - All adds in the room will help Thaurissan now

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4486
* commit: 59a579193a06e8a0f8e685eac680e8a3d466aa2c

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
