### ISSUE TITLE
[NPC][WOTLK] Perch Guardian, missing path/wrong spawns

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4488]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Npc http://wotlk.openwow.com/npc=29013 has 2 wrong spawns and 1 missing path.

**Expected behaviour**:
Screenshot from retail:
![image](https://cloud.githubusercontent.com/assets/6797611/23340716/e448a73a-fc43-11e6-99fe-1359c1b7bb20.png)

My suggestion:
``` sql
DELETE FROM `creature` WHERE `guid` IN (103499, 103502);
DELETE FROM `creature_addon` WHERE `guid` IN (103499, 103502);

-- Pathing for Perch Guardian Entry: 29013 'TDB FORMAT' 
SET @NPC := 103504;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `spawndist`=0,`MovementType`=2,`position_x`=6148.376,`position_y`=5688.788,`position_z`=5.203243 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`auras`) VALUES (@NPC,@PATH,0,0,1,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,6148.376,5688.788,5.203243,0,0,0,0,100,0), -- 16:44:25
(@PATH,2,6169.101,5707.134,5.400331,0,0,0,0,100,0), -- 16:44:42
(@PATH,3,6190.007,5726.017,-0.1746941,0,0,0,0,100,0), -- 16:44:57
(@PATH,4,6218.587,5752.638,-5.824851,0,0,0,0,100,0), -- 16:45:10
(@PATH,5,6196.124,5731.6,-0.3153446,0,0,0,0,100,0), -- 16:45:26
(@PATH,6,6176.313,5713.658,4.840062,0,0,0,0,100,0); -- 16:45:40
```

**Comment by Rushor** [comment]
DB/Creature: Perch Guardian - Add missing path & remove wrong spawns

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4488
* commit: 8a30674b80613f547642393981efc71a615db4ad

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
