### ISSUE TITLE
[NPC][WotlK] Cultist Saboteur <Cult of the Damned> and Servant of Freya, missing emotes,state

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4516]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Npc http://wotlk.openwow.com/npc=28538 and http://wotlk.openwow.com/npc=28320 are missing emotes and flags.
![image](https://cloud.githubusercontent.com/assets/6797611/23544590/40647066-0000-11e7-8b92-5e43351b1443.png)

**Expected behaviour**: Video from retail legion from 3.3.2017:
https://www.youtube.com/watch?v=yxvT4v7l_yI

What is done:
-added the emotes
-added the missing flags

To do:
-This fix brakes in a way event from quest http://wotlk.openwow.com/quest=12620 after you use item http://wotlk.openwow.com/item=38684 this should happen:
https://www.youtube.com/watch?v=nDBERhA8pto
However at the moment the flags, i just added, are not removed.
-add summon animation for all Servant of Freya http://wotlk.openwow.com/npc=29036

How it looks like:
![image](https://cloud.githubusercontent.com/assets/6797611/23546121/d29f2ede-0006-11e7-9189-2ebbeaf90ea9.png)

``` sql
DELETE FROM `creature_addon` WHERE `guid` IN (40467, 40462, 40452, 40272, 40277, 40274, 40275, 40273, 40271);
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `auras`) VALUES
(40467, 0, 0, 0, 1, 0, '52948'), -- 28320 - 52948 - 52948
(40462, 0, 0, 0, 1, 0, '52948'), -- 28320 - 52948 - 52948
(40452, 0, 0, 0, 1, 0, '52948'), -- 28320 - 52948 - 52948
(40272, 0, 0, 0, 1, 0, ''), -- 28320
(40277, 0, 0, 0, 1, 0, ''), -- 28320
(40274, 0, 0, 0, 1, 0, ''), -- 28320
(40275, 0, 0, 0, 1, 0, ''), -- 28320
(40273, 0, 0, 8, 1, 0, ''), -- 28320
(40271, 0, 0, 8, 1, 0, ''); -- 28320


UPDATE `creature` SET `unit_flags` = 33557248 WHERE `guid` IN (40454, 40460, 40461, 40451, 40456, 40458, 40457, 40459, 40453, 40455, 40466); 
UPDATE `creature` SET `spawndist` = 5 , `MovementType` = 1 WHERE `guid` IN (40272, 40277, 40274, 40275); 
UPDATE `creature` SET `position_x` = 6196.008 , `position_y` = 4761.999 , `position_z` = 220.904 , `orientation` = 1.25427 WHERE `guid` = 40276; 
UPDATE `creature` SET `position_z` = 223.327 WHERE `guid` = 40278; 
UPDATE `creature` SET `position_x` = 6197.026 , `position_y` = 4772.481 , `position_z` = 222.209 , `orientation` = 4.871033 WHERE `guid` = 40271; 
```

**Comment by Teridan-dal-wow** [comment]
Think this can easily be fixed added SAI for each servant on spellhit remove flags, but i can't first which spell is npc 40469 casting on them.

**Comment by Rushor** [comment]
we need to add the remove of the flaggs in the corescript spell_q12620_the_lifewarden_wrath

DB/Creature: Cultist Saboteur <Cult of the Damned> and Servant of Freya -- Add missing emotes and update states and flags

* also remove those flags again once the questitem from http://wotlk.openwow.com/quest=12620 was used
* closes: https://github.com/dalaranwow/dalaran-wow/issues/4516
* commit: 52d646875b23e9e6fbbd7fa13d81dcee0343e3ae

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
