### ISSUE TITLE
[ToC] Multiple issues

### ISSUE THREAD

**Issue by datbunneh** [dalaranwow/dalaran-wow#4518]
**1. Combat bug**
**Current:** after Arthas roleplay floor is destroyed, people fall down and get locked in combat.
**Expected:** people should not be in combat.

**2. Dying in water**
**Current:** for some reason sometimes people die of falling damage after falling into Anub'arak pit.
**Expected:** people should always safely land in water.

**3. Scarabs target**
**Current:** all scarabs target the same exact person who was the last one to relog/enter instance.
**Expected:** each scarab must pick random target with initial amount of threat on it regardless of who was the last person to enter.

**4. Frozen spheres**
**Current:** mages freeze effect prevents spheres from dropping onto the ground. Sometimes sphere simply becomes untargetable, sometimes it creates ice patch mid air.
**Expected:** freeze effect should never stop spheres from falling down and creating an ice patch.

**5. Ice Block when chased by burrowed Anub'arak**
**Current:** if mage chased by Anub'arak uses Ice Block, Anub'arak resets its speed and target.
**Expected:** Anub'arak must not reset speed at all and should change target only temporarily - after Ice Block is gone Anub'arak must immediately resume chasing mage.

**Comment by Rushor** [comment]
Scripts/TrialOfTheCrusader: Anub'arak Swarm Scarabs - Add combatchecktimer

* closes https://github.com/dalaranwow/dalaran-wow/issues/3046
* commit: c47b65fc00103bfe849282eccb5bd16c12486d46

Scripts/TrialOfTheCrusader: Stop combat at the end of the Lichking Roleplayevent

* closes https://github.com/dalaranwow/dalaran-wow/issues/3627
* commit: 91df9ac1f135bd554324f31aa2dc8f0bc8967945

Scripts/TrialOfTheCrusader: Anubarak Spike will now follow normal aggro behaviour

* Feign Death, Vanish, Divine Shield, Iceblock and silimar effects will now cause the creature to select a new target
* closes https://github.com/dalaranwow/dalaran-wow/issues/3979
* commit: 1771497dbc1b98039ab8df66c0a7bc7ef17a88d6

Scripts/TrialOfTheCrusader: Frost Speres - Improve landing event, add immunity to mind sear, ground aoe, starfall and Gnaw

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4518
* commit: 799ecbfba16c2bd2a6c05f75390a10d060cf4806

Everything ele already works on PTR.

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
> Scripts/TrialOfTheCrusader: Anub'arak Swarm Scarabs - Add combatchecktimer

Is not the correct/complete solution for issue:

> 3. Scarabs target
> Current: all scarabs target the same exact person who was the last one to relog/enter instance.
> Expected: each scarab must pick random target with initial amount of threat on it regardless of who was the last person to enter.

**Comment by Crispybuilt** [comment]
**Issue N02** that you've listed: It is impossible to die in the water unless the Death Knight uses his Path of Frost ability preemptively.

**Comment by Rushor** [comment]
Scripts/TrialOfTheCrusader: Anub'arak Swarm Scarabs - Add combatchecktimer

it's the only solution that can be provided currently, so the testers should check it out on ptr once apllied first. if it works better that the current behaviour it should be apllied on the live realm with the next update
