### ISSUE TITLE
[EVENT][WotlK] Avatar of Freya

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4522]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Npc http://wotlk.openwow.com/npc=27801 and the event that she is part of is missing.
![image](https://cloud.githubusercontent.com/assets/6797611/23564654/70687dea-0053-11e7-92e7-82c033fe1718.png)

**Expected behaviour**: Video from retail legion from 3.3.2017:
https://www.youtube.com/watch?v=fqT_xaN23Bw

**Comment by Rushor** [comment]
Scripts/Northrend: Avatar of Freya - Add castevent for Freya, reduced respawntimer for Servant of Freya and the nearby victim and spellhitevent for spell 'Freya Dummy'

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4522
* commit: d4c39bdf6eaea6a7c6f7074ea0a9afa2aa05390e

![GitHub Logo](http://i.imgur.com/uRe2CyP.jpg)
![GitHub Logo](http://i.imgur.com/IIOo7ao.jpg)
![GitHub Logo](http://i.imgur.com/prIMwyU.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
