### ISSUE TITLE
[NPC][WotlK] Skadir Longboatsman/Mistweaver/Raider 

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4543]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 
Npc http://wotlk.openwow.com/npc=25521 is missing paths/emotes and combat spells.
Npc http://wotlk.openwow.com/npc=25613 is missing spawns and have some wrong possitions.
Npc http://wotlk.openwow.com/npc=25522 is missing paths/emotes and combat spells.
There is also a missing mini event.

**Expected behaviour**: Video from retail legion from 8.3.2017 for the mini event only:
https://www.youtube.com/watch?v=dt5OVQ_QfiI&feature=youtu.be

Speech:
[15:43:38] Skadir Longboatsman yells: Send in the next pair of prisoners, let them fight to see who lives!
[15:43:09] Skadir Longboatsman yells: You may have survived for our amusement, but now, you shall die at our hands!

What is done so far:
-added 2 missing spawns
-added the missing speech of all npcs that should have
-redid all emotes
-added correct paths for raiders
-added combat spells for raiders, longboatsmen, and npc http://wotlk.openwow.com/npc=26449

To do:
-fix spell http://wotlk.openwow.com/spell=43414 (raiders are casting it correctly now but when a player moves near/over it has no effect, just disappears)
-add mini event

How it looks:
![image](https://cloud.githubusercontent.com/assets/6797611/23706676/d8e9d96e-0417-11e7-9a50-ceeb0bc2882b.png)
![image](https://cloud.githubusercontent.com/assets/6797611/23706686/e27a7056-0417-11e7-9052-542b69d80700.png)

**Comment by Rushor** [comment]
DB/Creature: Skadir Longboatsman/Mistweaver/Raider - Add and Update Pathing, Emote and Texts

* updates: https://github.com/dalaranwow/dalaran-wow/issues/4543
* commit: 13cde7afe37be17dcdbdbb82740ace4623cc35e2

Going to add the mini event this evening - Thanks for your work so far

**Comment by Teridan-dal-wow** [comment]
Small update, after checking all of the skadirs, they all seems to say the same speeches on aggro, however i missed 1 in this report in just 1 of the npcs. Here is the full log:
``` sql
DELETE FROM `creature_text` WHERE `entry` = 25522 AND `groupid` = 0; 
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
(25522,0,0,' You\'ve strayed too far from your comfortable soil, human.',12,0,100,0,4000,0,0,0,''),
(25522,0,1,' I will heave your carcass into the ocean myself!',12,0,100,0,4000,0,0,0,''),
(25522,0,2,' Look what\'s lost its way...',12,0,100,0,4000,0,0,0,''),
(25522,0,3,' Be consumed by the mist!',12,0,100,0,4000,0,0,0,''),
(25522,0,4,' YAAARRRGH',12,0,100,0,4000,0,0,0,''),
(25522,0,5,' You\'re not even fit to be fed to Leviroth.',12,0,100,0,4000,0,0,0,''),
(25522,0,6,' I shall draw your soul into the mist!',12,0,100,0,4000,0,0,0,'');
```

**Comment by Rushor** [comment]
DB/Creature: Gamel the Cruel + Skadir Mistweaver - Add textcomments, broadcasttextid and one missing text

* updates: https://github.com/dalaranwow/dalaran-wow/issues/4543
* commit: 5f9e5a5731d4df1e178e9ca028259341f13e1867

Thanks updated all the texts

**Comment by Teridan-dal-wow** [comment]
Note: Added
``` sql
UPDATE `creature_template` SET `unit_flags` = 768 WHERE `entry` = 24576; 
```
in next report, which will cause an issue in the event here, as the naga is the same entry as the one above.

**Comment by Teridan-dal-wow** [comment]
Also found a mistake that i made, this should fix it:
``` sql
UPDATE `creature` SET `phaseMask` = 2 WHERE `guid` IN (5005386, 5005385); 
```

**Comment by Teridan-dal-wow** [comment]
1 more small fix (that i always noticed when i was leveling, checked on retail also) and it works like that:
``` sql
UPDATE `creature` SET `phaseMask` = 3 WHERE `guid` = 104205; 
```

**Comment by Rushor** [comment]
hm minievent done so far, however the cast of ID - 45815 fails at the end - need to investigate this

**Comment by Rushor** [comment]
DB/Creature: Implement Minievent with Skadir Longboatsman, Invisible Stalker, Captured Tuskarr and Riplash Myrmidon

* during the event a Captured Tuskarr Prisoner and Riplash Myrmidon will spawn and start attacking after their initial walk
* if the Captured Tuskarr Prisoner survives you can take the quest for 15 seconds, after that the Skadir Longboatsman will kill the Captured Tuskarr 
* if the Riplash Myrmidon suvives they will kill him 3 seconds afterwards
* the event only restarts if both Riplash Myrmidon and Captured Tuskarr Prisoner are death and if there is an alive Skadir Longboatsman in the circle range
* also added the two texts for the Skadir Longboatsman
* closes: https://github.com/dalaranwow/dalaran-wow/issues/4543
* commit: 6845d84b400f0f6eaee06c945e487cbc1a9e06f6

![GitHub Logo](http://i.imgur.com/rUHBTvz.jpg)
![GitHub Logo](http://i.imgur.com/baI72DG.jpg)
![GitHub Logo](http://i.imgur.com/aZyAt2h.jpg)
![GitHub Logo](http://i.imgur.com/HVCDgCs.jpg)
![GitHub Logo](http://i.imgur.com/2h4UmJg.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
