### ISSUE TITLE
[Quest][Northrend] Tails Up - Missing respawn

### ISSUE THREAD

**Issue by Hmudvayne** [dalaranwow/dalaran-wow#4546]
Greetings 
THe Quest [Tails Up] in Zul Dark wont work 
The NPCs do not respownin again (Ice Paw Bear and Frost Leopards)
they are saying still and dead 
^Regards

**Comment by TheRealestMcCoy** [comment]
I guess you forgot to read.

[//]: # (***************************************************************)
**[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)**
[//]: # (***************************************************************)

**Comment by Teridan-dal-wow** [comment]
Hello, 
According to #1402 this should be fixed. I can't test this on live realm, but on TC this quest has really poor script.

**Expected behaviour**:  
 - When a player uses item http://wotlk.openwow.com/item=44890 on npc http://wotlk.openwow.com/npc=29319 or http://wotlk.openwow.com/npc=29327
 - When a bear or leopard get hit by spell http://wotlk.openwow.com/spell=62105 they should turn yellow and fall asleep
 - When a player speaks with them (bear/leopard) he (the player) should get general message if its male or female and according to that massage this should happen:
Note: If noone speaks with the sleeping bear/leopard within some time (let's say ~ 1 min or less) the npc should turn back to aggrasive and lose the sleep spell.

1) If its male, it should change npc to http://wotlk.openwow.com/npc=33008 or http://wotlk.openwow.com/npc=33007 then change back to red and attack the invoker.
Note: Here to avoid the issue described by @Hmudvayne  we can set on reset force despawn, which should trigger the normal respawn timer of the original creature.

2) If its female, it should lose the sleeping spell and gain flags 33554432 + 512 + 256 + original ones in the db and starts to follow the invoker.
Note: If the player fly, they should gain movement speed = to player's one and follow him on the ground level. If the player leaves the zones relevent to this quest, they should despawn or if the player stays in these zones and finishes the quest and turn it in, they should despawn just before the quest ender. Each player can have up to 3 female bears and leopards following him maximum and they should not engage in combat.
Reference from retail:
https://www.youtube.com/watch?v=ltgdlrFpjYw

**Comment by Rushor** [comment]
DB/Quest: Tails Up - Update Questscript and improve respawn behaviour

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4546
* commit: 695f3679e6ac70b7d24f531264741ebaa16fc836

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TheRealestMcCoy** [comment]
The whole issue with the quest i saw was if some one uses the item on one of the bears or cats if it spawned a male you could just run away from it and it wouldnt despawn to respawn what you needed.

**Comment by Rushor** [comment]
thanks added a savetiy for it.

DB/Creature: Set Frost Leopard, Female Frost Leopard, Icepaw Bear and Female Icepaw Bear to active in order to despawn them always after 60 seconds

* updates: https://github.com/dalaranwow/dalaran-wow/issues/4546
* commit: 5a6888b8cd84eb0e7376cf83c3771c20e94a6d46

**Comment by Teridan-dal-wow** [comment]
> Set Frost Leopard, ..... Icepaw Bear ....... to active in order to despawn them always after 60 seconds

Shouldn't these be males only?

**Comment by Lothloryen** [comment]
@TeridanDW Could you test this quest on PTR before I port Rushor's changes, please? I haven't seen any report about it in long time.

**Comment by TeridanDW** [comment]
Issues pointed above are valid on PTR, if player want he can "bug" all of the creatures:
![image](https://user-images.githubusercontent.com/6797611/31900694-041c92f6-b828-11e7-9e83-40308fae768a.png)

**Comment by Lothloryen** [comment]
Thank you. I have ported @Rushor 's changes then.
