### ISSUE TITLE
Blackwing Lair bosses respawn time

### ISSUE THREAD

**Issue by Klala** [dalaranwow/dalaran-wow#4548]
**Current behaviour**: Currently the respawn time of Razorgore the Untamed and Vaelastrasz the Corrupt is more or less 2 hours. If you don't clear the instance before that time the door to the room of Vaelastrasz the Corrupt will close because Razorgore respawned. I only know about those two because I couldn't go further after the wipe on neferian to check if other bosses respawned too but I suspect that the whole instance has that respawn time.

**Expected behaviour**: All the bosses in Blackwing Lair should have a one week respawn time or respawn after weekly raid reset which is friday in here.

**Steps to reproduce the problem**:

1. Go to Blackwing Lair
2. Kill Razorgore the Untamed.
3. Wait a few hours and come to check again.

**Comment by Rushor** [comment]
k will change that

**Comment by Rushor** [comment]
DB/Creature: Increase Respawntimer of Bosses in BWL to 7 days

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4548
* commit: 42282897f9b470388bb6f2a270d98b14b46ffe78

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Teridan-dal-wow** [comment]
I remember there was a bug in TC that involved raid bosses respawning incorrectly before the raid lockout is  done, but i can't find it now.
Note: It was relevent to all raids, not just BWL.
