### ISSUE TITLE
[NPC][WotlK] Wooly Rhino Calf/Matriarch/Bull and Tundra Wolf

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4549]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 
Npc http://wotlk.openwow.com/npc=25488 , http://wotlk.openwow.com/npc=25487 , http://wotlk.openwow.com/npc=25489 are missing a lot of spawns and formations and few auras/flags
Npc http://wotlk.openwow.com/npc=25675 is missing few spawns.
Npc http://wotlk.openwow.com/npc=25774 is missing a combat spell.

What is done:
-added the missing spawns
-added a lot of formations
-added 1 combat spell
-corrected few flags/auras

How it looks now:
![image](https://cloud.githubusercontent.com/assets/6797611/23763042/d5da38c4-0500-11e7-8c52-09d512bedb92.png)
![image](https://cloud.githubusercontent.com/assets/6797611/23763061/e6062bb8-0500-11e7-910b-b5dbc96e4ab4.png)
![image](https://cloud.githubusercontent.com/assets/6797611/23763085/00fa4526-0501-11e7-8bca-396ebca3efed.png)
![image](https://cloud.githubusercontent.com/assets/6797611/23763116/1691c33c-0501-11e7-9cfc-5e8ebd7b0b55.png)

**Comment by Rushor** [comment]
DB/Creature: Wooly Rhino Calf/Matriarch/Bull and Tundra Wolf - Update spawns, formation, spells and flags

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4549
* commit: 141c66f52309c8b90c666fb9943d6a2a7af5fb5e

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.


Thank you so much <3
