### ISSUE TITLE
[NPC][WotlK] Den Vermin/Firestarter/Harvester and Magnataur Huntress and Bloodspore Moth

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4552]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 
Npc http://wotlk.openwow.com/npc=24567 , http://wotlk.openwow.com/npc=25470 , http://wotlk.openwow.com/npc=25467 , http://wotlk.openwow.com/npc=24469 , http://wotlk.openwow.com/npc=25464 are missing spawns, paths, combat and out of combat spells and texts.

What is done here:
-added all missing spawns
-added paths
-added combat and out of combat spells and texts
-few more small things

How it looks like now:
![image](https://cloud.githubusercontent.com/assets/6797611/23812672/2d9fffb0-05e4-11e7-8a44-60e8a3e46162.png)
![image](https://cloud.githubusercontent.com/assets/6797611/23812704/3da0bbc0-05e4-11e7-8ea6-ebf95cac2bd7.png)
![image](https://cloud.githubusercontent.com/assets/6797611/23812713/47c3c1c4-05e4-11e7-8759-e7e5f94edaa5.png)
![image](https://cloud.githubusercontent.com/assets/6797611/23812728/61521eb0-05e4-11e7-919c-737d1a8c45d8.png)

**Comment by Rushor** [comment]
DB/Creature: Den Vermin/Firestarter/Harvester and Magnataur Huntress and Bloodspore Moth -- Add paths, spawns, combat spells and texts

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4552
* commit: 13385e4417898c5a237dd6ed18572982b06a3e63

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

Thank you Teridan, it looks great :)
