### ISSUE TITLE
Priest: Mind Vision

### ISSUE THREAD

**Issue by evilstein** [dalaranwow/dalaran-wow#460]
Casting Mind Vision on a target a great distance away, makes the debuff disappear immediately.

**Comment by Rushor** [comment]
Adjustment to Player::SetViewpoint to allow for Mind Vision "hops". (#17041)

* Adjustment to Player::SetViewpoint to allow for Mind Vision "hops".

* Dynamic objects should not be a valid viewpoint for spells like Mind Vision.

* Dynamic objects should not be a valid viewpoint for spells like Mind Vision.

* Removed redundant TYPEMASK_PLAYER check.

* Moved SetSeer outside of if statement.

* commit: 4e9686596efd3833146eebefd4141acec5af2f4f (by TC)

Game/Spells: Mind Vision - Increase range of applying aura + enable targeting if unit is not in LOS 

* updates: https://github.com/dalaranwow/dalaran-wow/issues/460
* commit: 1e979ae6fe609cb42aac1407aac53e2ec5b33eb5
* commit: c020e844b4f854c8b81dd7274b1c672d7850f710

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
