### ISSUE TITLE
[NPC][WotlK] Dalaran Visitor

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4604]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 
Npc http://wotlk.openwow.com/npc=32597 is missing all of it's spawns and is missing a mini event.
![image](https://cloud.githubusercontent.com/assets/6797611/24080118/01b7bb2c-0ca1-11e7-9464-e46a13337017.png)

**Expected behaviour**:
 Video from retail legion from 19.03.2017:
https://www.youtube.com/watch?v=CRlyuxh8jjY&feature=youtu.be
Note: They seems to use a lot  more kind of mounts than what is showed on the video, possibly all flying ones.

**Comment by Rushor** [comment]
you don't need to fix this, i already have a c++ script for this, just gimme a second

**Comment by Rushor** [comment]
concerning the mounts, i will use all entries from items with descriptions like : "Can only be summoned in Outland or Northrend."

**Comment by Rushor** [comment]
Scripts/Northrend: Implement Pooling, Pathing and different mount usage for Dalaran Visitors

* the mounts are faction divided depending on the faction (visual horde or alliance model) of the Dalaran Visitors
* closes https://github.com/dalaranwow/dalaran-wow/issues/4604
* commit: f500fff5556013af1b742203f6d51e15ebbed066

![GitHub Logo](http://i.imgur.com/mxfGLaB.jpg)
![GitHub Logo](http://i.imgur.com/FbSYMSG.jpg)
![GitHub Logo](http://i.imgur.com/nWLfwVX.jpg)
![GitHub Logo](http://i.imgur.com/lX7QqUe.jpg)
![GitHub Logo](http://i.imgur.com/27vkSWg.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
