### ISSUE TITLE
[GO][WotlK] Dalaran Fountain - Wrong orientation

### ISSUE THREAD

**Issue by TeridanDW** [dalaranwow/dalaran-wow#4635]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 
This is what we see currently:
![image](https://cloud.githubusercontent.com/assets/6797611/24322292/5fbb0392-1169-11e7-9868-d4c18b0681f0.png)

**Expected behaviour**: 
This is what it should be:
![image](https://cloud.githubusercontent.com/assets/6797611/24322309/cc1da602-1169-11e7-8631-5f18b73f7d55.png)

What is done here:
 - corrected the state of gameobject fountain

How it looks like now:
![image](https://cloud.githubusercontent.com/assets/6797611/24322322/0d85a68a-116a-11e7-8be0-d1346ca97708.png)

**Comment by Crispybuilt** [comment]
You see the 2nd version of the Fountain after The Lich King in Icecrown Citadel is defeated for the first time.

**Comment by Crispybuilt** [comment]
More  about can be found [http://wowwiki.wikia.com/wiki/Dedication_of_Honor](url)

**Comment by TeridanDW** [comment]
Right, my bad. Thank you at @Crispybuilt

**Comment by TeridanDW** [comment]
Even though the report isn't valid we can take the orientation fix for the fountain (coming from sniff) as valid.
``` sql
UPDATE `gameobject` SET `orientation` = 5.60251 WHERE `guid` = 151164; 
```

**Comment by Rushor** [comment]
updated the titel

DB/Gameobject: Dalaran Fountain  - Update position of object in Dalaran

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4635
* commit: fb94a314652070c4314150669e28e928fd79bf94

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Crispybuilt** [comment]
Need a feedback of it on the PTR.

**Comment by TeridanDW** [comment]
On ptr is not active yet too.

**Comment by TeridanDW** [comment]
Adding new commit to change the state of the fountain.

**Comment by TeridanDW** [comment]
Works as intended on PTR.
However the cinematic is missing.
