### ISSUE TITLE
[Mechanic] Charge/Intercept in deep waters

### ISSUE THREAD

**Issue by TeridanDW** [dalaranwow/dalaran-wow#4652]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 
Charge/Intercept are unuseable in deep waters.
Example:
![image](https://cloud.githubusercontent.com/assets/6797611/24555004/2dba2066-1638-11e7-8991-5788a6731b74.png)

Error message: No path found.
Note: If the creature/player is in water but there isn't ground near (under) him charge/intercept will not work.

**Expected behaviour**: 
Charge/Intercept should be useable in deep water too

**Steps to reproduce the problem**:

1. Go to any deep waters with creatures inside
2. Try to change any
3. Get error "No path found"

Charge - http://wotlk.openwow.com/spell=11578
Intercept - http://wotlk.openwow.com/spell=20252
Feral Charge Bear - http://wotlk.openwow.com/spell=16979

Note:
Feral Charge Cat - http://wotlk.openwow.com/spell=49376 works

Related to #3655

**Comment by Max0r847** [comment]
Huge problem in PvP. Getting hit by hunters/casters in water and cannot charge them.

**Comment by alexuktc** [comment]
In most other servers I have tried this it worked, but the Z axis was set to 0, meaning that the warrior would go to the bottom of the lake. "Path not found" is a better alternative in my opinion. Until it gets fixed.

**Comment by Aridam** [comment]
Confirming this as still being bugged when water is involved -- "No path found" error in all such cases as described and shown.

**Comment by Aridam** [comment]
Reposting to update on the matter.

The Charge mechanic is -- albeit improved -- still greatly-flawed to the extent of still being worthy of deemed broken. Underwater _and_ on-water Charge mechanic usage almost-always fails; it pretty much 90+% of all attempts, regardless of spamming and positioning. You are literally _unable_ to use any form of the Charge mechanic on _anything_ regardless of how far or close you are, regardless of whether or not there is a direct line between you and your Target with _absolutely nothing_ in the way of both -- be it on-water, underwater, on-water-to-underwater, and vice-versa. People sometimes abuse this by going to and sometimes even _staying_ in-/underwater. There can literally be a straight, clear and clean line whether on-water, underwater, or on-to-under and vice-versa, between you and your Target, and even _Mobs_ can travel to you fine, yet you _still_ just _can't_ almost-ever Charge successfully and correctly.

Furthermore, ground-to-water _as well as_ water-to-ground Charge mechanic usage also has a considerable chance to fail. This is rather evident by how even Mobs' pathing backfires on such staged occasions, as when try to traverse inbetween these terrains so to speak, they fail to do so and just get stuck at the border pretty much (one of the first occurrences of that for myself was the spawned Mobs in the water at the end of the Wailing Caverns) -- so too do you _sometimes_ suffer the same (back to my WC: I personally couldn't Charge from my position to the Mobs stuck at the edge minus one/two random times it worked).

On top of that, even aerial Charge isn't foolproof -- air-to-ground Charge mechanic usage is similar to ground-to-water and water-to-ground in that it works but still has a considerable amount of failed attempts, which basically renders this move to avoid Falling Damage _and_ do more, only half-effective, even if one spams the living daylights of whatever affected Charge Ability. Worst of all is if you're even close to being on-top of your Target when you attempt to do this, it fails almost-always. Personally I prefer to be fast and get a jump on something -- NPC or Player -- but this often backfires on me as even if I'm far from my Target while falling, spamming doesn't always save me, and if I get close to being above their head I'm basically doomed to take Falling Damage.

Traversing around/to/along tricky paths such as hills and virtually any sort of bumps that should be accessible with correct pathing of the Charge mechanic is still risky and either results in clipping through (sometimes even ending with _falling_ through) textures, or getting "No path found", when you actually _should_ be able to get a path to traverse the terrain as that's one of the Charge mechanic's uses -- getting somewhere you are likely unable to yourself.

I know this revolves around pathing and Charge may not be the only thing affected, but also any pathing-dependent CC (Disorients, Fears, etc.), and I am unsure of how that has been handled as I haven't let myself be CC-ed in any such way for long-enough to notice myself clipping/falling through textures, but this is not quite the right place for that topic (albeit someone should extensively-test this as well), hence this being specifically-aimed towards covering the Charge mechanic and its still-broken state, as this is still heavily-affected.

As of writing this, what I'm describing in bulk detail is legit-current on Live -- currently in the Borean Tundra, where the Murlocs are, on-water and underwater Charge mechanic is straight-up busted and almost-never works, while ground-to-water and water-to-ground scenarios work but at times fail nonetheless where they really shouldn't, and whenever I jump off higher places to land with a Charge mechanic Ability on a Target below, I find myself mashing as fast as I can and yet _still_ it's finicky and even _fails_ at times, _especially_ if I do so as close to being on-top of my Target as possible (but within effective Range of the used Ability of course), where it's _bound_ to fail.

Note: Haven't yet seen how Thunderstorm off a cliff + Charge mechanic works out (a form of aerial Charge -- from off the cliff back to the same ground via a Target there, even if it's the Shaman themself).

Since water-based and bumpy Charge mechanic issues have been discussed and checked acknowledgingly, I will not provide more gigantic walls of text with links and further explanations, but since it seems pathing of aerial Charge mechanic usage hasn't been delved-into enough from my perspective, I will post a few pointers.

Examples of aerial Charge:
https://www.youtube.com/watch?v=vK3IqseGEQE
https://www.youtube.com/watch?v=9HmgFbL-TKE
https://youtu.be/nD2stcm4W8M?t=166 (also notice how the initial failure in Charging was because of not facing the Target -- _not_ because of it reporting "No path found" or anything anomalous-seeming in general)
https://youtu.be/IijlbG7yrlc?t=181

Also if this should be derived into a separate report of my own due to how extensive and branched-off this post in itself is, let me know.

**Comment by Aridam** [comment]
Another update: Underwater Charge (so far) seems to be actually subjective; I have been retesting while furthering my questing in the Tundra -- this time at Lake Kum'uya, where the Loot Crazed Divers are.

What happens is, it's as if ground is necessary for Charge to work in some semblance of a proper way -- I stood near the top of the lake's surface, while targeting a Loot Crazed Diver located near the bottom where the ground of the lake is. As a result, I could not Charge due to "No Path found", but once I got down closer to the ground as the Loot Crazed Diver was, I seemed to be able to Charge with no issues.

It seems as though the way underwater Charge mechanics currently "work" is that if your Target is close to the depth of a waterbody, should you be so as well, then it seems to work -- if your Target _and/or_ you aren't as such, then it'll fail (which explains why the Winterfin area in the Tundra hardly-ever worked for me -- no ground on almost-all the Mobs there to use as pathing, which seems to be logical given this observation).

**In other words, it seems to act as if it's like aerial Charge mechanic usage, in that it requires some sort of ground to work with as pathing (which is ironic because with that it's more reliable than how air-to-ground Charge works at the moment) -- explains why on-water Charge just doesn't work, as there's no ground to use, and underwater Charge _only_ works when you can skim along the bottom of whatever waterbody you're in to your Target, while aerial Charge is finicky as even if you spam it as you get close-enough to ground-level on your Target, you either get invalid "No path found" (when there obviously should be), or "Out of range" (when you obviously aren't).

Charge on bumpy terrain is simple -- it just seems to ignore strict pathing whenever it works and clips you through, and ending one such Charge at such a place, you simply fall; other times it seems to ignore plausibly-valid and correct pathing and returns "No path found" when there is/should be.**

**Comment by Aridam** [comment]
Still an issue despite the improvements -- Charge now somewhat-usable in-/on-water, as it still gives the "No path available" error at times; furthermore you don't always Charge _directly_ to your Target, but somewhat-upwards towards it (perhaps related to the issue with juttering upwards while Charging a bigger Target/any Target in multi-storey places/caves etc.?)

**Comment by Aridam** [comment]
Reconfirming that Charge in general has rather poor pathing -- people on differently-elevated grounds often cause your Charge to not go-off on them due to not finding any paths; getting to places via Charge which you're otherwise unable to get to by normal means also seems impossible for the same reason.

**Comment by Aridam** [comment]
Charge still a mess; progress?

**Comment by Aridam** [comment]
Bump.

Still an issue -- Charge mechanics in any water still seem to be attempting to follow strict pathing instead of just letting you rush towards your Target.

Video showing it: https://www.youtube.com/watch?v=EOzj4eFFvyE
