### ISSUE TITLE
[NPC] Coilfang Enchantress - Wrong Cast Behaviour

### ISSUE THREAD

**Issue by TeridanDW** [dalaranwow/dalaran-wow#4655]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**:
Npc http://wotlk.openwow.com/npc=17961 has strange movement. When engaged in combat she sometimes continues her path (in combat) or stays on 1 place (in combat, without moving) and casts (if her target is out of range, her spells just fail and she doesn't move closer to target).

**Expected behaviour**: 
Npc http://wotlk.openwow.com/npc=17961 should behaive the same way like the other 3 creature from her "formation". They are:
http://wotlk.openwow.com/npc=21126
http://wotlk.openwow.com/npc=17957
http://wotlk.openwow.com/npc=21127

**Steps to reproduce the problem**:

1. Aggro npc http://wotlk.openwow.com/npc=17961
2. Move around

![image](https://cloud.githubusercontent.com/assets/6797611/24601644/62b70334-1862-11e7-82c7-e0c93a47dcfa.png)

**Comment by TheRealestMcCoy** [comment]
There are a few npcs in game that do this. You can engage them they will keep patrolling and casting at the same time.

**Comment by Rushor** [comment]
reason is the missing sai update (missing cmc flag)

**Comment by Rushor** [comment]
DB/Creature: Coilfang Enchantress - Add Smart Cast Combat Move Flag

* also add aggrotexts for creatures: Coilfang Enchantress, Coilfang Champion and Coilfang Tempest
* closes: https://github.com/dalaranwow/dalaran-wow/issues/4655
* commit: e5b0940902f24b9a871698799c6948c8051ef228

The issue was fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
**Only once the issue was marked with "Fixed - On Live Server", you can find the fix on your game server.**
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on PTR.
