### ISSUE TITLE
[NPC] Dark Ranger Clea

### ISSUE THREAD

**Issue by TeridanDW** [dalaranwow/dalaran-wow#4658]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 
Npc http://www.wowhead.com/npc=36224/dark-ranger-clea#comments is killing the creatures summoned in this mini event, when she passes near the place, as they are much lower level and she aggro from very far away.
![image](https://cloud.githubusercontent.com/assets/6797611/24667517/6fa1a620-196c-11e7-803e-d41419e305de.png)

**Expected behaviour**:
She should ignore these creatures (probably faction issue)

**Comment by Rushor** [comment]
DB/Creature: Dark Ranger Clea no longer attacks the summoned creatures from Lysta Bancroft

* the summoned creatures (Male Human Captive, FeMale Human Captive, Captive Zombie, Captive Ghoul, Captive Abomination)  from Lysta Bancroft now only attack tyler and Edward
* closes: https://github.com/dalaranwow/dalaran-wow/issues/4658
* commit: a90a0a01f436d92bf0091825f01253ec665f8f81

http://i.imgur.com/YQ4H1Gs.jpg

The issue was fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on PTR.
