### ISSUE TITLE
[Quest] [Northrend] [Kirin Tor] Home of the Bear-Men 

### ISSUE THREAD

**Issue by Zibathy** [dalaranwow/dalaran-wow#4689]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 
I'm not sure if I'm somehow doing something wrong, but when I bring my little baby Kekek to Grizzlemaw he doesn't seem to be satisfied and let me finish the quest.

**Expected behaviour**: 
According to http://wowwiki.wikia.com/wiki/Quest:Home_Of_The_Bear-Men, the Southeast entrance and/or the sapling in the center should trigger the quest to be completed. I have a screenshot of both of these places. 

https://www.youtube.com/watch?v=gIX9ZsdkXQw Here's a retail version of the quest, though it's from 2016.

![wowscrnshot_042817_123010](https://cloud.githubusercontent.com/assets/7729864/25540023/2df3f51a-2c0f-11e7-8821-8baa5603c8e0.jpg)
![wowscrnshot_042817_122950](https://cloud.githubusercontent.com/assets/7729864/25540024/2df8bc26-2c0f-11e7-8cc8-617bab723e01.jpg)

**Comment by Rushor** [comment]
Grids/Notifiers: Notify triggers of units moving within their LoS.

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4689
* commit: aa703983c9c2c6d52ae258299c1f64befce42b1d

The issue was fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
already on PTR.
