### ISSUE TITLE
[Quest] [Outland] [Kirin Tor] Visit the Throne of the Elements

### ISSUE THREAD

**Issue by Zibathy** [dalaranwow/dalaran-wow#4690]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

Current behaviour:
I'm not sure if I'm somehow doing something wrong, but when I bring my little blood elf orphan to Throne of the Elements she doesn't seem to be satisfied and let me finish the quest.

Expected behaviour:
According to http://wowwiki.wikia.com/wiki/Quest:Visit_the_Throne_of_the_Elements, entering the Throne of the Elements should trigger the quest to be completed. I have a screenshot attached.

https://www.youtube.com/watch?v=roYAePCuOAo Here's a retail version of the quest, though it's from 2015.

I have tried summoning, dismissing, and resummoning over and over and doesn't assist at all.
![wowscrnshot_042817_183023](https://cloud.githubusercontent.com/assets/7729864/25550689/d1861e84-2c40-11e7-8e09-eb3a3f43ce76.jpg)

**Comment by Rushor** [comment]
Grids/Notifiers: Notify triggers of units moving within their LoS.

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4690
* commit: aa703983c9c2c6d52ae258299c1f64befce42b1d

The issue was fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
