### ISSUE TITLE
[Mage][Spell] Flamestrikes of the same rank stack

### ISSUE THREAD

**Issue by datbunneh** [dalaranwow/dalaran-wow#4699]
Current behavior: Flamestrike of the same rank does not remove the previous one.
Expected behavior: Flamestrike of the same rank should replace the previous one. However it should not affect Flamestrikes of other ranks.

**Comment by TeridanDW** [comment]
Hello @datbunneh, could you provide some kind of a proof for this statement please.
Thank you.

**Comment by datbunneh** [comment]
Sure, gonna post a video soon.

**Comment by datbunneh** [comment]
https://www.youtube.com/watch?v=GLhaahAVMKQ - see that both casting Rank9+Rank9 and Rank9+Rank8 yield equal amount of total hits/crits. Also it's clearly seen in combat text.

**Comment by Haleorn** [comment]
This is indeed the case and can be easily reproduced on target dummies. Just throw down 2+ Flamestrikes of the same rank and the DoT damage for both will tick. 

The normal mage rotation for (arcane mage) AoE back in the day day Rank 9 Flamestrike, Rank 8 Flamestrike, Blizzard, repeat. Below rank 8 the spellpower dropoff made them a waste to cast. Unsure how to really prove that, but there's plenty of stuff from way back when of mages discussing it / macros for it / addon issues with it, eg:

Wowhead: http://www.wowhead.com/forums&topic=157338/arcane-aoe-flamestrike-and-or-blizzard
MMOC: http://www.mmo-champion.com/threads/692650-Arcane-AoE
Rankwatch Addon: https://wow.curseforge.com/projects/rankwatch/issues/6

**Comment by TeridanDW** [comment]
Thank you, the proof provided by @Haleorn is enough for me.

Spells:
Flamestrike Rank 9 - 42926
Flamestrike Rank 8 - 42925

Flamestrike Rank 9 - 42926:

**Effect 0**: Id 2 (SPELL_EFFECT_SCHOOL_DAMAGE)
BasePoints = 873 + Level * 3,50 to 1068 + lvl * 3,50
Targets (16, 0) (TARGET_UNIT_DEST_AREA_ENEMY, NO_TARGET)
Radius (Id 8) 5,00

**Effect 1**: Id 27 (SPELL_EFFECT_PERSISTENT_AREA_AURA)
BasePoints = 195
Targets (28, 0) (TARGET_DEST_DYNOBJ_ENEMY, NO_TARGET)
Aura Id 3 (SPELL_AURA_PERIODIC_DAMAGE), value = 195, misc = 0 (0), miscB = 0, periodic = 2000
Radius (Id 8) 5,00

 - **Effect 1** (applied by spell 42926) should replace the previous one (if one was casted) and not to stack (as they do now).
 - **Effect 1** (from spell 42926) should stack with the same effect from spell 42925

Note: 2 mages should be able to cast spell 42926 at the same position without one replacing the other.

**Comment by Rushor** [comment]
Game/Auras: Don't allow different ranks (or the same rank) of same spell to stack for Dynobj auras (many flamestrikes for example)

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4699
* commit: 524de86efbf25b36af8bf5fe9c06f13a56c03b4e

The issue was fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
