### ISSUE TITLE
[NPC] The Prophet Tharon'ja and Warrior Stances

### ISSUE THREAD

**Issue by monkey1688** [dalaranwow/dalaran-wow#4712]
The Prophet Tharon'ja fight in Drak'tharon Keep.  When he changes you back from a skeleton, you come out in no stance as a warrior.

**Comment by TeridanDW** [comment]
Hello @monkey1688 , for future reports please follow the instructions provided by the temple and fill them so we can get all of the needed information for the issue you want to report. Thank you.

Regarding the issue:
1. The creature pointed above is [The Prophet Tharon'ja](http://www.wowhead.com/npc=26632/the-prophet-tharonja) ID: 26632 .
2. Spell [Decay Flesh](http://www.wowhead.com/spell=49356/decay-flesh) ID: 49356 is been casted on all party members.
3. After Decay Flesh finishes spell [Gift of Tharon'ja](http://www.wowhead.com/spell=52509/gift-of-tharonja) ID: 52509 is casted on all party members, which transforms them to skeletons.
4. When Gift of Tharon'ja is applied to a warrior, he loses the stance aura.

So confirming the issue.
Additional problems that I saw with this fight:
 - There is a small delay (3-4 secs) between the end of spell [Decay Flesh](http://www.wowhead.com/spell=49356/decay-flesh) ID: 49356 and the applying of spell [Gift of Tharon'ja](http://www.wowhead.com/spell=52509/gift-of-tharonja) ID: 52509 which does not exists on retail. It should be almost instant.
 - Spell [Return Flesh](http://www.wowhead.com/spell=53463/return-flesh) is not been casted at all during the fight. It should be casted few seconds before the effect of [Gift of Tharon'ja](http://www.wowhead.com/spell=52509/gift-of-tharonja) ID: 52509 ends (it's a 26 secs debuff).

Proof for all this can be found here:
https://www.youtube.com/watch?v=rnLQHQVScBk

Regarding issue 1 at 9:30
![image](https://cloud.githubusercontent.com/assets/6797611/26282436/4e7dfc46-3e1a-11e7-90dc-ac109f95954c.png)

Regarding issue 2 at 9:50
![image](https://cloud.githubusercontent.com/assets/6797611/26282457/75f4b242-3e1a-11e7-9e8e-64d3c26d80ca.png)

**Comment by Rushor** [comment]
Scripts/DraktharonKeep: Tharon Ja - Restore warrior stances if Tharon-Ja-Fransform fades 

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4712
* commit: 150c2d164320bdd35cc8aa7733e04c7570ab4d94

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
