### ISSUE TITLE
[core] [taunting behavior] - Lich King and Thorim encounters

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#4730]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
When taunting a target that does not currently have a current target due to mechanics other than crowd control it turns and smacks the nearest player instead of going immediately to the player who taunted. This is more a universal behavior also  mostly commonly experienced before this point during the thorim encounter in ulduar.

**Expected behaviour**: Tell us what should happen instead
When a monster that currently does not have a target due to mechanics is taunted it should target the person who taunted instead smacking the nearest nearby player and then behaving like it got taunted.

**Steps to reproduce the problem**:

1.  Taunt spawning raging spirit, shambling horror, or ghoul as they are spawning or lich king directly after transition (ie - taunting while he is casting quake)
2.  Nearest nearby person gets smacked -> and killed (not with ghoul ofc, but same bugged behavior).

http://www.wowhead.com/spell=72262/quake
http://www.wowhead.com/npc=36597/the-lich-king
http://www.wowhead.com/npc=37695/drudge-ghoul
http://www.wowhead.com/npc=37698/shambling-horror
http://www.wowhead.com/npc=36701/raging-spirit

In regards to the thorim encounter, if taunted while he is casting Lightning Charge, he will smack the closest player to the center of his hitbox instead of targeting the player that taunted. After a single hit he will then target the person who taunted. 
http://www.wowhead.com/spell=62466/lightning-charge
http://www.wowhead.com/npc=32865/thorim

**Comment by plznoz** [comment]
There's also no DR (Diminishing returns) on taunts, meaning you could ping pong bosses endlessly even after enrage. This WILL get abused in icc, and maybe especially on LK hc.

**Comment by Lothloryen** [comment]
Hello there,

Issue corrected already. Thank you very much.

**Comment by ashido96** [comment]
NOT CORECTED, PLEASE re-open, you only fixed the comment lothloryen and not the original post.

**Comment by ashido96** [comment]
@Rushor

**Comment by ashido96** [comment]
@Lothloryen 
@Rushor

**Comment by plznoz** [comment]
xD

**Comment by ashido96** [comment]
Still not fixed

**Comment by ashido96** [comment]
Can this issue not stay closed please?

**Comment by Rushor** [comment]
could this have sth. to do with the binary system?

**Comment by Rushor** [comment]
some source for the taunt dr mechanic:

So if you taunt when a person is anywhere above you in threat, yet the mechanics of aggro still keep the mob attacking you yours and their threat will become equal. If you're fighting a boss where diminishing returns on taunt doesn't matter then using taunt when someone exceeds you in threat will be an extra threat boost off the GCD.

http://de.wowhead.com/spell=355/spott#english-comments

Taunt - Angered Earth, Challenging Howl, Challenging Roar, Challenging Shout, Dark Command, Death Grip, Distracting Shot, Growl (Druid), Hand of Reckoning, Mocking Blow, Righteous Defense, Taunt (Pet),Taunt (Warrior)

http://wowwiki.wikia.com/wiki/Diminishing_returns

http://wow.gamepedia.com/Diminishing_returns#Patches_and_hotfixes

http://wowwiki.wikia.com/wiki/Diminishing_returns

Zugleich eine Quelle und wie es bei Taunt vor und nach 3.3.0 funktionierte:

http://www.plusheal.com/home/m/1833799/viewthread/852917-psa-diminishing-returns-taunt-immunity

"Taunt has diminishing returns now. Basically, taunt now gives an invisible, stacking, 20 second buff to who you taunt. Each stack makes new taunts less effective, and at three stacks he goes immune" (Vor 3.3.0)

Patch 3.3.0 (08-Dec-2009): Taunt Diminishing Returns: We've revised the system for diminishing returns on Taunt so that creatures do not become immune to Taunt until after 5 Taunts have landed. The duration of the Taunt effect will be reduced by 35% instead of 50% for each taunt landed. In addition, most creatures in the world will not be affected by Taunt diminishing returns at all. Creatures will only have Taunt diminishing returns if they have been specifically flagged for that behavior based on the design of a given encounter.

_________________________
For now we are going to add the dr taunt mechanic for all wotlk bosses.

**Comment by Rushor** [comment]
Game/Unit: Implement Taunt Immunity for all WotlK Bosses

* Once 5 taunts have been casted on the boss (if the boss has CREATURE_FLAG_EXTRA_TAUNT_DIMINISH) it will become immune to taunts for 15 seconds after the last taunt was casted
* updates: https://github.com/dalaranwow/dalaran-wow/issues/4730
* commit: 545c56e8c14e29cad277490f94a31d582def9a3a

The issue was fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
