### ISSUE TITLE
[ICC][Lady Deathwhisper hc] Dark Martyrdom cast doesn't reanimate in phase 2

### ISSUE THREAD

**Issue by plznoz** [dalaranwow/dalaran-wow#4737]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
When Cult Fanatics and Cult Adherents cast Dark Martyrdom in phase 2, they don't reanimate, meaning you can ignore killing them once they transform, making the encounter too easy.

**Expected behaviour**: Tell us what should happen instead
They should reanimate even in phase 2.

**Steps to reproduce the problem**:

1. Reach phase 2 in the Lady Deathwhisper heroic encounter
2. Let Cult Fanatics and Cult Adherents cast Dark Martyrdom
3. See that they don't respawn as Reanimated Adherent / Reanimated Fanatic

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Fanatic Dark Martyrdom: 71236
Adherent Dark Martyrdom: 70903

**Comment by Lothloryen** [comment]
Hello there,

Thanks a lot for the report, this issue has been already corrected and it shall be applied to the live server with the next maintenance.

**Comment by Chenocide** [comment]
I have a very hard time finding any proof of Dark Martyrdom being cast in phase 2 at all. Making it cast in phase 2, turns the related achievement into a complete mess. Will update this comment if I find something concrete.

**Comment by Crispybuilt** [comment]
This report is incorrect, where did you get the information that ADDS should keep transforming in Phase 2?

**Current Issues:**
- Adds keep transforming in Phase 2 because she keeps casting her buffing spells. That should no longer happen.
- Adds are not prone to CC while they should be. Things such as Shackle/Polymorph Turn Evil and so on. (depends if it's Humanoid or Undead)
- Full House (10 Man) achievement is currently **IMPOSSIBLE** due to adds transforming in Phase 2. With some standard calculation, there is no way you can burst down 4 million HP when you enter Phase 2 with adds spawned from Phase 1 just a second before entering Phase 2, as they keep transforming after roughly 20-25 seconds.

**Evidence of this:**

*By GraveDiggerX (15,855 – 4·55·60) on 2009/12/26 (Patch 3.3.0)*
- During phase two, no more adds spawn and she will not cast her buffing spells anymore (Unless on Heroic)

--------------

*By Enquillion (35,490 – 8·42·198) on 2009/12/17 (Patch 3.3.0)*
- We used Polymorph on the Cult Fanatic and Fear on the Cult Adherent.
- It's imperative that you get her to P2 ASAP at this point! While she is in P1, she can turn the humanoids into undead, even if they are CC'd.
- Once in P2, finish off the aforementioned southernmost add and proceed to kill Lady Deathwhisper as normal while applying CC


Not working as intended.
Re-opening.

**Comment by Lothloryen** [comment]
Hello there,

Everything mentioned on this issue has been corrected. In addition, adds will not cast Dark Martyrdom during second phase at all.

Adds will now have the proper immunity mask and players can now properly apply crowd control auras on them, however there will not be a way to interrupt Dark Martyrdom.
