### ISSUE TITLE
[ICC][Valithria Dreamwalker heroic] Twisted Nightmares damage not resistable

### ISSUE THREAD

**Issue by strobe-light** [dalaranwow/dalaran-wow#4738]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Currently the damage dealt by stacks of Twisted Nightmares is not resistable.

**Expected behaviour**: Tell us what should happen instead
The damage from stacks of Twisted Nightmares should be able to be resisted based on nature resistance

**Steps to reproduce the problem**:

1. Go into portals on Dreamwalker heroic with a nature resistance buff
2. Take stacks of the Twisted Nightmares debuff
3. Notice that you never get a tick partially resisted

**Include proofs for this behaviour**
On Dalaran: all targets have talented Mark of the Wild which gives 75 Nature Resistance
![image](https://cloud.githubusercontent.com/assets/15903359/26814094/0d73614c-4ac6-11e7-87b4-f3f992fa19ad.png)

On [retail](http://www.worldoflogs.com/reports/ax7c5fwljuvuuir1/xe/?s=14240&e=14579&x=spell+%3D+%22Twisted+Nightmares%22%0D%0AAND+type+%3D+TYPE_DAMAGE), 24-03-2010
![image](https://cloud.githubusercontent.com/assets/15903359/26814112/4ec801a2-4ac6-11e7-9cb2-f3d5ca8127cf.png)

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

[Twisted Nightmares: 71940](http://www.wowhead.com/spell=71940/twisted-nightmares)

**Comment by Rushor** [comment]
Game/Spells: Twisted Nightmare - Enable damage reduction with resistances

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4738
* commit: 94d6dbe263dc37d677a723e0e4078a41be4babbb

The issue was fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
**Only once the issue was marked with "Fixed - On Live Server", you can find the fix on your game server.**
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

http://i.imgur.com/ZDH7jKX.jpg
