### ISSUE TITLE
[Ulduar] 10-Man Razorscale

### ISSUE THREAD

**Issue by Ekacarbez** [dalaranwow/dalaran-wow#4742]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

Current behaviour: During the 1st phase of the fight, the boss consistently spawns three drills, which therefore spawn three sets of adds. When Razorscale is impaled and brought to the ground, before she rises back into the air, her fire breath is shot into the ground and not directly in front of her. It does not hit any player or add for damage. 

Expected behaviour: Razorscale should spawn no more than 2 drills at one time. Razorscale should breath fire in front of her before she arises back into the air. 

**Steps to reproduce the problem**:

1. Wait until drills spawn (Observe 3 drills spawning)
2. Harpoon Razorscale to the ground
3. Wait until breaths fire
4. Observe her breathing fire into the ground

  #**Proof**: 
- https://web.archive.org/web/20100710160509/http://www.wowhead.com:80/npc=33186/razorscale
- http://wowwiki.wikia.com/wiki/Razorscale
- http://wotlk.evowow.com/?npc=33186

**Comment by ashido96** [comment]
a) Health scaling is correct for this server, the values for health and damage are scaled up for raids pre-icc.
b) Her breath does do damage to adds and players directly in front of her mouth before she flies back into the air.

c) it is incorrect that she is spawning 3 drills on 10-man though, it should only be 2. (It did used to spawn only 2 back in pre-toc days)

**Comment by Ekacarbez** [comment]
Why would only one boss be scaled?

**Comment by Ekacarbez** [comment]
Update: Upon further research, I discovered I was wrong about the health being over-scaled. With that said, the drills are still making this boss borderline impossible for the average group to kill. If the intent is to make this boss challenging, then the methodology of the progression system seems to be broken. 

We will have to complete Uld 25, then complete ToC25, then revisit Uld 10, once we are 245ilvl (5.4kgs average) geared. To me, that doesn't seem like proper progression, so I'd like to still submit this report to be investigated.

**Comment by ashido96** [comment]
It is most certainly very difficult the bugged number of drills.

@Ekacarbez I will tell you that is completely possible to kill razorscale as he is right now with a group in full 213/219, it will however require everyone to be in voice chat and communicating while everyone doing near optimal dps for their class. 
The way my guild aproached it at the time was to have the paladin or warrior tank tanking the smaller adds to have a complete block set making you completely immune to white hits (if set built correctly) from the small adds, and since these never do any aoe damage you can easily pull them under the boss for passive cleave (while tank hits razor as well). 
Have your stuns and disarms be coordinated on one of the sentinels each wave so you can pull a sentinel on top of the small adds that meele can be focusing down while cleaving the smaller adds - or just have smart meele that don't die to whirlwind is always the simplest solution, being able to have every add in a stack without people dieing is the most efficient way to kill the adds. 
Then with all the adds stacking up classes like unholy dks or fire mages specced for aoe start doing exponentially more damage, druids specced into hurricane (30% more), there's multiple 3-4 point things things in different classes trees that can really help out with clearing him.

**Comment by Rushor** [comment]
so which issue needs to be fixed here?

**Comment by Ekacarbez** [comment]
@Rushor Officially, Razorscale spawns 3 drills per wave of mobs. only 2 drills should spawn per wave. 
She also breathes fire into the ground, dealing no damage to raid members, or NPC mobs.

**Comment by ashido96** [comment]
http://wowwiki.wikia.com/wiki/Razorscale very specifically mentions splitting the dps up into 3 groups during 10 man razor scale so actually I don't think that's the issue. The issue is that the 10 man adds have near the same health as the 25 man adds on retail or TRIPLE the health to go through. 

10 man Dalaran		retail 10 		        retail 25
sentinel: 378k		        163800			390600
guardian: 289k		100800			277200
watcher: 191k		        806400			221760

Razorscale already has approximately 66% extra health which can be easily accomplishment by players of moderate gear and skill and I think should stay the same for this server. But bringing the 10 man adds more in line with retail values I think should be done. Something along the lines of:

Sentinel: 200k
Guardian: 125k
Watcher: 100k

Really though, I've been in groups where we kill yogg easily on the first time then just flounder against the sheer health of the adds that spawn trying to kill razorscale.

**Comment by ashido96** [comment]
Actually, as linked above: https://www.youtube.com/watch?v=RjU5w5Wnp-w clearly shows only 2 sets of adds spawling in 10 man razorscale, but if the health values are corrected to be in line with what I posted you really don't need to worry about fixing the 3rd drill. Groups in uld10 gear have the ability to kill the boss currently, it's just overtly difficult, taking away the extra health of the adds would still leave the fight much harder than retail (as intended by this server) but actually numerically doable by most groups without being the cake walk it seems to have been on retail.
