### ISSUE TITLE
Dungeon Finder Broken

### ISSUE THREAD

**Issue by Cedsson** [dalaranwow/dalaran-wow#4759]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Random Heroic is stuck on needing 1 dps, started 3 days ago. Forcing everyone to make RHC groups in global instead of using rdf to find groups. Can happen that you find a group but very very rarely.

**Expected behaviour**: Tell us what should happen instead
Click join queue, wait a few minutes have the rdf tool pop when you got a group ready.
**Steps to reproduce the problem**:

1. Queue Dungeon Finder

**Include proofs for this behaviour**
http://i.imgur.com/5B3ZkLN.png currently stuck like that for 14 minutes, but went on for 40 minutes

**Include Screenshots from the issue if necessary**
http://i.imgur.com/5B3ZkLN.png

**Comment by Rushor** [comment]
a possipbe fix for it was added here https://github.com/dalaranwow/dalaran-wow/issues/2331.

i close this issue because it's duplicate to my mind

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
