### ISSUE TITLE
Toravon 10 - require ToC 10+25

### ISSUE THREAD

**Issue by Nasfratus** [dalaranwow/dalaran-wow#4767]
Toravon 10
Official Attument for Spawn Tora10 was ToC10

After Release Tora for spawn him all ppl need Clear ToC10+ToC25 if any person dont have ToC25 = boss will ne not Spawn .

**Comment by Rushor** [comment]
http://www.dalaran-wow.com/news/104/new-content-and-attunements/

That's intended

**Comment by AgeAgainst** [comment]
Rushor - 

From what you linked:
-Toravon the Ice Watcher 10 will require Trial of the Crusader 10.
-Toravon the Ice Watcher 25 will require Trial of the Crusader 25.

I believe the issue was opened because a player with Trial of the Crusader 10 achievement was summoned inside just in front of the boss.  This player did not have Trial of the Crusader 25 achievement. Toravon the Ice Watcher 10 subsequently disappeared because the newly summoned player did not have the 25 achievement. 

If this is indeed what is happening, saying 'That's intended" completely contradicts what is stated in the news.  Currently on Dalaran, Naxx 10 is required for Ulduar 10.  Ulduar 10 is required for Trial of the Crusader 10.  This all works as intended.  However, Nasfratus is stating that Toravon 10 requires Trial of the Crusader 10 AND 25.  If you don't have both, Toravon 10 will despawn until that person leaves the raid.

If this is how it is indeed working, it goes against the entire progression system that Dalaran raids have done since day 1.  You can't expect us to believe that it was intended to require Trial of the Crusader 10 and 25 to do Toravon 10.

**Comment by Rushor** [comment]
well the player wrote: "if any person dont have ToC25 = boss will ne not Spawn .", he didn't said that the player was summoned.

Now i understood that you need 25 man mode + 10 man mode cleared to be able to spawn toravon. That's indeed wrong. However those changes which are required for the fix can only be made on the liverealm, not on ptr.

I will add the label for it, so loth can inspect the issue.

Thank you.

**Comment by Edzero** [comment]
Something has changed with this again.

Toravon 25 still requiring 10 and 25man ToC achievement, but I was able to do Toravon 10 yesterday without having ToC 10, ToC 25 or even Ulduar 10. Seems he had no requirement at all in 10man.

**Comment by Lothloryen** [comment]
Fixed, thank you.

**Comment by roblockster** [comment]
What's fixed? VOA 10 now only requires TOC 10 as intended--the original issue in this report--or only fixed TOC25 is fixed?
