### ISSUE TITLE
[Quest][Northrend] [Item] Neural Needler - creates client error

### ISSUE THREAD

**Issue by koray61** [dalaranwow/dalaran-wow#4769]
Greetings, today i was doing this quest and it all worked fine for as intended but when i clicked a few times on the quest item the client suddently crashed after for some reason..

Screenshot: <a href="http://nl.tinypic.com?ref=33krkld" target="_blank"><img src="http://i63.tinypic.com/33krkld.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by Rushor** [comment]
https://wowgaming.altervista.org/aowow/?item=34811

This item creates a wow-error if you spammclick it and then use [Esc].

It can be fixed by removing the triggered flag of the spell.

**Comment by Rushor** [comment]
Game/Spells: Neural Needle - No longer created a Client Crash by Spam clicking or hitting escape

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4769
* commit: b02cb4bd155811a68bed10fc7666c072f49758a8

The issue was fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
**Only once the issue was marked with "Fixed - On Live Server", you can find the fix on your game server.**
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
