### ISSUE TITLE
[ICC][Sindragosa] Line of Sight Bug/Exploit

### ISSUE THREAD

**Issue by Horvic** [dalaranwow/dalaran-wow#4773]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 

If you place the Ice Tomb close to her in the middle and stand at range you can be simultaneously both in line of sight to cast on her and out of line of sight to avoid Mystic Buffet.

I don't have footage from Dalaran yet but this video from Molten shows exactly how the bug works: https://youtu.be/M2MRo6F821Y?t=250
This breaks the main phase three mechanic reducing the difficulty significantly.

**Expected behaviour**: 

You should either be in or out of line of sight of Sindragosa never both at the same time.
While standing in a position where you are able to reset your Mystic Buffet stacks you should be unable to cast on Sindragosa.
If the Ice Tomb gets placed too close to Sindragosa the entire raid should still get Mystic Buffet as the Tomb is unable to provide adequate line of sight. 

**Steps to reproduce the problem**:

1. Go to Sindragosa phase 3
2. Place the Ice Tomb close to her in the middle
3. Stand 10-20 yards behind the Ice Tomb
4. Check your Mystic Buffet stacks not increasing while still being in line of sight to cast on her

**Include proofs for this behaviour**

http://wowwiki.wikia.com/wiki/Line_of_sight
Check any and every retail video, if this was possible on retail it would have been used as the primary strategy.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Sindragosa - http://www.wowhead.com/npc=36853/sindragosa#abilities
Ice Tomb - http://www.wowhead.com/spell=69712/ice-tomb#comments Note: "if the tomb get too close to her you'll still get the debuff." probably referring to the Mystic Buffet
Mystic Buffet - http://www.wowhead.com/spell=70127/mystic-buffet#comments

This issue might be related to her huge hit box.

**Comment by Rushor** [comment]
Game/Spells: Sindragosa - Mystic Buffet - Update LOS mechanic

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4773
* commit: 3b1313868622fa2f516e90e35a47610e43887b0e
* commit: d3444b14286c7f4359253222d368250df52df56a

The issue has been fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
**Only once the issue was marked with "Fixed - On Live Server", you can find the fix on your game server.**
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
