### ISSUE TITLE
VP

### ISSUE THREAD

**Issue by Rullez** [dalaranwow/dalaran-wow#4796]
hello, I used all my VP by mistake, I havent yet "used" the service I bought with 150 VP how can I get them back? I was trying to test a serivice but when I pressed next it just "bought" the service instead of check.

**Comment by Rushor** [comment]
The issuetracker is for serverside and gamemechanic issues only. Please write an Ingame-issue to a Gamemaster and the Gamemaster will then help you as soon as he can. (Or create a new Ingame-Account in order to be able to talk with a gamemaster with you new level 1 character) Thank you.

![GitHub Logo](http://i.imgur.com/bYkYeGQ.png)
