### ISSUE TITLE
[Dungeon] Halls of Stone

### ISSUE THREAD

**Issue by koray053** [dalaranwow/dalaran-wow#4803]
Normaly there should be coming out a fire laser beam out of the statue which is not happening as we're doing the boss 

<a href="http://nl.tinypic.com?ref=1q0tvk" target="_blank"><img src="http://i67.tinypic.com/1q0tvk.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by ashido96** [comment]
Since your ability to write bug reports continues to be extremely lackluster I'll fill this in for you. Fill in the templates please.
https://youtu.be/_LO_61yVl1w?t=14m26s
http://wowwiki.wikia.com/wiki/Tribunal_of_Ages
I'm also fairly certain the abilities on the adds are not scripted as well; all found here: (2nd tab for heroic abilities)
http://www.wowhead.com/npc=28234/tribunal-of-the-ages#article

Here are the 3 faces, but I can't find any spell IDs on what they cast or if they are even casting the spells (is it just appearing out of thin-air from some invisible NPC or what not? idk).
http://www.wowhead.com/npc=30898/kaddrak
http://www.wowhead.com/npc=30899/abedneum
http://www.wowhead.com/npc=30897/marnak

**Comment by Rushor** [comment]
issue moved to https://github.com/dalaranwow/dalaran-wow/issues/4803

**Comment by TeridanDW** [comment]
Think it's this one #2049
