### ISSUE TITLE
[Quest] Shoot 'Em Up

### ISSUE THREAD

**Issue by koray053** [dalaranwow/dalaran-wow#4812]
Current behaviour: Everything seem to work fine you can hop on the harpoon machine to shoot fired harpoons but the only issue here is that when you fire an harpoon to a drake that it deals no damage which should do so
Steps to reproduce the problem: Hop on the harpoon machine and fire a harpoon to a jotunheim proto drake and see that the drake does not take any damage or the harpoons does apply any damage to the drake that you shoot it might be the harpoons that don't do any damage or the drake doesn't take any damage i don't know what the exact main reason is that the drake doesn't take any damage

Include proofs for this behaviour

Quest: http://www.wowhead.com/quest=13069/shoot-em-up
Quest Item: None
Npc/Creature: http://www.wowhead.com/npc=30330/jotunheim-proto-drake

<a href="http://nl.tinypic.com?ref=24ottmx" target="_blank"><img src="http://i68.tinypic.com/24ottmx.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by alexuktc** [comment]
Here is my take on this quest. Bear in mind that I completed it twice - once as a normal quest and once as a daily. 

The harpoons do damage, but hitting the drake is not as straight-forward as it would seem. Also the drake does not get in combat from this. He takes damage but starts to regenerate shortly after. 

In order to kill them you need to spam the shit out of the harpoon and hit them with many harpoons in a very quick succession (bear in mind the harpoon has no ICD and can be used up to 20 times before energy runs out). 

Your real issue is that they do not get in combat. Not that the harpoons do not do damage or that they cannot be hit.

**Comment by catta000** [comment]
Can confirm that dragons do **not** take any damage from the harpoon even if you spam missiles and directly hit, the lifebar is not reduced at all. Tried it a minute ago.

![image](https://user-images.githubusercontent.com/14143422/28990179-18b001a8-797b-11e7-8bfe-97332094f396.png)

**Comment by TeridanDW** [comment]
Thank you for the report @koray053.
Issue related to #1898, up to @Rushor if he wants to move it there too.
