### ISSUE TITLE
Instant Lvl 70 problem

### ISSUE THREAD

**Issue by Mazzive94** [dalaranwow/dalaran-wow#4818]
1. Cant find my characters
2. Cant select characters
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Mazzive94** [comment]
The problem is that i cant choose any character for Instant lvl 70. I can change appearence and faction etc but i cant choose any of my characters when in instant lvl 70 screen.

**Comment by Rushor** [comment]
The issuetracker is for serverside and gamemechanic issues only. Please write an Ingame-issue to a Gamemaster and the Gamemaster will then help you as soon as he can. (Or create a new Ingame-Account in order to be able to talk with a gamemaster with you new level 1 character) Thank you.

![GitHub Logo](http://i.imgur.com/bYkYeGQ.png)
