### ISSUE TITLE
[Utgarde Pinnacle] King Ymiron is walking through the closed gate!!!

### ISSUE THREAD

**Issue by Nikvet** [dalaranwow/dalaran-wow#4819]
Utgarde Pinnacle - (http://www.wowhead.com/utgarde-pinnacle)
King Ymiron - (http://www.wowhead.com/npc=26861/king-ymiron)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**:
I saw a priest with a pet, sending it through the closed gate and pulling him. He walks through it.
**Expected behaviour**:
Pets and minions should not walk through closed gates and walls.
**Steps to reproduce the problem**:
Enter Utgarde Pinaccle, kill the Vry'kul there and the Abomination and try to move your pet through the gate. (if you have one)

**Proofs for this behaviour**:
<a href="http://nl.tinypic.com?ref=axf8ch" target="_blank"><img src="http://i63.tinypic.com/axf8ch.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by ashido96** [comment]
This applies to hunters, death knights and warlocks as well, they can walk in a manner such that the pet goes inside the door just a little bit then when they use their class spell to control the pet they can run at king ymiron (as the pet) and agro him.

**Comment by warcraftgeekygamer** [comment]
This is **not** supposed to be happening and imho...consider this to be exploiting.

**Comment by FireheartBDG** [comment]
This is actually supposed to happen, believe it or not. Well...not "supposed" to, but it was a real thing on live realms. Our hunters would do this every time we got this place and if I'm not mistaken, this can STILL happen on live today.

**Comment by warcraftgeekygamer** [comment]
No, it's not supposed to happen. at. all. Just because it might have happened on retail does not mean it is acceptable to happen here on Dalaran-WoW. Players and or pets are simply cannot ignore physics; that is to pull a mob through a wall, gate or other object otherwise restricting the spell.

**Comment by warcraftgeekygamer** [comment]
No, it's not supposed to happen. at. all. Just because it might have happened on retail does not mean it is acceptable to happen here on Dalaran-WoW. To tell yourself otherwise is a lie. Players and or pets simply cannot ignore physics; that is to pull a mob through a wall, gate or other object which restricts the user of a spell and or attack. Players and pets who attempt to attack a mob through any wall, gate or object should be informed with the message, "**Target not in line of sight**". In this particular case, that object is the gate.

**Comment by FireheartBDG** [comment]
I shouldn't have to explain the meaning of quotes to you. It is a bug, but its a bug from retail. It's entirely up to dalaran if it's something they want to keep like it was back then or fix it for their own server.

**Comment by warcraftgeekygamer** [comment]
Just because you used quotations around a word word does not give it a different meaning (although you seem to think it does). In addition, not one time did I say this was not a bug. In fact, I am supportive of the fact that this should be be occurring. You do not seem to understand that.

Ultimately, players and pets should not be permitted to cast spells through a wall so that they can skip the rest of the dungeon. Players and pets who attempt to attack a mob through a wall, gate or object should be informed with the message, "Target not in line of sight".

**Comment by FireheartBDG** [comment]
The issue causing it has been a known issue for many years and happens with more than just Ymiron, he is just the most affected because he's attackable while far away behind a door. To be honest, this is likely never going to be fixed as the people who tried failed and gave up.
(side note, the error is "No path available for your pet" not "Target not in line of sight", attack is a command not a spell)

**Comment by alexuktc** [comment]
Yo warcraftgeekygamer stop being so dramatic. 

For a server that strives to be Blizzlike the only thing that matters is how Blizzard was at the time. The second you start making decisions that differ from that based on your own judgment the server starts using custom content. 

If this was indeed the case in retail you have no say to claim that it should not be like this.

**Comment by warcraftgeekygamer** [comment]
@alexuktc 

you want dramatic? you got it. fuck you, eat shit and die you little scumbag. dalaran wow and its players here are so fucking stupid, that you dont even know the difference between a hole in the ground and your own asshole.

you have no brain and your safe spaces are invaded which prompts you to cry salty tears of bitch. fucking little faggots.
