### ISSUE TITLE
Daralan Wow, Wont let me login, error, Please Help!!!

### ISSUE THREAD

**Issue by ChickenBiscuits** [dalaranwow/dalaran-wow#4843]
![untitled](https://user-images.githubusercontent.com/30724051/28966684-8bca5e16-790f-11e7-878f-27f0ffac7f4e.png)

"Unable to connect please try again, if the problem persists please contact technical support"

I have tried email & username, I know the password matches the one I signed up to the Daralan website with, has anyone encountered this before? 
Any help is much appreciated thank you in advance!

I also tried login into a new account I just created. Still nothing

Thanks to everyone for the help

**Comment by Edzero** [comment]
This isn't the place to report that issue, this is for server side and game mechanic issues only.

Make sure you are logging in with your username and not your email address.

**Comment by Rushor** [comment]
The issuetracker is for serverside and gamemechanic issues only. Please write an Ingame-issue to a Gamemaster and the Gamemaster will then help you as soon as he can. (Or create a new Ingame-Account in order to be able to talk with a gamemaster with you new level 1 character) Thank you.

![GitHub Logo](http://i.imgur.com/bYkYeGQ.png)
