### ISSUE TITLE
Bugged with my hairlooms

### ISSUE THREAD

**Issue by Serty280** [dalaranwow/dalaran-wow#4851]
I'm hoping to get in touch with a GM here.

Earlier today I made a Death Knight on the main server: "Algalon".

I did all the questes and got to the last one: "The Lich King's Command".
Before I wanted to do that quest, I wanted to learn my spells.. So I took the bird up to the highground. But there was nothing here. And now I can't get down, I can't get anywhere.. I tried unstuck and summon a friend, nothing works. The sad part is, that I used 70 vote points for hairlooms on this guy, and I really want em back..

I hope someone can help me!

Serty280

**Comment by Edzero** [comment]
Make a ticket in-game.

**Comment by Serty280** [comment]
Already did - no response.. But I'll wait for it. 
How long is the answer time normally?

**Comment by Rushor** [comment]
The issuetracker is for serverside and gamemechanic issues only. Please write an Ingame-issue to a Gamemaster and the Gamemaster will then help you as soon as he can. (Or create a new Ingame-Account in order to be able to talk with a gamemaster with you new level 1 character) Thank you.

![GitHub Logo](http://i.imgur.com/bYkYeGQ.png)
