### ISSUE TITLE
A little mistake

### ISSUE THREAD

**Issue by Kyzart** [dalaranwow/dalaran-wow#4856]
Hi all, I bought the level service 70 but by mistake I deleted the mail containing the equipment.. can you resend it to me.. (Kyzart) its really hard leveling without equip.. pls, thx

**Comment by Edzero** [comment]
This isn't something for the bug tracker, you should make an in-game ticket for this issue.

**Comment by TeridanDW** [comment]
The issuetracker is for serverside and gamemechanic issues only. Please write an Ingame-issue to a Gamemaster and the Gamemaster will then help you as soon as he can. (Or create a new Ingame-Account in order to be able to talk with a gamemaster with you new level 1 character) Thank you.

![GitHub Logo](http://i.imgur.com/bYkYeGQ.png)
