### ISSUE TITLE
Missing heirloom 

### ISSUE THREAD

**Issue by Tobiaskern** [dalaranwow/dalaran-wow#4868]
Hi,

i wanted to send a heirloom to my alt account, the name of the heirloom is :  Champion's Deathdealer Breastplate. 
I send the item to my alt with another heirloom (Champion Herod's Shoulder) and some gold. Only the shoulder and the gold where received. Im a new player on Dalaran WoW and im kinda dissapointed that things like this happens. 
I got an screenshot of the item  
![img_2004](https://user-images.githubusercontent.com/31613928/30017101-1cc7e7c0-9158-11e7-8c34-58c517e5dd55.JPG)

My in game name is Tobiias
My account name is tobiiaskern

I hope i get an anwser, and it would be great if i got my heirloom back cause i voted everyday to get the item

**Comment by Edzero** [comment]
You should make a ticket for GM assistance, the bug tracker is only for reporting bugs.

If you deleted the character before you picked up the mail then that is what is supposed to happen. That is how it worked on retail.

**Comment by TeridanDW** [comment]
The issuetracker is for serverside and gamemechanic issues only. Please write an Ingame-issue to a Gamemaster and the Gamemaster will then help you as soon as he can. (Or create a new Ingame-Account in order to be able to talk with a gamemaster with you new level 1 character) Thank you.

![GitHub Logo](http://i.imgur.com/bYkYeGQ.png)
