### ISSUE TITLE
[Quest][Northrend] The Plume of Alystros

### ISSUE THREAD

**Issue by descendance** [dalaranwow/dalaran-wow#503]
First of all you can not use the provided item on the ground where you should as seen in the video 
http://www.youtube.com/watch?v=EZ8JkJAeNhs

You have to go in the water right in front of the hill he is standing on and use the item.The quest will autocomplete than and you will not have to fight the mob, he wont even start moving or anything he just sits there and is not attackable.

**Comment by Focused12** [comment]
Ummm.. I can pull him down quite easily standing in front of the hill on the water.. There is no "mindlessness" to this event as I got wrekt believing what was written here.  Anyone coming to find out about this quest grab a group or maybe I was simply unlucky.  Got the kill with a group as the quest should be intended.

**Comment by npmusicftw** [comment]
This quest is still not working as intended..
Alystros the Verdant Keeper (#27249) current can only be taunted down from one tiny little area beneath his perch. The distance in which the Skytalon Molts (#37881) can be used to taunt him is correct, but it doesn't have the correct result unless right under his perch.

**Comment by DrFuler** [comment]
[13/03/2016] - Doable.

It did not worked properly when I used the item from the ground, but I moved a bit further and climbed on top of the bones in front of it, and there it worked. The mob was taunted, killed and dropped the quest item. If its not working for you, I suggest you try a little bit closer!

**Comment by Rushor** [comment]
sai with abilities was already aplied

fixed things:
- radius to make the bird attack was increased a bit
- the bird should now always attack the player

**Comment by Golganeth** [comment]
Needs polishments, spots like this one will allow you to cast quest item but Alystros will not trigger.

![image](https://cloud.githubusercontent.com/assets/5057942/15801363/c05493a8-2a92-11e6-8d5e-f30dde2cd1b0.png)

The aggro range of Alystros is very small. If you use the quest item from as far away as possible, you will not be able to move back or else the NPC will reset.

**Comment by Rushor** [comment]
kk reduced the range again to 50 yards, since that change wasn't even blizzlike (if we compare it with videos)

**Comment by TheRealestMcCoy** [comment]
This quest works but bad if you cant fly. Just tried it using the item on the ground it pulls and just resets instead of coming down to fights. To make it work i had to fly on top of the mound where he is

**Comment by Rushor** [comment]
could be related to the combatdistance of the creature - i will check it out

**Comment by Rushor** [comment]
DB/Quest: The Plume of Alystros - Increase Combat Distance for Alystros the Verdant Keeper to 100 yards + increase spellfocusrange for questitem to match value of https://youtu.be/EZ8JkJAeNhs?t=4

* updates: https://github.com/dalaranwow/dalaran-wow/issues/503
* commit: dc06582c78ca85a5f6a4cd3852bbe41149a154e9
* commit: 0ee67ce2dcfd884847eb63893ddf30d956ccf32b
* commit: 1f741edc0652d4de73782b0a6c14d92c73ec4f41

![GitHub Logo](http://i.imgur.com/iB5qIYo.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on PTR.

Note: He resets very easily maybe because of short leash range. So it's general issue.
