### ISSUE TITLE
question about bug-fix on server

### ISSUE THREAD

**Issue by Radschpud** [dalaranwow/dalaran-wow#5096]
[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: a lot of quest doesnt work as supposed. i.e. cant get the giant q in outland/ hellfire peninsula, not enough rep with kuranai in zangar marsh, skettis birds are wierd, Murkblood Invasion Plans doesnt drop, test flight: ruuan weald goes deadly wrong etc pp.

I looked up the problems in this bug tracker and found these I looked for, closed.

What can I do to get the newest version of Wotlk?
Or
Why do I have old problems?

closed issues i found
#805
#4888
#1373

**Comment by Chenocide** [comment]
If you had read through the comments made by the developers, you would see that they are fixed on the PTR but not pushed to the live realm. Getting a new "version" of Wotlk won't change anything since these changes are server based, not client based. The only thing you can do is to wait for said changes to be pushed to live. There are currently hundreds of issues that are solved on the PTR but are waiting for implementation on the live realm, so you probably have to wait some time before that happens. It is also possible that the changes are present on live, but the implementation is wrong. Post proof of this in the relevant report for it to be re-opened.

**Comment by Radschpud** [comment]
Thanks for the answer :-) I didnt know that PTR and live are 2 different things :-) so I learnd something new :-)

**Comment by robinsch** [comment]
@Rushor @Lothloryen

**Comment by Radschpud** [comment]
I think the important question is well
DO WE GET A PATCH?

**Comment by robinsch** [comment]
Yes

**Comment by Radschpud** [comment]
when?

**Comment by Lothloryen** [comment]
Hello there, 

We apply fixes every 1-2 days on the live server, all of what you mentioned should be working on Algalon (some things were already fine).
