### ISSUE TITLE
Quest; NPC; Northrend: Prevent the Accord - NPCs' dialogue scripts missing.

### ISSUE THREAD

**Issue by Aridam** [dalaranwow/dalaran-wow#5115]
**Current behaviour**: Quest doable and completable, however the two NPCs in question for the Quest seem to be missing their dialogue scripts when engaged.

**Expected behaviour**: https://youtu.be/VhQfl6lUpnQ?t=47

**Steps to reproduce the problem**:

1. Get the Quest (need to do the prerequisites first -- more information below);
2. Fight the Wind Trader -- no dialogue coming from him;
3. Fight Goramosh -- no dialogue from him either.

**Include proofs for this behaviour**

Quest ID (for more information and prerequisite Quests to get to it first, and more): https://wowgaming.altervista.org/aowow/?quest=12005

Wind Trader Mu'fah's ID: https://wowgaming.altervista.org/aowow/?npc=26496
Goramosh's ID: https://wowgaming.altervista.org/aowow/?npc=26349

**Comment by Aridam** [comment]
This might as well have been split into two separate NPC-tagged reports as I have realized neither they nor their missing scripts are tied to the Quest, but rather just an in-Combat mechanic for them -- pardon for the unnecessity.

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Aridam,
Issue confirmed on PTR.
I would like to add that the position of Wind Trader Mu'fah is wrong.
Should be:
``` sql
UPDATE `creature` SET `position_x` = 3372.73 , `position_y` = 2594.68 , `position_z` = 40.2776 , `orientation` = 4.49236 WHERE `guid` = 200124; 
```

Regarding the missing texts on aggro, it can be added easily, however sometimes creatures have more than 1 text when you engage them. That's why I like to check these kind of issues on retail, but I can't at the moment. Easy workaround is to check diffrent videos of people doing that quest and see if they see the same text every time and add it here.
Also the exact text would be VERY helpful :)

**Comment by Aridam** [comment]
Good find on the incorrect positioning -- seems I overlooked at myself.

Regarding the missing text: https://youtu.be/VhQfl6lUpnQ?t=54 as well as https://youtu.be/VhQfl6lUpnQ?t=62 and https://youtu.be/zBQZynTcXAU?t=30 alongside https://youtu.be/zBQZynTcXAU?t=81 (they both seem to have only one triggered speech)

**Comment by TeridanDW** [comment]
Issue fixed.

**Comment by TeridanDW** [comment]
@Lothloryen, could you apply the first line of the commit again please.
Wind Trader Mu'fah's possition is still wrong, SAIs work fine.

**Comment by TeridanDW** [comment]
Poke @Lothloryen 

> @Lothloryen, could you apply the first line of the commit again please.
> Wind Trader Mu'fah's position is still wrong, SAIs work fine.
