### ISSUE TITLE
Quest : I'm Saved!

### ISSUE THREAD

**Issue by Snoren12** [dalaranwow/dalaran-wow#5138]
Kristen DeMeza dont spawns only  Gankly Rottenfist

**Comment by Aridam** [comment]
Confrmed, although she _is_ spawned -- she's at the beginning of the road back up from the camp itself. I suppose that means she just doesn't have the script to move from there to the camp itself and then trigger the self-dismount into the speech while Gankly's supposed to walk behind her, say something, and start attacking her so that you can actually save her by killing Rottenfist and then trigger the availability of this Quest once having done so (instead it's available without any of that being necessary).

http://wowwiki.wikia.com/wiki/Kristen_Dipswitch
http://www.wowhead.com/quest=9897/im-saved#comments
http://www.wowhead.com/npc=18294/kristen-dipswitch#comments
Kristen's ID: https://wowgaming.altervista.org/aowow/?npc=18294
Gankly's ID: https://wowgaming.altervista.org/aowow/?npc=18297

It's basically a World Event. It seems -- gathering from the pre-Cata comments at least (preferably the WotLK-time ones specifically as many as I could find), and the other sources I found (like the WoWWiki page), she has a 1.5h respawn time, she spawns at the road I mentioned (where she currently just stays on at the very-start of, where the border between the two Zones is, on her Mechanostrider), is supposed to go from there to the camp next to Harold and say a line, with Gankly -- who's Stealthed around the camp -- sneaking behind her, saying a line, and proceeding to infamously "gank" her, which is when you're supposed to save her. It seems she has a despawn timer of 5m or until she's been killed and despawns manually. The Quest stays available if she's saved until she despawns automatically, meaning anyone can take it without actually having saved her.

Video to show the practical part: https://www.youtube.com/watch?v=Hk5J2RU0NlE

**Comment by TeridanDW** [comment]
Hello and thank you for the report and comment @Snoren12 , @Aridam.
Issue was fixed in #827 and it worked fine on the old ptr realm.
