### ISSUE TITLE
Strand of the Ancients - new bugs

### ISSUE THREAD

**Issue by kysqt** [dalaranwow/dalaran-wow#5139]
The whole battleground isn't phased for all players, some can walk through gates while others cannot, I think players that join half way through cannot see changed made on the map.

Some players lose the ability to use vehicles for whatever reason half way through the bg.

I've only done the battleground once since it was enabled cannot be sure if there are more bugs than that and i know this is an incorrect bug report, but the bg is still unplayable as it currently stands.

**Comment by kysqt** [comment]
Also when a gate is destroyed there's no line of sight, so spells cannot be casted from 1 side of an open gate to the other.

**Comment by Aridam** [comment]
If a Gate is destroyed and still doesn't allow for Spells to go from one side to the other thereafter, that likely means the LoS for it isn't dynamic -- that it doesn't update based on its status (LoS omitted if up, still omitted if destroyed, when it should become present). That can be very-hindering, as RDpS and Healers would find themselves forced to move ahead to reach Demolishers/Passengers to destroy, as well as Players to kill/heal-up. Especially-problematic at the final stretch for the Titan Relic in order to stop people entering the chamber from claiming it; overall, that's a common bug -- does it happen with _just_ the Gates in SotA though, or practically any section with doors/other removable obscurities elsewhere? Such as the portculli in Warsong Gulch and similar ones in other Battlegrounds as well.

**Comment by TeridanDW** [comment]
Related to #5120

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the report. The problem with doors not being destroyed for every player is now fixed, it will be applied to Algalon during the next maintenance.

The other issue is related to #2253, so, closing this.
