### ISSUE TITLE
Teron

### ISSUE THREAD

**Issue by Radschpud** [dalaranwow/dalaran-wow#5180]
I somtimes transform into Teron sometimes not.
No enemy to see. noone to fight.

#3561

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)
![wowscrnshot_121217_154746](https://user-images.githubusercontent.com/14928789/33890910-ceb42c4c-df54-11e7-9c6a-f8ae72d2bea8.jpg)

**Comment by TeridanDW** [comment]
Hello @Radschpud,
The fix from #3561 is not applied on live realm yet, that's why there a label "DEPRECATED - Waiting for PTR Update", when you see fixed on live then the quest should be working properly.
![image](https://user-images.githubusercontent.com/6797611/33984548-af188ac8-e0c0-11e7-827e-8a8ab29c2c11.png)
from https://github.com/dalaranwow/dalaran-wow.

Also next time please just comment in the existing bug report, no need of a new one when there is already and existing one.
Thank you.
