### ISSUE TITLE
Quest: We Call Him Steelfeather

### ISSUE THREAD

**Issue by solasgg** [dalaranwow/dalaran-wow#529]
http://www.wowhead.com/quest=11418

Using quest item doesn't give the vision of Steelfeather.

**Comment by Lothloryen** [comment]
Working properly since long time ago.

**Comment by Rushor** [comment]
DB/Quest:  We Call Him Steelfeather - Improve questscript

* updates https://github.com/dalaranwow/dalaran-wow/issues/529
* commit: 25ffe993bd8b3706edfff5e4feb6975091e1492e

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on PTR.
