### ISSUE TITLE
Restoring deleted characters

### ISSUE THREAD

**Issue by Alternaria** [dalaranwow/dalaran-wow#5312]
**Current behaviour**: I accidentaly got all my characters deleted (account name: Alternaria)

**Expected behaviour**: I would like you to restore them if at all possible. I know it souldn't be posted here, but I have problems accessing the forums. :/

**Steps to reproduce the problem**

**Include proofs for this behaviour**

I don't think this issue needs a proof.

**Comment by Golganeth** [comment]
Greetings.

This is the ingame bugtracker, which lists ingame issues that can affect players. In order to deal with your issue, please e-mail us at: dalaran.community@gmail.com 

On the e-mail, please provide as much relevant information as you can, such as:
- Account name
- Deleted character(s) name(s)
- Approximate date of deletion

Closing up
