### ISSUE TITLE
voting shop system webpage

### ISSUE THREAD

**Issue by Sentaur** [dalaranwow/dalaran-wow#5361]
help i voted and use 35 voting points on an armor that i picked which is Preened Ironfeather Breastplate and so the problem was i did all the things i clicked voting points shop. then clicked the shop for "chest" and clicked my character name which is "Sentaur" and clicked search then i went down the armor i was going to buy then bought it. i scrolled up again then saw the character chosen for the armor to be sent was my deleted account.  i swear to god i did those exact things. then i double checked still nothing on my "sentaur" character. what i did next was did the samething and turns out if you click the search button when you picked everything it goes to the first character chosen on the account lol... my first character that i deleted was Qweqweew... please can you kindly send it to my character "Sentaur" i hope you guys can read this fast i need it to level up faster and to fight mobs that have higher level than me. thanks :)

**Comment by Rushor** [comment]
-- GM ONLY --
The issuetracker is for serverside and gamemechanic issues only. Please write an Ingame-issue to a Gamemaster and the Gamemaster will then help you as soon as he can. (Or create a new Ingame-Account in order to be able to talk with a gamemaster with you new level 1 character) Thank you.

![GitHub Logo](http://i.imgur.com/bYkYeGQ.png)
