### ISSUE TITLE
(Please, read) Disconnect issue

### ISSUE THREAD

**Issue by Sindrydavis** [dalaranwow/dalaran-wow#5363]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

Good evening. Writing you here because i got some issues creating topic on Dalaran-WoW forum. Hope, you'll answer me here and help me.

**Current behaviour**: 2-3 days ago a disconnect trouble occures. I sign in, choose my character, play for 2-3 minutes and then get disconnected (without any obvious reason). I checked my provider up, but it shows no problem with that. My internet connection is just good, but i can't play on this beautiful server. This issues concerns both of my accounts.

And about  "can't create topic on server forum" stuff - i log in, it's alright, but it shows that i got no character on account. It was not so big trouble for me, but it causes some inconvieniences to create issue thread properly, not here (i realise this is bug-tracker).

Please, write here if you are gonna solve this problem for me to give you any contact information: e-mail, account information etc.

Hope you can help me. Looking forawrd to your answer.

**Comment by Sindrydavis** [comment]
P.S. Please, write here if you are gonna solve this problem for me to give you any contact information^ e-mail, acoount information etc.

**Comment by Rushor** [comment]
Please see https://github.com/dalaranwow/dalaran-wow/issues/5289

@Lothloryen wrote:

Hello there,

Thank you for the report - it is not server's issue, else everyone will experience it and there are thousands of players without issues every day. The most common problem regarding packet routing is a malfunction on a network node from which your traffic is passing through to reach Algalon's host. Of course there could be many other problems either on your local network or Data Center, but the mentioned is the usual. I doubt is a Data Center issue, because a bigger subset of players from your country / area would experience the same than you.

If this is the case and you are having a routing problem, you can do two things: wait for the network to get a safe path from which route your traffic through, or use a VPN in the meanwhile from another location (E.g: London, Paris).

Of course, there could be a much simpler answer to your problem but I guess you have checked them all (corrupt client, P2P/Torrent or other software that may affect certain ports, modified addons...etc). I have seen players with such issues during the last years that thought it was the server, but they ended fixing by themselves after a thorough research on their end (random disconnects, MS increase on specific situations etc.).

Anyways, I hope you achieve to fix the issue - if you do, feedback would be welcome so players in the future can have a reference.

Best wishes.
