### ISSUE TITLE
Quest: Escape from the Staging Grounds

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#539]
http://wotlk.openwow.com/quest=10425
- **Issue:** After picking up the quest, the escort event doesn't start.

*Captured Protectorate Vanguard* - http://wotlk.openwow.com/npc=20763

**Comment by Shambulance** [comment]
Confirmed broken.

**Comment by Penguindrum** [comment]
![wowscrnshot_092015_200704](https://cloud.githubusercontent.com/assets/14281443/9987824/dc9d26ec-6053-11e5-8eb5-5bdf70839998.jpg)

When accpeting quest he just patrols between points A and B making the quest undoable. Also his spawn rate seems to be too long, way over 20 mins atleast.

**Comment by DrFuler** [comment]
18/12/2015: Can be done.

Apparently, you must accept the quest when he is OUT OF COMBAT. (simply kill the mobs attacking it before taking the quest)

**Comment by jonanone** [comment]
Captured Protectorate Vanguard now only gives the escort quest when out of combat. The fix will be applied to the live realm soon.

**Comment by MalkaviaDW** [comment]
- minor: If you start attacking NPCs before the Captured Protectorate Vanguard does, he will not help you with the fight and continues the path.
- minor: Captured Protectorate Vanguard will not trigger some enemies.
- cosmetic: Before he arrives to the Protectorate Watch Post there is a weird waypoint that will make Captured Protectorate Vanguard to go back and then follow again the proper path.
- cosmetic/pathing: After the completion of the quest, the NPC will do a path under textures, instead of despawn.

**Comment by Zibathy** [comment]
When accepting quest *OUT OF COMBAT* on Kirin Tor, the NPC in question either paces like in Penguindrum's post or stands still (see attachment). I am unable to complete this quest as a result.
![wowscrnshot_103116_182600](https://cloud.githubusercontent.com/assets/7729864/19875047/b2d32d14-9f97-11e6-8f86-1d6ff2b70462.jpg)
