### ISSUE TITLE
[Quest] If Chaos Drives, Let Suffering Hold The Reins

### ISSUE THREAD

**Issue by Imbarawr** [dalaranwow/dalaran-wow#5437]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Killing Scarlet Crusader currently does not progress your quest, you have to kill peasants and citizens.

**Expected behaviour**: Tell us what should happen instead
Killing both crusaders and peasants should be counted towards the completion of the quest.

**Steps to reproduce the problem**:

1. Acquire quest
2. Kill Scarlet Crusader
3. See that you do not get an increasement to the kill counter.

**Include proofs for this behaviour**
N/A

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Quest: http://www.wowhead.com/quest=12678/if-chaos-drives-let-suffering-hold-the-reins

**Include Screenshots from the issue if necessary**
N/A

**Comment by Rushor** [comment]
According to this:


By qataly (209 –  2)  on 2008/11/16 (Patch 3.0.3) |   |  
to do this quest u need kill the citizens which are the injured runing ppl.but a scarlet crusader wont be found so instead of killing them kill anything with the name scarlet. go for the ones working theyre lvl 43 i think. if this helped plz rate up

The Scarlet Crusader should not increase the kill counter.
They are not an objective of the quest as you can see here: 
http://www.wowhead.com/npc=28529/scarlet-crusader
http://www.wowhead.com/quest=12678/if-chaos-drives-let-suffering-hold-the-reins


By coriolis2012 (212 –  2)  on 2008/11/14 (Patch 3.0.3) |   |  
If you are looking for this NPC to complete "If Chaos Drives, Let Suffering Hold The Reins", this NPC doesn't exist in the public release. Instead kill anything in Havenshire with Scarlet in the name, including the very easy peasants.
http://www.wowhead.com/npc=28529/scarlet-crusader#comments


![GitHub Logo](https://i.imgur.com/aXosnl7.png)
