### ISSUE TITLE
Quest: Counterattack

### ISSUE THREAD

**Issue by Astraxa** [dalaranwow/dalaran-wow#547]
This quest works perfectly fine. However, I noticed that the mobs spawn only 1 time! I've   been waiting for the mobs to spawn for 5 hours ( checking every hour if they spawned ), so this is what I concluded: mobs only spawn once and needs a server restart or crash to have them spawn again.
I might be wrong about this but this is all I was able to know.
Please look into this quest.

**Comment by meowmewo** [comment]
Still not working on Algalon.

**Comment by Demlock** [comment]
And still not working properly...

**Comment by Blackoutx** [comment]
Was able to complete, Waves didn't work properly. After the first large wave of mobs there would only be one spawn at corresponding wave spawns. after ~ 8 single mob spawns the warlord came out and he dropped the flag.

**Comment by Rushor** [comment]
dac4544abe6e011a29e92433989394e3b93ba1a7
- you need to start the event now with a gossipoption on Regthar Deathgate
- the spawn will no always be excecuted correctly once the player talked to deathgate
- Warlord Krom'zar should always drop the object for the questitem

**Comment by Golganeth** [comment]
MalkaviaDW;

> The event starts right you accept the quest, not with the gossip.
1) The event stops after the first or second "wave" of attackers ends.
2) The NPCs spawns by default near the zone of the fight, without coming by waves. So the first 2 waves, are the nearest NPCs, not waves.
3) The script makes the defender spam random sentences without attacking them, so if you do not pull the enemies it still in a loop.
4) The gossip from Regthar Deathgate is unclear, seems informative instead of starting the battle.
5) The NPCs spawned start to disappear if you do not engage them, including Warlord Krom'zar.
6) Stuck in progress, not granting completion.
7) Abandoning the quest, the event still on, the NPCs continue their random spam of sentences even though the battle is not going on.
