### ISSUE TITLE
[Battlefield] Wintergrasp issues

### ISSUE THREAD

**Issue by globoxxd** [dalaranwow/dalaran-wow#561]
The graveyards in wintergrasp are not working during the battles, currently if you die you have to go to your corpse and ress with 50% hp and its usually where the enemy is still lurking so you just ress in the middle of everyone and die instantly.  It should work like a BG where you all ress at the same time and in the same place.

Also the workshops stay controlled by the faction who had them in the previous battle.  They should be neutral at the start of each WG battle.

Finally the quests to win WG, destroy enemy siege vehicles and destroy towers are not working.

**Comment by M0dinstaller** [comment]
I'll add a few things that I noticed earlier :
- The workshops in the defender base have huge teleporter looking platforms in front of them ... which are useless. I tried spawning a vehicle and walking on the teleporter but nothing happened and I couldn't click it. The attackers juste have to not break any wall around those workshops and they become effectively useless.
- The "RP-GG" rockets don't do anything. Not sure how it's supposed to happen in retail but according to wowhead comments, if I understood right, it was supposed to fire a missile right in front of you that exploded on the first thing it hit, so you had to lead a bit and it was risky because you had to be on the same level as your target (no ballistic or any targeting feature). Here it just doesn't do anything, no rocket comes out (or I didn't figure out how to use it).

**Comment by kalvindeane** [comment]
No staff activity in this thread since September 2013 and Wintergrasp is still full of bugs. Please look into these and consider fixing them instead of pushing PvE content forward all the time. At this rate it will be 2018 before we have a working Wintergrasp.

The towers (both the keep towers and the three southern towers) remain there after a battle and when they are respawned the old ones remain underneath. This causes some unnecessary burden on players and I assume the server as we all have to render these objects on our machines but they serve no purpose.

The three southern towers have a lot of issues for people fighting Warriors/Bears. The charge ability knocks their opponents under the ground where they remain for six minutes, unable to release their body or use the unstuck feature.

The resetting of workshops based on who is attacking and defending isn't working. As such the internal battle struggle is not working either. This is making it difficult for Alliance to win as we are often outnumbered 2 or 3 to 1 and on top of that we don't even start with the proper workshops. If the server crashes/resets, the attacking faction has initial control over all workshops which makes it more difficult for defenders. 

The queue system doesn't teleport players into the zone which effectively makes it useless.

Players under level 77 get kicked out when the battle starts. As far as I know in this patch, even characters of level 70 could enter the battle. The level 75 requirement was only for using the portal to Wintergrasp. There are no mentions of this changing in the patch notes so it should be like this unless Blizzard ninja-patched it like they sometimes do. If this is implemented here then only characters level 70 or higher should get completion in Wintergrasp and count towards/receive the Tenacity buff (from the patch notes on retail).

The marks are meant to be based on player rank for the winning side whilst the losing side should receive 1 mark regardless of rank. Currently all winners get 3 marks and all losers get 1 mark.

The vehicle teleporters inside the keep don't work at all which makes it far more difficult to defend.

The RP-GG does no damage and it's a pretty huge part of the battle. Sieges are far more difficult to kill without them.

Some of the NPCs near the three southern towers will fall through the map making it more difficult for the defending team to rank up.

Sometimes the quest NPCs near the Alliance landing camp also fall through the map (used Priest Mind Vision to check their location).

Tenacity is very broken and it always favours the Horde. Literally ever game I play (and I play 30-40 per week) it favours the Horde. In the last match I played it was around 30 Alliance vs 50 Horde and  the Horde had tenacity. There was always some debate on how Tenacity worked in retail as it was not announced publicly. From my own gatherings during retail as well as those of other players it seemed to be one stack per 10 people the smaller team is outnumbered by. It is certainly not meant to be that the larger team has it. In another battle on this server recently it was 41 Alliance vs 128 Horde and we had only two stacks which is a 38% increase in stats. That is nowhere near the value it was on retail and it is making it almost impossible for Alliance to win anymore. I recorded this match and it is worth noting that although some of us had Tenacity, very few of us did. It should be on everybody in the battle who is on the outnumbered faction.

Wintergrasp had a cap of 120 players on retail. It has no cap here. The queue system needs to be implemented alongside this player cap.

Standing at the graveyards of Eastspark and Westspark allows players to contribute to the capture of said bases whilst benefiting from the immunity buff. I have asked several times if this is considered a bug/exploit but never have I been given an answer.

**Comment by kalvindeane** [comment]
Last post is old so making a new one with numbers/more condensed:

1. There are still multiple towers in one position which hurts system resources and makes it hard to discern their current HP.

2. Pathfinding issues around the south towers and eastspark. Warrior/bear charges make players fall under the map, can't ress for 6minutes.

3. Workshops stay under the control of the faction who last held them instead of defaulting like they did on retail. Internal battle struggle system doesn't work either. Server crashes/resets cause the attacking team to gain all workshops.

4. Players under 77 can't join. Should be level 75 requirement.

5. Marks received should be based on rank for the winning team. 1 mark for recruit, 2 marks for corporal and 3 for sergeant. Atm all winners get 3.

6. Vehicle teleporters in keep don't work at all.

7. RP-GG doesn't work. The cast happens but no projectile is fired and it does no damage.

8. NPCs fall under the map or fail to spawn. Makes it a lot more difficult to rank up.

9. Tenacity is still broken. It doesn't update properly. Often times the larger faction has it on many of their players and the smaller faction has it on none. 

10. In the past, there were battles with 130 players on one faction but there should be a cap of 120 per faction.

11. Only the Victory in Wintergrasp quest works in a raid group. Southern Sabotage and Stop The Siege don't work at all. No Mercy For The Merciless only counts the generic NPCs and not players. Fueling The Demolishers can be completed twice by Alliance players. A Rare Herb, Bones And Arrows, Fueling The Demolishers are meant to be randomly selected each week. Only one of those quests can be completed, at the moment all three can be done.

12. Unknown how it is done but somebody is mass DC'ing Alliance players recently. Also happening in arena too so I assume it's one player or group of players who know some form of hack.

13. Creating a vehicle should automatically put you into the pilot seat of it, but it doesn't.

14. When the slider for a workshop goes from Alliance to neutral, it should update on the map and the NPC inside who makes vehicles should disappear. Neither of those happen. The NPC will disappear if you go out of view range but if you stay next to them, they won't disappear. This allows players to make vehicles at a workshop that they don't own and is a common issue.

15. Sometimes the cannons on the three attacking faction's towers will evade all damage but still be able to fire. It makes tower destruction very difficult.

16. If a friendly cannons is available at a tower before the start of the battle, a player can jump into that cannon and it won't despawn during the battle. E.g. A defender can jump into a friendly cannon on FlameWatch Tower, and use that cannon to destroy all the attackers who are near that tower.

17. Creating a vehicle at the same time the battle finishes allows that vehicle to remain instead of disappearing. Some players do this and then alt f4, then log back in during the start of the next battle. In the second battle, those vehicles aren't seen on the vehicle counter. One can use this to park vehicles inside the keep or at towers and destroy them immediately at the start.

**Comment by kalvindeane** [comment]
A note about the quests:

"Only the Victory in Wintergrasp quest works in a raid group. Southern Sabotage and Stop The Siege don't work at all. No Mercy For The Merciless only counts the generic NPCs and not players. Fueling The Demolishers can be completed twice by Alliance players. A Rare Herb, Bones And Arrows, Fueling The Demolishers are meant to be randomly selected each week. Only one of those quests can be completed, at the moment all three can be done."

A player recently claimed that they had done Stop The Siege by leaving the raid group and doing it independently. Defend The Siege still doesn't work on live or PTR, but it looks like maybe Stop The Siege is working but isn't flagged as a raid quest (which is a fix that all the quests in WG need anyway).

**Comment by debugger123** [comment]
> Unknown how it is done but somebody is mass DC'ing Alliance players recently. Also happening in arena too so I assume it's one player or group of players who know some form of hack.

This one is actually related to movement handler. I know how to reproduce it (not going into too much detail here, since people will start abusing the shit out of this (can only be achieved by a 3rd party program though)). The crash DC/freeze happens to everyone within the range of receiving your movement packets, excluding the hacker itself (thus, making it hard to pinpoint who's to fault). Seen someone using it in WG, didn't catch a name though, since my cursor wasn't hovered over their name, the person was quite far, and wow froze. What they do is sneak close to an area with lots of opposing faction players, perform the hack, and kill as many of them as they can before they restart their games.

**Comment by debugger123** [comment]
> Tenacity is still broken. It doesn't update properly. Often times the larger faction has it on many of their players and the smaller faction has it on none.

Fixed, on PTR

**Comment by kalvindeane** [comment]
>  Marks received should be based on rank for the winning team. 1 mark for recruit, 2 marks for corporal and 3 for sergeant. Atm all winners get

Whilst this is now working, it seems the amount of honor granted isn't as it was on retail unless I have misunderstood how it is supposed to work. Winning with rank 1 can grant the full amount of honor. The last defense match I was in I had Recruit rank and received the 3000 amount, and 3x 750 amounts, totalling 5250.

"Players will receive increased honor with increased rank." from the wiki page on Wintergrasp. I believe this means that a Recruit should only receive 3000, and Corporal should be able to receive 3750 with First Lieutenant giving the full 5250. I may have misunderstood this though, or perhaps it could be a max of 4500 for Corporal instead of 3750. 

Perhaps searching through all the patch notes and the undocumented changes might give more information.

**Comment by Edzero** [comment]
The last offense victory, I received 3000 honor for full rank. No honor was given for the intact buildings, which should give 750 honor each, totalling 5250 honor. Can upload video proof at some point if necessary. Recording OFW110 for future reference.

**Comment by ImprezaWoW** [comment]
Recently there have been many reports of players not getting Wintergrasp Marks of Honour, no matter if they win WG or lose. @Lothloryen  or anyone else, mind checking it?

**Comment by Edzero** [comment]
Also heard of this but haven't seen any proof yet and haven't been able to replicate it thus far. If anybody can provide proof it would be appreciated.

**Comment by Edzero** [comment]
Re-tested this on the PTR.

Winners are receiving proper marks in relation to their rank. Losers are only gaining 1 mark if they are First Lieutenant. What is meant to happen is that all losers should gain 1 mark regardless of mark.

Can't replicate a winner getting the incorrect amount of marks. Perhaps this is just inaccuracy in reports.

**Comment by robinsch** [comment]
@Edzero Source for one mark for loser no matter what rank?

**Comment by Edzero** [comment]
"As of patch 3.0.8, players will receive the rank of Recruit upon entering the zone during a match. At the end of a match that results in a win for your side, players will be awarded 1 Mark for being a Recruit, 2 Marks for being a Corporal, and 3 Marks for being a First Lieutenant.[4] Players of all ranks will earn just 1 Mark if their side loses the battle."

Taken from wowwiki page for Wintergrasp. Phone won't let me link it for some reason.

**Comment by robinsch** [comment]
Losing team will now get one mark no matter what rank - On PTR.

**Comment by TheRealestMcCoy** [comment]
Isn't the portal for the current faction that has control of WG suppose to be open.

**Comment by Rushor** [comment]
no, a fix for the portal was pushed to PTR 2 weeks ago. It will be tested soon.

**Comment by Edzero** [comment]
The issue with the larger faction getting Tenacity has resurfaced. There were 3 raids on Horde tonight making 109 players, with 69 Alliance. Some Horde (but not all) had Tenacity.

Has something been reverted @Lothloryen ? Or maybe it's related to the raid groups themselves as WG here often doesn't have more than 1 raid group.

**Comment by Linandir** [comment]
Ed, I believe this occurs when there are multiboxers joining early in the battle as hordes are slower to join. I had tenacity yesterday twice when both you and aj multiboxed. Same happened the most recent wg when Aj joined. When testing make sure to multibox so that you quickly are more ppl on alliance in the beginning and then horde gets more players. (Not that I mind tenacity against multiboxers :) )

**Comment by Edzero** [comment]
Tenacity should be constantly recalculating itself throughout the battle and not taking a snapshot at the start and staying that way.

In the past this used to happen, but when you killed the player with Tenacity he would lose it upon resurrecting. However this is no longer the case. I've seen 30v40 fights where the 40 player side has some Tenacity which they are retaining even after death.

Some time ago it was updating itself regularly so some update somewhere has either been reverted or has interfered.

**Comment by Edzero** [comment]
Several players on the losing side of the WG 5 minutes ago said they didn't get their mark, myself being one of them. 

I had Recruit rank. Originally when the fix for this was pushed it had this issue too and it was then subsequently corrected back in November. Possibly has this been reverted or it was a freak occurrence?

**Comment by roblockster** [comment]
RP-GG still doesn't work etc. Maybe ask Feenix how they made it work since it worked for them on launch.

**Comment by Linandir** [comment]
Yeah Ed I had tenacity in that one but didn't see anybody else with it. Is it something I'm doing maybe? I Instaclick portal when it spawns while not in a raidgroup and seem to get it more often than not, at least yesterday.

**Comment by AgeAgainst** [comment]
Winning or losing a match, if you are dead at the graveyard you will receive no mark(s) or honor.  As it's rare that I'm dead a few seconds prior to the match ending, I apologize for not having a screenshot of proof but I'll try to get a screenshot as soon as possible.  However, it should be easily tested on PTR to confirm this is happening.  Rank is irrelevant when this happens.

> Losing team will now get one mark no matter what rank - On PTR.
http://wowwiki.wikia.com/wiki/Wintergrasp
Patch 3.0.8 (2009-01-20):
Players will be eligible for participation rewards after two honorable kills.

Players are coming into Wintergrasp with a few minutes left in the match and are rewarded a Wintergrasp Mark of Honor.  Some come in at the beginning of the match and do nothing at all except hit space bar every 4 minutes to avoid the AFK mechanic that kicks you out of Wintergrasp.  Either way, no participation is required and is that is not how it's supposed to work.

**Comment by Lothloryen** [comment]
Hello there,

Updated @Edzero 's list with the fixed issues. Such corrections will be applied to Algalon with the next maintenance. I will continue reviewing Wintergrasp during the next few days so, any feedback / addition would be very welcome.

Open question, what is currently wrong with the Graveyards? I have seen ingame some players complaining about it, but can't find a definitive answer.

**Comment by Edzero** [comment]
Sometimes a player can be teleported to a graveyard but they will not be able to see the NPC and will not get resurrected. As they cannot see the NPC they cannot choose to transfer to another graveyard. On occasion the NPC will be in view but will not resurrect the player.

There was a particular graveyard that was problematic for horde. I believe it was Broken Temple graveyard. Sometimes when a workshop changes from one faction to another and a player releases at the same moment they can be sent to a graveyard which their faction no longer owns.

Have not played in some time so cannot say for certain if these still exist in game.

> Whilst this is now working, it seems the amount of honor granted isn't as it was on retail unless I have misunderstood how it is supposed to work. Winning with rank 1 can grant the full amount of honor. The last defense match I was in I had Recruit rank and received the 3000 amount, and 3x 750 amounts, totalling 5250.

"Players will receive increased honor with increased rank." from the wiki page on Wintergrasp. I believe this means that a Recruit should only receive 3000, and Corporal should be able to receive 3750 with First Lieutenant giving the full 5250. I may have misunderstood this though, or perhaps it could be a max of 4500 for Corporal instead of 3750.

Perhaps searching through all the patch notes and the undocumented changes might give more information.

This part was incorrect and can be ignored. The rank-related honor increases mentioned on WoWWiki are instead referring to the amount of honor granted for honorable kills during the battle if my current understanding is correct.

**Comment by Lothloryen** [comment]
Thank you, I will look into it.

**Comment by AgeAgainst** [comment]
In 3 years of playing Horde on Algalon with over 100 victories in Wintergrasp, not once have I ever been resurrected at the graveyard nearest to Broken Temple.  It simply will not see Horde as a valid resurrection target.

Horde have to spend the time going to the graveyard at the Horde starting area, wasting more time just to get a resurrect, and the longer travel time to get back to Broken Temple.  Alliance on the other hand are sometimes back into the fight near instantly because it works for Alliance. 

That's the issue with the graveyards.  The one in The Chilled Quagmire simply does not work the way it's supposed to work for Horde.  It appears to work fine for Alliance.

**Comment by Edzero** [comment]
https://imgur.com/Kwr0F9i

**Comment by kysqt** [comment]
Also there's a problem with tenacity stacks, most of the time half the players get it while the other half don't get any.

**Comment by TeridanDW** [comment]
Hello, I can add 1 more missing feature from Wintergrasp:
-[] Balance changes when 1 faction is winning the battle of Wintergrasp for few times in a roll

Additional information regarding this:
http://www.wowhead.com/news=145516/patch-3-3-3-upcoming-wintergrasp-balance-changes

**Comment by Edzero** [comment]
That's what the "internal battle struggle" system in the posts above is.

**Comment by Lothloryen** [comment]
Hello again,

I believe I have found the issue with the graveyard, the fix will be applied tomorrow morning to Algalon. Will perform some updates to the tenacity system and the rest of the issues during the next few days.

Thank you very much.

**Comment by Lothloryen** [comment]
Every issue with Tenacity should be now fixed, it will be applied to Algalon tomorrow's or Monday's morning.

**Comment by Lothloryen** [comment]
Quick update, fixed the issue with Goblins/Gnomes engineers not being visually updated upon Workshop control change, it shall be also deployed with the next maintenance.

**Comment by Lothloryen** [comment]
I do not seem able to reproduce the issue with the cannons from the towers, if anyone knows how to make them evade, feedback would be more than welcome.

**Comment by Edzero** [comment]
It happens more often to the three southern towers than to the four towers in the fortress.

Possibly it may be related to them not despawning if they are mounted before the battle starts? Try a match where alliance attack the fortress and they win. Just before the next battle starts, take an alliance character to the flamewatch tower and mount the cannon before the battle starts.

Horde should own the tower now but the ally cannon will not despawn (which is a bug). Stay in the cannon until the end, with horde losing again. On the next match do the same. See if it now evades damage. 

If not, the players Cromanthus, Alandi and Awesom know how to make them evade. They also know how to rotate the cannons further than should be possible. Drop them a message if any still play.

On a similar note there is a cannon on flamewatch tower that can spawn underground or sometimes inside the tower which can be mounted but can't always be hit. Needs relocating.

**Comment by Lothloryen** [comment]
Hello there,

@Edzero 's Issue list updated.

I didn't achieve to reproduce it that way, however did several improvements to the cannon management system and it should be fine now. In addition, they will not be available between games. Also corrected the orientation of some of them.

Players will now be automatically teleported to their corresponding initial positions upon joining the battle.

I gave a quick look to two battles on Algalon, and every of the previously mentioned fixes seem to properly work (tenacity looks perfect now, good calculation, properly applied and refreshed etc.), but if someone sees anything that is not, let me know, please.

**Comment by Edzero** [comment]
https://youtu.be/Wm03136FTI4

Players who fly to the zone should remain in their current position when the battle starts. Only those who entered via the queuing system should be teleported to the starting position.

**Comment by Lothloryen** [comment]
Hello there,

Okay, I have reworked the workshop / capture point system.

Now, the map states will be properly updated to every player within the map. Workshops/Graveyards will now properly reset on every battle: North East/West will belong to the defender and South East/West ones to the Attacker upon battle start - until the battle struggling feature is implemented.

**Comment by Edzero** [comment]
@Lothloryen that issue mentioned in #5120 regarding the passengers scaling with gearscore is present on wintergrasp vehicles too the last time I played. Possible to 1shot other players by riding as a passenger on a demolisher.

**Comment by Lothloryen** [comment]
Hello there,

Thank you Ed.

Fixed the issue with the passengers of vehicles (not only from the Strand of Ancients or Wintergrasp, it is general) being able to benefit from the gear scalling spell, it will be on the live realm with the next maintenance. The rest of the fixes are already on Algalon.

**Comment by Lothloryen** [comment]
Hello again,

I have some things in mind to work first that have some priority but, after I am done with them I shall implement the "Internal Battle Struggle" system for Wintergrasp.

**Comment by Lothloryen** [comment]
Hello there,

I have fixed the last issue on Wintergrasp, that with multiple towers spawned on the same spot. So closing this. The latest fixes will be deployed to Algalon within the next maintenance, which should be this evening.

I would like to thank everyone who collaborated here, specially to @Edzero

**Comment by Lothloryen** [comment]
Every fix is already on Algalon.

**Comment by Edzero** [comment]
Make sweet love to me Loth.

**Comment by Edzero** [comment]
@Lothloryen will you be keeping it that all players are ported or have it like retail?

**Comment by Lothloryen** [comment]
Hello there,

After tomorrow's maintenance the teleport's correction will be on live.

**Comment by Edzero** [comment]
You're a good egg.

Send nudes.

**Comment by Lothloryen** [comment]
There might appear a new issue after so many fixes, so please, report them here and we will take a look as soon as they are reported.

**Comment by Lothloryen** [comment]
I was reviewing some things from Wintergrasp's code and just found an issue where the workshops in the keep would not properly be owned by the defender faction - I am surprised that no one reported this problem yet.

I have fixed it already and will be deployed with tomorrow's maintenance.

**Comment by Edzero** [comment]
People were mentioning it today but didn't bother to report it properly.

Send lewds.

**Comment by Edzero** [comment]
@Lothloryen The quests that are meant to be randomly picked from a pool are still all available at the same time.

Tenacity was not kicking in despite an 82 v 40 match.

**Comment by Edzero** [comment]
Same issue on tenacity persists, 32 versus 68 and no buff.

Will trade nudes for fix.

**Comment by Lothloryen** [comment]
Hello there, 

I think I know what could have generated a conflict, it will be deployed tomorrow morning.

Thank you for the heads up.

**Comment by kinpie** [comment]
Cannons shown here are able to shoot opposite of the direction intended:

![wgcannon1](https://user-images.githubusercontent.com/36087298/35753918-85b7b910-082f-11e8-9747-7aeb5ec470b0.jpg)
![wgcannon2](https://user-images.githubusercontent.com/36087298/35753921-894c0eaa-082f-11e8-82d0-3dbb13a1b690.jpg)
![wgcannon3](https://user-images.githubusercontent.com/36087298/35753923-8ae9d21a-082f-11e8-9b94-289ac7379aec.jpg)

here is me inside the same cannon towards the end of the battle:

![wgcannon4](https://user-images.githubusercontent.com/36087298/35753961-aaa5505c-082f-11e8-86be-4d42f9be3daa.jpg)
![wgcannon5](https://user-images.githubusercontent.com/36087298/35753964-ac198bc4-082f-11e8-849e-f00a61c3fc12.jpg)

Yes, this could easily mean the difference between a win or loss.

**Comment by Lothloryen** [comment]
Hello there,

Thank you @kinpie , I will take a look.

While debugging few things, I noticed an issue where there was a chance of Tenacity not applying correctly, I have corrected it already and it will be on the live realm after the next scheduled maintenance.

Regards.

**Comment by Lothloryen** [comment]
Also, I got a report about the RPGG going through walls - it should also be fixed with the next maintenance.

**Comment by Edzero** [comment]
Being dead when the battle ends limits the amount of honor that you can gain still.

The 3000 honor granted for winning an offense isn't given, but the 750 or 1500 per tower objective damaged/destroyed is given.

**Comment by Edzero** [comment]
The NPCs throughout the zone have strange pull behaviour.

This is currently being abused by certain players who are pulling all of the NPCs in the zone to one area, so that the whole raid can instantly get full rank.

It's an easy fix for an overpowered exploit.

**Comment by Lothloryen** [comment]
Hello there,

Thank you very much @Edzero , it is a general issue. I have fixed it and will be fine after the next maintenance.

**Comment by globoxxd** [comment]
Wow can't believe I posted this nearly 5 years ago.  Hope the server is going well :)

**Comment by Edzero** [comment]
I don't know what happened exactly but we lost a match with the outer walls being intact and the inner wall being destroyed. The only wall that could have been shot through with a siege was the southern side, which I was standing near up until about 10 seconds before we lost.

Did we miss something stupid, or is this a cheat? Nobody in the fort saw any horde vehicles or players there. Maybe if people were inside the fortress and blew the wall from the inside with explosives, but that'd take a lot of players a lot of time to achieve.

![wowscrnshot_042218_212641](https://user-images.githubusercontent.com/16586559/39099834-92c10d1e-4678-11e8-834b-f061df69eb34.jpg)

**Comment by Edzero** [comment]
Global Thermal Sapper Charge (item ID 42641 / spell ID 61765) is not dealing damage to the inner door of the fortress in WG, though it should. Tried using it 20+ times and no damage no matter where I stand.
