### ISSUE TITLE
Quest: The Flesh Giant Champion [13235]

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#576]
The whole event is missing.

Quest: http://www.wowhead.com/quest=13235
Morbidus: http://www.wowhead.com/npc=30698
Video: http://www.youtube.com/watch?v=VoR6xR_CmYQ

**Comment by Golganeth** [comment]
The NPC Morbidus doesn't seem to attack players at all, related to #220

**Comment by Kaporalhart** [comment]
The event is here now and we can kill the abomination, but the quest doesn't register the kill. i've killed him twice now but it's not granting me the kill.

**Comment by deasease** [comment]
i cna approve it didnt count kill

**Comment by Linandir** [comment]
Killed him about 10 times and never registers the kill. I was thinking it might be due to the fact that I am not doing the majority of the damage done to him? I will try this with a group and see if that helps.

**Comment by DrFuler** [comment]
[22/04/2016] - Still bugged.

The event occurs but you don't get the credit for it. I've tried a couple of times. I had the same thought as Linandir (that maybe is because the npcs are doing most of the damage), so I tried to burst as much damage I could on it, and leave my Kill Shot to finalize the mob, but still no credit for the kill.

**Comment by Lothloryen** [comment]
Hello there,

It has been corrected and applied to the live server.

Thank you.

**Comment by Zibathy** [comment]
The fix was not applied to Kirin Tor. There is no NPCs or enemies at all that spawn after acquiring this quest.
