### ISSUE TITLE
[Quest][Outland] Nexus-King Salhadaar

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#586]
http://wotlk.openwow.com/quest=10408

**Issue:** You are not able to attack nor target Nexus-King Salhadaar regardless what you do.

**How it should work:** There should be three force fields (sort of a blue beams) protecting the boss, one from each of the conduits. Once you successfully use the provided item near all of them, the boss becomes vulnerable and charges on you.

**Video of how it should look like**: www.youtube.com/watch?v=Rs8zH2vtpGY#t=0m26s 

---
- _Protectorate Disruptor_ - http://wotlk.openwow.com/item=29618
- _Nexus-King Salhadaar_ - http://wotlk.openwow.com/npc=20454

**Comment by Demlock** [comment]
Works just fine now...

**Comment by Daveonx** [comment]
Tested and working, but [Nexus-King Salhadaar](http://www.wowhead.com/npc=20454/nexus-king-salhadaar) needs some improvements when he becomes active, doesn't enlarge in size or darker and doesn't descend unless engaged.

**Comment by Rushor** [comment]
DB/Quest: Nexus-King Salhadaar - Update combatscript and add spell 'Salaadin's Overspark'

* closes https://github.com/dalaranwow/dalaran-wow/issues/586
* commit: 94a985e8e86aad93abbfba18b00dc5d693dbb0bb

![GitHub Logo](http://i.imgur.com/QIE2A98.jpg)
![GitHub Logo](http://i.imgur.com/gGlC6UQ.jpg)
![GitHub Logo](http://i.imgur.com/AgHauV3.jpg)
![GitHub Logo](http://i.imgur.com/59UPema.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
