### ISSUE TITLE
Quest: Wandering Shay

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#59]
http://wotlk.openwow.com/quest=2845
The NPC does not follow the Player
http://wotlk.openwow.com/npc=7774

**Comment by n-ghost** [comment]
Still an issue.

**Comment by Spruitje** [comment]
Did this quest just recently, but it was very buggy
Shaw does follow the player, however seems not to be walking but just teleports or 'blinks' to you every few yards or so when you move away from her current position
Also she disappears under texture on many occasions
Even at the spot where you start this quest she kind of 'blinks' around, sometimes on and sometimes under texture
Best to set a raidmark on her so you won't lose track of her current position, and keep a close eye on the chatlog because it states when she does start 'wandering off' and you need to use the bell
This quest is completable this way, but the visual issues make it annoying

I would say 'working but needs attention'

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/commit/d26cae7e1109b9db41b62a67d7e0e9c3359864c7

already fixed by tc
