### ISSUE TITLE
[Quest][Classic] The Angry Scytheclaws

### ISSUE THREAD

**Issue by Astraxa** [dalaranwow/dalaran-wow#598]
This quest requires an item that drops from raptors in the barrens.
The item drops after few kills, but the problem is here:
this item is used on raptor nest for some reason ( quest objective ), but it can be used from a unlimited range. Shouldn't it be used from a 5 yards max range?
Using it from very far makes the quest easy and simple - the player can avoid killing the raptors around the nest.
I just did the quest: when the player comes close to the nest, the cursor becomes yellow, meaning it can be clicked on to activate whatever needs to be done.
Please look into the quest.
Thank you.

**Comment by Rushor** [comment]
DB/Quest: The Angry Scytheclaws - Sunscale Feather should only be castable in 5 yards range to the Raptor Nests

* closes https://github.com/dalaranwow/dalaran-wow/issues/598
* commit: 8699e9c50fbc1691163908f54c297030b7f99068

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
