### ISSUE TITLE
[Quest][Classic] Egg Hunt

### ISSUE THREAD

**Issue by Astraxa** [dalaranwow/dalaran-wow#601]
This quest is taken and done in the Barrens.
An item is given from the quest giver in order to do the quest: "Digging Claw".
This item is used on little scorpion "nests" to extract from them the eggs needed to complete the quest. However, mobs around those nests drop those eggs as loot ( Silithis grub, Silithid Protector ), which shouldn't. Eggs must only be obtained from the scorpion nests. And I'm not sure about the amount dropped when a scorpion nest is opened: I used to get 3 eggs from 1 nest.
Please look into this quest.
Thank you.

**Comment by Rushor** [comment]
DB/Quest: Egg Hunt - Eggs should not be contained in creatures and every Silithid Mound should contain only one egg

* closes https://github.com/dalaranwow/dalaran-wow/issues/601
* commit: e92690375097c45dff504d9e4129bba1dfd4c5ab

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
