### ISSUE TITLE
Roleplay Event: Cleansing Drak'tharon Keep - The Lich King

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#608]
**Quest** Cleansing Drak'tharon Keep - _12238_
**The Lich King ID on that event** - _28498_

**EVENT WORKS FINE BUT ONE PART IS BROKEN**

---
- **Minor issue present with Roleplay** - When you start the roleplay event, everything works perfectly fine until the point where **The Lich King** is about to spawn. 

The issue is that **The Lich King** spawns somewhere underground, not in the line of sight. Maybe even Pathfinding is screwing him. In any case, the thing is that **The Lich King** is slowly traveling through textures/ground until he gets to his point to start his roleplay speech. 

Because of that, the script is still going, but the timing is wrong and all the quotes are messed up because of him.

**How to fix and it will sure work after that:** - Make sure to spawn **The Lich King** on a solid ground, just like **Drakuru**.
**The Lich King** smoothly has to spawn from the portal and not somewhere underground where his model/creature will fall down and then go back up through textures.

![image](https://f.cloud.github.com/assets/5054924/969957/bb56a306-05cd-11e3-836e-383328e0b794.png)

---

http://www.wowhead.com/quest=12238/cleansing-draktharon#screenshots
http://www.wowhead.com/npc=28498/the-lich-king

**Comment by TeridanDW** [comment]
The Lich King's spawn position is correct now however he still falls underground at this point:
![1](https://cloud.githubusercontent.com/assets/6797611/24449643/a2e52494-1480-11e7-9361-942847c7f68b.png)

and after ~ 10 secs he comes up at his correct position however it's too late the timing of the texts is all messed up because of that fall. Maybe if we add more points to his path?

**Comment by Rushor** [comment]
i will try flagextra ignore pathfinding

**Comment by Rushor** [comment]
kay had to change a few points but it works now

**Comment by Rushor** [comment]
DB/Quest: Roleplay Event: Cleansing Drak'tharon Keep - The Lich King - Correct waypoint movement

* closes: https://github.com/dalaranwow/dalaran-wow/issues/608
* commit: 042390aecb67b40c968334ab4473bb0924416b3e

![GitHub Logo](http://i.imgur.com/T9uP6pP.jpg)
![GitHub Logo](http://i.imgur.com/fgZOppE.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
