### ISSUE TITLE
[NPC] Terokkar Arakkoa Fly Target [22340]

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#613]
It is visible for players but it shouldnt be

**Comment by Rushor** [comment]
DB/Creature: Terokkar Arakkoa Fly Target + Jump-a-tron 4000 - should be invisible for player

* closes https://github.com/dalaranwow/dalaran-wow/issues/613
* commit: 7aa37b9e58dd237082e3a04f281ca72f9a6f77a5

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
