### ISSUE TITLE
[Quest][Classic] Revenge of Grann

### ISSUE THREAD

**Issue by Astraxa** [dalaranwow/dalaran-wow#634]
This quest is in the Barrens.
A quest item is given to burn and destroy a plane, but the problem is that the plane's re-spawn takes a lot of time - more than 15 minutes!
Please look into this quest.
Thank you.

**Comment by Rushor** [comment]
DB/Quest: Revenge of Gann - Reduce spawntime for object 'Bael Modan Flying Machine' to 60 seconds 

* closes https://github.com/dalaranwow/dalaran-wow/issues/634
* commit: 942c1998e5270c4ad5604b4773f3a3ff87b0b3bf

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
