### ISSUE TITLE
Quest: Adding Injury to Insult

### ISSUE THREAD

**Issue by Muncic** [dalaranwow/dalaran-wow#639]
The "boss" turns tails right before the ambush, has to be killed manually which is not right.

**Comment by Kaporalhart** [comment]
I confirm SadhuArch, Bjorn is supposed to have the same speed as the player so he can't catch up with you, and the npc that helps is supposed to use a poison, saying as he uses it that he was saving it for this occasion, and it is quite powerful as i remember it.

**Comment by arvidinge** [comment]
Clearly you need to take another look at this quest, should be as easy as any other, currently the only way for me to beat it on my warlock was using 2x on use sp trinkets, blood fury, and for healing; lifeblood, healthstone, haunt, death coil and drain life instead of shadow bolt. I died when boss was around 10%, ressed with soul stone and finished off barely.

**Comment by jonanone** [comment]
Bjorns speed and behaviour has been adjusted.
It will arrive to the Ambush zone if used properly (start running once used).

The fix will be applied to the live realm soon.
