### ISSUE TITLE
Misc: Pending Sale: Estimated Delivery Time

### ISSUE THREAD

**Issue by Gordin508** [dalaranwow/dalaran-wow#658]
__Current Issue:__ When you get the info-mail about a succesful sale via action house, the listed "Estimated Delivery time" is always 0:00.
__How it should work:__ It should show the specific time the earned money is going to arrive (one hour after the sale).

A screenshot of an example mail:
![image](https://f.cloud.github.com/assets/5062634/987134/d38f7446-08e5-11e3-8aec-e490a2f1c42b.png)

**Comment by Sagrath** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/2873
merging

**Comment by Rushor** [comment]
Game/AuctionHouse: Fixed timestamp for pending mails

* closes https://github.com/dalaranwow/dalaran-wow/issues/658
* the time should be displayed correctly now.
* commit: a8b21b8c14117f20bafc99ce33fb34dfe33a6a7b

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
