### ISSUE TITLE
[Quest][Outland] Battle of the Crimson Watch

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#659]
http://www.wowhead.com/quest=10781
Only the first wave of mobs are attacking the players, rest of the event is broken
There should be 3 wave of mobs and final 4th wave boss

http://www.youtube.com/watch?v=tiwpKqlLGaM

**Comment by Bonham01** [comment]
I completed this quest today on Algalon. It bugged the first time and only spawned the first wave. I dropped the quest, reaccepted and nothing happened this time (nothing spawned). So I flew away until I received the "Failed" message and then dropped/reaccepted again. This time however, I stood in the middle of the platform after the first mob and all 4 waves (including the boss at the end) spawned just as they were supposed to do. Might be a fix, might have just gotten lucky.

**Comment by Cone182** [comment]
Still bugged.

**Comment by medan** [comment]
This quest works, but is a bit tricky. I did it as Bonham01 described. After first wave zone out and quest will fail. Then abandon and take again. Stay in the middle of that platform and kill all waves. Finaly get your tabard.

**Comment by Sagrath** [comment]
Update: NPC Lord Illidan Stormrage 22083 have reseting issues

**Comment by datbunneh** [comment]
The first wave does not spawn, after I zone out the quest does not fail.

**Comment by Rushor** [comment]
Scripts/Quest: Battle of the crimson watch - Increase DeadMemberCount also for player which are not in range of 65 yards of the area

* closes https://github.com/dalaranwow/dalaran-wow/issues/659
* the quest should fail and the creature should reset if the player zones out
* commit: b6b08cb22f05747bb64508ddf56f08137e8a4d1d

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
