### ISSUE TITLE
Object: Supply Crate 166872

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#666]
the Supply Crate http://old.wowhead.com/object=166872
should drop (among other things) Stratholme Holy Water
http://old.wowhead.com/item=13180 
needed for quests Houses of the Holy http://old.wowhead.com/quest=5243
and Collection of Goods http://old.wowhead.com/quest=7642

Only way to get Stratholme Holy Water http://old.wowhead.com/item=13180 now 
is from the 3 Stratholme supply crates http://old.wowhead.com/object=181085 
all the way in the last area with the abominations and the baron.

**Comment by n-ghost** [comment]
Still an issue, quest is on auto-complete.

**Comment by n-ghost** [comment]
At the moment maybe 1/3 of crates can be salvaged, those actually can be tracked with Find Treasure.

**Comment by jonanone** [comment]
Supply crates behaviour has been adjusted. Now they will break if they don't contain anything. The fix will be applied to the live realm soon.

**Comment by Rushor** [comment]
Ref: https://github.com/dalaranwow/dalaran-wow/issues/1817

DB/Quests/Stratholme: Houses of the Holy - Collection of Goods.

Supply crates behaviour has been adjusted. Now they break if they don't contain anything.

Closes https://github.com/dalaranwow/dalaran-wow/issues/666
* commit: e1de3d7ccc265661047bfd59bce5c53860e6f022

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
