### ISSUE TITLE
[Druid] Enrage

### ISSUE THREAD

**Issue by Niny** [dalaranwow/dalaran-wow#67]
The Enrage spell of a Druid tank dosent reduce the Druids Armor as it should during the 10 sec of the buff duration the armor stays the same.
http://wotlk.openwow.com/spell=5229

**Comment by Golganeth** [comment]
It reduces armor but not the correct amount. It should reduce reduce base armor by 27% in Bear Form and 16% in Dire Bear Form.

Right now it reduces roughly 10% in Bear Form and 4-5% in Dire Bear Form.

**Comment by robinsch** [comment]
I'm closing this. According to the tooltip base armor should be reduced, which is just Armor from Item stat (not from Agility). If someone has a proof that it should decrease the entire amount of armor feel free to reopen this issue.

**Comment by Golganeth** [comment]
http://vanilla-wow.wikia.com/wiki/Enrage_(druid_ability)

> Enrage generates rage. It also reduces your base armour, which includes benefits from Bear forms, but doesn't include spell buffs such as Gift of the Wild. For example, if you have 15000 armour in Dire Bear form, you will lose 2400 armour whilst enrage is active.

Bear Form increases armor contribution from items by 180%, enrage should reduce base armor while in this form by 27%.

Dire Bear Form increases armor contribution from items by 370%,, enrage should reduce base armor while in this form by 16%.

Since it's a bear-only skill, I'm assuming the calculation of the % base armor reduced must be based only after 180%/370% extra armor have been calculated, otherwise the reduction is so small that it's pointless.

Pending of feedback and/or conclusive proof. Reopening for now

**Comment by Golganeth** [comment]
PTR results with spell power gear (so that agility doesn't interfere that much):

Bear Form: No Enrage: 6249 armor
Enrage: 5122 armor
(18%~ armor reduced, should be 27%)

Dire Bear Form: No Enrage: 10005 armor
Enrage: 9056 armor
(10%~ armor reduced, should be 16%)

**Comment by TheRealestMcCoy** [comment]
Tested on a level 74 as the level should have no effect.
Tested with and with out talents these are the results.

With talents
Armor 16339-enrage=13724
**Current Enrage Armor 14775**

No Talents
Armor 11330-enrage=9517
**Current Enrage Armor 10220**

**Comment by Rushor** [comment]
Game/Spells: Druid - Update Enrage armor reduce part and move it to HandleAuraSpecificMods

* updates: https://github.com/dalaranwow/dalaran-wow/issues/67
* commit: b4e6c3863a2d077e5d56d0a5cef4d19a8f509cb3
* commit: e962062c11e8eb0c9c227d0b473e87280ca67900
* commit: 7e03e2ad39faadeb1944476aa2b02c24d076c797

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
