### ISSUE TITLE
[NPC] Spells causing infinite NPC chase

### ISSUE THREAD

**Issue by Gordin508** [dalaranwow/dalaran-wow#682]
**Current issue**: If you mind control a humanoid mob/NPC and then cancel it (or channel it long enough so it gets automatically cancelled), the NPC will chase you for an unlimited distance until killed.
**How it should work**: The NPC should only follow you for a certain distance to his spawn/path like usually.

Spell link: http://wotlk.openwow.com/spell=605

**Comment by Golganeth** [comment]
#2217 -
> Issue Present: Damage with buffs like Retribution Aura, Thorns or Fire Shield reset the leash range of mob

**Comment by moodyblues4me** [comment]
This also occurs with a druid and the use of Thorns.

**Comment by Rushor** [comment]
more info in this since the bahaviour was updated with this commit:

Game/Unit: Add attackstart for creatures once the charm fades away + add basic SAI to all creatures with CREATURE_FLAG_EXTRA_CIVILIAN which are spawned in the world

* updates: https://github.com/dalaranwow/dalaran-wow/issues/4613
* commit: 88398faa1a75beba3b21e477de03f9ae7da14168

The creatures actually resets correctly after the **first respawn**. But if you mind control (and cancel it) the creature directly after spawn (e.g.: if the creature spawns for **the first time after sever restart**) it will chase you infinite.

maybe the ai is somehow not loaded correctly?

**Comment by Rushor** [comment]
> AND THE BIG ONE Charming a target with this spell completely eliminates its evade leash, allowing a priest to kite a mob indefinitely.

Already reported in https://github.com/dalaranwow/dalaran-wow/issues/3314 (Merging those 2 issues)

Once https://github.com/dalaranwow/dalaran-wow/issues/3314 was fixed it will be fixed for all other spells too, because this missing reset behaviour is not bound to the spell "Mind Control" but instead depending on missing AI load after all charm effects are removed.
