### ISSUE TITLE
NPC: Dawnblade Hawkrider (TBC)

### ISSUE THREAD

**Issue by riddermark** [dalaranwow/dalaran-wow#730]
**Minor issue**
___

http://www.wowhead.com/npc=25063/dawnblade-hawkrider

There's a really annoying problem with these NPCs on the isle of quel'danas. They have what seems to be an endless range for their fire attack.

If you walk around on the ground in the square you will get hit by 1 or 2 that fly around repeatedly - and the hits do they from your HP and the HP of other ground NPCs around.

From what I've gathered the should be able only to reach the archers put around the terraces.

Minor annoyance.

EDIT:
I want to add the same range problem with http://www.wowhead.com/npc=24979/dawnblade-marksman

And introducing a screenshot to prove my point (npc on the far right on the terrace is shooting at me)
http://i.imgur.com/HFwzLAu.jpg

**Comment by Golganeth** [comment]
#1657

**Comment by Rushor** [comment]
Game/Spells: Dawnblade Attack + Flaming Arrow should only target Shattered Sun Marksman

* closes: https://github.com/dalaranwow/dalaran-wow/issues/730
* commit: 44cf942065dc14e70ed66afb7b5d31615fbae3d8

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
