### ISSUE TITLE
Item: Bubbling Brightbrew Charm

### ISSUE THREAD

**Issue by riddermark** [dalaranwow/dalaran-wow#800]
http://www.wowhead.com/item=49118#comments
Nothing works on this trinket. The summoned "pet - The Brewmaiden" should do the following:
- Cast this spell on party (adjust for lvl 80 = heals 103 every 2 secs)
  http://www.wowhead.com/spell=51847
- When a player /waves at her she should toss him a Brewfest Brew
  http://www.wowhead.com/item=33929
  by using this spell:
  http://www.wowhead.com/spell=48249
- Her duration of existence should be 35 seconds:
  http://www.wowhead.com/spell=101286/summon-the-brewmaiden

**Comment by Rushor** [comment]
DB/Item: Implement the The Brewmaiden for 'Bubbling Brightbrew Charm'

* closes https://github.com/dalaranwow/dalaran-wow/issues/800
* commit: c4c1be8e48ed4615639022971f50612829c6af78

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
