### ISSUE TITLE
Quest: Test Flight: Ruuan Weald

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#805]
**Quest Test Flight: Ruuan Weald** - *(ID:10712)*

- **Issue Present:** After the latest fix for this quest this is what happens:
After you talk to NPC **Rally Zapnabber** *(ID:21461)* and you choose gossip option, **Take me to Ruuan Weald**, you get teleported on the platform to get launched. Now, the issue is after you get launched into the air, you do not get the credit for the first part of your quest, which is **Launch to Ruaan Weald**.

- **How it should work:** After getting launched, players should get the credit for the 1st part of the quest, **Launch to Ruaan Weald**, marked as completed.

________________

http://www.wowhead.com/quest=10712/test-flight-ruuan-weald
http://wotlk.openwow.com/quest=10712

**Comment by jonanone** [comment]
Now it's working as intended.

**Comment by Jezzybane** [comment]
Dont wanna ruin anything but i try to get it to work for like an hour and it aint working correctly. Even tho i got credit in both the item and the flight i cant hand it in.
![tf1](https://cloud.githubusercontent.com/assets/20131443/17412354/984a2e62-5a7c-11e6-8c10-0537a707a16a.jpg)
![tf2](https://cloud.githubusercontent.com/assets/20131443/17412363/9e92bafa-5a7c-11e6-930e-91286db34d50.png)

**Comment by Guzzone** [comment]
Just wanna confirm what Jezzybane said, I can't complete the quest even if both requirements are met.

If anyone know a workaround that would be appreciated

**Comment by Rushor** [comment]
DB/Quest: Test Flight: Ruuan Weald - Add Questcredit for Spell: Spin Nether-weather Vane 

* updates: https://github.com/dalaranwow/dalaran-wow/issues/805
* commit: c3f915522462ad55659e734da187f3c0d1e86fb2

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
