### ISSUE TITLE
[Spell] Shadow Sight

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#816]
http://www.wowhead.com/spell=34709
Shadow sight powerup applies as a buff rather than a debuff, also does not unstealth a stealthed  who picks it up.
Shadow Sight:
Stealth Detection.
Invisibility Detection.
Increases damage taken by 5%.
Duration: 20 seconds.

**Comment by Rushor** [comment]
DB/Spell: Shadow Sight - should be a debuff

* closes https://github.com/dalaranwow/dalaran-wow/issues/816
* commit: a21e5bd53ab2e42ce263b071d25b50aa12789a21

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
