### ISSUE TITLE
Quest: Assault by Ground (Daily)

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#823]
**Quest Assault by Ground** - *(ID:13284)*
**Quest Assault by Ground** - *(ID:13301)*

- **Issue present**: Once you pick up the quest either from **Skybreaker Squad Leader** or **Kor'kron Squad Leader** the escort event doesn't start.

- **How it should work**: Once you pick up a quest, the escort event should start and you have to follow and protect the ground units until they reach their destination from point A to point B.

**Partial video of how it should work:** *http://www.youtube.com/watch?v=b8juh_f_ueU*

_________

http://www.wowhead.com/quest=13284/assault-by-ground
http://www.wowhead.com/quest=13301/assault-by-ground

**Comment by Mantigora** [comment]
confirmed does not work. Event does not start, making impossible to complete quest.

**Comment by Arrowzinger** [comment]
Still nothing on this?

**Comment by deasease** [comment]
yup still not work

**Comment by MrAndersonX** [comment]
Confirmed - bugged. Needs a fix.

**Comment by DrFuler** [comment]
[21/04/2016] - Still bugged.

**Comment by Lothloryen** [comment]
Hello there,

Already implemented, it will be live after the next realm restart.

Thank you for the reports.

**Comment by Randomi** [comment]
Hello, this quest worked correctly at first but i failed to complete it so i retook it, since that time, only the party leader starts running, no infantry is following him making quest completion impossible.

**Comment by Rushor** [comment]
cannot reproduce that since we have this scriptline

```sql
(@ENTRY,0,5,0,61,0,100,0,13284,0,0,0,45,0,1,0,0,0,0,9,31701,0,10,0,0,0,0,"Skybreaker Squad Leader - On Quest 'Assault by Ground' Taken - Set Data 0 1"),
```

which always makes the follower to start the path and follow their leader

**Comment by Edzero** [comment]
1 of the infantry fails to despawn and won't grant credit.

Also credit is not given to the whole group but only one person at a time.

https://drive.google.com/open?id=0B4oLoQsMtUhCdzFUdzFvZVQ5LXc

**Comment by Rushor** [comment]
DB/Quest: Assault by Ground (H)(A) - Implement questevent, increase despawnrange and questcreditrange for Skybreaker Infantry and Kor'kron Infantry

* closes: https://github.com/dalaranwow/dalaran-wow/issues/823
* commit: 8c9acfdabe88dea89d1c21cd96bac0e2751b1600

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
the fix for the quest was not yet applied on ptr, so i added the scripts from scratch
