### ISSUE TITLE
NPC: Kilix the Unraveler

### ISSUE THREAD

**Issue by Tasserski** [dalaranwow/dalaran-wow#856]
Kilix the Unraveler is an important quest giver in Dragonblight.

Currently when other mobs in the cave happen to attack Kilix (not sure if this is a timed event), the quest giver also becomes attackable by players. This shouldn't happen.

**Comment by jonanone** [comment]
Kilix won't attack incoming creatures so it will not be attackable by players.
This update will be applied to the live realm soon.

**Comment by Rushor** [comment]
DB/Creature: Kilix the Unraveler and Azjol-anak Battleguards - no longer attackable as player

* closes https://github.com/dalaranwow/dalaran-wow/issues/856
* commit: ab2d571cbdf67891190f5bc4a8ae483acfa58ad9
* commit: fb0b32e89f52768e93a2a36de283012e5a782891
* commit: 6c1db78f95395f6bced8637cf9cd1eb33bd13860

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
