### ISSUE TITLE
Daily Quest: Song of Wind and Water  12726

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#862]
http://www.wowhead.com/quest=12726/song-of-wind-and-water
Mobs cant be killed cause they keep reseting thier HP as you are in the water elemental vehicle, and the third spell for dvouring dosnt work
http://www.wowhead.com/npc=28999
http://www.wowhead.com/spell=52864
http://www.wowhead.com/spell=52862

**Comment by Khronos-** [comment]
It works of now but there is still some bugs.

Devour ability only works with mob at 35% Hp or less. Which is working as intended.

However, both #1 abilities, Lightning Bolt for Lightning Elemental and Water Bolt for Water Elemental, are dealing waaaay too little dmg: 150 dmg per ability, which is not working as intended. Lightning Elemental has ability #2 which compensates for the lack of dmg, but Water Elemental form can be destroyed by Lightning enemies due to it's very little dmg.

The only workaround I've found is to down Lightning enemies to 35% hp as your normal character and then summon the Haiphoon to consume them. Then proceed to (slowly) kill the Water enemies.
