### ISSUE TITLE
Misc: Tailoring: Lightweave Embroidery

### ISSUE THREAD

**Issue by untitledlives** [dalaranwow/dalaran-wow#865]
Greetings, 

I'm a Resto Druid, I just enchanted my cloak with lightweave embroidery

i've done some extensive testing to with the spell i've casted 

rejuv, lifebloom and wilid growth over 50 times and i have not been able to attain the buff.

i believe it should be working on all spell casts

not just the ones with cast times

**Comment by Rushor** [comment]
DB/Spell: Update procflags for 'Lightweave Embroidery'

* closes https://github.com/dalaranwow/dalaran-wow/issues/865
* commit: 6a8c5c6c65f600837345665b8338f1221a3efe0b

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
