### ISSUE TITLE
[Quest][Classic] Vyletongue Corruption

### ISSUE THREAD

**Issue by vexohm** [dalaranwow/dalaran-wow#869]
http://www.wowhead.com/quest=7041

Using the "Filled Cerulean Vial" on the Vine objects inside the instance does not spawn the "Noxxious Scion" as supposed to, it simply removes the vine object.

http://www.wowhead.com/item=17696 - filled quest item
http://www.wowhead.com/spell=21885 - spell it casts
http://wotlk.openwow.com/object=178905 - the object to be cast near
http://www.wowhead.com/npc=13696 - NPC that should be summoned

Comment from wowhead: "Two or three Noxxious Scion spawns and you need to kill 8 of these in total to complete the quest." - that's from one object.

**Comment by stromex** [comment]
Still not working.

**Comment by Daveonx** [comment]
The [Noxxious Scion](http://www.wowhead.com/npc=13696/noxxious-scion) are now spawning when the [item ](http://www.wowhead.com/item=17696/filled-cerulean-vial)is used, the issue that occurs now, is that only one spawns, when it should be 2-3, thus taking longer for the quest to be completed.

**Comment by Rushor** [comment]
DB/Quest: Vyletongue Corruption - After itemuse, two Noxxious Scion will now always appear and for 40 percent a third one

* closes https://github.com/dalaranwow/dalaran-wow/issues/869
* commit: 9065bcdca53604d8a67fbd3b63053795ec939d3c

![GitHub Logo](http://i.imgur.com/DV4dFi3.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
