### ISSUE TITLE
[GO] "Soothsaying for dummies" in north east Tanaris

### ISSUE THREAD

**Issue by LFlorschutz** [dalaranwow/dalaran-wow#870]
Hello,

I can't switch specializations ( Goblin engineering to Gnomish engineering). Book at the table which can accomplish that is not working. Any help please?

proof:  http://i.imgur.com/Jy9fGyv.jpg?1

Thank you in advance

**Comment by Poonchy** [comment]
Bump, still not fixed.

**Comment by Rushor** [comment]
Scripts/Gameobject: Implemented Book "Soothsaying for dummies" for change of engineering/leatherworking specs

* commit: 1c836c78e6c13c5dd792fafa275abb8d54975648
* commit: 1c89b4dcdfa0e25aee28245513b1cf464e3d9e7b (profession relurn on login disabled)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
@Lothloryen, please review this fix as there are tickets coming for this book from time to time.
Thank you.

**Comment by ErasmusHereticus** [comment]
Still not working on live.

**Comment by lkrocek** [comment]
if it is fixed already for 3 months and mentioned in http://www.dalaran-wow.com/changelog/21/the-path-to-a-new-dawn could you please deploy it!

**Comment by Lothloryen** [comment]
Updated.
