### ISSUE TITLE
[Quest][Classic] Toxic Tolerance

### ISSUE THREAD

**Issue by vexohm** [dalaranwow/dalaran-wow#874]
Greetings.

Issue with quest "Toxic Tolerance" in Un'Goro. The spell "Venomhide Poison" from "Venomhide Ravasaur" is able to miss, although I have read, that it should not be able to miss at all. At lvl 77 (no gear) I got roughly 40x "Venomhide Poison" misses in combat log before getting the first hit. Thus the quest would take way too much time than supposed to.

http://www.wowhead.com/quest=13850

http://www.wowhead.com/npc=6508 - Venomhide Ravasaur

These are the "Venomhide Poison" spells:

http://www.wowhead.com/spell=14792
http://www.wowhead.com/spell=14108
http://www.wowhead.com/spell=14795

Not sure which part may not be working properly.

**Comment by Rushor** [comment]
the used spell is http://www.wowhead.com/spell=14792 and has SPELL_ATTR3_IGNORE_HIT_RESULT. spells with this attribute will not miss. That is already fixed.

Concerning getting the buff:

> By thetacoman (7,374 – 3·8·38) on 2009/06/29 (Patch 3.1.3)
> It seems that you only get splashed if you are HITTING the revasaurs. Best thing to do is to unequip your weapon and beat on em with your fists while AFK

You need to hit the creature in order to get the spellhit.

So the only thing that needs to be fixed here is the missing prev.quest

**Comment by Rushor** [comment]
DB/Quest: Toxic Tolerance - Update prevquest-order

* closes https://github.com/dalaranwow/dalaran-wow/issues/874
* commit: 21ff2590b3e80f9b31fbb8586fca359c8a3a3c46
* quest 13887, now has the prevquest 13850

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
