### ISSUE TITLE
[Quest][Northrend] Drake Hunt 

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#877]
http://wotlk.openwow.com/quest=11919
http://wotlk.openwow.com/quest=11940 (Daily)

**Issue:** Once Nexus Drake Hatchling is tamed, there is a visual bug and only the name plate follows the player. Other than that, the quest works flawlessly.

---
- _Nexus Drake Hatchling_  - http://wotlk.openwow.com/npc=26127

**Comment by Rushor** [comment]
going to fix this today :)

**Comment by Rushor** [comment]
DB/Quest: Drake Hunt - Improve behaviour for Nexus Drake Hatchling

* closes https://github.com/dalaranwow/dalaran-wow/issues/877
* commit: 08a6a309759e095de46655d930d3d0980714b02d

![GitHub Logo](http://i.imgur.com/jardVDL.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Aridam** [comment]
Currently on Live there are no Hatchlings around -- been roaming Coldarra staring up at the sky and even going up the separate elevators in case of the Realm's lower view distance but still nothing; can't do the Quest.
