### ISSUE TITLE
[Quest][Classic] When Smokey Sings, I Get Violent

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#881]
**Quest When Smokey Sings, I Get Violent** - _(ID:6041)_
- **Issue present:** When you place the quest item,**Smokey's Special Compound** _(ID:15736)_, on the object, **Mark of Detonation** _(ID:177668)_, nothing happens.
- **How it should work:** When you do that, you should get the credit for destroying the Zigurat Building (Scourge Structure).
- **Additional informations:** Remember that quest item can be used only once on the mark and not mutiple times so players cannot spam the quest item on the same spot multiple times to get the credit.

---

http://www.wowhead.com/quest=6041/when-smokey-sings-i-get-violent
http://www.wowwiki.com/Quest:When_Smokey_Sings,_I_Get_Violent

**Comment by Daveonx** [comment]
Quest currently works with a minor issue. Once the item [Smokey's Special Compound](http://www.wowhead.com/item=15736/smokeys-special-compound) is used on the [Mark of Detonation](http://db.vanillagaming.org/?object=177668), players get credit and the object disappears, but players are still able to use the item again without getting credit and using up a charge of the item.

**Comment by Rushor** [comment]
Scripts/EasternKingdoms: Add spellscriptsupport for quest When Smokey Sings, I Get Violent

* player are no longer able to use the item again without getting credit and using up a charge of the item.
* closes https://github.com/dalaranwow/dalaran-wow/issues/881
* commit: c7beb0d00685c90ddc1da1529015b02d5a42e335

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
