### ISSUE TITLE
Item: Design: Fractured Scarlet Ruby

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#886]
**Item Design: Fractured Scarlet Ruby** - _(ID:41817)_
- **Issue present:** The following item is supposed to drop from **Nascent Val'kyr** _(ID:29570)_ but it doesn't after internal testing. Killed 500 Val'kyrs on Horde & Alliance character, not a single drop. Drop chance is around 1%
- **How it should work:** The following item should drop and the loot table has to be corrected. 
- **Additional info:** Two players came across this issue already, killed over 200 Val'kyrs, it didn't drop. Take note that you do not have to be Jewelcrafter for this item to drop. 

---

**Wowhead comment:**

_It took me 105 kills to get this recipe._
_Got the design after 9 Kills, assumed it would take me longer since the RNG usually hate me ^^
I also think people who killed more then 50 mobs are a little unlucky._

---

http://www.wowwiki.com/Design:_Fractured_Scarlet_Ruby
http://wowpedia.org/Design:_Fractured_Scarlet_Ruby
http://wowpedia.org/Nascent_Val%27kyr
http://www.wowhead.com/npc=29570/nascent-valkyr

**Comment by Rushor** [comment]
DB/Item: Design: Fractured Scarlet Ruby - will now drop for 3 percent from Nascent Val'kyr if you have the skill Jewelcrafting

* closes https://github.com/dalaranwow/dalaran-wow/issues/886
* commit: 052c7b7756d46915cd7b1f69cff3c0d1e858d0ee

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
already on PTR.
