### ISSUE TITLE
[Quest][Classic] Hints of a New Plague

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#894]
**Quest Hints of a New Plague?** - _(ID:660)_
- **Issue present:** Quest is automatically completed upon picking it up, it shouldn't be. There should be an escort / protective event going on.
- **How it should work:** Once picking up the quest from the NPC, **Kinelory** _(ID:2713)_ the escort event should start.

**WoWwiki info:**

_This is a fairly difficult escort, compounded by the fact that the Forsaken Courier and his Forsaken Bodyguards could be near Apothecary Jorell at the time that Kinelory gets to him._

_Kin runs east to a location where she can get to the bottom without taking fall damage, then turns around west hiding behind the stables and silos. There are two scripted spawns of two Hammerfall Grunts, one behind the second silo [59.6, 55.6] and the other just south of the barn [59.8, 57.9]. After walking between the two silos and south in front of the barn she'll enter the building with Apothecary Jorell in it. Afterwards, she'll run south to exit the farm then around the edge of the cliff to get back to Quae._

> On accept

_Kinelory says: Well then, let's get this started. The longer we're here, the more damage the undead could be doing back in Hilsbrad_

> Reaching the bottom

_Kinelory says: All right, this is where we really have to be on our paws. Be ready!_

> On aggro

_Kinelory says: Attack me if you will, but you won't stop me from getting back to Quae._

> Reaching Jorell

_Apothecary Jorell says: You have my word that I shall find a use for your body after I've killed you, Kinelory._

> Defeating Jorell

_Kinelory says: Watch my rear! I'll see what I can find in all this junk..._

> Kinelory begins rummaging through the apothecary's belongings.

_Kinelory says: I bet Quae'll think this is important. She's pretty knowledgeable about these things--no expert, but knowledgable._
_Kinelory says: Okay, let's get out of here quick quick! Try and keep up. I'm going to make a break for it._

> Returning to Quae

_Kionelory says: We made it! Quae, we made it!_

> Kinelory hands her pack to Quae.
> ---
> 
> http://www.wowwiki.com/Quest:Hints_of_a_New_Plague%3F_(4)
> http://www.wowhead.com/npc=2713#comments
> http://www.wowhead.com/quest=660/hints-of-a-new-plague

**Comment by Rushor** [comment]
DB/Quest: Hints of a New Plague - Add escortevent

* closes https://github.com/dalaranwow/dalaran-wow/issues/894
* commit: 5ec5608ab81d39c7b7ca48c4a34e512da44368ae

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
