### ISSUE TITLE
Object: Harthal Truesight

### ISSUE THREAD

**Issue by riddermark** [dalaranwow/dalaran-wow#898]
http://www.wowhead.com/object=210489

Content of the Object is wrong. It should be:

Harthal Truesight
Lord Paladin of the Scarlet Crusade 
Citizen of Azeroth - Knight of the Silver Hand
Last seen entering the cursed city of Stratholme

**Comment by Rushor** [comment]
DB/Gameobject: Harthal Truesight - Update Pagetext

* closes https://github.com/dalaranwow/dalaran-wow/issues/898
* commit: 729457fabee6cfc013989d62ec5334503d5dacf1
* remember to delete the cache folder before testing

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
