### ISSUE TITLE
[Quest][Classic] Hurley Blackbreath 4126

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#917]
http://old.wowhead.com/quest=4126
http://old.wowhead.com/npc=9541
http://old.wowhead.com/item=11312

Breaking open the kegs in BRD should spawn mobs that drop the recipe required for the quest. The kegs do nothing when broken.

**Comment by n-ghost** [comment]
Still is an issue.

https://github.com/dalaranwow/dalaran-wow/issues/1613

**Comment by Demlock** [comment]
This is still an issue...

**Comment by Rushor** [comment]
DB/Quest: Hurley Blackbreath - Add spawnevent for Hurley Blackbreath and Blackbreath Crony

* closes https://github.com/dalaranwow/dalaran-wow/issues/917
* commit: 42882d2f52298a774a816a64115323e97632f376

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
