### ISSUE TITLE
[Brewfest] Brewfest apple trak and Bok Dropcertain

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#939]
Apple Trap  ID: 186331 x3
[DND] Brewfest Delivery Bunny ID: 34337
Bok Dropcertain 24527
in durotar still ingame, should be visible only when brewfest is

**Comment by Rushor** [comment]
http://wotlk.openwow.com/npc=24337

is not spawned on ptr

**Comment by Rushor** [comment]
DB/Creature: Brewfest apple trap and Bok Dropcertain - Add guids to game_event

* closes https://github.com/dalaranwow/dalaran-wow/issues/939
* the object and the creature will now only be visible if event (24 = Brewfestevent) is active
* commit: f2791700e5cf2f86809f354088df87b6782464c9

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
