### ISSUE TITLE
[NPC] Mine Cart

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#941]
ID 28821
should not be targetable by players

**Comment by Rushor** [comment]
DB/Creature: Mine Cart - should not be targetable by players

* closes https://github.com/dalaranwow/dalaran-wow/issues/941
* commit: 06f059a8b9dda845996ddbf47c5d2b84a1047b80

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
