### ISSUE TITLE
[Quest]Classic] The Caverns of Time  10277

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#946]
Quest : http://www.wowhead.com/quest=10277/the-caverns-of-time
Custodian of Time spawns but doesnt start its waypoints upon accepting the quest

**Comment by Rushor** [comment]
this happens only sometimes

**Comment by Rushor** [comment]
Scripts/: The Caverns of Time - Start escort on summon

* not on MoveInLineOfSight, if the player does not move after quest accept, everything will stuck
* closes https://github.com/dalaranwow/dalaran-wow/issues/946
* commit: 54da722814d7e449da9f7fa9c7dbfc93990159b5

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
