### ISSUE TITLE
[Item] Rivers heart - Sholazar fishing

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#949]
At Rivers heart in sholazar basin the fishing loot is always empty except if one is fishing for daily quest or from fish schools

**Comment by Rushor** [comment]
DB/Fishing: Add Barrelhead Goby for Rivers heart zone

* closes https://github.com/dalaranwow/dalaran-wow/issues/949
* commit: 0a245ff9e7e1a2725d8293f9c7cff5593c3cabaa

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
