### ISSUE TITLE
Quest: Returning the Favor 9931

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#951]
http://www.wowhead.com/quest=9931/
Place Kil'sorrow Banner on top of a fallen Warmaul ogre. 
players are able to place a banner anywhere no conditions for area nor warmaul ogre corpse
http://www.wowhead.com/item=25555

**Comment by Tarpor** [comment]
Confirmed, someone blocked the Auction House with this today (http://i.imgur.com/DbP4d81.jpg), if this gets larger we can see a lot of abuse using platforming / LoS / blocking people. Needs to be fixed.

**Comment by Zibathy** [comment]
LMAO. That's amazing

**Comment by socialmedia1** [comment]
![capture1](https://cloud.githubusercontent.com/assets/8617360/15992072/d302f6ca-3078-11e6-956b-760f172124f6.PNG)

**Comment by Rushor** [comment]
DB/Quest: Returning the Favor - Summon banner only near dead Warmaul Ogres and only if there is no banner in range

* also reward the questcredit to the whole group
* closes https://github.com/dalaranwow/dalaran-wow/issues/951
* commit: 060542ac57c6316811fc5b4f4108dbf164e87275

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
