### ISSUE TITLE
[GO] Dark Keepers and Relic Coffer Events,Relic Coffer.

### ISSUE THREAD

**Issue by GMJeina** [dalaranwow/dalaran-wow#958]
Okey I've been in BRD today and tried to loot Relic Coffers, and I saw a few bugs.
1) Dark Keepers Event.
How should work:
In order to open Dark Keeper Vault I need Dark Keeper Key. That key is holded by one of the following Dark Keepers: 
Dark Keeper Bethek
Dark Keeper Ofgut
Dark Keeper Pelver
Dark Keeper Uggel
Dark Keeper Vorfalk
Dark Keeper Zimrel

After opening Dark Keeper Portrait (outside of the vault) one of the dark keepers is spawned and I must read the portrait to see in which location is spawned.
How does it work: 
After opening the Dark Keepers Portrait I'm not able to read it and Dark Keeper npc is not spawned.

2) Secret Relic Coffer Event: 
How should work:
I must gather 12x Relic Coffer keys and after that need to open 12 Relic Coffer Vaults, after opening them Watchman Doomgrip npc should be spawned in the vault, after killing him the Secret coffer safe should be uncover.
How does it work: 
After opening 12 vaults Watchman Doomgrip doesn't spawns.

3) Relic Coffer lootable.
How should work: 
In 12 vaults (13 with dark keeper's vault and 14 with secret vault) there is a chest called Relic Coffer, this chest should be lootable: 
http://www.wowhead.com/object=160836
How it works: 
The chest is not lootable.

**Comment by n-ghost** [comment]
Still is an issue.

**Comment by Demlock** [comment]
It is still an issue. None of these are scripted and do not appear at all ingame...

**Comment by Rushor** [comment]
DB/Gameobject: Add scripts for Dark Keepers and Relic Coffer Events, Relic Coffer

* closes https://github.com/dalaranwow/dalaran-wow/issues/958
* commit: 3e396a205cb780ef5b0ff537b06261f77a5971b0

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
related: https://github.com/dalaranwow/dalaran-wow/issues/2707
