### ISSUE TITLE
[Skill/Enchanting] Abyssal Shatter  Spell ID: 69412

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#959]
http://www.wowhead.com/spell=69412
The skill is learned from enchanting trainer at 445 skill with enchanting
Upon learning it is yellow and should give skills but it doesnt give any enchanting skills tested with multiple stacks also player did report the issue with it
should turn green at skill 447

**Comment by Rushor** [comment]
Core/Spells: Abyssal Shatter should have a chance to skill up

* commit: 711e11b21fda034b45c09b2deee99c5d4641fc6d

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
