### ISSUE TITLE
[Quest[[Classic] Misplaced quest: Letter to Stormpike

### ISSUE THREAD

**Issue by highness** [dalaranwow/dalaran-wow#982]
Here's the quest chain in Hillsbrad Foothils: http://www.wowwiki.com/Quest:Encrypted_Letter_%28Hillsbrad_Foothills%29

It should start from http://www.wowwiki.com/Quest:Encrypted_Letter_%28Hillsbrad_Foothills%29

Instead, Loremaster Dibbs (http://www.wowhead.com/npc=2277) already offers a second quest in chain, Letter to Stormpike (http://www.wowhead.com/quest=514) without prerequisite.

Here you can see me having Encrypted Letter: 

![1](https://f.cloud.github.com/assets/5235996/1631492/142fbb72-5766-11e3-828d-c00ba552f0cd.jpg)

Here I abandon it:

![2](https://f.cloud.github.com/assets/5235996/1631493/1ad15af8-5766-11e3-842b-c486d0b13a8e.jpg)

Here Loremaster still offers me to turn it to IF even before I actually would give it to him:

![3](https://f.cloud.github.com/assets/5235996/1631504/408f90b6-5766-11e3-946a-250e8bd3a339.jpg)

He shouldn't.

Cheers.

**Comment by Rushor** [comment]
DB/Quest: Letter to Stormpike - Add prequest "Encrypted Letter"

* closes https://github.com/dalaranwow/dalaran-wow/issues/982
* commit: 2eb69c402dd0f64098eaf9fee06d8ebcd529fb9a

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
