### ISSUE TITLE
[Item] Misplaced text: Foreboding plans.

### ISSUE THREAD

**Issue by highness** [dalaranwow/dalaran-wow#983]
You loot this thing in Hillsbrad when getting the quest that goes by the same name (http://www.wowhead.com/quest=510)

Here's the item: http://www.wowhead.com/item=3718

It should say when 'read': 

"L. F. has ordered increased aggression against the fools in the Alliance.  Below is a list of materials needed for an important mission against Southshore:

1 week travel rations for 20 men
20 black night suits
20 pairs new shoes
25 new swords
30 throwing knives
20 black masks
10 vials inflammatory oil
50 doses paralytic poison
5 stolen Southshore guard uniforms, if available
100 silver coins

--Baron V.
Quartermaster"

Currently it says this instead: 

![wowscrnshot_112713_152949](https://f.cloud.github.com/assets/5235996/1631577/17ec395a-5768-11e3-8d41-caaf30b1530c.jpg)

Cheers.

**Comment by Rushor** [comment]
DB/Item: Foreboding Plans - Update pagetext

* remember to delete the cache before testing
* closes https://github.com/dalaranwow/dalaran-wow/issues/983
* commit: 6b472ad151ee91febb8ba012583291109da075f5

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
