### ISSUE TITLE
[Quest][Classic] Shady Rest Inn misplaced stuff.

### ISSUE THREAD

**Issue by highness** [dalaranwow/dalaran-wow#994]
http://www.wowwiki.com/The_Shady_Rest_Inn_quest_chain

Not found any direct proof for this, but probably three 'clue' quest in chain (http://www.wowhead.com/quest=27252, http://www.wowhead.com/quest=27262, http://www.wowhead.com/quest=27263) are misplaced a bit, you can pick them up even before actually turning the previous quest (http://www.wowwiki.com/Quest:Inspecting_the_Ruins_%28Alliance%29) to the inspector.

![wowscrnshot_120513_162052](https://f.cloud.github.com/assets/5235996/1683598/220ff4a4-5dc0-11e3-80a3-606a4529d0ce.jpg)

Also, upon turning in the Hoofprints quest (http://www.wowhead.com/quest=27262), a followind dialogue should occur (it doesn't currently):

"Captain Garran Vimes says: Tesoran! I need someone--Falgran Hastil, preferably--to take care of <name>'s lead on the prints near the Shady Rest Inn.
Adjutant Tesoran says: Right away, sir.
Falgran Hastil says: Falgran Hastil reporting, sir. I will find where the hoofprints lead and report back to you."

**Comment by Augur89** [comment]
Ok, leveling an alt gave me the option to make some experiments. So this long quest chain hast two lead-ins: either you speak with Connor Rivers (npc 5081) in Stormwind and then with Vincent Hyal (npc 5082) in Menethil Harbor ("James Hyal", quest id 1301) or you speak with Guard Byron (npc 4921) in Theramore Island ("They Call Him Smiling Jim", quest id 1282). Either way, you end up meeting Captain Garran Vimes (npc 4044) who puts you in charge of the investigation.

But if you go the Stormwind way, Garran Vimes doesn't offer the "Inspecting the Ruins" quest (id 27249, I suspect id was changed in Cataclysm) and thus there is a disconnection in the chain's flow. You can continue with it, but it seems weird. What I did: take the "James Hyal" quest in Stormwind, go to Theramore, take the "They Call Him Smiling Jim" quest and complete it so Garran Vimes offers "Inspecting the Ruins". The "James Hyal" lead-in can be later completed at Menethil Harbor with Vincent Hyal, who will not offer the second part (but you get the exp from the first). Or you just can ignore the Stormwind way and enjoy a better questing experience, as the exp gains are the same but there are no holes in the chain.

Anyway, the "James Hyal" lead-in should also make Garran Vimes offer the "Inspecting the Ruins" quest so both lead-ins are actually equivalent.

**Comment by Rushor** [comment]
https://www.youtube.com/watch?v=KTHYaf9o9kw

**Comment by Rushor** [comment]
DB/Quest: Update questevent for Captain Vimes
DB/Quest: Implement questevent for Suspicious Hoofprints and add prevquestorder for the alliance and hordeversions

* closes https://github.com/dalaranwow/dalaran-wow/issues/994
* updates https://github.com/dalaranwow/dalaran-wow/issues/1008
* commit: 2152885ac705e5ba33c1b0ff435bd9fb942694bd

![GitHub Logo](http://i.imgur.com/0Br7yVl.jpg)
![GitHub Logo](http://i.imgur.com/EPSuAcb.jpg)
![GitHub Logo](http://i.imgur.com/tTrq7Hf.jpg)
![GitHub Logo](http://i.imgur.com/omRkiQJ.jpg)
![GitHub Logo](http://i.imgur.com/W22NWmX.jpg)
![GitHub Logo](http://i.imgur.com/VshFWnM.jpg)
![GitHub Logo](http://i.imgur.com/1tLWdxm.jpg)
![GitHub Logo](http://i.imgur.com/8o4L0mK.jpg)
![GitHub Logo](http://i.imgur.com/YK4YWZ8.jpg)
![GitHub Logo](http://i.imgur.com/eZs2ggC.jpg)
![GitHub Logo](http://i.imgur.com/qIrqSxW.jpg)
![GitHub Logo](http://i.imgur.com/5qrkxin.jpg)
![GitHub Logo](http://i.imgur.com/YXrlW41.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
ref: https://github.com/TrinityCore/TrinityCore/issues/18426
